### ISSUE TITLE
Feature Request: Field Annotations

### ISSUE THREAD

**Issue by oysteinsigholt** [pocketbase/pocketbase#1024]
Pocketbase is a great project, and I've been loving the developer experience so far, but I have a small feature request that I think would enable me to stay on the master branch instead of my own fork.

Currently, I maintain [my own branch with a custom field type and a custom field options svelte component](https://github.com/oysteinsigholt/pocketbase/commit/9a3e244ab919bf9c8d55b82fd7b2c7735842134f) to be able to use the UI to rapidly prototype adding custom logic tied to special fields.

My event callbacks look something like this:

```go
app.OnRecordBeforeUpdateRequest().Add(func(e *core.RecordUpdateEvent) error {
	for _, field := range e.Record.Collection().Schema.Fields() {
		if field.Type == schema.FieldTypeMyCustomField {
			options, ok := field.Options.(*schema.MyCustomFieldOptions)
			// custom logic here
		}
	}

	return nil
})
````

I don't really need the flexibility of a custom field type, and would be happy to use the the built-in ones if there was a way to add arbitrary metadata to the fields in the admin ui that was available to me in the event hooks.

Therefore, I propose extending `SchemaField` with an annotations map:

```go
type SchemaField struct {
	...
	Annotations map[string]string `form:"annotations" json:"annotations"`
}
````

And making the annotations map editable through the ui:

![annotations editor](https://user-images.githubusercontent.com/6284064/201725515-31e12c06-6d6e-4f7f-a9f1-ad63da05c0a3.png)

So that my event callbacks can look like this:

```go
app.OnRecordBeforeCreateRequest().Add(func(e *core.RecordCreateEvent) error {
	for _, field := range e.Record.Collection().Schema.Fields() {
		if val, ok := field.Annotations["myCustomAnnotation"]; ok {
			// custom logic here
		}
	}
	return nil
})
````

I hope that this would help others extend the behaviour of pocketbase in library mode as well without having to mess with the internals.

Thanks!

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand really the use case for this and in my opinion it will be too confusing for several reasons:

1. The definition of the annotation is too limited and while it may work for your use case, someone for example will want more flexibility, eg. defining more than one value, defaults, etc.

2. Since the annotation is practically whatever the user has typed, there is no default behavior attached to it and will be up to the developers to determine how they will use the value of "transform" or "trim" annotation.

3. For those who doesn't use PocketBase as framework (aka. use only the prebuilt binary), the annotations wouldn't make sense because there would be no default behavior attached to them and will just clutter the UI unnecessary.

In my opinion this type of data transformations are best suited outside of the UI because it is a lot more flexible.
