### ISSUE TITLE
Add function support like aws

### ISSUE THREAD

**Issue by Xander-Br** [pocketbase/pocketbase#1026]
It could improve the user flow instead of extending the go project directly write go functions in the ui then expose if needed a custom endpoint

**Comment by ganigeorgiev** [comment]
Cloud functions support for now is not planned. Another user already started experimenting with that in https://github.com/benallfree/pockethost/tree/master/packages/js-cloud-funcs so you may have a look at it if you really need cloud functions.

Eventual support for extending PocketBase with JavaScript using a JS interpreter like goja or otto could be added in the future and it is in the [roadmap](https://github.com/orgs/pocketbase/projects/2) and I'll research it in more thoroughly after the upcoming v0.8.0 release.

**Comment by benallfree** [comment]
Hello, pockethost maintainer here. If it's any help, we are working on a cloud functions solution that may give you some insight on an implementation, or it might be possible to pull the package from our monorepo.

@ganigeorgiev I know you haven't looked too closely yet, but the goja idea is challenging. It may require a lot of bindings and helper functions to be imported into JS/TS in order to map objects to the compatible structs on the Go side. Plus maintaining callback references. I'm looking into a different approach, maybe not as great, but something where a PocketHost JS client runs in admin mode. If you ever end up impelementing webhooks into PocketBase, it might some day be possible to use HTTP as the bridge between GO and JS rather than goja. Just a little preview of what's ahead :)

**Comment by Xander-Br** [comment]
@benallfree Hi mate, I might have a idea for implementing without goja and http functions and might reduce bindings

I think its possible to use wasm for that
https://github.com/wasmerio/wasmer-go
So u don't even need to write binding for every language and the code is self contained

**Comment by Xander-Br** [comment]
I'll try experimenting with this solution

**Comment by benallfree** [comment]
@Xander-Br Check out https://github.com/benallfree/pbscript/issues/3 before you try to go too far with WASM and feel welcome to [open a discussion in the pockethost repo](https://github.com/benallfree/pockethost/discussions) if you would prefer to chat there.
