### ISSUE TITLE
make url case insensitive

### ISSUE THREAD

**Issue by PRCV1** [pocketbase/pocketbase#1028]
while testing my C# SDK, i faced the following problem:

requesting a list with the following url:
`http://127.0.0.1:8090/api/collections/restaurants/records?`
results in a 200 statuscode. but a request to
`http://127.0.0.1:8090/api/collections/Restaurants/records?`
results in a 404 not found statuscode.

the only difference is the uppercase R. 
since i cannot create multiple collections with the same name, why is it restricted in the url?

**Comment by ganigeorgiev** [comment]
This is an implementation detail of [echo](https://github.com/labstack/echo) (PocketBase internal router) and url path params are bound case sensitive.

Collection names technically are also case sensitive, but since they are used also as table names we have an extra validator for that when saving the form.

We can add an exception for this, but I'm not sure if it will be worth the effort.

What is your use case and why you can't use the original case?
