### ISSUE TITLE
Admin UI: .jfif images are not displayed

### ISSUE THREAD

**Issue by flomero** [pocketbase/pocketbase#1047]
just a small thing i noticed:
.jfif image upload and thumb generation works fine, but they are not being displayed in the admin UI

![image](https://user-images.githubusercontent.com/49640251/202411550-37df8221-865a-4096-b3af-7e93c2d7962f.png)

**Comment by ganigeorgiev** [comment]
I wasn't aware of the `jfif` file format. The thumbs generation properly works because it's mimetype is detected as image/jpg or image/jpeg. The preview in the UI on the other hand relies mainly on the file extension.

I'll test it later today and eventually will add jfif to the preview-able types before the final v0.8.0

**Comment by ganigeorgiev** [comment]
A fix was added in the `rc` branch. It will be available with the final v0.8.0 release later this week.
