### ISSUE TITLE
Moving fields in collection creation phase resets them

### ISSUE THREAD

**Issue by smaddiona** [pocketbase/pocketbase#1079]
Nothing super important but just reporting
When creating a collection if a field is of type "Relation" or "Select", if you re-arrange the order, the configuration resets to blank.

**Comment by ganigeorgiev** [comment]
Thank you for reporting it. I've pushed a fix in `master` and it will be available with the next release (_the issue was because we were using the field.id as a key for the #each block but for new fields the id is empty and the reactivity wasn't resolving correctly because of the keys collision; we are now using the field object reference as a key_).

**Comment by smaddiona** [comment]
Lovely, you guys made my life easier with pocketbase, thanks a lot!
