### ISSUE TITLE
Proposal: HTTP range request for files

### ISSUE THREAD

**Issue by TcMits** [pocketbase/pocketbase#1125]
Hi

I looked filesystem `Serve` function, it seems like Pocketbase does not support [byte range request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). Byte range requests are very useful when you have large files.

I have an idea to implement `ServeRange` function. Do you need a PR for this?

**Comment by ganigeorgiev** [comment]
I'm not how useful this would be and how it will integrate with the `OnFileDownloadRequest` hook (and the future private/protected files).

Could you elaborate a little more what is your use case for this?

**Comment by TcMits** [comment]
I don't have any personal use cases for this now, but Safari requires webserver to support "[Range](https://www.rfc-editor.org/rfc/rfc2616#section-14.35)" request header in order to play your media content.

[Resource](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6)
> HTTP servers hosting media files for iOS must support byte-range requests, which iOS uses to perform random access in media playback. (Byte-range support is also known as content-range or partial-range support.)

**Comment by ganigeorgiev** [comment]
Hm, this will be difficult to implement in a generic way when external storage is used because it may not be supported by every S3 provider. Furthermore, things may get further complicated when we add support for CDN url redirects in the near future (see https://github.com/pocketbase/pocketbase/issues/28, https://github.com/pocketbase/pocketbase/pull/986).

I'll leave the request aside for now to research it later in more details after the migration flow improvements and filters enhancements. For now there is nothing wrong to implemented is as an external "plugin" by attaching to the `core.App` instance if you really need it. You can intercept the [`OnFileDownloadRequest` event hook](https://pocketbase.io/docs/event-hooks/#file-api-hooks) and implement your own custom serve method (in the future we may also add support to allow attaching to the hooks externally via a JS interpreter).

**Comment by TcMits** [comment]
Thanks for reply, love this project!

Anyone is having issues in serving mp4 on safari. You can use [Nginx proxy cache](https://www.nginx.com/blog/nginx-caching-guide/)
> If the file is up‑to‑date in the cache, then NGINX honors a byte range request and serves only the specified bytes of the item to the client. If the file is not cached, or if it’s stale, NGINX downloads the entire file from the origin server. If the request is for a single byte range, NGINX sends that range to the client as soon as it is encountered in the download stream. If the request specifies multiple byte ranges within the same file, NGINX delivers the entire file to the client when the download completes.

**Comment by ganigeorgiev** [comment]
I've found out that `blob.Reader` implements the Seeker interface (https://github.com/google/go-cloud/pull/3145), which allow us to use the std `http.ServeContent` handler that already supports the `Range` request. Still this doesn't fully solve the issue and it is possible that some provider that don't support range requests will have to read the whole content in order to support the "sniffing" part but at least it will work for most use cases.

This is implemented in `master` and will be available with the next release.
I don't have access to a mac to test the media playback, but sending manual curl requests and checking the response headers in the automated test (https://github.com/pocketbase/pocketbase/commit/bd6512574465fef6b07e4091b1e7a0ba012e9dad#diff-e53aa5846a9af92424f81ee60585dd7b25350763d770888a1624de00356edf0aR302-R334) seems to show the correct range behavior.

**Comment by TcMits** [comment]
Great job !!

Don't forget adding tests for [multiple range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges).
