### ISSUE TITLE
All options in Relation not showing up.

### ISSUE THREAD

**Issue by BowersIndustry** [pocketbase/pocketbase#1128]
Hello! I have a collection and it has a relation field. This field grabs the authors from the authors collection and lets you choose one. But not all of them are showing up. I have searched and found the author in the author collection I want to select, I copied the ID and pasted it in the relation, but is says no results. Why is this?

**Comment by ganigeorgiev** [comment]
This is because relation search is only client-side and loosely checks for the user input anywhere in the records response. This means that you need to have all records available/loaded in order to perform a search from the dropdown.

This, and other things related to the relations picker will be fixed in https://github.com/pocketbase/pocketbase/issues/100 and https://github.com/pocketbase/pocketbase/issues/976.
