### ISSUE TITLE
Select only certain fields

### ISSUE THREAD

**Issue by sonovice** [pocketbase/pocketbase#1174]
Is it possible to query only certain fields from a collection using the WebAPI? Similar to `expand` but for the actual queried collection.

**Comment by ganigeorgiev** [comment]
_This was discussed in https://github.com/pocketbase/pocketbase/discussions/354 and https://github.com/pocketbase/pocketbase/issues/259._

For now this is not possible, since it could complicate the handling of some planned features (eg. hidden fields). As mentioned in the linked discussion, the proposal will be revisited in the near future, but for this remains out of the scope for v1.

**Comment by sonovice** [comment]
Thanks, I overlooked #354. This is a show stopper for me, but I will watch PB closely > v1 then.
Thank you again for the quick response!
