### ISSUE TITLE
Failed to create record.

### ISSUE THREAD

**Issue by Fuchsoria** [pocketbase/pocketbase#1187]
`{
  "errorDetails": "Failed to save the record: database is locked (5) (SQLITE_BUSY)",
  "errorMessage": "Failed to create record."
}`
![2022-12-06_09-26-22](https://user-images.githubusercontent.com/43413472/205860614-8da8d30c-b813-46aa-ad88-0383e6116d19.png)

I'm getting this problem when I'm sending less than 100 requests concurrently via go routines, I'm sending there file and 2 text fields.
![2022-12-06_09-31-02](https://user-images.githubusercontent.com/43413472/205860711-77acc75d-bb1f-4b2a-b5e9-744e52e7a7d9.png)

And logs are looking very bad at this moment:
![2022-12-06_09-28-35](https://user-images.githubusercontent.com/43413472/205860870-9ddece20-c0b4-4c40-a5c3-debe353c5171.png)

As hardware I'm using raspberry pi 4(ubuntu 22.04 arm64) and external samsung T7 ssd (exfat) via USB
Last version of pocketbase builded from master, version from release still has same issue.

I guess problem is because of files uploading, like we are locking sqlite on uploading start and unlock on end, but there are a lot of parallel uploadings. Currently my collection size is more than 80k items

**Comment by Fuchsoria** [comment]
Maybe it's possible to support another DB providers for a better high loading? Like postgres for example, or don't block DB while creating and add something like a queue for TXs?

**Comment by Fuchsoria** [comment]
In my case I'm hosting app which sends requests on same host like pocketbase instance, that means I have direct connection via localhost, and it creates requests and sends requests parallel without latency, right now I use only 1 sender instead of multiple routines, and it's my temp solution to let service alive

**Comment by ganigeorgiev** [comment]
@Fuchsoria Support for other databases is in the roadmap, but has the lowest priority for now and may or may not be implemented for v1.

Yesterday I've pushed in `master` a quick fix that move out the files handling from the transaction so the file upload no longer should affect the locking times.

We don't have control over the sqlite db locks. SQLite supports only a single writer at a time (writes queue up) but when mixing read&write in a transaction it could lead to a deadlock situation and SQLite ignores the busy_tiemeout pragma and directly throws the "database is locked error" since there is no point of waiting the transaction to complete.

I'm currently experimenting with a mixed fail/retry + optional blocking waitgroup/queue approach for all Dao operations. Will post an update once I manage to finalize the tests and eventually release it as v0.9.1.

**Comment by ganigeorgiev** [comment]
@Fuchsoria A blocking query semaphore and base fail/retry handling was implemented in `master` and it will be released as part of v0.9.1 soon. Please give it a try and see if it improve the concurrent requests processing (I've tested locally with 5k concurrent create requests and collection structure similar to yours with body size of ~ 500kb).

The blocking semaphore currently is only per query basis to avoid performance issues with the general requests handling so there are still edge cases where SQLITE_BUSY could occur. There is no easy way to solve that and it's just how SQLite works. I'm not familiar with your use case, but if your app needs high concurrent requests processing all the time and it is not just for some temporary data import, then you could consider:
- batching the requests
- use the CGO driver by building with `CGO_ENABLED=1`(it is ~2-3 times faster then the noncgo version)
- reavaluate whether PocketBase is suitable for your use case since we inherit some of the SQLite limitations (you could also check https://www.sqlite.org/whentouse.html)

**Comment by Fuchsoria** [comment]
@ganigeorgiev Thank you for fast update, I build yesterday master branch and started with my default configuration, ~50 parallel requests with images ~1mb-4mb are looking really nice now, I see my logs clean. Small question about releases, are releases build with CGO=1 or not? I tested it with CGO=0

**Comment by ganigeorgiev** [comment]
> Small question about releases, are releases build with CGO=1 or not? I tested it with CGO=0

No, the GitHub releases are with `CGO_ENABLED=0` because it is easier to cross-compile.
You can find the goreleaser config in https://github.com/pocketbase/pocketbase/blob/master/.goreleaser.yaml.

**Comment by ganigeorgiev** [comment]
The above fixes are now part of [v0.9.1 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.9.1).

If you stumble on something else, please let me know and I'll investigate it.

**Comment by Fuchsoria** [comment]
It's possible that in next days I will migrate more than 25k objects from another db to pocketbase through API with many parallel post/get requests, I will write feedback here

**Comment by Fuchsoria** [comment]
![image](https://user-images.githubusercontent.com/43413472/206820391-27a52cb9-aa7a-477a-bba0-6c7b42dfc347.png)
```
2022/12/10 01:51:55 readObjectStart: expect { or n, but found 5, error found in #1 byte of ...|502 Bad Gat|..., bigger context ...|502 Bad Gateway     
Unable to reach the origin service.|...
```
I had something like 25k items, started everything together with routines, and send there first request to get data, second request to post new data with relations from loaded data. And service died
![image](https://user-images.githubusercontent.com/43413472/206820484-0c2d5bb7-aee7-412a-a9c3-19194c29d18b.png)
![image](https://user-images.githubusercontent.com/43413472/206820535-3d4039dd-2d4f-44b7-bf7a-0ce921a2d156.png)

**Comment by ganigeorgiev** [comment]
I don't think this is related to the latest changes.

PocketBase usually doesn't return 502 and I guess the service was killed due to the high memory consumption or drained file descriptors (you can find your fd with `ulimit -a`). You can also check https://github.com/pocketbase/pocketbase/discussions/1224.

Memory allocations will be improved in the near future (there is a [task in the roadmap](https://github.com/orgs/pocketbase/projects/2) for that). I've already identified at 2 places inefficient assignments in hot paths that takes ~20% of the total memory and fixes for that will be submitted soon.
