### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by ThatOneCalculator** [pocketbase/pocketbase#1229]
I don't see why it wouldn't work, but I'm setting up a couple VPS's soon and I'd like to know if there's any compatibility issues I should be aware of when running PocketBase on FreeBSD.

**Comment by ganigeorgiev** [comment]
I haven't tested it on FreeBSD but it should with both the cgo and noncgo sqlite driver (https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures).

But you'll have to build it on your own since currently we don't ship freebsd binaries. To build the same Go main program that the prebuilt binaries use:

1. Clone/Download the repo

2. Navigate to `examples/base`

3. Run `GOOS=freebsd GOARCH=amd64 CGO_ENABLED=0 go build`
   (_https://go.dev/doc/install/source#environment_)

**Comment by realtothstar** [comment]
Hi ganigeorgiev, when its so simple why you doesn't build the binary for freebsd ? What's wrong with that?
