### ISSUE TITLE
Feature Request: Add dedicated before/after auth request hooks

### ISSUE THREAD

**Issue by 0xTux** [pocketbase/pocketbase#1240]
Hey, I recently learned about Pocketbase and I'm really fond of its ease of use.

I want to migrate my existing app which uses SHA512-CRYPT to hash user passwords but Pocketbase uses BCRYPT.
I think there should be a couple more Event hooks

- OnRecordBeforeAuthRequest: we can implement our custom password hashing and sign a JWT token
- OnRecordAfterAuthRequest: same as current OnRecordAuthRequest but renamed to OnRecordAfterAuthRequest

```go
// Extended User Auth Func
app.OnRecordBeforeAuthRequest().Add(func(e *core.RecordBeforeAuthEvent) error {
    username := e.username
    password := e.password

    // this is going to be our custom func where we can check passwords against any hashing algorithm
    err := ValidateUserAndPassword(username, password)
    token := GenerateJWT(jwtclaims)
    // pass the token to be set in cookie etc
      
    return nil
})
 
// Extended User Register Func
app.OnRecordBeforeCreateRequest().Add(func(e *core.RecordCreateEvent) error {
    username := e.username
    password := e.password

    // check if record type is auth
    
    // generate custom hashed password
    hashedPassword := GenerateCustomHasedPassword(password)
    
    // saved the record
    
    return nil
})
```

**Comment by ganigeorgiev** [comment]
We can add a `Before/After` auth hook(s) but allowing the user to set a custom password hashing algo may be troublesome since it could happen at different places and we will also need a validation function that can be called not only as part of the AuthRequest but also for example in the RecordUpsert form in case of user password change, confirm-password-reset request, etc.

The easiest approach in my opinion would be to store in some internal table the old passwords hash with the users id and before the first authentication to verify the plain password against the old hash and then resave it (aka. `record.SetPassword()`) with the new hash.

In order to do that we'll need to add before and after auth request hooks (maybe different for each auth method and eventually soft deprecate the existing `OnRecordAuthRequest`). This will be done in the near future.

**Comment by ganigeorgiev** [comment]
This is implemented in the `develop` branch and will part of the next v0.12.0 release.

The following new hooks were added:

```go
OnRecordBeforeAuthWithPasswordRequest()
OnRecordAfterAuthWithPasswordRequest()
OnRecordBeforeAuthWithOAuth2Request()
OnRecordAfterAuthWithOAuth2Request()
OnRecordBeforeAuthRefreshRequest()
OnRecordAfterAuthRefreshRequest()
OnAdminBeforeAuthWithPasswordRequest()
OnAdminAfterAuthWithPasswordRequest()
OnAdminBeforeAuthRefreshRequest()
OnAdminAfterAuthRefreshRequest()
OnAdminBeforeRequestPasswordResetRequest()
OnAdminAfterRequestPasswordResetRequest()
OnAdminBeforeConfirmPasswordResetRequest()
OnAdminAfterConfirmPasswordResetRequest()
```

`OnRecordBeforeAuthWithPasswordRequest` and `OnAdminBeforeAuthWithPasswordRequest` allow also returning a custom Record/Admin model so that a different unique field (eg. phone) could be used to locate the auth model.
