### ISSUE TITLE
Feature request: Limit image width and height

### ISSUE THREAD

**Issue by profispojka** [pocketbase/pocketbase#1266]
Instead of only limiting file size, I would like to be able to require the uploaded image to be restricted by width and height rules.

I have a preview component, that expects an image of specific size, so I would like to prevent user from uploading image that is not of that size. But preventing images that are smaller than certain resolution would also be helpfull.

**Comment by bradley-varol** [comment]
For now you can probably do this [on the client](https://www.npmjs.com/package/image-size?activeTab=readme), but I'd also like to see this as part of Pocketbase.

**Comment by ferealqq** [comment]
I was wondering, should image be a independent field type. Because images are a essential part of many web application.  Limiting the width and the height of a image could be one of the use cases for the  image field type. Others could be for example return type (base64 sting, cdn url etc) and/or image type validation (jpeg, png etc)?

**Comment by AmFlint** [comment]
Hello,

I created a Pull Request to include that feature (linked to the PR).

**Comment by ganigeorgiev** [comment]
After some consideration, I've decided to leave this out of the scope for v1.

I think it would cause confusion being part of the `file` field for some users since the validator technically will work only with images and it will always have some limitations (eg. someone probably will want a min-max width/height validator instead of fixed size(s)).
I had similar concerns with the "Thumb size" but the difference is that here it is an option, not a validator, and in the future it could be also eventually used with other mimetypes (eg. videos, pdf documents, etc.).

As @ferealqq suggested, it may be better to create a dedicated `image` type, but let's keep it simple for now and leave the image width/height handling to the client.
