### ISSUE TITLE
Feature Request: Header auth from trusted proxy

### ISSUE THREAD

**Issue by kennethklee** [pocketbase/pocketbase#136]
Hi, would it be possible to forward headers with username/email to pocketbase as auth?

My setup has a caddy proxy with an identity provider like Authelia that does the auth flow.

pocketbase has it's own authentication, but i'd like to use the one already setup.

Some reference docs if it helps:

- https://www.authelia.com/integration/proxies/caddy/
- https://caddyserver.com/docs/caddyfile/directives/forward_auth#authelia

**Comment by ganigeorgiev** [comment]
PocketBase maintain its own authentication and users data that could also take part in the collection API rules, so **I don't think you can use external auth providers without first recreating the users in PocketBase** (similiar to the OAuth2 integration).

I'll close the issue for now, because I think this is too user-land specific and requires a special handling depending on a lot of external factors.

I haven't use Authelia before and may have misunderstood the couple of examples I've checked on their websites, so feel free to correct me If you think that this could be handled differently.

**Comment by kennethklee** [comment]
recreating the users in pocketbase makes sense.

I'm afraid i made it sound more complex than it is.

I'll try again:
every http request to pocketbase will have **user-data in the request headers**. for security, also have a list of trusted proxies.

pocketbase would have a setting to know which headers map to which authUser fields (id, name, email, avatar)


use-case examples:

- for Authelia, user would input, `Remote-User`, `Remote-Name` and `Remote-Email`. no avatar.
- for Tailscale, it may be `Tailscale-User`, `Tailscale-Name`, `Tailscale-Login`, `Tailscale-Profile-Picture`.
- for SAML, it'll be something like `X-Saml-Displayname`, `X-Saml-Email`.
- for webauthn, usually something like `X-Webauthn-Name`. you get the idea.

this would allow pocketbase to be used in any auth scenario.


two more advantages:

1. no more effort into auth. pocketbase already has more than enough for standard use. you'll be able to defer to this in the future for requests for AD, SAML, LDAP, or even more OAuth.
2. enterprise ready. this is the typical use case for enterprise.

**Comment by ganigeorgiev** [comment]
I don't think this could be part of the prebuilt base application because I'm not sure how those headers will be configured in a secure manner.

But that doesn't mean that you cannot implement it a middleware and attach it to you application when using PocketBase as framework. Here is an example how to authenticate a regular user with an email from a header:
```go
package main

import (
	"log"

	"github.com/labstack/echo/v5"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
	// enable if you are using formatted errors
	// "github.com/pocketbase/pocketbase/rest"
)

func customAuth(app core.App) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			// read the header values
			email := c.Request().Header.Get("Remote-Email")

			// authorizing regular users (the same could be done for admins)
			user, err := app.Dao().FindUserByEmail(email)
			if err != nil {
				return err
				// or if you want a formatted error
				// rest.NewUnauthorizedError("User doesn't exist", err)
			}

			// "authenticating" the user
			// for admins it would be `c.Set(apis.ContextAdminKey, admin)`
			c.Set(apis.ContextUserKey, user)

			return next(c)
		}
	}
}

func main() {
	app := pocketbase.New()

	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.Pre(customAuth(app))

		return nil
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by kennethklee** [comment]
fascinating! that's amazing.

thanks Gani. that will work.

**Comment by septatrix** [comment]
Maybe this could be documented somewhere? I feel like this would be very beneficial for corporate authentication which often use SAML or LDAP without implementing the functionality but instead leaving it to a reverse proxy

**Comment by kennethklee** [comment]
@septatrix if it helps, i made an auth library that might help you -- https://github.com/kennethklee/pb-auth
