### ISSUE TITLE
Nonempty validation is incorrect for boolean and number

### ISSUE THREAD

**Issue by TylerBarnes** [pocketbase/pocketbase#1360]
Setting a value of `0` for a number or `false` for boolean when creating a new collection item results in a validation error when Nonempty is set to true on the collection for those fields, but these are not empty values

**Comment by ganigeorgiev** [comment]
You can check https://github.com/pocketbase/pocketbase/issues/1324, https://github.com/pocketbase/pocketbase/issues/1246, https://github.com/pocketbase/pocketbase/issues/1085, https://github.com/pocketbase/pocketbase/issues/852 and probably others.

The behavior is intentional. PocketBase doesn't use `null` as field value and instead makes use of zero-defaults (similar to Go), which for `bool` is `false` and for `number` is `0`.
You can also find a table with all supported field values in https://pocketbase.io/docs/collections/#overview.

If you want to accept `false` and `0` as value, don't mark the field as "Nonempty" (there should be also a tooltip to the "Nonempty" toggle that explains which value will be considered valid by the constraint).

**Comment by TylerBarnes** [comment]
Odd but fair enough. Might be better to name it "Nonfalsy" 🤷‍♂️

**Comment by ganigeorgiev** [comment]
Initially it was "Required" and was recently renamed to "Nonempty".

I'm planning Admin UI improvements for v0.12/v0.13 and I'll consider renaming/explaining it better.
