### ISSUE TITLE
Allow OAuth2 login for Admin API

### ISSUE THREAD

**Issue by coherent-cache** [pocketbase/pocketbase#1388]
First off, great work with pocketbase so far!

It would be great if the admin API in pocketbase could support OAuth2 login in addition to the current authWithPassword method. This would allow administrators to access the admin UI using central authentication, which would be a valuable feature to have out of the box. I couldn't find any previous discussions or issues related to this.

I understand that this would also involve some work in the UI, but I believe it would be worth the effort. 

Currently the admin API provides only authWithPassword method in [pocketbase](https://github.com/pocketbase/pocketbase)/[apis](https://github.com/pocketbase/pocketbase/tree/master/apis)/admin.go:

```go
func (api *adminApi) authWithPassword(c echo.Context) error
```

Was looking at the authWithOAuth2 method that is already available for collection records in [pocketbase](https://github.com/pocketbase/pocketbase)/[apis](https://github.com/pocketbase/pocketbase/tree/master/apis)/record_auth.go:
```go
func (api *recordAuthApi) authWithOAuth2(c echo.Context) error
```
I believe that the admin model could be extended with a similar method; will raise a PR soon after testing locally

**Comment by ganigeorgiev** [comment]
This was an early decision and at least for v1 there are no plans for admins OAuth2 login.

While we can allow OAuth2 sign-in, we can't allow easily OAuth2 sign-ups since the admin accounts need to be **created beforehand**. Additionally, since not all providers return an email address, it will be required also to link the OAuth2 user profile manually (aka. associate the OAuth2 user id with the PocketBase admin id).

Please also note that all admins are "developer" accounts and shouldn't be confused with the "admin accounts" in your app.
