### ISSUE TITLE
Response always 404 Not Found

### ISSUE THREAD

**Issue by fachryansyah** [pocketbase/pocketbase#1410]
i'm trying to login my new user, but still get 404 Not found, idk reason why i'm getting 404. i'm already follow the docs and re-check the account is Verified.
<img width="759" alt="Screen Shot 2022-12-28 at 21 09 30" src="https://user-images.githubusercontent.com/14109765/209825054-bd4f4de2-a5f3-45ab-85e3-1a4d934bc0fd.png">
<img width="589" alt="Screen Shot 2022-12-28 at 21 09 59" src="https://user-images.githubusercontent.com/14109765/209825070-601469de-b041-4b66-a958-55489cf0179a.png">

**Comment by ganigeorgiev** [comment]
From the Admin UI screenshot it seems that you are using a very old PocketBase version (< v0.8.0) and the API has slightly changed since then.

If you want to upgrade an older project you can check the [v0.7 -> v0.8+ migration guide](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md#migrate-from-v07x).

If you are working on a new project, you can just download the latest version for your platform from the releases page - https://github.com/pocketbase/pocketbase/releases.

_Additionally, please note that officially only `application/json` and `multipart/form-data` content-types are supported._

**Comment by fachryansyah** [comment]
thanks, it solve my problem
