### ISSUE TITLE
Verify jwt token flow for other application integration

### ISSUE THREAD

**Issue by ktyborowski** [pocketbase/pocketbase#144]
Hey, thanks for creating PocketBase. Looks really great!

I would like to use it as a kind of convinient user managment application. At the same time I want to have other services, that authenticate users based on the JWT tokens from PocketBase (eg. a Python Flask REST API). A common solution for this is to use RS256 for the tokens and share the public keys on an endpoint. Then all services can verify the tokens. This is what [Firebase](https://firebase.google.com/docs/auth/admin/verify-id-tokens) does as well as [Authorizer](https://docs.authorizer.dev/core/endpoints#well-knownjwksjson).

Would love to see something like this at some point. 

As for now I see that one could create and additional endpoint that uses the getUserByToken Dao or just share the private key across the services.

**Comment by ganigeorgiev** [comment]
This is a good suggestion, but may complete things consider how PocketBase manage tokens.

To avoid storing the tokens in the database and requiring something to take care of the tokens table to not grow too big, currently PocketBase uses a not very common way for generating the JWT token secret - by using the default HS256 but with a secret that is derived from 2 different parts:
- **common part** - random string that is static and shared among all users
- **user unique part** - a unique random string that is stored for each user in the `_users` table

Having a secret constructed this way allow us:
- to not store any tokens in the database and have a truly stateless api
- to invalidate all issued tokens for all users by just changing the **common part**
- to invalidate the tokens only for a specific user by just changing the **user unique part** (aka. on user password reset)

Adding support for RS256 tokens may complete things a little since we'll not be able to invalidate the tokens easily.
Furthermore, we also use for each different token type (verification, password-reset, email-change, etc.) a different secret (the [common part only is different](https://github.com/pocketbase/pocketbase/blob/master/core/settings.go#L66-L89)).
I'll reconsider reviewing the proposal once I managed to complete the other major tasks, but for now I'll leave this as not supported or planned.

**Comment by manish181192** [comment]
I am also looking for a similar Setup. @ganigeorgiev Is there a solution now?

**Comment by ganigeorgiev** [comment]
@manish181192 I don't understand what do you mean. Please file a new Q&A discussion with more details about your use case and what you are trying to do.

I'll close this issue, as for now there are no plans to change the existing way how the JWT token authentication works.
