### ISSUE TITLE
Email addresses case sensitive

### ISSUE THREAD

**Issue by pieter-experience-republic** [pocketbase/pocketbase#1465]
Hi,

Let me start off by saying I'm very impressed with your work. After creating a project with it I've noticed 2 small issues, Perhaps I should split this up in 2 issues, but I think they are small enough to put into one.

1. Email addresses are case sensitive when created from the admin UI. 
2. When creating an integer value, 0 is not accepted as a valid value.

**Comment by ganigeorgiev** [comment]
1. Please check https://github.com/pocketbase/pocketbase/discussions/756

2. My guess is that your field is marked "Nonempty" (there is a tooltip alongside the toggle that explains what the constraint will require). Note that PocketBase doesn't store `null` as field value (with exception of the `json` type field) and use zero-defaults (table with supported values could be found in https://pocketbase.io/docs/collections/#overview). Please note that currently in v0.10.4 there is a minor bug with the number visualization in the table listing (https://github.com/pocketbase/pocketbase/issues/1447) but it is already fixed in `master` and will be available with the next release sometime later this week.
