### ISSUE TITLE
Feature Request: Show specific user in logs

### ISSUE THREAD

**Issue by xNaii** [pocketbase/pocketbase#1493]
Now there is no way to know what user did what action only that it's admin/auth/guest which is pointless.
![image](https://user-images.githubusercontent.com/22669597/210806193-0118acf5-4a25-47b4-94c9-7acacfae6209.png)

Would suggest to show Auth -> Provider / User / Token (maybe)

**Comment by ganigeorgiev** [comment]
I'm not sure about this.

Another user recently raised a question for the "opposite", aka. to not have user information in the logs because of a gdpr or other privacy policy concerns in https://github.com/pocketbase/pocketbase/issues/1477, so if we decide to add any user identifiable information we also will have to make it optional somehow and I'll have to think a little more on this whether it is worth doing it.

There are plans in the future to refactor the logs and to make it more generic so that we can external logs submission from 3rd party apps (eg. from a SSR action), but for now this is a very low priority and it is left temporary out of the [scope for v1](https://github.com/orgs/pocketbase/projects/2).
