### ISSUE TITLE
When uploading mp4 the database removes the sound.

### ISSUE THREAD

**Issue by Zilonis123** [pocketbase/pocketbase#1496]
It's me again.

I have a issue when uploading a .mp4 file witch is 52 minutes long. The file uploads fine just without the sound. I went into the debug mode and nothing seemed out of order. At first i thought it would have to do something with the uploading taking too long and there for not uploading sound. 

I've had no problem uploading files at 48 minutes and 32 minutes, but closer to the hour mark is where the problem arises. As like in my last issue the problem might be/is about the file being too large and timeouting.

**Comment by ganigeorgiev** [comment]
If the file was successfully uploaded than I don't see why the sound will be missing.
Could you confirm that the uploaded file has the same size as the original uploaded file?

**Comment by Zilonis123** [comment]
Yes the both videos have the same amount of bytes in size and there is sound when i download the video from pocketbase.
Yet whenever i go to http://127.0.0.1:8009/api/files/COLLECTION_ID/RECORD_ID/FILE_NAME it starts playing the video, but not the sound. 

For my application a video platform i don't want to download all the videos on the users pc i want to play them using a `<video>` tag. 

This problem only occurs for that video. I understand that the problem is in the video itself, but then why does a normal video player play the video with sound, but a `<video>` tag can't.

**Comment by ganigeorgiev** [comment]
Hm, this seems more like a browser codec issue. Are there any js errors in browser console?

Could you try to open the video file in chrome/firefox from your filesystem not from the PocketBase file endpoint (eg.: file://path/to/video/file)?

**Comment by ganigeorgiev** [comment]
@Zilonis123 I'm not able to reproduce the issue locally. I've tested it with 60min dummy MP4 file encoded with H.264 video and MPEG-4 AAC audio.

I suspect that this is caused by the encoding of your mp4 file. Note that mp4 is just a packaging/container format to holds audio and video data, but there are several video and audio codecs/compressions that may not work everywhere.

If opening directly the file from the filesystem in the browser works, then it could be an issue in file serving endpoint, but I can't think of a reason that could cause this (make sure to check the browser console for warning/errors).
