### ISSUE TITLE
Feature Request: Event System & Email Template

### ISSUE THREAD

**Issue by LeCyreaxYT** [pocketbase/pocketbase#1616]
**Hey,**

There are currently 2 things that I am missing and that I wish for. 

**1. Event System**
An Event System where I have the possibility to send things between all users data like

```typescript
pocketbase.event.trigger
pocketbase.event.triggerAll
pocketbase.event.on
```

There should be the possibility to send something to a person you could take as identifier the token when he is logged in.

That you can send data easier to each other.

**2. Email Templates**
A possibility that you can create custom email templates like Email Verification or Password Reset only that you can trigger them with something that can be filled with certain params.

Suggestion

```typescript
pocketbase.sendEmail("nameofTemplate", {
   test: "test"
});
```

In the template you have the possibility to use a paramater like {test} which will be replaced automatically.

These are my suggestions that I would celebrate and improve my everyday life.

**Comment by ganigeorgiev** [comment]
1. I don't understand the suggestion. You can subscribe to the realtime changes of a collection using the `pb.collection("example").subscribe("*", func(e){ ... })`. If you are asking to extend PocketBase with events, you can make use of the Go event hooks (_JS equivalent hooks will be available with v0.13/v0.14_) - https://pocketbase.io/docs/event-hooks/.

2. Sending custom emails with the web API for now is not planned because only admins will be able to trigger the action and I'm not sure how useful that would be (especially once we introduce the JS app hooks). You may also want to check #317.
