### ISSUE TITLE
Validate api rules in migration

### ISSUE THREAD

**Issue by iskaa02** [pocketbase/pocketbase#1625]
### invalid api rules don't raise an error if added via migrations

Example:

the `createRule` in following code is invalid (comparison used `==` instead of `=`).
after running `go run main.go migrate` no error is raised.
```go 
createRule:="user.id==@request.auth.id"
collection:= &models.Collection{
	CreateRule:&createRule
	...
}
```
the migration should failed and prints an error for the invalid rule.

**Comment by ganigeorgiev** [comment]
This is "expected".

When operating with the Dao there are no data validations.
And in most cases you don't need validations inside a migration because validation rules can change and sometimes you may want to perform an action that is not usually allowed/valid during normal app operation (eg. changing the type of a field).

If you want data validations for the collection you have to use the `forms.CollectionUpsert` as shown in https://pocketbase.io/docs/collection-methods/#create-new-collection-with-data-validations, but currently it cannot be created inside a migration because you don't have direct access to the app instance. Exposing the `core.App` was requested previously and it is in my todo, but I'm still not sure if it will be a good idea and for now it is left aside for later consideration.
