### ISSUE TITLE
Wrong example in dashboard for `client.Records.getList`

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/pocketbase#166]
Haven't tested it with latest v0.3.0 release, but issue is currently present on https://pocketbase.io/demo/

1. Navigate to a collection, open "API preview" - "List"
2. Look at JavaScript example

Currently it shows that second argument should be an object:
```
client.Records.getList("posts", { page: 2 })
```
Moreover, further down this page lists "page" and "perPage" in "query parameters" section, together with "sort", "filter", and "expand". 

While documentation at https://pocketbase.io/docs/api-records/ shows that "page" and "perPage" should be second and third arguments, while others should go in a separate object:
```
const resultList = await client.Records.getList("demo", 1, 100, {
    filter: "created >= '2022-01-01 00:00:00'",
});
```

Documentation at https://github.com/pocketbase/js-sdk and my experience seem to agree with this. Probably documentation inside pocketbase admin panel wasn't updated?

**Comment by ganigeorgiev** [comment]
I've updated the examples in [v0.3.1](https://github.com/pocketbase/pocketbase/releases/tag/v0.3.1) release.

`page` and `perPage` are within the "Query parameters" table, because they are actually query parameters, just for convenience they are set as arguments in the SDK because most of the time user will have to pass them, while `filter` filter for example is mostly optional. I agree that it is a little inconsistent and In future I may update the SDK to support both format (and eventually will soft-deprecate one of them):
```js
// current version with 4 arguments
client.Records.getList("posts", 2, 50, { /* other optional parameters */ });

// eventual future version with only 2 arguments
client.Records.getList("posts", { page: 2, perPage: 50, ... });
```
