### ISSUE TITLE
Feature Request : Okta Oauth2 support / Generic oauth2 support

### ISSUE THREAD

**Issue by AlexGiroud** [pocketbase/pocketbase#1675]
Hello,

It would be nice if pocketbase would support Okta oauth2 as an authentication provider or a more generic way to add an Oauth provider in the admin pannel.

https://developer.okta.com/docs/reference/api/oidc/

**Comment by ganigeorgiev** [comment]
I don't plan working on this, but users contribution for new OAuth2 providers are welcomed. If some one want to contribute, you can use the latest merged Gitea and Authentik integrations:

- Gitea #1643: https://github.com/pocketbase/pocketbase/commit/4c73e16f5404383ed73aa13d4643b477f68ff48e
- Authentik #1377: https://github.com/pocketbase/pocketbase/commit/6d08a5f36fb92ac00409c9405a7c8d0d5f9f18d5

_(the generated `ui/dist` files can be ignored)_

Support for creating external OAuth2 providers from the Admin UI is not planned because each integration requires some manual mapping (and sometimes even more than 1 request to fetch the necessary user data) and this will differ from one provider to another.
