### ISSUE TITLE
Weird interactions with json values in the record editor interface

### ISSUE THREAD

**Issue by DaniDipp** [pocketbase/pocketbase#1703]
Severity: Minor (visual inconsistency)

When editing a json-type field through the web interface, there are weird interactions with literal strings and the value `null`.

If the current value of a json field is a string, the editor strips out the quotes when first rendering it. Editing this value without adding the missing surrounding quotes results in a validation error (unless it's a number which is of course a valid json value).
If the current value is `null`, the editor is just empty, which can be especially confusing when the column is marked as `nonempty`.

**Comment by ganigeorgiev** [comment]
Because of the support for both json and multipart/form-data (where in the latter everything is a string) we try to perform "normalization" on the string value, which as you noted could have some unexpected results.

I'll think a little more on it tomorrow and will try to provide a better normalization fix in the upcoming v0.12 release.

**Comment by DaniDipp** [comment]
The thing is, in the list, strings are displayed correctly in the row list (with proper quotes). The quotes are only stripped away when the value is displayed in the editor text box.
Thanks for looking into it!

**Comment by ganigeorgiev** [comment]
I've pushed a fix for the `json` field Admin UI visualization and updated string data normalizations in the `develop` branch (the fix will be included in the upcoming v0.12.0 release soon).

In order to support seamlessly both json and multipart/form-data request bodies, the following normalization rules are applied for plain `json` field **string** values:
- "true" is converted to the json `true`
- "false" is converted to the json `false`
- "null" is converted to the json `null`
- "[1,2,3]" is converted to the json `[1,2,3]`
- "{\"a\":1,\"b\":2}" is converted to the json `{"a":1,"b":2}`
- numeric strings are converted to json number
- double quoted strings are left as they are (aka. without normalizations)
- any other string (empty string too) is double quoted

Additionally, the "Nonempty" `json` field constraint now checks for `null`, `[]`, `{}` and `""` (empty string).

**Comment by DaniDipp** [comment]
That sounds like it will change this from a visual bug to a functional bug. Am i understanding this correctly that if I were to submit the string `"0000"` will now be silently converted to `0000`, stored as a number, and returned as a number to the SDK?

I use the json fields in a table for the settings of my app because it's a free-form value and records in this collection are not related to each other. I would not expect for perfectly valid strings to get automatically coerced to numbers or booleans.

Also, I would not consider `[]`, `{}` and `""` to violate the nonempty-constraint. These are valuable bytes that carry information and their presence proves that the field is not empty. `null` could be a point of discussion here since it is a valid json literal, but i understand the technical restriction. The string `"null"`, however, should not get coerced to `null` and fail the constraint.

**Comment by ganigeorgiev** [comment]
The previous behavior was not only a visual bug. It was inconsistent with how the submitted value was evaluated and returned in the response.

The above normalizations are needed as a away to support seamlessly both json and multipart/form-data request bodies. Otherwise we will have to introduce a special case and parsing just for the `json` field and this will complicate too much the internals and tests.

> if I were to submit the string "0000" will now be silently converted to 0000

In this specific case since it is not a valid number it will be stored as `"0000"` json string in the database and returned as string in the response. If the value was `"123.456"` then it will be coerced to number (**but the number coercion is how it works at the moment too**).

> I use the json fields in a table for the settings of my app because it's a free-form value and records in this collection are not related to each other.

The `json` field type was initially intended to hold only array and object like values and the idea to allow only numbers, strings, bools was introduced at a later stage as an escape hatch for some rare cases. My recommendation would be if you really want to store an arbitrary value, then you can wrap you data inside an object, eg. `{"data": anything}`.

**Comment by DaniDipp** [comment]
Alright, I'll have a look at what kind of settings I want to store and decide between storing straight json or strings that I `JSON.stringify` myself, to avoid type mismatch of user-submitted data.

Thank you for the clarification and recommendation!
