### ISSUE TITLE
`?=` not working as expected?

### ISSUE THREAD

**Issue by jorgestg** [pocketbase/pocketbase#1725]
Hello,

I have 2 collections that roughly look like this

```
players                         |  skills
---------------------------------------------------------
- id    text                    |  - id  text
- name    text                  |  - name  text
- skills   []relation(skills)   |
```
I wanted to filter down players by their skills, so I tried the following filter:
```
skills ?= "some skill ID"
```
which, to my surprise, didn't work (got an empty array). I got around the issue by using `skills.id` instead of just `skills`, which seems odd considering skills is a list of IDs.

The issue now is that I can't manage to filter by more than 1 skill. I've tried using this filter:
```
skills.id ?= "some skill ID" && skills.id ?= "some other skill ID"
```
Again, I get an empty array (yes, there is data that matches that predicate). What is weirder is that the same filter with `||` instead of `&&` works just fine.

Is there something not working as expected?
Or am I doing something wrong? 

Cheers

**Comment by ganigeorgiev** [comment]
It is working as intended.

`skills ?= "something"` compares the plain array value (eg. `"[id1, id2]"`).

If you want to check the id you have to use the dot-notation (aka. `skills.id ?= "something"`).

> The issue now is that I can't manage to filter by more than 1 skill.

Combined multiple filters or "IN" expressions are not supported at the moment because the implementation ended up with too much performance overhead. It is in my todo and eventually will be added in the future but for now is low priority.

One workaround could be to use the `~` operator against the serialized array, something like:

```
skills ?~ "some skill ID" && skills ?~ "some other skill ID"
```
