### ISSUE TITLE
Feature Request: Admin Panel upload image?

### ISSUE THREAD

**Issue by dsm-72** [pocketbase/pocketbase#1748]
Right now it seems I have to just write a `.js|.ts` file to connect to the client and upload a file to a particular record.
Can we get a drag / drop  or file select in the Admin panel?

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what do you mean.

You can upload a file from the Admin UI just fine (_drag&drop is not supported at the moment, but I've added it in my todo to eventually consider it for a future release_).

Note that you'll not see the "Upload file" btn if you've reached your `file` field "Max select" limit (removing the file, aka. clicking on the "X" btn, should show the upload btn again).

**Comment by ganigeorgiev** [comment]
I'll consider making the upload btn disabled with a tooltip instead of hiding it for the next release, so that it is more clear.

**Comment by dsm-72** [comment]
Huh, strange. I could seem to see that option when in the admin panel. I'll try again. Sorry for the inconvenience 😅
While I got you here, however, do you have a good demo / template for docker / hosting?

**Comment by ganigeorgiev** [comment]
> I could seem to see that option when in the admin panel. 

This is most likely because your record has already reached your `file` field "Max select" limit. As mentioned in the previous, I'll disable the button instead of hiding it and will add a tooltip to make the file upload a little more user friendly.

> do you have a good demo / template for docker / hosting?

You can find an example Dockerfile setup in https://pocketbase.io/docs/going-to-production/#using-docker. The PocketBase binary is completely portable since it is statically linked (aka. there are no external dependencies) and usually the process is just:
- download and extract the archive for your platform from the [releases page](https://github.com/pocketbase/pocketbase/releases)
- start the executable
