### ISSUE TITLE
Realtime UnsubscribeFunc doesn't always work

### ISSUE THREAD

**Issue by Aragur** [pocketbase/pocketbase#1751]
I have a special case where my UnsubscribeFunc doesn't work as expected.  
See the screenshot below.
If you need additional information to reproduce, hit me up.

<img width="813" alt="Screen Shot 2023-02-02 at 19 57 05" src="https://user-images.githubusercontent.com/11004008/216424078-b435736a-f1fd-4e89-85af-155dc73e703f.png">

**Comment by ganigeorgiev** [comment]
Please provide a little more information. Minimal reproducible repo or at least steps what you are doing and where your code is running will be also helpful.

**Comment by Aragur** [comment]
> Please provide a little more information. Minimal reproducible repo or at least steps what you are doing and where your code is running will be also helpful.

That's really difficult as this happens only on one place in my project.
I'm using the OnUmounted hook from Vue to call this function, which I get returned after a subscription was successful.

> What versions of the SDK and PocketBase you are using?

I'm running the JS-SDK v0.10.1 and PocketBase v0.12.2

**Comment by ganigeorgiev** [comment]
Hm, I'm not sure how to reproduce it.

Could you provide at least a code sample/snippet what how you are subscribing/unsubscribing?

Are you able to reproduce the error every time?

Are you working on a SPA or SSR application?

**Comment by ganigeorgiev** [comment]
You could also try starting the PocketBase executable with `--debug` to get some more insight on the realtime events and their sequence.

**Comment by ganigeorgiev** [comment]
The only way I'm able to reproduce the 404 error during unsubscribe was following these steps:

1. Establish realtime connection

2. Slow my network connection from the Inspect network tools to something very slow, eg. 1kbit/s

3. Unsubscribe call started with Client ID 123X...

4. While the unsubscribe call is still sending, restart the server or drop the connection (**this also clears all realtime information**)

5. The Unsubscribe call is received by the server but since it was restarted/disconnected in the meantime there is no longer information about the old client id sent with step 3) and therefore 404 is returned


This is working as intended since we currently doesn't support buffering or messages queue for the realtime events.

If the above steps are the reasons for the error in your app, then it is safe to ignore it (aka. provide an empty `catch` for the unsubscribe promise).

If that's not the case, please provide more information about your code and steps to reproduce it and I'll investigate it more thoroughly.
