### ISSUE TITLE
Feature request: Export and Import - Data Along with Schema

### ISSUE THREAD

**Issue by mmv-dev** [pocketbase/pocketbase#1753]
Hi team,

As i can see, Sync is no longer in experimental in v12 and above. Your Export and Import Collections is a life saving feature to say the least. Quickly copy the table structure instead of creating them manually. 

Will it be possible to do it with the data also. Just a suggestion. I am no expert on migrations and stuff. This would help me alot for rapid prototyping without disturbing existing working structure.

Also thanks for the amazing product ❤️.

**Comment by ganigeorgiev** [comment]
This eventually will be handled in #48, but currently is on hold because I've stumbled on some issues that I have to investigate in more details how to solve better (see https://github.com/pocketbase/pocketbase/issues/48#issuecomment-1211775627) and for now I've prioritized other tasks but will get back to it most likely somewhere after v0.14-v0.16.
