### ISSUE TITLE
Bad Schema Behavior: Combination of "Unique" and "NonEmpty" is broken

### ISSUE THREAD

**Issue by Shafik23** [pocketbase/pocketbase#1755]
Simple steps to reproduce:
- Create new "test" collection
- Add a random text field (e.g. "foo")
- Set the "Unique" flag", but keep "NonEmpty" unselected - i.e. allow empty values.

Notice you can't add 2 records with empty "foo" fields:

![image](https://user-images.githubusercontent.com/1048673/216478047-e96406d3-3186-4bfa-98f9-58cb6e54167a.png)
![image](https://user-images.githubusercontent.com/1048673/216478203-98f8e765-28cc-4033-a4aa-65c850863e9a.png)

**Comment by ganigeorgiev** [comment]
This is working as intended, although I agree it may not be very clear.

The unique constraint is triggered because most likely you already have another record with emtpy value. Unuqie options that will allow to exclude this behavior was discussed in https://github.com/pocketbase/pocketbase/discussions/542 and will be eventually added as part of https://github.com/pocketbase/pocketbase/issues/544.
