### ISSUE TITLE
Suggestion: Logging date and time with messages

### ISSUE THREAD

**Issue by agreensh** [pocketbase/pocketbase#1822]
Would it be possible to add the date/time to logging?
For example, on server restart (production, when using systemctl), it would be useful to see the date/time when "pocketbase serve" was executed in the log file given by "StandardOutput".
Same for errors. Date/time would be useful.

**Comment by ganigeorgiev** [comment]
All error logs that are printed to the std output should already have a datetime prefix with them.

I'll consider prefixing the "Server start message" with the current datetime in the next release.

**Comment by ganigeorgiev** [comment]
A datetime prefix was added to the server start message in [v0.12.3 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.12.3).

_Note that in the future the logs reporting will be generalized and the current stdout logs may eventually be migrated to the logs db so that you can explore/search/filter the logs from the Admin UI._
