### ISSUE TITLE
Discord Channel or Live Chat

### ISSUE THREAD

**Issue by catalinux17** [pocketbase/pocketbase#185]
I really really love your project, but I do have some questions and I don't know where to address them.

I want to import a database in pocketbase.

Can you create a discord server or live chat so users can discuss how they used pocketbase.

**Comment by ganigeorgiev** [comment]
Hi, it is better to use the GitHub's [Discussions](https://github.com/pocketbase/pocketbase/discussions) instead of Discord/Slack/etc. because they are public and can be indexed and show in google searches.

About your question how to import database in PocketBase - currently there is no integrated import functionality for importing data from external sources. This is already planned in the [roadmap](https://github.com/pocketbase/pocketbase/discussions/123) per issue #48 (I plan to start working on it after the Dart SDK).

If that's not what you are looking for, please elaborate on your use case by adding a comment or creating a new discussion(s).

**Comment by catalinux17** [comment]
Thanks for your quick and prompt reply!! I really appreciate your work.

**Comment by rawandahmad698** [comment]
I made one!
https://discord.gg/8TnN92pbFB
