### ISSUE TITLE
SSO Login

### ISSUE THREAD

**Issue by catalinux17** [pocketbase/pocketbase#186]
Can you add SSO login so big companies use their company's accounts?

**Comment by ganigeorgiev** [comment]
PocketBase maintain its own authentication and users data that could also take part in the collection API rules, so I don't think we can add support for external Identity providers in a generic/common way since this will require the external accounts to be recreated in PocketBase and the implementation usually will differ from provider to provider.

I may consider implementing SAML SSO in future versions, but there are already a lot of [tasks piled in the roadmap](https://github.com/orgs/pocketbase/projects/2), so I'm not sure that I'll be to pick it before v1.0.0.

That doesn't mean that you cannot implement it on your own if you use PocketBase as framework. In [issue #136](https://github.com/pocketbase/pocketbase/issues/136) you'll find an example authenticating a user with a middleware based on some external header value.
