### ISSUE TITLE
Will importing from a flat file like a CSV ever be possible?

### ISSUE THREAD

**Issue by migur0sa** [pocketbase/pocketbase#1863]
Hey, 

I love Pocketbase and it is a great project. But, I'm trying to build a small POS (Point of Sale) software using Pocketbase and it is going great but I'm thinking about what would happen if I get a customer that has an existing POS. How will I import his existing data from his current POS into mine?

I've read a couple of questions about this topic from last year but just wondering if this will get added in the near future.

Thank you, and keep up the good work!

**Comment by ganigeorgiev** [comment]
Please check https://github.com/pocketbase/pocketbase/issues/48#issuecomment-1211775627.

> How will I import his existing data from his current POS into mine?

You can insert the data directly into the pb_data/data.db file using the sqlite3 tool (eg. `sqlite3 pb_data/data.db '.import test.csv foo --csv'`), but keep in mind most of the time you'll have to adjust the data so that it can match with your PocketBase collections structure. There is no automated solution for this.

If you need help with the import, feel free to open a new [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) provide more details about your collections structure and the data you want to import and I'll try to help.

**Comment by amirkhalil22** [comment]
sqlite3 pb_data/data.db '.import test.csv foo --csv' 
doesn't work for me ??

![image](https://user-images.githubusercontent.com/104743918/223869536-60c2a11d-1d06-4f5b-8c6a-fae7e0bee556.png)

**Comment by ganigeorgiev** [comment]
@amirkhalil22 It works fine for me. It could be something specific to the windows cmd.

In any case, you don't have to execute it as one-line. You can run `sqlite3 pb_data/data.db` and then type `.import YOUR_CSVFILE YOUR_TABLE --csv`.

You can find more information about the SQLite cli in https://sqlite.org/cli.html.
