### ISSUE TITLE
Feature Request: Add column sorting UI to profiles collection

### ISSUE THREAD

**Issue by MeharGaur** [pocketbase/pocketbase#189]
Hi,

In the admin UI, I noticed that user-created collections have arrows on the column name so that you can sort the records. However, the profile fields in the users tab do not have sorting. Sorting by profile fields in the UI would be very useful to non-developers and marketers for finding specific users, based on say number of profile views. 

![has sorting](https://user-images.githubusercontent.com/36120952/180298239-0b65c82a-a32d-4675-8103-8bcdb275ef6e.png)

![does not have sorting](https://user-images.githubusercontent.com/36120952/180298464-4fb6b994-f38c-44ec-9614-c13160b550bb.png)

**Comment by ganigeorgiev** [comment]
Hi, thanks for the suggestion. I've added it to the [roadmap](https://github.com/orgs/pocketbase/projects/2).

For now it is a low priority, but I agree that the Users listing could be improved (in order to support the sorting and filtering of the profile file from the users api, we will have to define a custom field resolver similar to [`record_field_resolver.go`](https://github.com/pocketbase/pocketbase/blob/master/resolvers/record_field_resolver.go)).

**Comment by ganigeorgiev** [comment]
This is now available as part of the [v0.8.0-rc1 pre-release](https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1).
