### ISSUE TITLE
Add an option to disable the default email template styles

### ISSUE THREAD

**Issue by doppiaesse** [pocketbase/pocketbase#1904]
I have configured my Pocketbase to send emails over SMTP. I'm using a simple mail template and I found that when sent by Pocketbase it doesn't display correctly. I tested the template using Nodemailer and it's perfect. Look at the images:

**SENT BY NODEMAILER**
![Screenshot 2023-02-23 133009](https://user-images.githubusercontent.com/24417264/220924067-a8c013e6-a1ec-495f-b082-fb61d796c18f.png)

**SENT BY POCKETBASE**
![Screenshot 2023-02-23 132940](https://user-images.githubusercontent.com/24417264/220924258-1f57f7e1-af44-4824-87cf-54a617e380b6.png)

They are the exact same template. Also the mails sent by Pocketbase require a couple of minutes, depending on the template (only using a blank template with just a link is instant), while nodemailer send the mails instantly (so it's not a SMTP configuration problem). Pocketbase updated at the latest version.

Any idea on how to solve this? I love using Pocketbase but this is a very strange behaviour. Thanks in advance.

**Comment by ganigeorgiev** [comment]
This is because the default templates content has a wrapper element and some general default styles - see https://github.com/pocketbase/pocketbase/blob/master/mails/templates/layout.go.

I've added the task to the [roadmap](https://github.com/orgs/pocketbase/projects/2) consider sometime in the future to move the default styles (or maybe provide an option to chose the layout), but for now this is a low priority.

> Also the mails sent by Pocketbase require a couple of minutes, depending on the template (only using a blank template with just a link is instant), while nodemailer send the mails instantly (so it's not a SMTP configuration problem). 

A lot of reason could affect the deliverability and most likely the receiver is holding the email to perform some additional spam checks (it depends on the mail content, hosts, links, etc.)

**Comment by doppiaesse** [comment]
Fantastic answer, thanks a lot! For my use case I decided to remove the content of layout and rebuild the application.

**Comment by ganigeorgiev** [comment]
To minimize the breaking changes, the default email template styles were simplified and the wrapper elements are removed from the layout. The default templates will look like this (gmail):

![email_screenshot](https://i.imgur.com/G0B9jgS.png)

The changes are currently only in the `develop` branch and will be available with the next v0.14.0 release.
