### ISSUE TITLE
Proposal: Add support for SQL date functions

### ISSUE THREAD

**Issue by terehov** [pocketbase/pocketbase#1931]
I'm really enjoying working with Pocketbase, and I'm currently migrating a Supabase application to Pocketbase as it needs to run offline on Raspberry Pi devices. For our use case, it's important to set a timestamp in the database. In Postgres, we were able to simply execute a `now()` function to set the database timestamp. Although SQLite allows for similar functions, it doesn't seem to be possible with Pocketbase and the date has to be set through JavaScript using `new Date().

It would be great if Pocketbase could add support for SQL date functions to make it easier to set timestamps in the database. For example, it would be beneficial if we could execute the following code:

```typescript
await pocketbase.collection("order_item").update(orderItemId, { started_at: "SELECT datetime('now')" });
```

This would allow us to easily set the timestamp using the SQL date function and provide a better developer experience.

**Comment by ganigeorgiev** [comment]
For now this is out of the scope since it will complicate too much the internals and the API rule checks.

If you want more advanced create/update functionality, you can make use of the [OnRecordBefore*Request](https://pocketbase.io/docs/event-hooks/#record-crud-api-hooks) or [OnModelBefore*](https://pocketbase.io/docs/event-hooks/#db-hooks) hooks.
