### ISSUE TITLE
Update where (condition) implementation in 1 method

### ISSUE THREAD

**Issue by elsacutealways** [pocketbase/pocketbase#1992]

**Comment by ganigeorgiev** [comment]
Could you elaborate a little more?

**Comment by elsacutealways** [comment]
Something like
```
UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;
```
in one js method like
`....collection.updateWhere(condition, data)`

**Comment by ganigeorgiev** [comment]
There are no plans to allow raw SQL statement via the web APIs since it will be hard to perform the required access checks.

If you want to perform raw queries, you can [use PocketBase as framework](https://pocketbase.io/docs/use-as-framework/) and use directly the [db abstraction and its helpers](https://pocketbase.io/docs/database/).

**Comment by elsacutealways** [comment]
How to update all rows created more than 1 hour ago? (JS)

**Comment by ganigeorgiev** [comment]
Bulk create/update/delete at the moment is not supported and this eventually will be handled as part of #48.

You can update a record only if you know its primary key (id). We can't allow updating via a condition, because it could return more than 1 record and it will be ambiguous.

If you want to update all rows created in the past 1 hour:

- fetch all records using `getList()` or `getFullList()` by specifying the `filter` param.
- send individual `update()` requests for each record.

If you want transactional safety, you'll have to use db Go helpers - https://pocketbase.io/docs/database/#transaction.

**Comment by elsacutealways** [comment]
Why this 2 actions couldn't be implemented in 1 js method
updateWhere(filter, newData)?

**Comment by ganigeorgiev** [comment]
@elsacutealways

I think you missed/misread my comment.

**We can't allow updating via a condition, because it could return more than 1 record and it will be ambiguous.**
Additionally we can't allow client-side execution of any write transactional operation since it could lead to excessive db lock times making your application unresponsive (as mentioned, this eventually will be handled as part of https://github.com/pocketbase/pocketbase/issues/48#issuecomment-1211775627).
