### ISSUE TITLE
Initialize pb_data with default tables

### ISSUE THREAD

**Issue by glitchedgitz** [pocketbase/pocketbase#2003]
Hi,
I am using pocketbase with [wails](https://wails.io).
For my desktop application, every new project will have its own `pb_data`.

And I need some default tables and an admin user that initialize with every project automatically.
One solution can be I make a copy of `pb_data` with the default table and user that I need and use it for every other project.

But Is this kind of behaviour possible programmatically?

**Comment by glitchedgitz** [comment]
Currently, I am using this `app.OnAfterBootstrap` but I have to run the command 2 times to make this work.

**Comment by ganigeorgiev** [comment]
You can check [migrations](https://pocketbase.io/docs/migrations/).

When using Go migrations, since they are regular Go files, they will be automatically embedded in the final executable. You can also enable the `Automigrate` functionality to generate migration files on collections change from the Admin UI.

**Comment by glitchedgitz** [comment]
Awesome! Thanks @ganigeorgiev
