### ISSUE TITLE
Documentation: One more backup method: Litestream?

### ISSUE THREAD

**Issue by imWildCat** [pocketbase/pocketbase#201]
https://pocketbase.io/docs/going-to-production/#backup-restore mentioned backup strategy. 

For the SQLite database, https://litestream.io is a great option.

Should we mention it in the doc?

**Comment by ganigeorgiev** [comment]
It is already in the FAQ - https://pocketbase.io/faq/. I will consider mentioning it in the backup docs too (in general docs will need to be improved since they currently lack also more advanced usage guides and examples; this exists in the the [roadmap](https://github.com/pocketbase/pocketbase/discussions/123) but it is better to first stabilize the api before investing more times in the documentation).

**Comment by imWildCat** [comment]
Thanks!
