### ISSUE TITLE
golang https use custom certificate

### ISSUE THREAD

**Issue by MuhammedKilinc60** [pocketbase/pocketbase#2055]
Hello 
How can I use my own certf and key ?

**Comment by ganigeorgiev** [comment]
At the moment custom certificates are not supported out of the box.
This may be added eventually in the future since it was requested also in https://github.com/pocketbase/pocketbase/discussions/930 but for now is out of the scope for v1.

As a workaround you can put PocketBase behind a reverse-proxy (nginx/apache/caddy, etc.) and manage the custom certificate via certbot or other similar tool.

For an example nginx config you can check https://pocketbase.io/docs/going-to-production/#using-reverse-proxy.
