### ISSUE TITLE
Feature request: default field values

### ISSUE THREAD

**Issue by kennethklee** [pocketbase/pocketbase#206]
Would love to create an `active` field in a collection schema, with default `true`.

**Comment by ganigeorgiev** [comment]
Adding support for default values as part of the collection schema may do more harm than good since it will make the API ambiguous (at least in my opinion).

This feature request was asked previously (see https://github.com/pocketbase/pocketbase/issues/42), but I'm not planning to introduce defaults because it is not clear when they should apply:
- on create, on update or both?
- when do we fallback to the defaults - on missing body parameter, on zero value or both?
- when using `multipart/form-data` do we also treat empty string as missing value?

So for now, if you really need defaults, my recommendation would be to set them client-side or with the before hooks.

**Comment by Lex-2008** [comment]
Also note that while it's not possible to specify _default_ values (i.e. those which are set if you don't specify them in API), it's still possible to _enforce_ them (i.e. reject "create record" requests which don't satisfy some criteria) - see #200 for a longer explanation, but TL;DR version is to set "create action" to something like `active=true` - in that case attempts to create records with a different value of this field will be rejected.

**Comment by kennethklee** [comment]
I'm using it as a framework, so the before create record event will do as mentioned.

Or perhaps, would altering the table with `default true` persist between collection changes?

**Comment by ganigeorgiev** [comment]
@kennethklee The field's sql column definition will not change after the initial creation (it could be only renamed).

But keep in mind that, even if you decide to alter the underlying table, when creating/updating a record with the API, the field values are always casted and normalized to a non-null zero-value equivalent in case null or invalid type is assigned (see [`SchemaField.PrepareValue()`](https://github.com/pocketbase/pocketbase/blob/master/models/schema/schema_field.go#L215-L284)).

The before create hook should be enough without altering the table. Note that there is a slight difference between these 2 before create hooks:
- `OnModelBeforeCreate` - triggered before each db insert operation from the `app.Dao()` for every model. Which means that it will be triggered even if you create the record manually. You could type check the returned event model to target only the records from specific collection:
  ```go
  api.app.OnModelBeforeCreate().Add(func(e *core.ModelEvent) error {
    if record, ok := e.Model.(*models.Record); ok && record.Collection().Name = "YOUR_COLLECTION" {
      record.SetDataValue("active", true);
    }
    return nil
  })
  ```

- `OnRecordBeforeCreateRequest` - triggered only on API POST create request, after request data load and form validations but before persisting the record changes. You can also use this event to return a completely different API response to the client.

**Comment by kennethklee** [comment]
ah drat.

I understand now. thanks! and thanks for clarifying the difference between the model hook and the record hook.
