### ISSUE TITLE
Serving static files not working for all paths

### ISSUE THREAD

**Issue by johnnypea** [pocketbase/pocketbase#2072]
PocketBase v0.13.4

This doesn't work
```go
	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.GET(
			"/custompath/*",
			apis.StaticDirectoryHandler(site.DistDirFS, false),
			middleware.Gzip(),
		)

		return nil
	})
```
`http://127.0.0.1:8989/custompath/` and `http://127.0.0.1:8989/custompath` (without trailing slash)
```
{"code":404,"message":"Not Found.","data":{}}
```
But works with `http://127.0.0.1:8989/custompath/index.html`

---
This does work
```go
	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		e.Router.GET(
			"/*",
			apis.StaticDirectoryHandler(site.DistDirFS, false),
			middleware.Gzip(),
		)

		return nil
	})
```

`http://127.0.0.1:8989/` redirects to `http://127.0.0.1:8989` and works.
`http://127.0.0.1:8989/index.html` works too.

Why, please?

Thank you!

**Comment by ganigeorgiev** [comment]
`http://127.0.0.1:8989/custompath` doesn't match the registered path, but `http://127.0.0.1:8989/custompath/` should work.

At the moment the latter is not working due to the `RemoveTrailingSlash` middleware that it is enabled by default for all routes.

I've added to the [roadmap](https://github.com/orgs/pocketbase/projects/2/views/1) to consider registering the middleware only for the `/api/` group routes in the next v0.14.0 release.

As a workaround, for now you can define your path as `/custompath*`.
