### ISSUE TITLE
Feature Request: The ability to specify an schema file when running the exe.

### ISSUE THREAD

**Issue by shadowoff09** [pocketbase/pocketbase#2081]
It would be great if PocketBase could support a schema file argument that the user can specify when running the PocketBase executable. This schema file would allow the user to define the structure and properties of the data that will be stored in PocketBase.

By including a schema file argument in the command-line interface, users would be able to define the data constraints and ensure that data adheres to a specific format. This would be particularly useful in cases where data needs to be consistent across different applications or systems.

The schema file argument would allow users to validate data upon insertion, ensuring that the data conforms to the defined structure and properties.

The schema file argument could be included in the PocketBase executable as a command-line option, such as `--schema pb_schema.json`. This would make it easy for users to integrate with other tools and scripts, as well as to automate the deployment and configuration of PocketBase instances.

Overall, adding a schema file argument to PocketBase would enhance its usability and functionality, making it a more powerful tool for storing and managing data.

**Comment by ganigeorgiev** [comment]
Hm, I don't think this is necessary since we already support migrations (aka. the files located in the `pb_migrations` directory).

You can generate a snapshot of your current collections configuration with `./pocketbase migrate collections`.

Migrations are automatically applied on `serve` (as long as there is a `pb_migrations` directory; for the prebuilt executable you can specify a different migrations dir location with the `--migrationsDir='/path/to/pb_migrations'` flag).
