### ISSUE TITLE
Can Go be used as a client?

### ISSUE THREAD

**Issue by gcstang** [pocketbase/pocketbase#22]
Very interesting project.

As there are some projects built in Go using HTML Templates and other frameworks and a UI (Fyne as well as others) will there be a client API or if this is already able to be used as a client in Go then documentation like you have for JS?

**Comment by ganigeorgiev** [comment]
Currently only Dart SDK is planned for the near future, since Flutter is a very common client for PocketBase.

I don't think I'll have the time to start and maintain a Go SDK client (at least for now [Presentator v3 remaining tasks](https://github.com/presentator/presentator/issues/183) are with higher priority).

As an alternative, you could also embed PocketBase in your existing Go app and directly interact with the database (see [DB Queries](https://pocketbase.io/docs/db-queries/) guide).

Community contributions are also more than welcomed.
