### ISSUE TITLE
Feature Request: "Parametrized" views

### ISSUE THREAD

**Issue by silberjan** [pocketbase/pocketbase#2242]
Lets say i want to build a small social network with pb and i have the collections `post`, `user` and `follow_relation`. 

- The `follow_relation` table is a join table to model the m:n relationship of users following other users
- The `post` table has an `author` column wich is a ref to the `user` who created the post

Now i would like to show a feed to a logged in user that only contains posts of the users they follow. AFAIK there are currently only 2 ways to achieve this:
1. Use PB as a framework, create an endpoint that looks up the follow relations based on the requesting user and return the posts that match
2. Create a view that joins the posts with the follow relation and then use the generic filter functionality to only return the relevant posts

Both of them are fine but 1. requires a lot of knowledge and 2. can result in huge views as soon as we talk about more than just a single simple join.

I think the complexity involved in simple look ups like this is still generic enough to consider adding an abstraction for this use case to admin interface. In my head it could look something like this:

- Add an additional "parametrized" view option when creating a collection
- Such collection would require to define one (or multiple?) required input parameters and a SQL statement that can reference the input params.
- To consume this a user would need to add the defined parameters as query string to the requests on the endpoint
- It could also be interesting to use the existing filter syntax that is used to authorize requests as input parameters. This way one could easily use the requesting user as input parameter.

**Comment by ganigeorgiev** [comment]
Sorry but for now this remains out of the scope for v1 since the "parameterized" views behavior is too ambiguous and it is not clear for me how this will work (what if users want to define different type of parameters - string, number, array, etc.; I'm not sure even how the Admin UI should look like in case no parameters are send with the request,).

If someone want to give it a try, feel free to open a PR and I'll review it but I think it will complicate too much the internals and for now I'm not planning working on it.
