### ISSUE TITLE
Feature Request: add PUT method on WebAPIs - Records - Update

### ISSUE THREAD

**Issue by M4rk3tt0** [pocketbase/pocketbase#2243]
Hi, I'm using a scripting language for a project and I'm connecting if to PocketBase through the WebAPIs.
The problem is that this scripting language doesn't support the PATCH method for the updates but only the PUT method.

Of course I could write a "proxy server" to receive the PUT request and then using the SDK to update the record, but I was wandering if the PUT method could be added in the WebAPIs. Thank you!

**Comment by ganigeorgiev** [comment]
Could you elaborate a little more about your use case and what scripting language you are using?

We can add an alias handler for the PATCH method but only if it is really necessary since I want to minimize having multiple ways of doing more or less the same thing.

**Comment by M4rk3tt0** [comment]
> Could you elaborate a little more about your use case and what scripting language you are using?

**Comment by M4rk3tt0** [comment]
> Could you elaborate a little more about your use case and what scripting language you are using?

I'm using the LSL Scripting Language that is used inside Second Life. Objects can connect to external resources using a function called [llHTTPRequest](https://wiki.secondlife.com/wiki/LlHTTPRequest) but it can handle only GET, POST, PUT and DELETE requests.

**Comment by ganigeorgiev** [comment]
Interesting language, first time hearing about it.

Sorry but I don't think the use case is very common and it may not be a good idea to have a `PUT` alongside the `PATCH` request in PocketBase because it could cause some confusion, especially if the `PUT` handler is just an alias and doesn't correspond to the common expected semantic of the HTTP verb.

I understand your use case but I think it would be better instead to file an issue or send a request to the Second Life developers/support.
