### ISSUE TITLE
Feature Request: Query Console

### ISSUE THREAD

**Issue by TylerJonesDNA** [pocketbase/pocketbase#2317]
Within the Admin UI, having a dedicated console to run SQLite queries would be nice. 
This could be especially useful when debugging queries that will be used to create View Collections.

Suggestions
- Multiple queries edited within their own "tab"
- Perhaps, within this console, buttons to "Save query as View Collection"
- Within the settings of an existing View Collection, add a button to "Debug Query", which will take the query and bring it into a new console tab.

**Comment by ganigeorgiev** [comment]
At least for now there are no plans to add support for executing raw SQL statements from the Admin UI since it could have unintended side-effects and will clutter the UI unnecessary.

Eventual support for executing raw sql statements via cli may be added as part of https://github.com/pocketbase/pocketbase/issues/2236.

I've added it in my todo to consider a "preview" for the View collections, but for now is a very low priority. If you have an idea how this could look like, feel free to file a PR and I'll review it.
