### ISSUE TITLE
Feature Request: Scalability

### ISSUE THREAD

**Issue by m00nyONE** [pocketbase/pocketbase#234]
Hey :-)

are you planning on implementing external database support such as PostgresSQL or others?
This would allow us to containerize PocketBase in Kubernetes & make it more scalable as there could be more than one instance running at the same time. This would increase the amount of requests and load handable. 
I know, this is against the "single executable file" policy but it would be nice if this could be optionally done. For example via environment variables.

**Comment by ganigeorgiev** [comment]
Hi,
Support for external SQL database is in the roadmap (with the lowest priority for now), but the reason to add it will be not because of scaling, but for having the option for deployment on hosts with ephemeral filesystem. You can follow this discussion - https://github.com/pocketbase/pocketbase/discussions/14#discussioncomment-3109447

About the scaling - the embedded database is not the only issue that prevents PocketBase to scale horizontally. Even if you deploy PocketBase on multiple servers and use an external database and file storage, there is currently no mechanism that will synchronize the multiple API instances - the event hooks,  the realtime connected clients, app specific cache, etc. they are all attached to a single app instance and this is why often application uses redis or similar in addition to the main database. This was also discussed here - https://github.com/pocketbase/pocketbase/discussions/71.

To keep it short - my recommendation is:
- first benchamark and see if a single server would be sufficient for your use case
- if it turn out that you really need horizontal scaling, then check the already existin great open source alternatives:
  [Supabase](https://supabase.com/), [Nhost](https://nhost.io/), [Appwrite](https://appwrite.io/), etc.

**Comment by ganigeorgiev** [comment]
The database is not the limitation here. PocketBase is simply NOT designed with horizontal scaling in mind and I have no plans changing that because I don't think it is needed.

In any case, this topic was discussed dozen times already and I would appreciate if users stop spamming me about "scaling" without providing even basic information about their use case. Just use something else please.
