### ISSUE TITLE
Required Boolean field does not work

### ISSUE THREAD

**Issue by ludwigHoon** [pocketbase/pocketbase#235]
In the UI, creating a new record with a required boolean field could not be saved if the selection is false (error 400: "validation_required", message: "Missing required value.")

![image](https://user-images.githubusercontent.com/30918181/181415770-043c2b7c-8d38-4b31-9073-5973bfa0c1f2.png)

**Comment by ganigeorgiev** [comment]
Hi, this was reported previously in https://github.com/pocketbase/pocketbase/pull/72.
All field values are normalized and non-nullable (see table with all supported values in https://github.com/pocketbase/pocketbase/issues/122#issuecomment-1186466209).

In short, the above validation is correct and intentional. Consider for example having a collection with "I agree checkbox" field - it's a lot easier for the developer to just mark the field as required and expect only `true` to pass the create/update validations.
Or in other words - if you want to allow `false` boolean values, don't mark the field as required.

In future versions, I will consider adding a comment somewhere in the Admin UI to make it more clear.
