### ISSUE TITLE
Feature request: Repeater field and Many to many relation

### ISSUE THREAD

**Issue by vtisnado** [pocketbase/pocketbase#2357]
Hi @ganigeorgiev it's me again hehe,

I'm continuing testing the platform and found couple features that would be awesome to have in the future, so I will let them here for you consideration:

**1. Repeater field:** This is a kind of field that allows to repeat any other field type or even repeat a group of fields. This is useful for the `ingredients` field I mentioned in previous suggestion, to display working hours, cinema movie schedule and so.
**2. Many to many relation** At the moment I see we can create `one-to-one` relations and `one-to-many`, but it will be nice to also have the option to create `many-to-many` relations.

Thanks again for taking the time to read these requests.

**Comment by ganigeorgiev** [comment]
Please don't file issues like that and instead create a dedicated issue for each request since it is hard to track them.

"Repeater/subcollection" type of field is in my todo to research it how feasible it would be but for now remains out of the scope for v1.

About the "Many to many relation" - I don't understand what exactly you have in mind and how this will work. Please file a new issue/discussion with more details and example expected usage.
