### ISSUE TITLE
Feature Request: S3 key prefix

### ISSUE THREAD

**Issue by kennethklee** [pocketbase/pocketbase#237]
When uploading via S3, files live directly in the bucket root. My S3 is used as a CDN, and I'd like to put a key prefix on the uploaded files.

i.e. instead of `https://cdn.myserver.com/<collectionId>/<recordId>/<filename>`, to `https://cdn.myserver.com/<prefix>/<collectionId>/<recordId>/<filename>`

**Comment by ganigeorgiev** [comment]
We can add support for additional prefix(es) to the existing 2 (aka. `/<collectionId>/<recordId>/`) but since the prefixes are currently set as part of the object name, the additional prefix will be active for both local and s3 filesystems which may cause some confusions down the road and may complicate the migration from one files storage to another if the option initially wasn't set.

Is there any particular reason why you cannot create a bucket only for your PocketBase files?
Most providers have distribution configurations and allow associating multiple buckets to a single CDN (eg. AWS Cloudfront).

Furthermore, PocketBase currently doesn't support fetching S3 blobs from a CDN address (https://github.com/pocketbase/pocketbase/issues/28) and will always fetch your files with the S3 API.

**Comment by kennethklee** [comment]
unfortunately my s3 (digital ocean spaces) doesn't support multi bucket cdn.

furthermore, I maaaay have extended pocketbase to give uploaded files `public-read` acl on s3 so that they can be used on a cdn.

I think I'll try configuring pocketbase to upload to a private bucket so that it works as normal. and then extend pocketbase with a duplicate upload to a cdn bucket.

thanks Gani

**Comment by ganigeorgiev** [comment]
@kennethklee I understand. I'll have to think a little more on this then.

I wouldn't recommend this, but there is hacky workaround by temporary changing the collection id in the before create/update hook that you could give a try:
```go
app.OnRecordBeforeCreateRequest().Add(func(e *core.RecordCreateEvent) error {
	e.Record.Collection().Id = "YOUR_PREFIX/" + e.Record.Collection().Id;
	return nil
})
app.OnRecordBeforeUpdateRequest().Add(func(e *core.RecordUpdateEvent) error {
	e.Record.Collection().Id = "YOUR_PREFIX/" + e.Record.Collection().Id;
	return nil
})
```

_I haven't tested the above, but in general it should work because we are using the Collection and Record model `BaseFilesPath()` to determine the stored location._

**Comment by ganigeorgiev** [comment]
_Old issues cleanup: I'm closing this as I don't plan working on it. In case a more prominent use case arise I may reconsider it but for now remains a low priority and the recommendation to use a custom bucket per app remains._
