### ISSUE TITLE
Admin change own password.

### ISSUE THREAD

**Issue by maxNodeJs** [pocketbase/pocketbase#2459]
Hi, Sorry if this already been posted and I missed it. And I hope I am not wasting your time.

When I change my own password as an Admin user ( in the Admin UI). I get update successful toast, then get signed out and the following errors show in the console.

1) is been signed out automatically after update an expected behaviour?

2) And are the following errors in console normal?

GET http://127.0.0.1:8090/api/settings 401 (Unauthorized)
GET http://127.0.0.1:8090/api/admins?page=1&perPage=100&sort=-created&filter= 401 (Unauthorized)
http://127.0.0.1:8090/api/settings 401 (Unauthorized)

ClientResponseError 401: The request requires valid admin authorization token to be set.
    at new e (index-3d896dce.js:4:21064)
    at index-3d896dce.js:4:61111

Failed to load app settings. ClientResponseError 401: Something went wrong while processing your request.
    at new e (index-3d896dce.js:4:21064)
    at index-3d896dce.js:4:61111
    at async p (index-3d896dce.js:211:2377)
    
Thanks for your help.

**Comment by ganigeorgiev** [comment]
> 1. is been signed out automatically after update an expected behaviour?

Yes, this is the correct behavior since changing password invalidates all previously issued tokens to ensure that there are no other "sessions".

> 2. And are the following errors in console normal?

Yes, those requests could be triggered after admin save and the 401 response(s) are actually the reason for the login redirect. We can avoid them if manually checking in the UI whether the admin update operation is for password change but I don't think it is worth complicating the codebase at the moment as the Admin UI will be refactored anyway with #898.
