### ISSUE TITLE
Feature request: Allow configuring the username regex.

### ISSUE THREAD

**Issue by jjgmckenzie** [pocketbase/pocketbase#2462]
> I'll consider adding in the documentation sometime later.
The username string must satisfy the ``^[\w][\w\.]*$`` regex (it could change in the future).

From https://github.com/pocketbase/pocketbase/discussions/1315#discussioncomment-4681667

I would like to use hyphens instead of underscores for usernames; which currently requires a middleware. I do not think allowing a regex configuration in the settings would significantly affect the maintainability of the project.

Thank you greatly for your hard work on this project; it is a very clever, elegant & easily deployable solution to a difficult problem.

**Comment by ganigeorgiev** [comment]
I was planning initially to allow configuring the username regex and min length as collection options but I dropped that idea in favor of making the username field entirely optional in the future in order to allow using any unique field as `identity` field, meaning that the `username` will be a regular `text` field and you'll have full control on its min/max length and the supported regex pattern.

I've outlined some of the idea in https://github.com/pocketbase/pocketbase/discussions/2425#discussioncomment-5818276.

This for now is a low priority but exists in my todo and will be implemented somewhere after v0.17.
