### ISSUE TITLE
Feature Request: add redirectUrl field in OAuth2AuthConfig for authWithOAuth2

### ISSUE THREAD

**Issue by Nikhil1920** [pocketbase/pocketbase#2581]
In the new Simplified OAuth2 authentication flow(#55) there is no option to specify a custom redirect url after the flow is completed

this will be useful in apps where deep linking is setup  and pocketbase backend is hosted on a different url

**Comment by ganigeorgiev** [comment]
This doesn't make much sense to me. The idea of the "all-in-one" call is to handle everything in the user app without redirect.

If you want to provide a custom redirect url and to handle a deeplink, you can use directly the ["Manual code exchange" flow](), aka. the "old" way (internally the "all-in-one" call is using it).

**Comment by einarpersson** [comment]
If I have
1. a SvelteKit application (using Pocketbase) on `mydomain.com`  (vercel)
2. a PB instance running on `https://mypbinstance.fly.dev` (fly.io)

does this men that I cannot use the Simplified OAuth2 authentication flow. Is that correct, or have I misunderstood?

**Comment by ganigeorgiev** [comment]
@einarpersson The "all-in-one" OAuth2 flow works only in environments where you can open a browser window (eg. in a client-side browser, cli or desktop application).

It won't work in a node server-side context (_unless you proxy it somehow_) because it requires a long running persistent HTTP connection to remain active during the entire OAuth2 signin/signup process.

**Comment by Nikhil1920** [comment]
@einarpersson it will work in your mentioned scenario the problem I had with it in my use case was that my svelte app is running in an android app so the user is not being automatically redirected to my app after authentication flow is completed just a go back message was being displayed
