### ISSUE TITLE
Feature Request: Real-time subscription 'before'

### ISSUE THREAD

**Issue by User00092** [pocketbase/pocketbase#2640]
I would like to propose the inclusion of ```"before": {<data>}``` in the real-time subscription to ```"action": "update"```.

This idea draws inspiration from discord's API, specifically the ```discord.on_user_update(before, after)``` event. Although it may not be widely utilized, it has the potential to be valuable in certain scenarios. To maintain backward compatibility, retain the existing ```"record": {<data>}``` structure and adding ```"before": {<data>}``` to the event data.

If implementing this change proves to be excessive, please do not feel pressured.

**Comment by ganigeorgiev** [comment]
It can be implemented without too much changes but I'm not sure how useful that would be because usually when you track updates client-side you already have the old/before record state somewhere (eg. fetched from a getList/getOne call) and we may end up sending too much unnecessary information which could further increase the messages latency.

Do you have a real use case for it? How do you plan to use it?

**Comment by User00092** [comment]
Message latency is a concern, which could be solved by:
```js
pb.collection('---').subscribe('*', function (e) {
    console.log(e.record);
}, true);
```
```true``` representing ```include_before_data```. While this would add another check to the pb backend, it would reduce payload when sending an event if the extra information is not wanted. ```include_before_data``` defaulting to ```false```, obviously.

My case for it is outside client side usage, being used in the backend. For instance, when the email successfully changes, you could check if `e.before.email !=== e.record.email` and log the change, or send an email to the `e.before.email` saying their email successfully changed. Sure, this can be done client side too, but it is an example of possible usage.

Another usage would be hiding sensitive data, such as SMTP login or admin login, in the event the client app was cracked. By having the ability to know previous data, I can track changes in the database as well as I could client-side, while protecting the information that matters the most.

**Comment by ganigeorgiev** [comment]
I don't think the suggested flag proposal is good idea because it will work only with the `update` action and it doesn't make much sense to have it for every other `subscribe` action and topic.

I could understand the first example when you have another middleware service involved, but I don't understand the other one with _"hiding sensitive data, such as SMTP login or admin login".

In general, if you need more control over the realtime events you can attach to the [Go app hooks](https://pocketbase.io/docs/event-hooks/) (_soon there will be an option to attach to the app hooks with JS too_). The realtime APIs relies on the `OnModel*` hooks.

I'll close the issue for now as I think the cons outweigh the pros, but depending on the users demand and the eventual blocker use cases that could arise, I may reconsider it in the future.

**Comment by User00092** [comment]
Okay! Thank you for your consideration, it's much appreciated.
