### ISSUE TITLE
Example to create a user doesn't qualify to default setting for min password length

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/pocketbase#27]
First, great project!

Second, do you prefer us to post found typos / suggested corrections as separate issues, or as comments under one, or?

Third, my latest find:

"Create user" API call on https://pocketbase.io/docs/api-users/ has example creating user with password "123456". But default settings (in http://localhost:8090/_/#/settings/auth-providers - Email/Password) seem to specify Minimum password length of 8. In which case, the example API call fails with return code 400 :)

Not sure if it's by design or not.

**Comment by ganigeorgiev** [comment]
Separate issues are OK.

About the user password length - it is just an example. The default user password length is 8 characters but it could be changed from "Settings > Auth providers > Email/Password" options.

**Comment by Lex-2008** [comment]
Yes, I know! Sorry I wasn't clear - my suggestion here is to change the example to have a longer password ("12345678", for example) - this way copy-pasting from example into fresh installation will "just work".

**Comment by ganigeorgiev** [comment]
On a second thought, I think its better to leave it "123456" since the default min password length could change in future and this way it is consistent with the admin api examples (for admins the min password length is 10, currently not configurable).

In the end, it is just an example and the error code and message in the error response should be clear enough for most users to see that there is a password length validator behind the scenes.
