### ISSUE TITLE
Collect schema field FieldTypeBool does not save "false"

### ISSUE THREAD

**Issue by mbecker** [pocketbase/pocketbase#270]
Hi,

I have the following custom DB migration file with a schema field `FieldTypeBool` which is `required`:

```go
...
&schema.SchemaField{
	Name:     EmailValid,
	Type:     schema.FieldTypeBool,
	Options:  &schema.BoolOptions{},
	Required: true,
	Unique:   false,
},
...
```

I'm trying to save the record with the value `false` (or `int(0)` or `"false"` or `nil`) as follows:
```go
// Values like false, int(0), "false", nil doesn't work either
rec := models.NewRecord(emailCollection)
rec.SetDataValue(migrations.EmailValid, false)
err = forms.NewRecordUpsert(app, rec).Submit()

// This results in the error: valid: Missing required value
```

The same code with the value `true` does work as expected.

How can I save a boolean value `false` in the database? Thanks for your help!

Different question, but related to schema fields / database: Is it possible to have a composite key / constraint like the combination of userId and email must be unique? (Don't know if this works in sqlite in general; haven't yet looked for it)

Thanks guys!

**Comment by ganigeorgiev** [comment]
Required `bool` type fields can be only `true`. This is because since v0.3.0 PocketBase doesn't handle `null` values anymore and uses the respective zero-value as default (see the table in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0)

So to allow `false` you'll have to set `Required` to `false` for the field.

About the composite unique key/constraint - you cannot do it from the Admin UI but you could create a composite unique index  (that will also add a unique constraint) with the raw query:
```sql
CREATE UNIQUE INDEX combined_unique_idx ON YOUR_TABLE (field1, field2, field3);
```
