### ISSUE TITLE
Bug: Backups don't work with 5GB 

### ISSUE THREAD

**Issue by pyronaur** [pocketbase/pocketbase#2721]
I created a new DB today and filled it with ~5GB of png files (~1-3mb each), about 5000 rows more or less.

I backed up the db successfully from the UI before adding images, and after I've added the images - I can no longer backup. At first, I thought this is just taking its time, but looking at `top` I don't see Pocketbase doing anything, so either 5GB backups take more than 30 min, or maybe it crashes silently in there?

**Comment by ganigeorgiev** [comment]
Are there any stdout/stderr logs? Do you have enough free disk space?
Could you check your total `pb_data` directory size?

It is possible that the zip compression needs more time as its visit each file one by one (_we may also have to adjust the compression level as we currently use the default_). I'll try to test it sometime later this week and will see if I can reproduce it.

**Comment by pyronaur** [comment]
Yep, it's the disk space. Weird how 5 GB of files take more than 7GB free space to compress.

```
2023/06/16 05:47:04 blob (key "after-image-uploads.zip") (code=Unknown): write /home/[.....]/pb_data/backups/after-image-uploads.zip.17690d8893615e0a.tmp: no space left on device
```

Well, not a bug then. Thanks!

**Comment by ganigeorgiev** [comment]
Thanks for checking the logs. It is possible that the zip may require more space then the actual file that it is compressing because we have to store a header and a descriptor for each file.

There is definitely room for improvements from our end since for the zip generation we use the std Go `archive/zip` package with the default [`zip.Deflate` compression](https://pkg.go.dev/archive/zip#pkg-constants) (the only other available builtin option is `zip.Store` which is used for no compression at all and will produce even larger file). I'll try to find some time next week to experiment with different approaches to see if we can reduce the initial required disk space and/or speed up the overall process a little.

**Comment by pyronaur** [comment]
I think that's alright - this was an edge case when the disk space is low. An easier fix than dealing with better compression would probably be a UI message warning of disk space is too low.
