### ISSUE TITLE
Changing the OAuth2 account email will create a new PocketBase user

### ISSUE THREAD

**Issue by zzzhouuu** [pocketbase/pocketbase#276]
According to the current design, the Auth process will use email to constrain whether to create a new account, but in a third party (github) we can modify the email address of the current account, at this time in the login / registration will be because the mailbox will be changed will create a new account and then the problem of data loss.  The unique identifier of this provider corresponds to the account number and not to the email address

![CleanShot1](https://s3.bmp.ovh/imgs/2022/08/08/ef571b9fefebb1b1.png)

![CleanShot2](https://s3.bmp.ovh/imgs/2022/08/08/751beaa685bccb16.png)

The design below is the way we are currently using it:

```sql
create table users (
  id serial primary key,
  username citext not null unique check(username ~ '^[a-zA-Z]([a-zA-Z0-9][_]?)+$'),
  name text,
  avatar_url text check(avatar_url ~ '^https?://[^/]+'),
	is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table user_emails (
  id serial primary key,
  user_id int not null default current_user_id() references app_public.users on delete cascade,
  email citext not null check (email ~ '[^@]+@[^@]+\.[^@]+'),
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, email)
);

create table user_phones (
  id serial primary key,
  user_id int not null default current_user_id() references app_public.users on delete cascade,
  phone citext not null ,
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, phone)
);

create table  user_authentications (
  id serial primary key,
  user_id int not null default current_user_id() references app_public.users on delete cascade,
  service text not null,
  identifier text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uniq_user_authentications unique(service, identifier)
);
```
This can be authorized by username/email/phone + password， email/phone + passcode , multiple social connectors

**Comment by zzzhouuu** [comment]
Sample identities from a user who signed in with both WeChat and Facebook:
```json
{
  "facebook": {
    "userId": "5110888888888888",
    "details": {
      "id": "5110888888888888",
      "name": "John Joe",
      "email": "johnjoe@logto.io",
      "avatar": "https://example.com/avatar.png"
    }
  },
  "wechat": {
    "userId": "O8sU-6JWMMNZzuXo6-xaEjouyQZ8",
    "details": {
      "id": "O8sU-6JWMMNZzuXo6-xaEjouyQZ8",
      "name": "John Joe",
      "avatar": "https://example.com/avatar.png"
    }
  }
}
```

**Comment by ganigeorgiev** [comment]
That's correct - currently, once the OAuth2 account change its email, we will "lost" the link with the PocketBase user and will create a new one.

In future versions, I'll consider adding a secondary table, similar to your example, that will store the relation between the OAuth2 account and the PocketBase user and in case the OAuth2 email change we'll update accordingly the PocketBase user email (the email sync need to happen because otherwise it will be a security issue if someone has access to the old email).

**Comment by zzzhouuu** [comment]
I think this adjustment should be prioritized, otherwise it will involve the problem of account migration in the later stage and will affect the contributions related to OAuth

**Comment by ganigeorgiev** [comment]
@zzzhouuu The adjustment doesn't require changes in the OAuth2 provider interface and will be backwards compatible.

I will consider implementing it in v0.5 or v0.6 release.

**Comment by ganigeorgiev** [comment]
@zzzhouuu This is now implemented in [v0.6.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.6.0).

**Comment by mbecker** [comment]
Looking at the referenced commit [https://github.com/pocketbase/pocketbase/commit/f5ff7193a94a3a04942b7fa8e4a87f8fb9e443c8](https://github.com/pocketbase/pocketbase/commit/f5ff7193a94a3a04942b7fa8e4a87f8fb9e443c8) and the described uses case I've still some challenges to understand how the linking process of an "signed in user" with a new OAuth provider which does not return the same email / no email works.

The referenced commit has only methods like "Delete, Find, List" but bot method to add a linked oauth provider to a user.

My understanding of the use case is as follows:
```sh
User signs up with email / password
User confirms email address
User signs in (response is auth token)
User links (authenticate) an oauth provider (different email or no email)
User signs out
User signs in with the linked oauth provider
```

Does this work? Is this implemented in the referenced commit and released in v0.6.0?

Thanks for your clarification!

**Comment by ganigeorgiev** [comment]
@mbecker This issue and the related commit is not for that. The implemented solution is when the user decide to change their OAuth2 email after already authenticated in PocketBase, aka. the following flow:
- user authenticate in PocketBase with an OAuth2 provider
- we create a user account with the associated OAuth2 profile email and id
- the user decides to change their OAuth2 profile email
- next time when authenticating again in PocketBase instead of creating a new user account, we will link the previously created user by the OAuth2_id-user_id relation in the _externalAuths table.

Because the first linking (aka. user creation) is done via the OAuth2 profile id, we now supports providers that doesn't return an email address, like Twitter for example. Of course, if the user doesn't have an email we can't allow automatically linking multiple OAuth2 authentications to the same user account because each provider uses different ids.

If you want to manually link an OAuth2 authentication to an existing user account, you can create a `models.ExternalAuth` instance and save it.

```go
rel := &models.ExternalAuth{
    UserId: "YOUR_USER_ID",
    Provider: "google",
    ProviderId: "YOUR_OAUTH2_PROVIDER_ID",
}

if err := app.Dao().SaveExternalAuth(rel); err != nil {
    return err
}
```

**Comment by mbecker** [comment]
Hi @ganigeorgiev , thanks for the detailed description. Great that this use cases has added more or less the feature of linking additional OAuth 2.0 providers :-) I've thought about this the last days. Thanks for sharing the sample code to add manually an OAuth 2.0 provider. I would like to see some built-in methods (backend / client SDK) to link the OAuth 2.0 providers.

I think that the Client SDK methods must be extended as follows:

```javascript
client.users.authViaOAuth2(clientName, code, codeVerifier, redirectUrl, bodyParams = {}, queryParams = {})
-> Add the token to the http request if the token exists in the auth store (I think this is already globally implemented for all http requests by you)
````

On the backend I think the checks in requesting the OAuth 2.0 access token and adding user model, oauth relation must be extended as well to check if the request includes a  token and if yes extract the user from the access token:
https://github.com/pocketbase/pocketbase/blob/b79a7982bf29c274036f3d0d226a45dd4e62cca1/forms/user_oauth2_login.go#L129

```go
if TOKEN {
  user = EXTRACT_USER_FROM_TOKEN(TOKEN)
} else if rel != nil {
  rel, _ := form.config.Dao.FindExternalAuthByProvider(form.Provider, authData.Id)
  user, err = form.config.Dao.FindUserById(rel.UserId)
  if err != nil {
	return nil, authData, err
  }
} else if authData.Email != "" {
  // look for an existing user by the external user's email
  user, _ = form.config.Dao.FindUserByEmail(authData.Email)
}
```

Does this makes sense?

**Comment by ganigeorgiev** [comment]
@mbecker Yes, that makes sense. I'll consider it when reworking the forms in #376, although it may not be expected by everyone and we'll have to document it properly or add an extra argument/config object to explicitely send the authentication header (currently it is excluded from the auth requests - https://github.com/pocketbase/js-sdk/blob/master/src/services/Users.ts#L132,  because there is server-side validation that allow the route only for "guests").
