### ISSUE TITLE
Feature request: Logs routes with filter in query

### ISSUE THREAD

**Issue by pnmcosta** [pocketbase/pocketbase#2766]
Currently if you go to the admin's `/_/#/logs` any changes to the filter does not update the url route as record lists do. This is really handy to keep bookmarks for. 

Happy to contribute if not planned for yet.

**Comment by ganigeorgiev** [comment]
It could be added but it might be better to implement it together with the logs generations as the logs page will change anyway.

**Comment by pnmcosta** [comment]
Though so, cool. Looking forward to logging update. It would be great to find out more about it. Any chance you could share some details? Don't expect commitment.

**Comment by ganigeorgiev** [comment]
Sorry, I haven't thought much on the implementation yet. The general idea is to allow any type of logs, not just requests, including custom logs triggered from within the application, eg. something like:

```go
app.LogInfo("something has happened...", anything_extra)
```

I haven't decided yet on the log data structure, but probably we'll have minimum `type` (system types + anything custom), `message`, `data`(json) fields. The detailed log visualization in the UI (and how the `data` field will be parsed) could differ depending on the `type` field value.

**Comment by pnmcosta** [comment]
That looks good, so one of the `type`'s would be `request` for the current request logs?

It would be nice if request's logs to be `context` aware, and by this I specifically mean headers, for example it would be nice that the logged entry for a particular request inherits the `X_REQUEST_ID`, if using https://echo.labstack.com/middleware/request-id/, and potentially that other `type` log entry could inherit it too for their structured data, from a `context`.

It would also be nice to have opentelemetry optionally, but I think that might be another convo.

**Comment by gerryfletch** [comment]
> It would also be nice to have opentelemetry optionally, but I think that might be another convo.

This is definitely worth its own thread, OT would be a _huge_ win.

**Comment by blackfyre** [comment]
👍 For OpenTelemetry but as @gerryfletch has mentioned... it might be a different conversation

**Comment by ganigeorgiev** [comment]
The listing filters are now preserved with the refactored logs. The changes will be available with the upcoming v0.20.0 release sometime later today.

**Comment by ganigeorgiev** [comment]
@pnmcosta I'll consider allowing users to specify custom activity log attributes via a reserved `echo.Context` key (either via a middleware or route), but for now there are no plans to add the request headers out of the box as it could be unsafe and difficult to generalize.

With the internals refactoring after the Presentator release, there will be also app level hooks for the logs so that users will be able to intercept or redact some the logs, but there will be more info about this in the near future.

Alternatively, if you want to keep track of your user requests you can add your request/client identifier as query parameter (if you use the JS SDK it can be registered globally using the [`onBeforeSend` hook](https://github.com/pocketbase/js-sdk#send-hooks)).
