### ISSUE TITLE
Incorrect content-type being returned for jpg

### ISSUE THREAD

**Issue by kvnlnt** [pocketbase/pocketbase#2781]
My image field allows jpg, png etc except it returns a content-type of png for everything. 

Here are the results of a `curl -I https://localhost:8080/api/files/podcast/vssjja7gihpj60z/test-image.jpg` call:

```bash
HTTP/2 200
accept-ranges: bytes
alt-svc: h3=":8080"; ma=2592000
cache-control: max-age=2592000, stale-while-revalidate=86400
content-disposition: inline; filename=test-image.jpg
content-security-policy: default-src 'none'; media-src 'self'; style-src 'unsafe-inline'; sandbox
content-type: image/png # <======== should be image/jpg
date: Fri, 23 Jun 2023 15:33:56 GMT
last-modified: Fri, 23 Jun 2023 15:33:12 GMT
server: Caddy
vary: Origin
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-length: 814668
```

![image](https://github.com/pocketbase/pocketbase/assets/577412/99e3cc4d-6a0a-40bc-82af-2c955872c605)

**Comment by ganigeorgiev** [comment]
Additionally, if in your example the `test-image.jpg` file is thumb uploaded before https://github.com/pocketbase/pocketbase/issues/440, it is possible to be a `png` since before the related issue commit we were compressing any thumbs as png (as mentioned earlier the file extension doesn't really matter in this case).
