### ISSUE TITLE
Required boolean field can't be set to false in admin dashboard

### ISSUE THREAD

**Issue by abeisgoat** [pocketbase/pocketbase#283]
Hello! Thanks for the cool project!

If you create a boolean field which is required, it can't be set to false in the admin UI, it says that the field is required when obviously "false" should be a valid value for a bool.

**Comment by ganigeorgiev** [comment]
Hi, this was reported previously (most recently in https://github.com/pocketbase/pocketbase/issues/270). I'll consider adding a help-text/tooltip somewhere in the UI to make it more clear.

In short - If you want to allow your boolean field to have a `false` value just remove the required constraint.

This is because since v0.3.0 PocketBase no longer support `null` as value for the record fields - more details and table with supported values you could find in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0.
Similar as in go, all field values have a default "zero-value", which for bool that is `false`. So in other words, even if you send `null` as body param value, it will be normalized and stored as `false`.

The required constraint doesn't allow "zero-values" and this helps to simplify a lot of user-land code, at least in my opinion, because for example if you have "I agree" checkbox, the only thing that the developer will need to do is to mark the field as required and the validator will prevent create/update if someone tries to submit without marking the checkbox.
