### ISSUE TITLE
Feature Request: Update all records at once

### ISSUE THREAD

**Issue by Voxeliorn** [pocketbase/pocketbase#2834]
Basically, a feature to change a field on every record at once :)

**Comment by ganigeorgiev** [comment]
There are no plans to add web APIs for this since it will be very uneffecient if we had to trigger individually the update hooks for each record inside the collection, but you can do this in a more performant way already when [using PocketBase as framework](https://pocketbase.io/docs/use-as-framework/) either in a migration script (Go/JS) or in custom route (Go). Here is an example in a JS migration:

```js
migrate((db) => {
  // set "pending" status to all articles with empty status field
  db.newQuery("UPDATE articles SET status = 'pending' WHERE status = ''").execute()
}, null)
```

_Better documentation regarding this will be available with the next release._
