### ISSUE TITLE
CLI command to backup

### ISSUE THREAD

**Issue by jeffrey0606** [pocketbase/pocketbase#2839]
Please can we have the backups features/functionality already available via the PocketBase admin dashboard as CLI command?
ex: `./pocketbase backup`

I will like add it to my deployment workflow.
to make sure I backup the previous version of the DB to my S3 bucket before any update.

Jeffrey.

**Comment by ganigeorgiev** [comment]
I'm not sure, since it can get misused if you run the cli command while the PocketBase server is running because the write db lock will not work as expected in this case as you'll have 2 different app processes.

I may reconsider it in the future but for now if you use PocketBase as framework you can register the command on your own:

```go
package main

import (
	"context"
	"log"

	"github.com/pocketbase/pocketbase"
	"github.com/spf13/cobra"
)

func main() {
	app := pocketbase.New()

	app.RootCmd.AddCommand(&cobra.Command{
		Use:   "backup",
		Short: "Creates pb_data backup",
		Run: func(cmd *cobra.Command, args []string) {
			if err := app.CreateBackup(context.Background(), ""); err != nil {
				log.Println("Failed to create backup")
			}
		},
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by jeffrey0606** [comment]
Thank you @ganigeorgiev . will do exactly that
