### ISSUE TITLE
Feature Request: Implement soft delete by default

### ISSUE THREAD

**Issue by skowrons** [pocketbase/pocketbase#2866]
# Use Case:
Soft delete is a common feature that allows data to be marked as deleted without actually removing it from the database. This enables the recovery of mistakenly deleted data, and also maintains the historical record for audit purposes. Currently, users have to manually implement this feature, which can lead to inconsistencies and extra work.

# Description:
We propose to implement soft delete by default for every collection. Users should also have the ability to deactivate this feature if desired. Currently, tools like Gorm (insert link to the documentation here) use a "deleted" timestamp and filter out all issues where this timestamp is set. We suggest a similar approach.

# Implementation:
The main aspect of the implementation will be adding a "deleted" timestamp column to all collections. This column will mark when an item was "deleted", without actually removing the item from the database. Secondly, all API functions that retrieve data will need to be updated to filter out the items marked as deleted, unless specifically requested.

# Requirements:
- Add a "deleted" timestamp column to all collections.
- Modify all API retrieval functions to filter out items marked as deleted.
- Provide an option for users to deactivate the soft delete feature.
- Update the API to include functionality that allows retrieval of items marked as deleted when specifically requested.

# Advantages:
- Consistent functionality across all collections.
- Users can recover mistakenly deleted data.
- Decreased need for manual implementation by users.
- Maintains a historical record of all data, which can be beneficial for auditing purposes.

# Workaround for users that will implement it on there own:
Currently, users can manually implement this feature by adding the "deleted" timestamp column and modifying their queries to filter out items where this timestamp is set. However, this can lead to inconsistencies and adds an extra layer of work for the users. The proposed implementation would streamline the process and ensure consistent functionality across all collections.

**Comment by ganigeorgiev** [comment]
This was suggested before, but I'm not sure if it can be generalized so easily.
How the soft-delete will reflect in the relation fields - will the record id will be removed from the relation field or delete the parent in case a cascade delete is set?

**Comment by JFGHT** [comment]
> This was suggested before, but I'm not sure if it can be generalized so easily. How the soft-delete will reflect in the relation fields - will the record id be removed from the relation field or will delete the parent in case a cascade delete is set?

Both options with the cascade optionality to be soft-delete too?

**Comment by ganigeorgiev** [comment]
@JFGHT This doesn't makes sense to me. If you have an idea how this could be implemented, feel free to outline the implementation details and I'll have a look at it.

I'm closing the issue for now as I don't think this could be handled in a general way (_especially the revert/restore operation_).

**Comment by joachimBrindeau** [comment]
Hello,

This might sound like a candid question, but as I see it, soft delete is just delayed hard delete.

I am planning soft delete on the app I am building and I fear I am missing something. What is the concern related to reverting changes?

My understanding was that soft delete would have the exact same logic as delete (including cascading logic) but it’s just an order to delete at a certain timestamp. 

So the “deleted” field would cascade the same way the hard delete does (so filtering out soft delete would also hide what would have been hard deleted).

I hope I am clear, don’t know if I am missing something obvious.

Cheers.
Joachim

PS: apologies for the rogue PR earlier today, I had this idea and told Claude to challenge its implementation. It went rogue because I had temporarily bypassed permissions to test an MCP I am building… again, sorry about that. If you can delete it, I would appreciate it.

**Comment by ganigeorgiev** [comment]
@joachimBrindeau It can be easy or complicated depending on your use case. My concern regarding the revert/restore was mostly when mixed relations are involved (aka. relations between soft and hard deleted records).

Also things like API rules and direct DB operations like `FindRecordById` is also not clear whether they should use the flag automatically since they may not rely on any access controls (aka. they may execute in a non-request context where there is no information whether the action was initiated by superuser or somebody else). View queries are also another thing that users will have to keep in mind when interacting with such collections. There are probably  other edge cases that I can't think of at the moment and it is just difficult to generalize, so it is better to leave to the users to implement it externally on their own until a more prominent and clear use case arise.
