### ISSUE TITLE
Rich editor fields convert links from '/foo/bar' to '../foo/bar'

### ISSUE THREAD

**Issue by adamshand** [pocketbase/pocketbase#2871]
When using the rich editor:

- create a link with a target of "/foo/bar" 
- view the source (before or after saving) and the target has been changed to "../foo/bar"

This seems like a bug, but perhaps there's a reason that absolute URLs aren't allowed?

![image](https://github.com/pocketbase/pocketbase/assets/130651/3d9084f4-83da-4e17-a434-1a3b17b3013f)

![image](https://github.com/pocketbase/pocketbase/assets/130651/0724013f-08e1-4257-8210-bfde903c9bf5)

**Comment by ganigeorgiev** [comment]
This is similar to https://github.com/pocketbase/pocketbase/discussions/1975#discussioncomment-5206644.

In short - it is a default TinyMCE configuration and I think it is better to keep it as relative path since it allows more easily migrations between environments (_eventually in the future I may consider making it configurable together with a "media" plugin that will allow browsing and import all collections with file fields_).
