### ISSUE TITLE
[Feature] Request Add and Custom more email template

### ISSUE THREAD

**Issue by nguyenthanhtien** [pocketbase/pocketbase#2918]
Hi all,

I think Pocketbase should allow user Add and Customize email template (with parameter) in Mail Settings for Pocketbase, it's easy for dev config and send email for application.

**Comment by ganigeorgiev** [comment]
This is out of the scope for now because it is not clear to me what the flow should be. Even if we allow custom templates, how this templates will be triggered?

Detailed guide how to send custom emails (with both Go and JS) will be available soon. Eventually in the future we may add UI for the emails as part of #317, but for now this is remains a low priority.

You can also check https://github.com/pocketbase/pocketbase/issues/2111, which is kept as a reminder to eventually add sometime in the future admin-only web API for sending emails.
