### ISSUE TITLE
Bug: Api rule filters bug on multiselect relation fields

### ISSUE THREAD

**Issue by GD-coding** [pocketbase/pocketbase#2930]
There seems to be an issue with the multiselect :length operator when using it on relational fields. The below example is not working in my case.

`@request.auth.admin = true || users:length = 0 || users.id ?= @request.auth.id`

<img width="646" alt="image" src="https://github.com/pocketbase/pocketbase/assets/63622794/50670ceb-9197-4551-9c21-b3c5f6cdf89c">

The code works when the user is an admin or is in the list of related fields, but the :length operator is not working when trying to check if the property is empty.

Version 16.9

Thank you for all of the hard work that you do on this project!

**Comment by ganigeorgiev** [comment]
I suspect that the `users` field was added at later stage when there were already records in the collections, right? If that's the case then it is possible that default inserted value would be empty `""`string  and not `[]` because we currently don't normalize the default/missing value for already inserted data.

I'll have a look at it sometime later today, but as a workaround, if your field doesn't have more than 1 user yet assigned to it, you can try to change the `users` field to "single" and then back to "multiple" to retrigger the field value normalization.
