### ISSUE TITLE
Unable to display PDF in browser or to embed them

### ISSUE THREAD

**Issue by ByScripts** [pocketbase/pocketbase#294]
Hello,

First of all, thank you for PocketBase which is really a great product, really easy to use and that "just works".

I encounter a little problem with PDF attachment.

The files are served with `Content-Disposition: attachment; filename=....pdf`, thus it prevents opening them directly in the browser.

The other problem is that PDF cannot be embedded directly in an `iframe` (this triggers the download of the file).

Could it be possible to add an option to get a `Content-Disposition: inline; filename="....pdf"` header instead?

Thank you.

**Comment by ganigeorgiev** [comment]
I'll consider adding an exception for the `application/pdf` mime type for the next release.

This was done for security to avoid accidentally executing malicious script. Currently some common image and video mime types are enabled (you could read more here - https://github.com/pocketbase/pocketbase/discussions/164#discussioncomment-3196837).

Since we now have a default CSP for both the Admin UI and the File serving endpoint, it should be ok to allow some other common mime types too (eg. audio files).

**Comment by ganigeorgiev** [comment]
I've just pushed a fix in `master` that adds the pdf mime type to the exceptions list.
It will be publicly available with the next feature/bugfix release (~ next week or the week following it).
