### ISSUE TITLE
feature request: Validate JWT Token Endpoint

### ISSUE THREAD

**Issue by Autumnlight02** [pocketbase/pocketbase#2997]
Currently If you would like to run a normal backend you need to refresh the auth token and that generates a bit of overhead. To allow pocketbase to easily integrate with custom backends it would just need (imo) a endpoint to validate if a given token is valid. If we had this we could do other kinds of more complex validations (which are for example hard to do in pocketbase).
I also think that this implementation would not take much time at all since we could just slice half the refresh token backend and return if its valid or not

**Comment by ganigeorgiev** [comment]
For now there are no plans for this as it may add unnecessary confusion what APIs to use.

I'll consider adding a test in the [benchmarks repo](https://github.com/pocketbase/benchmarks) sometime later this week, but I don't think the HS256 token generation has any significant impact on the performance. Additionally having an endpoint that will just check whether a token is valid or not may not be that useful because most of the time you'll need the user data anyway.

**Comment by ganigeorgiev** [comment]
Just for info below are results from my ancient laptop (_8GB RAM, i5 CPU_) comparing the fetch of a public user by its id (_aka. the fastest scenario - fetch by primary key, no rules, no authentication_) **VS** `authRefresh()` (_it performs fetch by primary key, token verification and token generation_).

The results show that the difference between the 2 is negligible (note that even if we had a dedicated token validate action you still have to perform the token verification, which usually the "slow part" because we have to check not only the secret but the other token claims).

Tomorrow I'll submit the updated tests in the benchmarks repo with results from the Hetzner VPS (both with Go and CGO), Fly and Hop.

---

## List records
#### users - getOne for auth-refresh comparison (high concurrency) [reqs:1000, conc:1000, rule:`""`, query:`/2fjwpm5dv7jl7zu`]
```
┌─ Best:      126.006505ms
├─ Worst:     816.41113ms
├─ Completed: 823.690849ms
└─ Errors:    0
```
#### users - getOne for auth-refresh comparison (medium concurrency) [reqs:1000, conc:100, rule:`""`, query:`/2fjwpm5dv7jl7zu`]
```
┌─ Best:      4.022329ms
├─ Worst:     376.740587ms
├─ Completed: 959.969796ms
└─ Errors:    0
```

## User auth refresh
#### users auth refresh - high concurrency [reqs:1000, conc:1000]
```
┌─ Best:      189.241049ms
├─ Worst:     959.085336ms
├─ Completed: 983.969796ms
└─ Errors:    0
```
#### users auth refresh - medium concurrency [reqs:1000, conc:100]
```
┌─ Best:      5.184422ms
├─ Worst:     289.038639ms
├─ Completed: 891.631588ms
└─ Errors:    0
```

**Comment by Autumnlight02** [comment]
yikes, you right, also what i later on noticed was that i was confusing this api with the cognito one. (cognito one has on the jwt token the user data)
