### ISSUE TITLE
Vulnerability of dependency "github.com/labstack/echo"

### ISSUE THREAD

**Issue by Silence-worker-02** [pocketbase/pocketbase#3015]
Hello, we are a team researching the dependency management mechanism of Golang. During our analysis, we came across your project and noticed that it contains a vulnerability (CVE-2022-40083). In your project, the github.com/labstack/echo package is being used at version github.com/labstack/echo/v5 v5.0.0-20220201181537-ed2888cfa198, this is a pseudo-version, and the v5 is a alpha branch. The patch version is v4.9.0, and the fixing commit released in 2022-09-04, the pseudo-version that you used was released in 2022-02-01. To fix the vulnerability, we recommend modifying the go.mod file to update the version to v4.9.0 or higher, and not used v5. Thank you for your attention to this matter.

**Comment by ganigeorgiev** [comment]
I'm not sure if this is a bot account but please when reporting security issues consider checking first the [Security policy](https://github.com/pocketbase/pocketbase/security/policy).

In any case, we are not affected by this because we don't use the default echo Static serve action and has our own static directory handler.

Additionally, echo `v5_alpha` branch was recently synced with the changes from the echo `master` branch, so with the upcoming PocketBase v0.17.0 release this will no longer be an issue even in case user uses the default echo handlers.

**Comment by Silence-worker-02** [comment]
Thank you for your reply. We assure you that we are not a bot account. Regarding the v5_alpha version that you used, the commit was released on 2022-02-01(https://github.com/labstack/echo/commit/ed2888cfa198), but the fixing commit(https://github.com/labstack/echo/commit/0ac4d74402391912ff6da733bb09fd4c3980b4e1) was released on 2022-09-04. If you update the dependency to the latest v5_alpha version, the issue should be resolved. Additionally, if the dependency is not be used in the next version, it will not pose any vulnerability concerns. Thank you for your attention.
