### ISSUE TITLE
Bug: updating record data in hook automatically commits to the database

### ISSUE THREAD

**Issue by SunPodder** [pocketbase/pocketbase#3027]
I was writing a hook for my app to assign users with a default avatar.
```js
onRecordsListRequest((e) => {
    e.records = e.records.map((user) => {
        if (!user.get("avatar")) user.set("avatar", "https://api.dicebear.com/6.x/pixel-art/svg?seed=" +
            user.get("username") +
            "&background=%23fff&radius=50")

        return user
    });
}, "users");
```
But I noticed this updates the database value even though I'm doing nothing related to database here. Updating the records in a hook should only update the response object instead of committing to the database.

**Comment by ganigeorgiev** [comment]
The changes are not "committed" or persisted in the database.

What you are practically doing is overwritting the users list response, **but this same list/search API is used by the Admin UI, aka. you are just seeing the above change in the Admin UI.**

If you want to ignore the change for the Admin UI, you can check whether there is an admin authenticated - see https://pocketbase.io/docs/js-routing/#retrieving-the-current-auth-state.
In your case that could look something like:

```js
onRecordsListRequest((e) => {
    const admin = e.httpContext.get("admin");

    e.records = e.records.map((user) => {
        if (!user.get("avatar") && !admin) {
            user.set("avatar", "https://api.dicebear.com/6.x/pixel-art/svg?seed=" +
                user.get("username") +
                "&background=%23fff&radius=50")
        }

        return user
    });
}, "users");
```

Also if `avatar` in the above is a file field I'd advice against doing the above, because you are the new value type technically will be different compared to the original field value. The better approach in my opinion would be to have the default avatar set client-side.
