### ISSUE TITLE
Extend with Dart

### ISSUE THREAD

**Issue by iampopal** [pocketbase/pocketbase#3042]
As we are use to code in Dart language, 
We need to Extend Pocketbase as a framework with Dart language. 

When will we able to Extend with Dart?

**Comment by ganigeorgiev** [comment]
Sorry, there no plans for this.

**Comment by iampopal** [comment]
It will be great to add this feature as it make all development friendly for Dart developers.

**Comment by ganigeorgiev** [comment]
This is not easy to implement and I certainly don't have the time to work on it yet.

The only reason we've added the recent "[Extend with JS](https://pocketbase.io/docs/js-overview/)" support is because we use an existing JS interpreter written in Go ([goja](https://github.com/dop251/goja)) and there is no such thing for Dart.

If you decide to contribute, keep in mind that this doesn't need to be part of the main package and it can be implemented as standalone "plugin" (for example see https://github.com/pocketbase/pocketbase/tree/master/plugins).

**Comment by iampopal** [comment]
Ok thank you, 

But It will be awesome to have Extend with Dart 

Because we the Dart developers are looking for it for a long time.
