### ISSUE TITLE
Delete files on collection field removal

### ISSUE THREAD

**Issue by apptonet** [pocketbase/pocketbase#305]
when I removed row from collections , Image file wasn't remove from disk.
and its difficult when I remove multi row together

**Comment by ganigeorgiev** [comment]
We are currently removing the uploaded files only when deleting a single record or the entire collection (see https://github.com/pocketbase/pocketbase/blob/master/core/base.go#L788-L799).

At the moment there is no easy way to delete the record files when you remove only a collection field (I guess this is what you are asking, right?). I'll consider implementing it for future versions, but for now this is a low priority since it could complicate a lot the collections update operation - we will have to create a diff with the old and updated collections state and store somewhere the ids of the deleted files for each record before dropping the records table column, so that we can iterate over them and delete each individual file.

**Comment by apptonet** [comment]
An easy solution is also possible.
Records that have files or photos, when choosing to be deleted, leave a list of file addresses in the log file, which the site administrators can delete with a script after each session.

**Comment by ganigeorgiev** [comment]
@apptonet Hm, but that shouldn't be needed. Maybe I misunderstand your initial request.

Currently we are NOT deleting the files **only when you decide to remove a collection field**  (aka. changing the schema). This doesn't seem to be what you are describing.

**When you delete an entire record or a collection, deletion of the associated file(s) should be already handled.**

If in that case the files are not deleted then this need to be investigated. Locally I cannot reproduce it - the files are deleted for me (we also have integration tests that confirms this behavior).

Could you elaborate more on your issue?

**Comment by apptonet** [comment]
Yes you are right
The problem was due to the permission of the original folder, when was changed by the Internet Guard software, and it was corrected by returning it to 755.
And by deleting a row , images and files, it will be deleted.
Thanks

**Comment by hugo-abdou** [comment]
@ganigeorgiev please I'm trying to make some custom view collections but for all the queries I put the validator complaint is there any place where I can see or learn how pocket base queries work

![image](https://github.com/pocketbase/pocketbase/assets/44982282/d2f2cc34-cdfd-41c0-813e-563d4cd412cc)

**Comment by ganigeorgiev** [comment]
I don't see how your question is related to the above issue.

In any case I don't exactly understand what your query is supposed to do but it seems that it is missing a `SELECT` statement outside of the `WITH` clause.

To inspect what queries are being executed you can run the executable with `--dev`.

If you have other questions please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details about your use case and what you are trying to do.

**Comment by ganigeorgiev** [comment]
_Old issues cleanup: I'm closing this issue as I no longer plan working on it. Automatically deleting files on collection schema field will not only introduce extra complexity for tracking the files associated with the removed field but it could be also dangerous and cause accidental data loss in case of multi-stage migrations and it is better left for now for those rare cases where it actually matters users to handle it explicitly._
