### ISSUE TITLE
Feature Request: The feature of being able to name the file.

### ISSUE THREAD

**Issue by Samuelseidelc2518** [pocketbase/pocketbase#306]
It would be great if in some new version the uploaded files could be named so as not to download them with the autogenerated name they have

**Comment by ganigeorgiev** [comment]
Hi,
This was discussed previously in https://github.com/pocketbase/pocketbase/discussions/210.

I'm not planning to change the existing behavior since the pros of autogenerated filenames outweigh the cons and there are already workarounds for the cases where you really need to use a custom name:

- add additional text field to your collection alongside the file to store the custom file name
- overwrite the downloaded file name, by making use of the `OnFileDownloadRequest` hook:
```go
app.OnFileDownloadRequest().Add(func(e *core.FileDownloadEvent) error {
    fs, _ := app.NewFilesystem()
    defer fs.Close()

    // extract the stored text from the record's `filename` field
    customName := e.Record.GetStringDataValue("filename")

    if err := fs.Serve(e.HttpContext.Response(), path, customName); err != nil {
        return rest.NewNotFoundError("", err)
    }

    return hook.StopPropagation
})
```
