### ISSUE TITLE
Wrong comparison between dates

### ISSUE THREAD

**Issue by jiri** [pocketbase/pocketbase#3073]
Hi,

I have a collection with two datetime columns, `start` and `end`. However, when I'm trying to filter by date, I'm getting a seemingly wrong result -- see the attached screenshot:

![image](https://github.com/pocketbase/pocketbase/assets/661524/8fe8b964-0807-4b41-ac47-b0f192b58e1c)

Shouldn't the string "2023-08-06T00:04:33Z" compare as less than the start column?

**Comment by ganigeorgiev** [comment]
The `date` field value must be in the format `Y-m-d H:i:s.uZ`, aka. without the `T`.

We are using space instead of `T` as separator for backward compatibility with earlier versions.

_This may change in the future as there are plans to introduce date filter normalizations to allow searching by custom timezone._
