### ISSUE TITLE
Feature Request: Public Views

### ISSUE THREAD

**Issue by carlosblanco** [pocketbase/pocketbase#3096]
It would be awesome to be able to enable/disable public views for collections. Something similar to these [feature](https://www.basedash.com/features#views) in basedash. Public views can be very similar to the current ones in the admin panel. The admin panel views are pretty good already. View Rules can apply to them in a similar fashion to API rules.

**Comment by ganigeorgiev** [comment]
This was requested before, but at least for v1 (and until https://github.com/pocketbase/pocketbase/issues/898) there are no plans to allow access to the admin (or portion of it) to non-admin accounts because it will be limited and I don't think it will be very useful.

Users can always implement manually their own custom interfaces and branding for previewing the data if they want to, for example by creating html file(s) in `pb_public`.

**Comment by RepComm** [comment]
I have a use case for view collections as non-admin:
I'm building a forms app and the frontend needs view access to collection schemas in order to generate the correct UI and show form fields properly. The forms map directly to one or multiple collections.

I think my go-to for now will be to 'hack' around the limitation, but I'd love a legit API rule for pb.collections.getOne for instance

**Comment by ganigeorgiev** [comment]
@carlosblanco I don't see how your comment is related to the initial post but in any case I don't recommend the above and it would be insecure since you'll expose the collection API rules to anyone.

If you really need access to the collection fields definition a better option would be to create a [View collection](https://pocketbase.io/docs/collections/#view-collection) with query like:

```sql
select id, schema from `_collections`
```

**Comment by RepComm** [comment]
It's possible I misinterpreted the original context. I didn't realize the solution you've suggested, that seems like a much better and easier way to do it. Thank you very much!
