### ISSUE TITLE
Admin API keys

### ISSUE THREAD

**Issue by nzhenev** [pocketbase/pocketbase#3118]
Hello everyone! @ganigeorgiev what do you think about this feature? Something like API key, but with admin-level permissions. We start using pocketbase on daily basis for internal services in my company, and this functionality looks important for "horizontal" integrations, — storing admin password for this on the other side is really ugly )) and as i see, it's not for plugins — it looks like "core" part for me. 

Also, thnx for your work, pb is really awesome! one of the best from github due last year for me

i'll would be glad to contribute in this product. If it's "ok", a can implement this function — in near future (in days)

**Comment by ganigeorgiev** [comment]
This was suggested before in https://github.com/pocketbase/pocketbase/discussions/342 but for now is left aside as I have some security concerns related to its implementation. I don't like granting full access with just a single string key as it could be very easily abused since we currently don't have builtin mechanism to restrict admins access or to prevent bruteforce attacks (_the latter is still doable with email/password combination but it is inherently little more difficult due to the required email/password pair match and the slow hash verification_).

I have it in my todo and eventually may reconsider it at later stage, but at least for now this remains out of the scope.

**Comment by ganigeorgiev** [comment]
On second thought, I think it won't compromise too much the security.

For me the main problem of using directly the admin password is not that it needs to be stored on the other end (you can always create a system admin account for that), but that that it is slow if performed for each request and users are required to "cache" the generated token (_see for example https://github.com/pocketbase/pocketbase/discussions/2922#discussioncomment-6470104_).

So I guess we can implement as requested in #342 permanent/stored admin tokens (in some sidecar table linked to the admins and with different auth type).

I'll think a little more on it as this seems to be a common feature requested but that will be after the JS SDK refactoring.

In the meantime, if you have ideas feel free to outline your implementation details.

**Comment by nzhenev** [comment]
maybe rsa keypair (private / public) in ssh manner? I undestand, this question is complex, i'll read this tickets. Bruteforce attacks may become real problem, but, rate-limit can resist. Maybe better to implement plugin at this moment, and deploy as optional feature, work with this solution it in production due time. Also, may be, it's process (plugins in general) can become become an incubator for primary project's lib, — in theory, this simplify making complex decisions within project, similar to this. Anyway, my experience in oss development is not too long, sorry me, in advance, if anything wrong with my actions / communication :)  I have more complex ideas about this project, i'll implement them in draft-like plugins, and show you, this will be better. thnx!

**Comment by whmeitzler** [comment]
An HTTPS cert scheme could be a good option here. It's orthogonal to JWTs in that its connection based rather than request based, and, AFAICT, mTLS can be a good way to constrain rather powerful keys.

Pocketbase trusts a self signed root CA that can issue TLS certs.

When a client is connected, Pocketbase validates the CN of the cert as, say, a user id. If the lookup passes, that request is automatically authenticated as that user.

I've explored pulling the TLS cert out of the request option, it's definitely doable. Managing a CA seems to be one of those tasks that is relatively straightforward to implement, but does require a decent amount of implementing and documentation.

Stateful auth does make the app picker about its environment.
I'm not sure how proxies deal with apps that want to be able to terminate the TLS stream directly. 
I suspect there are also administrative actions (revoking or rotating certs) that would also crop up.

I guess we need to find a way to determine if the reduced overhead of not needing to ship and process auth tokens is worth the extra state management

**Comment by whmeitzler** [comment]
Seems like a reasonable tradeoff, thanks for thinking it through.
FWIW, as I explore using PB in IoT settings, I am also sensitive to token size. Sending tokens weighing in at a few hundred bytes on each request can chew up a cellular connection quickly. Hence my interest in connection-level auth.

There are, of course, other ways to deal with this, and PB is decidedly not an IoT hub.

**Comment by ganigeorgiev** [comment]
_Just for info in case someone stumble her: Support for generating non-refreshable tokens as part of the impersonate API was added in v0.23.0 which to some extend can be used as "API keys" (short lived tokens generated from email+pass is still more secure but for server-server communication a fixed long-lived token should be fine). You can find more details in https://pocketbase.io/docs/authentication/#api-keys._
