### ISSUE TITLE
Feature request: Prepend types declarations reference when creating javascript migration file

### ISSUE THREAD

**Issue by einarpersson** [pocketbase/pocketbase#3188]
I suggest that `/// <reference path="../pb_data/types.d.ts" />` is added to every new javascript migration file that is generated (by the running application or by the CLI).

This will ensure that types work out-of-the-box which brings clarity to the newcomer who wants to understand what's going on, and/or create custom migrations.

**Comment by ganigeorgiev** [comment]
I think we already do this with the autogenerated migrations and the migration templates (eg. when running `./pocketbase migrate create`).

We don't prepend the reference directive to already existing non-empty migration or hook files because prepending something to a file usually require creating a copy or reading the entire file, which in some scenarios, especially if there is autoformat/autosave running concurrently, could lead to content loss.

It is doable, but requires more extensive checks to avoid the above and for now remains a low priority.

**Comment by einarpersson** [comment]
@ganigeorgiev Sorry, I realized that this was implemented in recent versions. It was not included in the 0.16.x version I was running but now that I have updated I see that it is working as I wanted to.

I am closing this. 🙏
