### ISSUE TITLE
Bug: Record is not updating on cron job

### ISSUE THREAD

**Issue by usamashafiqs** [pocketbase/pocketbase#3197]
I am using pb_hooks (JS) to run a cron job. Every run of the job will result in a -1 day form days. On Console commands, I'll get mines every time I run the ```./pocketbase run``` command, but when I run the cron job, nothing happens and no errors are reported.
```js
function findAllCustomers() {
  const records = arrayOf(new Record());

  $app
    .dao()
    .recordQuery('customers')
    .andWhere($dbx.hashExp({ 'isLifetime': false, 'isActive': true }))
    .limit(-1)
    .all(records);

  return records;
}

$app.rootCmd.addCommand(
  new Command({
    use: 'run',
    run: (cmd, args) => {
      console.log('Run!');
      const customers = findAllCustomers();
      customers.forEach((customer) => {
        if (customer.getInt('days') === 0) return;
        console.log('Updating!');
        customer.set('days', customer.getInt('days') - 1);
        $app.dao().saveRecord(customer);
      });
    },
  })
);

function goWork() {
  const customers = findAllCustomers();
  customers.forEach((customer) => {
    if (customer.getInt('days') === 0) return;
    console.log('Updating!');
    customer.set('days', customer.getInt('days') - 1);
    $app.dao().saveRecord(customer);
  });
}

cronAdd('customers', '*/2 * * * *', () => {
  console.log('cron job running...');
  goWork();
});

```

**Comment by ganigeorgiev** [comment]
Cron job and route handlers can't access variables and function declared in the top/root level scope because they execute in their own separate goroutine (see https://pocketbase.io/docs/js-overview/#handlers-scope), aka. in the above `goWork` results to `undefined` and technically there should be an error, but I guess it crashes silently because the cron job is executed in the background (I'll consider improving the error reporting with the next release).
