### ISSUE TITLE
[ERROR] Unexpected "\x7f"

### ISSUE THREAD

**Issue by wineTGH** [pocketbase/pocketbase#3203]
I'm trying to use pocketbase with svelte, but I'm getting this weird error
![Error](https://github.com/pocketbase/pocketbase/assets/66317493/1d534ca4-a201-45e7-90b3-28142c0381d4)

`$lib/pocketbase.js
```
import PocketBase from 'pocketbase';

export const pb = new PocketBase("http://127.0.0.1:8090");
```
routes/admin/keys/+page.svelte
```
<script lang="ts">
    import { pb } from "$lib/pocketbase";
    import { onMount } from "svelte";

    let keysList = [];

    onMount(async () => {
        const result = await pb.collection('keys').getFullList({sort: "created"});
        keysList = result.items;
    });
</script>
```

OS: Debian Linux 12
Pocketbase: 0.17.7

**Comment by ganigeorgiev** [comment]
I'm not sure what is the cause of the error, but I don't think it is PocketBase or JS SDK related.

If you haven't found the cause of the issue, please create a **minimal** reproducible repo and I'll try to investigate it further.

**Comment by ganigeorgiev** [comment]
Side-note: if you have the binary in the same location as your frontend files, try to move it in a different location (or rename it) because it is possible, depending on your bundler config, when you have `import PocketBase from 'pocketbase'` the bundler to try to import the binary instead of the node_modules dependency.

**Comment by wineTGH** [comment]
Yep. I moved `pocketbase` to another directory and this fixed issue. Thanks
