### ISSUE TITLE
Internationalization feature request

### ISSUE THREAD

**Issue by DenisBalan** [pocketbase/pocketbase#330]
Feature request - internationalization for collection items. 
As done in other headless cms (one starting with letter s).
Also to be available via API in a handy way.

Hope this will be implemented so that we could switch to PocketBase.

Thanks.

**Comment by ganigeorgiev** [comment]
Hi, unfortunately, at least for v1.0.0, I don't plan to work on built-in internationalization support.
There are several existing workarounds for this, you could check - https://github.com/pocketbase/pocketbase/discussions/154

Although it could be used as a very basic headless CMS, PocketBase wasn't really intended to be a replacement for [Strapi](https://strapi.io/), [Directus](https://directus.io/) or any other more focused solution.
The Admin UI is primarily a developer dashboard (similar to Firebase console) since we don't support permissions on admin account level (the api rules affect only the users; all admins acts as "super admin" and have access to everything).

**Comment by candidosales** [comment]
@ganigeorgiev Thanks for the explanation :)
