### ISSUE TITLE
Add Option To Disable `SELECT COUNT(*) ...` when viewing Records in Admin Panel

### ISSUE THREAD

**Issue by flarco** [pocketbase/pocketbase#3344]
Hi, I have a large collection/table. And whenever I want to query it in the Admin Panel, it takes a really long time, because I believe it is fetching the total row count to display at the bottom (with `Load More`). This is especially bad when in production, and it hangs.

<img width="326" alt="image" src="https://github.com/pocketbase/pocketbase/assets/7671010/ec94a32d-a96a-4ed9-939d-2d0d95774913">

Is there a way to disable the fetching of total row count? I know `skipTotal=1` is implemented on the API side.

**Comment by ganigeorgiev** [comment]
> Is there a way to disable the fetching of total row count?

There is no option at the moment to disable the count in the Admin UI.

I'll consider with the next v0.19/0.20 release eventually removing it (_or maybe fetch it separately with some timeout for large tables like the above_).

**Comment by ganigeorgiev** [comment]
This should be fixed in the `develop` branch and will be part of the next v0.19.0 release together with some other listing improvements (_there are no ETAs yet_).

_If you want to test it locally:_

0. [Install Go 1.18+](https://go.dev/doc/install)
1. Checkout or clone the `develop` branch
   ```sh
   git clone https://github.com/pocketbase/pocketbase.git --branch develop --single-branch
   ```
2. Navigate to `examples/base`
3. Run `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build` (_https://go.dev/doc/install/source#environment_)
4. Start the created executable by running `./base serve`.

**Comment by flarco** [comment]
Great, thanks man.
