### ISSUE TITLE
Multiple pocketBase instances in one app

### ISSUE THREAD

**Issue by ICTServ** [pocketbase/pocketbase#3345]
Is it possible to use multiple pocketBase instances in one app? E.g. 1 pb instance for user management and authentication. Another one for storing data and both instances sharing the same auth collection. If this is impossible, how can I use SSO using JSON Web Token (JWT)?  If both options impossible, what's your suggestion?

**Comment by ganigeorgiev** [comment]
No, a single PocketBase instance can work only with 1 database.

>  If both options impossible, what's your suggestion?

I'm sorry, I don't understand your use case and why do you need 2 separate instances for auth and data to recommend a solution.

**Comment by ICTServ** [comment]
@ganigeorgiev  Thank you for the quick reply.  

Let me explain my use case. I have about 40 departments and each has different application form. They only share some common entities like users, locations, departments, ..etc.  If I use 1 instance for all departments I will run out of resources quickly and PocketBase doesn't allow horizontal scaling. That's why I want use multiple instances to store formApplications data of each departments on separate instances.

**Comment by ganigeorgiev** [comment]
I understand, but this is not possible at the moment because there is no easy mechanism out of the box to sync and share the different states and data across the multiple instances.

If a single server and a single PocketBase instance is not enough to handle your expected traffic, you can look at some other open source options that are designed with scaling from the beginning like Supabase, Nhost, SurrealDB, EdgeDB, etc.

**Comment by ICTServ** [comment]
Thank you!
