### ISSUE TITLE
Accept `application/x-www-form-urlencoded` requests

### ISSUE THREAD

**Issue by emarj** [pocketbase/pocketbase#3377]
Hi there,

First of all thank you for creating this very useful project.

I was trying to create a record by submitting a request with content-type set to `application/x-www-form-urlencoded` (the default for forms) and I encountered a `400` error. After some debugging I found the issue: the function https://github.com/pocketbase/pocketbase/blob/ff08fc0fa428a8b0e5a4251ba792f0715b39e9b5/forms/record_upsert.go#L120-L133
does not support `application/x-www-form-urlencoded`.

I confirmed this by quickly adding the additional case and specific function that parses the form and returns `r.PostForm`. Since I do not fully understand the purpose of the `keyPrefix` and how to properly return the values, I won't submit a PR.
For someone that better understands the codebase this should be a 5 minutes fix. Or, if you prefer to give me some guidance I can also do that of course.

I am not sure if this is intentional or just a bug, in any case I think should be quite easy to support this usecase.

Thanks in advance

**Comment by ganigeorgiev** [comment]
It is intentional. Even the existing json and multipart support complicates the internals (eg. the `json` field string normalizations) and I'm not sure if it will be a good idea to add support for other content type.

I may reconsider it if there is a good reason for it but for now this remains out of the scope.
