### ISSUE TITLE
Feature Request: Twitch Auth Provider

### ISSUE THREAD

**Issue by KopiNinja** [pocketbase/pocketbase#340]
Your project is fantastic! 
I'm not sure how difficult it is to implement Twitch auth, but it would be awesome to use with Twitch chat bot.

**Comment by ganigeorgiev** [comment]
Twitch has [OAuth2 api](https://dev.twitch.tv/docs/authentication) with [scopes to return the user email](https://dev.twitch.tv/docs/authentication/scopes) but unfortunately they don't seem to support the PKCE flow.

There is an existing feature request in the Twitch uservoice forum to add support for that - https://twitch.uservoice.com/forums/310213-developers?query=pkce

For now I'll close the issue because as it is now, this could work securely only in the browser, but depending on the users demand for this provider, I may reconsider it.
