### ISSUE TITLE
Major Issue: API rules should be per-field not per-record 

### ISSUE THREAD

**Issue by vtempest** [pocketbase/pocketbase#3425]
Typical social media site has
```

posts {
author: single rel: user, 
text, 
comments: multi rel: comment
}
```
posts should only updated by author.id = @request.auth.id 
however they also need to be updated by the commenter logged in to update the overall list of comments

`author.id = @request.auth.id || @request.data.comments:isset = true `

Something like this would work but the api can easily be hacked by malicious users, they can still remove and unlink comments of other commenterers. So therefore commenters should have permission to execute a very specific function of add to comment stack. That's why api rules need to be handled at the function level sometimes for some routes.

**Comment by supercoolspy** [comment]
You could implement some code in the [go API](https://pocketbase.io/docs/go-overview) to try and make this work. There may also be a way to do it using the API rule syntax though I am not sure. But I doubt it is a major issue as you could configure it to work on the per-field level with go, rules or javascript.

**Comment by ganigeorgiev** [comment]
I don't understand what is the issue here. The multiple relation behavior is working as expected.

If you don't want your users to be able to change the multiple "comments" fields then create a junction collection "commentPostRel" that will have 2 relation fields - 1 to the "comments" and another one to the "posts" collection.
