### ISSUE TITLE
Migrate to SvelteKit + Typescript

### ISSUE THREAD

**Issue by candidosales** [pocketbase/pocketbase#343]
Hi everyone 👋,

I'm delighted to find this project! I love Go and Svelte! I think that I can contribute to your project 😄 .

Also, I was looking for a CMS headless, and I found Strapi. I'm using it for now, but I would like to migrate in the future to PocketBase. 

I took a look into the project, and I found some improvements that I can make:

- Upgrade the project to use [SvelteKit](https://github.com/sveltejs/kit);
- Adapt all javascript files to typescript;

First, I'll study the project and then plan how to do this PR.

**Comment by ganigeorgiev** [comment]
Hi,

PocketBase it is not really intended to be a replacement for a full-fledged headless CMS like [Strapi](https://strapi.io/) or [Directus](https://directus.cloud/). Rather it is intented to be a base/core that you can build on top of it (similar discussions could be found in https://github.com/pocketbase/pocketbase/issues/330 and https://github.com/pocketbase/pocketbase/discussions/50).

---

> Upgrade the project to use [SvelteKit](https://github.com/sveltejs/kit);

Why? We don't need SSR or support for different routing adapter, so I don't see any practical benefit for the Admin UI to migrate to SvelteKit.

> Adapt all javascript files to typescript;

Here I could understand why some users would prefer TypeScript over plain old JavaScript, but I actually prefer the latter because I find TypeScript to be too "noisy" and could actually make the code harder to read and maintain. While the [JavaScript SDK](https://github.com/pocketbase/js-sdk) is written in TypeScript, at the end it is a library that is expected to be part of external user land code, where the Admin UI is a SPA, distributed as part of prebuilt embedded application (`ui/dist`).

You are free to fork the project and improve it any way you want, but I don't plan to merge the proposed changes unless there is a real benefit that will outweigh the maintenance cost in the long run.

_Also keep in mind, as noted in the footer section of the readme, that PocketBase was created for my other open source project ([Presentator #183](https://github.com/presentator/presentator/issues/183)) so all feature requests will be first aligned with what we would need for Presentator v3._

**Comment by candidosales** [comment]
@ganigeorgiev Thanks for the explanation :)
