### ISSUE TITLE
Thumb not generated if jpeg file is ending ext *.jpeg

### ISSUE THREAD

**Issue by cesboa** [pocketbase/pocketbase#3433]
Hi,
It took me a while to get thumb generation to work, because if file ext is .jpeg it doesn't work. Is it possible to get to work without an upload check workaround?

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it.

The file extension shouldn't matter when generating thumbs because we check the file MIME type.

I've tested with the first JPEG image that came up in Google search https://en.wikipedia.org/wiki/File:Sample_0.JPEG and it works fine for me.

Double check that your file is actually a jpeg and not another image format with just jpeg extension. The thumbs generation currently support only the following formats: `image/png`, `image/jpg`, `image/jpeg`, `image/gif`.

If you are stull not able to resolve it, please provide a file sample.

**Comment by cesboa** [comment]
> I'm not able to reproduce it.
> 
> The file extension shouldn't matter when generating thumbs because we check the file MIME type.
> 
> I've tested with the first JPEG image that came up in Google search https://en.wikipedia.org/wiki/File:Sample_0.JPEG and it works fine for me.
> 
> Double check that your file is actually a jpeg and not another image format with just jpeg extension. The thumbs generation currently support only the following formats: `image/png`, `image/jpg`, `image/jpeg`, `image/gif`.
> 
> If you are stull not able to resolve it, please provide a file sample.

Strange... But tank you for your answer, it must be something on my end then. I will test again. Cheers!
