### ISSUE TITLE
Feature Request: Index for field

### ISSUE THREAD

**Issue by andre-gitdev** [pocketbase/pocketbase#345]
It would be nice to be able to create an index on a specific field in the dashboard view. For example, if you rely heavily on a field when filtering or searching. An index would provide a performance boost in this situation.

**Comment by ganigeorgiev** [comment]
This is already in the [roadmap](https://github.com/orgs/pocketbase/projects/2) and was previously discussed in https://github.com/pocketbase/pocketbase/discussions/84. I'll use this issue and will link it to the roadmap for better visibility and tracking.

Currently this is planned only for simple single field indexes and it is a low priority since there are already workarounds if you really need indexes:
- use the sqlte3 cli tool to add the index manually
- OR create the index inside a DB migration:
  ```go
  package migrations

  import (
      "github.com/pocketbase/dbx"
      m "github.com/pocketbase/pocketbase/migrations"
  )

  func init() {
      m.Register(func(db dbx.Builder) error {
          // up
          _, err := db.CreateIndex("COLLECTION_NAME", "INDEX_NAME", "FIELD_NAME").Execute();
          return err
      }, func(db dbx.Builder) error {
          // down
          _, err := db.DropIndex("COLLECTION_NAME", "INDEX_NAME").Execute();
          return err
      })
  }
  ```

**Comment by ganigeorgiev** [comment]
@andre-gitdev  Thanks, but it is better to wait #376.
