### ISSUE TITLE
On Fly.io: ./pocketbase update Error : invalid cross-device link [pb folder is encrypted]

### ISSUE THREAD

**Issue by MarArMar** [pocketbase/pocketbase#3498]
```
flyctl ssh console
Connecting to fdaa:2:c8d4:a7b:126:7127:f9be:2... complete

e82d524f29d558:/# find / -type f -name "*pocketbase*"
/pb/pocketbase

e82d524f29d558:/# cd pb

e82d524f29d558:/pb# ./pocketbase update
Fetching release information...
Downloading pocketbase_0.18.10_linux_amd64.zip...
Extracting pocketbase_0.18.10_linux_amd64.zip...
Replacing the executable...
Failed replacing the executable: rename pb_data/.pb_temp_to_delete/extracted_pocketbase_0.18.10_linux_amd64.zip/pocketbase /pb/pocketbase: invalid cross-device link
```

Seen on SO :

https://unix.stackexchange.com/questions/79132/invalid-cross-device-link-while-hardlinking-in-the-same-file-system

=> Maybe the directories are not in the same partitions ?

=> Maybe the source or destination folder are fscrypt encrypted folders ? (2 : https://unix.stackexchange.com/a/717318)
"Within the same fscrypt encrypted folder (i.e., both source and destination in the same fscrypt encrypted folder or any of its subdirectories), hard linking should work normally."

```
e82d524f29d558:/pb# lsattr -d /pb
--------------e----- /pb
```

Based on this output, it can be concluded that the /pb folder is an fscrypt encrypted folder
 
 Is there a way to make pocketbase update work in this setting ?
 
 
 Note : I tried 
 
 ```
 fscrypt unlock /pb
-ash: fscrypt: not found
```

`sudo`, `apt`, `go`, `yum`, `dnf` are not available as well

**Comment by ganigeorgiev** [comment]
Running the `update` command in a Fly.io environment doesn't really make much sense because on redeploy the binary will be loaded from the Dockerfile.

If you wan to update your PocketBase instance when using Docker you should update the binary version in the Dockerfile instead. This can be done multiple ways depending on what your Dockerfile looks, but if you use the example from https://github.com/pocketbase/pocketbase/discussions/537, then you have 2 options:

- Change the `ARG PB_VERSION=0.18.10` instruction in the Dockerfile
- Define a build argument in your `fly.toml` config and change the argument from there:
   ```
   [build.args]
     PB_VERSION="0.18.10"
   ```

In all cases always make sure to have a backup of your `pb_data` before upgrading in case something goes wrong (with the resent PocketBase versions you can create a backup from the _Admin UI > Settings > Backups_).

**Comment by MarArMar** [comment]
Superb, thank you so much for you answer, will try it now

**Comment by MarArMar** [comment]
It worked perfectly. Thanks you again!
