### ISSUE TITLE
pushed pb_data

### ISSUE THREAD

**Issue by serkan-bayram** [pocketbase/pocketbase#3509]
I accidentally pushed db_data to github, would it create problems? Should I  delete and re create my repo?

**Comment by ganigeorgiev** [comment]
`pb_data` contains PocketBase env specific data - database, uploaded files (if local filesystem is used), etc.

It will not create problems but everyone who pull your project will have access to the uploaded database, which is usually not what you want with some exceptions (for example we have a [test `pb_data`](https://github.com/pocketbase/pocketbase/tree/master/tests/data) in the main repo that is deliberately committed so that everyone who pull/fork the project can have access to the same test database and can run the test without any upfront setup).

If you want to share just your db structure, you can commit your `pb_migrations` instead.

If it is a new GitHub repo, you can either prune your history or just recreate it (aka. delete your local `.git` folder and run `git init`, `git remote add origin ...` and `git push origin master -f` to replace the remote).
