### ISSUE TITLE
Mime type checking does not work for .wav files

### ISSUE THREAD

**Issue by alexmercier25** [pocketbase/pocketbase#351]
Mime types permitted:
audio/x-wav,audio/mpeg

but still throws an error:
2022/08/25 16:56:16 audio_file: The following mime types are only allowed: audio/x-wav,audio/mpeg..

However it works great with mp3 files.

**Comment by ganigeorgiev** [comment]
PocketBase uses `http.DetectContentType()` from the standard Go library, which has some limitations and quirks.

For full list with the supported mimetypes and their signatures you could check - https://github.com/golang/go/blob/8b364451e2e2f2f816ed877a4639d9342279f299/src/net/http/sniff.go#L66-L195.

There is no `audio/x-wav` in the above list, BUT there is `audio/wav` so you could try replacing it with that.

**Comment by ganigeorgiev** [comment]
For clarity, here is the full list with the supported mime types:

```
text/html; charset=utf-8
text/xml; charset=utf-8
text/plain; charset=utf-16be
text/plain; charset=utf-16le
text/plain; charset=utf-8
application/pdf
application/postscript
image/jpeg
image/png
image/gif
image/bmp
image/webp
image/x-icon
audio/aiff
audio/mpeg
audio/midi
audio/wave
application/ogg
video/avi
video/mp4
video/webm
font/ttf
font/otf
font/collection
font/woff
font/woff2
application/vnd.ms-fontobject
application/x-gzip
application/zip
application/x-rar-compressed
application/x-rar-compressed
application/wasm
---
# everything else will be detected as:
application/octet-stream
```

I'll update the "Mime type" field validator in the next v0.6.0 release to be more "strict" and allow only the above mime types.

**Comment by ganigeorgiev** [comment]
Instead of restricting the supported mimetypes, and for better distinguishing document files from `application/zip`, I've decided to replace the standard library with [gabriel-vasile/mimetype](https://github.com/gabriel-vasile/mimetype), which has far more complete list of file singatures - https://github.com/gabriel-vasile/mimetype/blob/master/supported_mimes.md
_(when serving files the standard go lib still will be used because `gocloud/blob` content-type check is based on it, but that's ok since the types we are serving inline are already supported)_.

This is currently only in the `develop` branch, but will be publicly available with the next v0.6.0 release (_sometime next week or the week following it_).

@alexmercier25 If you don't want to wait for v0.6.0 release you could use `audio/wave`. For future backward compatibility my recommendation would be to replace your `audio/x-wav` string with `audio/wave, audio/wav`.

I'll close the issue for now, but if the above doesn't work for you, please let me know and I'll investigate it further.

**Comment by WilliamRelken** [comment]
@ganigeorgiev 

I have noticed that non-matched files are returned with an empty content type instead of `application/octet-stream`:

curl -v <domain>/test.apk
curl -v <domain>/favicon.ico

```
> 
< HTTP/2 200 
< access-control-allow-origin: *
< cache-control: no-cache
< content-type: 
< date: Tue, 31 Dec 2024 20:38:47 GMT
```

**Comment by ganigeorgiev** [comment]
You are commenting to a very old issue that may not be relevant anymore as many things has changed since then.

I don't even understand what the above `curl` example is supposed to show.

Note that the originally discussed issue is only for the uploaded collection files, aka. files served via the [`/api/files/...` endpoint](https://pocketbase.io/docs/api-files/#download-fetch-file).

If your example is illustrating serving static files, then for that we use the std Go `http.ServeContent` method and there is no special MIMEtype handling.

If you still have an issue, please open a Q&A discussion and try to elaborate more on your use case and what actually is the problem in the first place.
