### ISSUE TITLE
Headers on authRefresh()

### ISSUE THREAD

**Issue by serkan-bayram** [pocketbase/pocketbase#3522]
I'm searching it up for hours but I couldn't understand how do we pass headers to this function?

```jsx
  const pb = new PocketBase("http://127.0.0.1:8090");

  const authData = await pb.collection("users").authRefresh();
```

**Comment by ganigeorgiev** [comment]
If you want to pass custom headers you can pass them as object, aka:

```js
await pb.collection("users").authRefresh({
    headers: {
        'X-Custom-Header': "example",
    }
});
```
See also [Custom request options](https://github.com/pocketbase/js-sdk#custom-request-options).

_Note that if you want to pass the `Authorization` header, usually you don't have to set it manually as `pb.authStore` will add it automatically if valid._

If the above doesn't help, please elaborate and consider filing a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details about your use case.

**Comment by serkan-bayram** [comment]
I'm thinking to open a Q&A but before that I get this error, when I try to call an authRefresh():
![image](https://github.com/pocketbase/pocketbase/assets/68502470/4194f5c4-d33a-40dd-9231-fa1f8e7f2a76)
I can reach my session data without any problem and I know I'm authenticated. Do you have an idea why that might happen?

**Comment by ganigeorgiev** [comment]
I don't think you are authenticated. You can add `console.log(pb.authStore.isValid)` before the `authRefresh` call and confirm it.

**Comment by serkan-bayram** [comment]
Yes you are right it returns false, so I think the problem here is somehow next-auth thinks I'm authenticated because middleware let me see certain pages but pocketbase thinks I'm not. This is how I handle my authentication, do you have and idea?


```jsx
import CredentialsProvider from "next-auth/providers/credentials";
import PocketBase from "pocketbase";

export const options = {
  providers: [
    CredentialsProvider({
      async authorize(credentials, req) {
        const { username, password } = credentials;
        const pb = new PocketBase("http://127.0.0.1:8090");
        const authData = await pb
          .collection("users")
          .authWithPassword(username, password);

        // after the above you can also access the auth data from the authStore

        const user = authData;

        if (user) {
          // Any object returned will be saved in `user` property of the JWT
          return user;
        } else {
          // If you return null then an error will be displayed advising the user to check their details.
          return null;

          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }
      },
    }),
  ],
  pages: {
    signIn: "/giris",
  },
  callbacks: {
    async session({ session, token }) {
      session.user = token.user;
      return session;
    },
    async jwt({ token, user }) {
      if (user) {
        token.user = user;
      }
      return token;
    },
  },
};
```

**Comment by ganigeorgiev** [comment]
If the above is executed server-side then the newly created PocketBase instance will have its own `pb.authStore` different then the one in the component. You need to somehow share the auth state from the middleware instance with the component one (you can manually update the auth store by calling `pb.authStore.save(token, model)` or use the cookie helpers).

In any case, this is not a PocketBase issue and in general I'd recommend to not use Next.js SSR/RSC if you are not sure what you are doing. Syncing the auth state between the node server and PocketBase (or any other 3rd party service) in Next.js specifically is not easy at the moment because there isn't an easy way to share complex objects between middlewares and server components.

You can also check https://github.com/pocketbase/js-sdk#ssr-integration.
