### ISSUE TITLE
Return timestamps in API as ISO8601

### ISSUE THREAD

**Issue by matsimitsu** [pocketbase/pocketbase#357]
Right now, timestamps are returned in a format that is not easily parsable in JS, e.g. `2022-08-24 15:10:34.961`, there's also no timezone information, though one could assume it's always UTC.

It would be nice if the API returned timestamps in the ISO8601 format (`2022-08-24T15:10:34.961Z`), this way its possible to parse the strings with native JS `new Date()`. Many other libraries that consume JSON also kind-of assume the timestamps are ISO8601.

**Comment by ganigeorgiev** [comment]
That's correct. The date is stored as UTC string in the format "Y-m-d H:m:s.u".

We cannot change the API response format because this will be a major breaking change. You can create a tiny wrapper around the response if you want to adjust the format to your needs. If you are using the JavaScript SDK you can make use of the `client.afterSend` function hook - https://github.com/pocketbase/js-sdk#send-hooks
