### ISSUE TITLE
Docs Issue: Typo under OnUserAfterOauth2Register

### ISSUE THREAD

**Issue by theMackabu** [pocketbase/pocketbase#358]
![Screen Shot 2022-08-29 at 10 24 02 AM](https://user-images.githubusercontent.com/32078755/187260926-14b95a5c-e1f7-4e38-ad90-7eef16afbf42.png)
I believe this should say `OnUserAfterOauth2Register`

**Comment by ganigeorgiev** [comment]
Actually `OnUserBeforeOauth2Register` and `OnUserAfterOauth2Register` will be removed in the next v0.6.0 release (sometime this week or the week following it) because of some internal changes related to https://github.com/pocketbase/pocketbase/issues/276 (this day I'll try to submit the changes at least in the `develop` branch, but I want to finalize the integration tests before that).

If you are planning to use them, my advice would be to wait until I finalize the API to avoid changes in your code.

**Comment by theMackabu** [comment]
ah, alright
