### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by hkbertoson** [pocketbase/pocketbase#3662]
Not sure if this is an issue with my typescript set up for the actual repo. But I deleted the pb_data and ran `./pocketbase serve` again and still throwing this error. 

![Screenshot 2023-11-02 at 7 55 26 PM](https://github.com/pocketbase/pocketbase/assets/44106297/88b3db1e-aeb5-46c8-bbe9-22b23cbb2d13)

**Comment by ganigeorgiev** [comment]
This is already fixed in `master` (see https://github.com/pocketbase/pocketbase/issues/3627).

I'll publish a minor release sometime later today, but as mentioned in the above discussion, this file is not required for PocketBase to work and it is not intended to be part of your TypeScript project build chain. It is there as ambient TS declarations to help your editor's LSP to provide basic intellisense (docs on hover, methods auto completion, etc.).
