### ISSUE TITLE
Carry on Presentable Fields in Admin UI

### ISSUE THREAD

**Issue by pranjaldugar** [pocketbase/pocketbase#3666]
Hi,
It would be nice to ...,
lets say we have 3 collections,

- `Persons` with fields `name`, ....
- `Subscriptions` with fields `person` (Relation to collection Persons), ...
- `Events` with fields `subscribers` (Relation to collection Subscriptions), ...,

if field `name` (Persons) & `person` (Subscriptions) are marked Presentable,
it would be nice to be able to see the person's name in Events when selecting (instead of ids) subscribers (Relation Picker and Relation Chip).

Thanks for your work!

**Comment by valentincostam** [comment]
I would love to see this implemented.

Does it have anything to do with [this issue on the roadmap](https://github.com/orgs/pocketbase/projects/2/views/1?filterQuery=relation&pane=issue&itemId=32121831)? If so, I'm glad to see it on the backlog.

**Comment by mrelemerson** [comment]
Hello, I am just implementing this scheme and it happens that it does not show the presentable field of "objects" referenced in "permissions" in the "role_permissions" collection

![image](https://github.com/pocketbase/pocketbase/assets/9539916/628e4570-b885-4455-8c97-41f81f7432a0)
[https://mfi.engineering/extensible-and-secure-authorization-with-nestjs-and-casl-c6f6d1ceefd5](url)

![image](https://github.com/pocketbase/pocketbase/assets/9539916/bca504cb-8619-49df-9ceb-cb1716742190)

![image](https://github.com/pocketbase/pocketbase/assets/9539916/17233d08-85e9-46e6-8717-11a7094c93de)

Thanks for your work!

**Comment by austinkeil** [comment]
Would like to revisit this, would be really nice to have this feature

**Comment by austinkeil** [comment]
Thanks for offering to take a look @ganigeorgiev and apologies for posting in both threads. Here's the exported collections structure. 

[pb_schema.json](https://github.com/user-attachments/files/16402503/pb_schema.json)

I have a "workout" that has a relation to a "split" which is its parent. Each split has a workout_list, and each workout in the list has a parent split it belongs to. 

When I create a new empty workout split, I want to be able to create new workouts for that split. Those workouts will often have the same name as a workout from another split, despite being made up of different exercises. For example, both the "Austin Split" and "PPL Split" may have a "Push Day," but these will be different workouts by both ID and the exercise list, and they should have different parents. In the admin UI, when I view the split collection and try to add workouts to the workout_list using the picker, I can't see what the parent name of each workout is. Without the parent name, I'll have multiple "Leg Day" workouts but will be unable to see which one goes to which parent, and won't know which to select from the picker.

<img width="1225" alt="Screenshot 2024-07-28 at 12 19 44 AM" src="https://github.com/user-attachments/assets/e7cd9d9a-c1e3-4755-8e35-6a88f7942e2e">
<img width="877" alt="Screenshot 2024-07-28 at 12 19 56 AM" src="https://github.com/user-attachments/assets/4b743af2-8c7c-479e-9268-236d5319eee0">

**Comment by ganigeorgiev** [comment]
@austinkeil You are posting at multiple places and it is getting really confusing to follow. Please stop doing it. Your issue is the same as the above requested feature. Currently the Presentable option is not recursive (aka. it doesn't work in nested relation fields) primarily because of:
- performance concerns
- planned experimenting with different relations representation and eventually removing the "Presentable" option entirely

This issue remains a low priority and I'll appreciate if users stop spamming me unnecessary with it.

**Comment by austinkeil** [comment]
Yeah man I just apologized for posting in both threads, intention wasn’t to spam just contributing to two different discussions but it won’t happen again. Thanks for explaining why it’s not implemented. 

I do think my use case is going to be pretty common and it would be nice to have a solution for it. Showing the ID instead of the name of the parent makes it pretty difficult to build my app as the object ID doesn’t tell me much without a lot of digging to find what it represents.

Not intending to spam, but things like this remain low priority if nobody requests them and if discussions about them are hidden and discouraged.

**Comment by ganigeorgiev** [comment]
This is implemented as part of the ongoing [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) together with some other minor `relation` field changes and will be available with the next v0.23.0 release soon (_there are no ETAs yet_).

For now the Presentable option is checked up to 2 nested levels depth and it is applied for all relation representations - records listing, relation field form input and the relation picker.
