### ISSUE TITLE
Internationalization Support

### ISSUE THREAD

**Issue by Tim-Paik** [pocketbase/pocketbase#37]
I didn't find a way to switch languages on the official website, documentation, dashboard, etc. Maybe one would be nice? Great projects need international support!

**Comment by gedw99** [comment]
I use i18n for golang backend. Dates and Tines and currency need to be handled too. 

Have not checked if db late stores datetimes in Zulu tine and convers to uses local for gets and the opposite for sets to the db . Anyone know if it does ?

**Comment by gedw99** [comment]
The standard golang way is also good . Explained ere: https://www.alexedwards.net/blog/i18n-managing-translations

**Comment by ganigeorgiev** [comment]
Internationalization for the error responses could be done client side because each error comes with a fixed key `code` that could be used as a translation key. Internationalization for the user defined data is left to the users, either by creating a multiple fields (eg. `enTitle`, `deTitle`, etc.) or by maintaining each language data in its own collection.

About the internationalization for the public resources - coming from maintaining [Presentator](https://github.com/presentator/presentator), which is pretty much stable and where we support more than 8 languages via [Transifex](https://www.transifex.com/presentatorio/web-platflorm/), it's really hard to maintain and verify users' contributions (for documentation will be a nightmare to support).

PocketBase is still in its very early development stage and a lot of things would change making the translations irreverent.

I'll close the issue for now, but when we reach v1.0.0 will definitely reconsider it and will start a discussion with the community to see how many people are willing to help.

**Comment by iskaa02** [comment]
As you proposed having something `enTitle`,`deTitle` would work just fine for bilingual application but application that support over 4 languages it will be hard to maintain and use.

what i thought about is having a new field type called 'i18n' and it will be JSON, each key will represent a language.
```json
{
  "en":"support for more than one language"
  "ar":"دعم لأكثر من لغة"
}
```
 when resolving records the language will be taken from Http header and there should be a fallback language when the language on the header not supported.
this would make it more convenient and easier to use.

Not sure if you think if this is good fit for the project, or specialized use case, I've already built a very basic version that fits my needs, if you want we can work on this together.

**Comment by ganigeorgiev** [comment]
@iskaa02 For strings this will be fairly simple, but we will have to add support for all the other types and their validators and options (how for example unique will work in this case?). i18n in my opinion will complicate too much the UI management, the API rule checks and will be hard to maintain in general. It could be handled eventually as "hidden" special collection type, but then the create/update will have to have a special handling for nested data... Overall there are several ways to handle this but it's not something that can be done easily.

**Comment by gedw99** [comment]
weblate is pretty good and also open

here is a golang project that uses it
https://github.com/binwiederhier/ntfy

examples for their docs at least:
https://github.com/binwiederhier/ntfy/tree/main/web/public/static/langs

**Comment by gedw99** [comment]
https://docs.photoprism.app/developer-guide/translations-weblate/ also uses it
https://translate.photoprism.app/projects/photoprism/

you can self host the translation server with a simple docker.
https://github.com/WeblateOrg/docker

**Comment by ravelinodecastro** [comment]
When creating new collection (called scheme inside the squidex) you have a checkbox called localizable. If you selected this for any kind of fields (text, file, etc) you have a tab in ui with the langs that your app support (you define it in settings) then you can save new records with the desired transalations and you can return it via API in two ways. E.g: Consider that we have a collection that returns a **title** that it's localizable and an image which it is not:

First way:
`
title: {
en: "Hello World",
pt: "Olá Mundo"
}`

Second way (based on a headers sent by the client, you can return in a specific lang:  headers': { 'en: this.$i18n.locale, 'X-Flatten': true }

title: "Hello World"

So this will be a interesting feature for pocketbase.

**Comment by ganigeorgiev** [comment]
@ravelinodecastro, @gedw99 Internationalization support for the records data is not planned since it will complicate too much the internal and the query/filtering layer and therefore at least for now this remains out of the scope for v1.0.0 (if you haven't already, you could check our current roadmap in https://github.com/orgs/pocketbase/projects/2).

**Comment by ravelinodecastro** [comment]
This is a much an amazing project. Maybe this feature will be considered one day.

**Comment by gedw99** [comment]
Ok I understand. Thankyou for the efforts and updates.

**Comment by gedw99** [comment]
@ganigeorgiev you have definitely lite a spark - lots of interest is this firebase alternative

**Comment by gladson** [comment]
To help with the discussion...

https://github.com/maximilien/i18n4go

**Comment by lifetin** [comment]
It's been two years, but there's still no support

**Comment by ganigeorgiev** [comment]
@lifetin As mentioned in https://github.com/pocketbase/pocketbase/issues/3422#issuecomment-3449706346, this will be the last time when I'll ask you to stop spamming.

**Comment by thelooniepen** [comment]
I see this is closed. I was looking to selfhost for a small family business for my in-laws. The company is run out of Colombia, so Spanish support would be awesome. My partner and I would be happy to help with that translation if you ever reopen this issue.  Otherwise, this is a beautiful project, thank you for the work :D 

Edit: to add for anyone coming across this later -- the built-in browser translation worked perfect for the UI 🤦‍♀️ (even changed "John Doe" to "Juan Doe" haha) They won't be setting up any tech side anyways, so documentation won't be an issue for me. The offer above still stands though!
