### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by ganigeorgiev** [pocketbase/pocketbase#370]
This was discussed in https://github.com/pocketbase/pocketbase/discussions/50, https://github.com/pocketbase/pocketbase/discussions/360, https://github.com/pocketbase/pocketbase/discussions/369 and others.

We can use the existing `text` field type and add a new field option to toggle between "_Plain text_" and "_Rich text editor_" which will change only the visualization in the Admin UI Record upsert form.

**Comment by theMackabu** [comment]
sounds pretty good, makes markdown in the text field probably easier to write in

**Comment by somarand** [comment]
I suggest lexical from facebook. The web version has been stable and being used on facebook, whatsapp etc. [https://lexical.dev/](https://lexical.dev/)

**Comment by paulocoutinhox** [comment]
+1

**Comment by brewhousedigital** [comment]
I'd recommend Quill. Used it in the past on a project and found it very easy to work with:
https://quilljs.com/

**Comment by jmas** [comment]
I'm using https://ckeditor.com/ version 5 and I guess it's cooked well. Please check it also. Thanks.

**Comment by Zagorodnyi** [comment]
Any updates or plans on this?

**Comment by ganigeorgiev** [comment]
@Zagorodnyi It is in the [roadmap](https://github.com/orgs/pocketbase/projects/2) but it is a low priority for now.

**Comment by blackfyre** [comment]
Probably the worst thing about this would be to find a usable editor... But yes, this is definitely on the top of my whish list!

**Comment by sn0rk64** [comment]
There are svelte implementation for quilljs https://github.com/typewriter-editor/typewriter. +1 For quilljs editor

**Comment by blackfyre** [comment]
> There are svelte implementation for quilljs https://github.com/typewriter-editor/typewriter. +1 For quilljs editor

tbh, quill is missing tables... my personal preference would be a relatively simple markdown editor, but it's not our decision.

**Comment by emastho** [comment]
Very excited for this

**Comment by chz** [comment]
Need this one

**Comment by emastho** [comment]
If we are making it CMS friendly, boolean types also could just be switch buttons instead of open sidebar then switch

![2022-12-16-211549_1920x1080_scrot](https://user-images.githubusercontent.com/100141028/208172782-73ea7ff7-52d7-4460-ad9f-b883b7bd3d6d.jpg)

But these are just my thoughts

**Comment by denisgurev** [comment]
@ganigeorgiev Can we get an estimate for this feature and when it will be available? I'm planning to use PocketBase for a new project and the existing functionality + the text editor is probably 90% of what I need.

**Comment by ganigeorgiev** [comment]
@denisgurev This is already in the roadmap and it will be available in the near future but there are no fixed ETAs.

You can check the currently planned tasks priority in https://github.com/orgs/pocketbase/projects/2.

If nothing critical come up, this feature probably will be implemented as part of PocketBase v0.12 or v0.13.

**Comment by AmFlint** [comment]
Hello,

I looked at a few of these libraries.

Lexical seems to be the most "complete" option, however it is also pretty complex to use, although there's a Svelte implementation available (https://github.com/umaranis/svelte-lexical). This implementation seems pretty new and I don't know if it is/will be maintained in the future. Re-writing an implementation could take time, complexity and might require maintenance in the future.

Typewriter seems like a good alternative as the base library supports Svelte out of the box (built with Svelte), it is a more lightweight editor, and does not have as many features (for example, no support for `tables` at the moment, but it's on the roadmap).

Another good alternative would be [ByteMD](https://github.com/bytedance/bytemd), which is also built with Svelte and supports Svelte out of the box. It supports Markdown very well, the Playground shows a "split" panel with Markdown editor on the left and Preview on the right. I haven't looked at how it could be customized for PocketBase's needs.

I could take on this issue and write the implementation for it but I'd need more informations regarding what PocketBase would like to do, because as explained above, there are pros and cons to each approach (lexical => Complexity and maintenance, TypeWriter => lack of features ?, ByteMD => Edit mode = mardown, and Preview mode = rendered content ?).

In my opinion, ByteMD would be the best option here, as most PocketBase users who'd want to use a TextEditor will probably use Markdown (although there's a toolbar that generates Markdown for you -> bold,italic,headings,tables,lists...) and users could easily switch between edit and preview mode (PB's admin UI upsert panel is probably too small to open both modes next to each other).

In my opinion, Lexical is definitely too complex for the use case. TypeWriter is a good alternative too.

Also there are some other questions to ask ourselves: How do we handle images embedded in the text ? Should the user upload the images to another "file" field, and then refer to the link to this image in the editor (I guess that's how it would work, right ?)

**Comment by ganigeorgiev** [comment]
@AmFlint I'm planning to use [TinyMCE](https://github.com/tinymce/tinymce) (the latest v6 is MIT licensed) since it is the most user friendly of all the alternatives I've tested (CKEditor also works nice but it is GPL licensed).

Image embedding will be handled either via abs url and/or base64 data/uri string (I believe TinyMCE has already support for this, but even if it is missing, we can create a small plugin for that).

User contributions are welcomed but I don't want to rush and merge features just because there is a PR, especially when I'm not entirely sure what would be the best approach to handle it (my initial idea was to add an optional "Appearance" field to the `schema.TextOptions` but I haven't though too much on it and maybe there is a better way).

**Comment by hungcrush** [comment]
![Image](https://user-images.githubusercontent.com/8098916/209494781-d1e9af7a-9467-425d-881c-d5e2cf5380a1.png)

![Image](https://user-images.githubusercontent.com/8098916/209494789-2eadafa4-3a43-4b56-a5a3-239e4e8dfd66.png)

I'm feeling "a new field option" to _text_ will make it complicated.. anyway it's just my opinion..

**Comment by fbaube** [comment]
There is also [TipTap](https://tiptap.dev/), which builds on ProseMirror.

**Comment by filipsobol** [comment]
Hey 👋

CKSource offers Open Source projects the ability to choose the license they like/need. You can read more about it here: [https://ckeditor.com/wysiwyg-editor-open-source/](https://ckeditor.com/wysiwyg-editor-open-source/)

**Comment by ganigeorgiev** [comment]
This is implemented in the `develop` branch as new `editor` field type.

Although I also liked the editing experience in CKEditor, I've decided on TinyMCE because it has similar functionality and its license (MIT) is a little more permissive and it allows to be used even in private forks without the extra conditions.

For now the new field doesn't have any options and it is kept as simple as possible but depending on how users end up using it, we may eventually enable customizing the default toolbar(s) and plugins individually for each `editor` field. Here is how it looks at the moment with the default configuration:

![screenshot](https://i.imgur.com/bgnXkai.png)

The field will be available with the next v0.12.0 release soon.

**Comment by blackfyre** [comment]
Personally, I would love a markdown option! But one step at a time! 😃

**Comment by filipsobol** [comment]
For those who may come across this post in the future, I want to clarify that [CKSource licenses that we offer to Open Source projects](https://ckeditor.com/wysiwyg-editor-open-source/) also apply to forks.

We also have [great support for (GitHub Flavored) Markdown](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html) 😊

**Comment by ganigeorgiev** [comment]
@filipsobol While the CKEditor license may apply to forks (not all forks are public!), still per the website the following conditions must be met:

> - **Your project needs to be released under an [OSI-approved license](https://opensource.org/licenses/category).**
> - **Your source code needs to be publicly available.**
> - Your software must not enter into direct competition with our products.
> - You must contact us to obtain a license.

**Comment by juangiordana** [comment]
I'm digging into the project and I'm delighted! Thanks @ganigeorgiev !

I really enjoy the fact that the current interface allow developers to be closer to the metal (code/db).

Having a WYSIWYG editor may add a layer of complexity in the maintenance of the backend's UI and may cause backwards compatibility issues in the future, like which flavour of markdown is supported, etc.

IMHO today's frontend frameworks provide enough facilities for developers for adding an editor. It's a developers' job to add that functionally to whatever they are building.

Just a thought.
