### ISSUE TITLE
Roles and Permissions (Feature)

### ISSUE THREAD

**Issue by suryatmodulus** [pocketbase/pocketbase#377]
User Roles Tab - Which contains collection-wise permissions - Display UI Elements based on permissions
Ex: Collection tab must be visible if user has read access. Create button must be visible if user has write access. etc
Similar to https://docs.strapi.io/user-docs/latest/users-roles-permissions/introduction-to-users-roles-permissions.html

**Comment by ganigeorgiev** [comment]
This was previously discussed in https://github.com/pocketbase/pocketbase/discussions/94, https://github.com/pocketbase/pocketbase/discussions/261.

This has 2 nuances depending whether you want to create roles for users or admins.

PocketBase admins act as developer accounts - they can read and modify everyhing. Collection API rules don't apply for them.
At least for v1.0.0, I don't plan adding support for admin roles because it will complicate unnecessary the public API when PocketBase is used as framework.

For user permissions on the other hand, we have Collection API rules and custom fields that you can use to create your own role/team/group access controls.

I agree that user role level permissions are simpler but they also are very limited because you cannot create easily an "ownership" type of relation with just roles (for example, allow read/modify access to a set of projects that are owned by a user/team based on a `projectId` field).

Role style permissions are more suitable for general content management, while PocketBase try to be a little more "low level" than that.

Please keep in mind that there is an active proposal to merge the existing users and profiles entities into a single one, which is expected to simplify the users management. You can review the proposal and share your feedback here - https://github.com/pocketbase/pocketbase/issues/376
