### ISSUE TITLE
Fail to update settings through migrations when using `encryptionEnv`

### ISSUE THREAD

**Issue by SkYNewZ** [pocketbase/pocketbase#3793]
I want to update some settings using migrations. I'm using the example from documentation: https://pocketbase.io/docs/go-migrations/#examples, especially the `dao.FindSettings` method.

But when using it on a Pocketbase instance already running, initiated with `--encryptionEnv`, this method raise an error telling the encryption key is missing. It seems normal but how to specify the value of the `--encryptionEnv` flag on migration file ? We don't have access to a `pocketbase.App` instance.

```go
func init() {
	m.Register(func(db dbx.Builder) error {
		dao := daos.New(db)

		settings, err := dao.FindSettings()
		if err != nil {
			return fmt.Errorf("failed to load settings: %s", err)
		}

		// some settings tweaks
	}
}

```

**Comment by ganigeorgiev** [comment]
Migrations currently doesn't have access to the app instance because the runner needs only access to the database. This may change in the future but for now if you use settings encryption you need to pass the env variable as argument to the [`FindSettings` call](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.19.4/daos#Dao.FindSettings).

The variable can be read for example with `os.Getenv("YOUR_ENV")`.

If that doesn't help, feel free to let me know and I'll investigate it further.

**Comment by ganigeorgiev** [comment]
_Also note that when saving the settings you need to pass again the encryption key as second argument in [`dao.SaveSettings(newSettings, encryptionKey)`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.19.4/daos#Dao.SaveSettings)._
