### ISSUE TITLE
Dockerhub images

### ISSUE THREAD

**Issue by wojtekw92** [pocketbase/pocketbase#381]
Hey, are you planning to release pocketbase as Docker image? According to goreleaser docs that should be quick and easy setup(https://goreleaser.com/customization/docker/). I'm happy to extend the configuration as Pull Request. The question is which registry should be used for this project.

**Comment by ganigeorgiev** [comment]
It is in the roadmap (you can subscribe to this issue https://github.com/pocketbase/pocketbase/issues/92), but it's a low priority because it will be hard to maintain while sill making frequent releases. I had bad/cumbersome experience in the past with docker hub while maintaing my other open source project Presentator and for now I don't want to bother with the same while working on PocketBase.

You can always create your own dockerfile pretty easily. PocketBase is fully portable and basically the commands that you'll have to execute are:
- download the linux archive for the specific release version from https://github.com/pocketbase/pocketbase/releases
- extract it
- RUN the executable

And that's it.
