### ISSUE TITLE
Issues with email feedback (`requestPasswordReset`, `requestVerification`, etc.)

### ISSUE THREAD

**Issue by Amir-Zouerami** [pocketbase/pocketbase#3831]
I have recently discovered two potential problems in Pocketbase mail service.

## 1. No Proper Feedback After Calling `requestPasswordReset`

In my application Logic I use `requestPasswordReset` to send a password reset request. The request resolves successfully and even in the logs there are no errors (`200` status). However, the email was not sent. After sending a "test email" from admin UI I get the following error:
```
Failed to send the test email. Raw error: 
500 Error: (DataError) 1406 (22001): Data too long for column 'subject' at row 1.
```
After changing the subject, the email was sent, however the subject was not that long to constitute such error. So I looked further.

## 2. Conversion of Arabic & Persian Characters
The subject line in my email is in Persian (لطفا حساب کاربری خود را تایید کنید):

![01-mail-subject](https://github.com/pocketbase/pocketbase/assets/53701884/8e380685-da2a-4de8-8d68-ae789923cf8a)

However the subject I receive is this:

![02-subject-received](https://github.com/pocketbase/pocketbase/assets/53701884/61832a5a-4def-43c0-906f-bc25f01d4ffe)

I am assuming Pocketbase encodes characters behind the scene? I can't be sure though because I am using a test SMTP email service from [wpoven](https://www.wpoven.com/tools/free-smtp-server-for-testing) and I don't know if the problem is of this service or Pocketbase.

---

 Even if the encoding problem is from the test SMTP service, I am still not getting proper feedback in my application because Pocketbase SDK simply returns `true`.

**Comment by ganigeorgiev** [comment]
0. The error seems to originate from the mail service and not from the PocketBase validations. Please try with mailtrap.io or other similar SMTP service.

1. This is intended because the reset password action is always public and it is done to avoid (to some extend) emails enumeration. In the next release the error will be available in the "Logs" section in the Admin UI instead printed in the stderr.

2. We don't perform any additional encoding to the subject field (at least not explicitly). The issue is most likely with the client of the SMTP service. It works fine for me when testing with mailtrap.io.
