### ISSUE TITLE
Feature Request: request rate limit

### ISSUE THREAD

**Issue by chunlee-thong** [pocketbase/pocketbase#387]

**Comment by ganigeorgiev** [comment]
This is usually hard to implement because the requirements could differ from use case to use case (for example, rate limit per what metric - ip, api usage, request bursts, etc.).

As mentioned in the documentation (https://pocketbase.io/docs/going-to-production/#deploy-behind-reverse-proxy), if you need more advanced network controls like individual timeouts handling, rate limiting, ip whitelist/blacklist, etc., my recommendation is to use nginx/apache as a reverse proxy.
