### ISSUE TITLE
Content-Type header for .aac and .m4a files

### ISSUE THREAD

**Issue by soukupl** [pocketbase/pocketbase#390]
Hi, there is an issue `/api/files/...` when .aac or .m4a file is uploaded. Uploading via web admin checks for correct mime-type, but the file itself is served with `video/mp4` mime-type when requested via API.

![2022-09-05---000282](https://user-images.githubusercontent.com/1013968/188438535-77c5640d-9f48-4c98-bc52-ac42048ebeb1.png)

The wrong mime-type is stored in .attrs file. When fixed in the .attrs file to `audio/x-m4a`, correct mime-type is returned via API.

PockletBase v 0.6.0 and JS-SDK 0.7.0

**Comment by ganigeorgiev** [comment]
Yes, slight differences between the admin checks and the returned response are possible because the stored mimetype in the .attrs file is set using the standard go `net/http` package, where when doing validation we have our own check with a little more detailed mimetype signatures (see https://github.com/pocketbase/pocketbase/issues/351#issuecomment-1228031449).

We can add an exception to some audio files and manually set a custom mimetype (similar to how we handle svg files).
Does the returned `video/mp4` mimetype cause issues? Currently `video/mp4` is part of the [inline serving file mimetypes](https://github.com/pocketbase/pocketbase/blob/master/tools/filesystem/filesystem.go#L182), so browsers should be able to display a preview for the file.

**Comment by ganigeorgiev** [comment]
Actually, we may be able to remove the inconsistency between the detected and the stored/served mimetype. `ContentType` is part of the [`WriteOptions`](https://github.com/google/go-cloud/blob/master/blob/blob.go#L1234) struct so it may be possible to force a different content type sniffing during the upload instead of using the default `net/http`.

I'll have to experiment with that and eventually will release a fix as v0.6.1 sometime later this week.

**Comment by ganigeorgiev** [comment]
@soukupl I've added a fix in master - now we'll serve the same mimetype that was detected during upload. An exception to this rule will be only `.svg` because it doesn't have an official unique bytes signature (https://github.com/whatwg/mimesniff/issues/7) and we will always force `image/svg+xml` so that browsers could load it in a img tag.

I'll close the issue for now. The normalization will be available in v0.6.1 (sometime later this week).

**Comment by soukupl** [comment]
Hey! Thank you very much! It was actually a problem as React Native implementation of AV depends on mime-types and video/mp4 will prevent audio from playing directly from the URL... At least iOS will try to play it as video and will raise an error.

So thank you guys!
