### ISSUE TITLE
Feature Request: allow filter `@request.headers.x_token` to be match to a collection

### ISSUE THREAD

**Issue by copongcopong** [pocketbase/pocketbase#3928]
From my tests, request headers can only be match with a string. 

This request will make the matching dynamic with a specified field of a collection.

sample filter can be:

`(@request.headers.x_service_token = @collection.configs.keyval && @collection.configs.keyid = 'MY_KEY_TOKEN') && @request.auth.id != '' `

where `@collection.configs` is a simple key-value like collection/table

**Comment by ganigeorgiev** [comment]
Each side of an expression can be compared to technically anything.

I don't understand your specific use case, but note that `@collection.*` rule is intended to be used as "join" and it usually needs to be combined with the any/at-least-one operators (aka. prefixed with `?`), otherwise the rule will attempt to perform a match-all by default (aka. all records from the joined collections will have to match with your condition(s)).

I'm not sure if that's what you are looking for but you could try:

```js
@request.auth.id != '' &&
@request.headers.x_service_token ?= @collection.configs.keyval &&
@collection.configs.keyid ?= 'MY_KEY_TOKEN' 
```
The above rule would roughly translates to:
_ require the request to be authenticated AND
- require the `x-service-token` header value to have at least one matching `configs.keyval` record value AND
- require the matching configs records from the previous rule to also have a keyid='MY_KEY_TOKEN'

In any case, I'll close the issue as I think we already support what you seems to want, but if that's not the case please elaborate and/or provide a sample data structure to understand better your use case.
