### ISSUE TITLE
I cannot delete tables or views with "Failed to delete collection due to existing dependency."

### ISSUE THREAD

**Issue by pagoru** [pocketbase/pocketbase#3947]
- Create a new table (v0.20), 
- Try to delete it
- "Failed to delete collection due to existing dependency."

It doesn't make any sense

**Comment by ganigeorgiev** [comment]
I don't think this is a PocketBase issue.

Double check that there is no other collection that reference the one you are trying to delete/rename.

If you are still not able to find the culprit, feel free to paste your collections configuration as json (Admin UI > Settings > Export collections) and I'll have a look.

**Comment by pagoru** [comment]
I cannot send you my collections, this is a bug. I'm gonna downgrade...

**Comment by ganigeorgiev** [comment]
It is not a bug because we have automated tests that checks the delete operation and also the issue is not reproducible in the live demo.

If you jumped several versions, double check your view queries for missing dependencies.

But without export of your collections configuration I don't know how to help you.

**Comment by ganigeorgiev** [comment]
You can enable the debug logs in v0.20 by going to the _Admin UI > Logs > Log settings_ and set `-4` as "Min log level" value.
 

Perform again the delete operation and check if there is a more detailed error message with the failed request. To see the admin request logs make sure to switch the "Include requests by admins" toggle.

**Comment by pagoru** [comment]
The tests are not checking what happens if a collection has a problem (because has an outdated data) and you try to delete a different collection with no problem or relation at all. So when you delete the new collection, because of the other problem, you cannot. Stop checking for every collection and check only related ones.

You try to close issues as soon as possible to have good numbers (like a lot of current open software, and this doesn't make a good image of the community tbh), but this is a real bug.

**Comment by ganigeorgiev** [comment]
@pagoru I don't care about any "numbers", nor "image". I'm not selling you anything, this is just a hobby project. What I care is about is my mental health and having cluttered issues tab with unreproducible reports and constant spam doesn't help with that.

We have to resave all views because we don't know what collections take part of a view query. The view can be literally anything and the source of the view records could be even an expression, eg. union between multiple other collections or even manual typed data (eg. `select 1 as id`). It is not a bug and it is just how it works. It is better to throw a validation error to the user instead of leaving your db in a broken state.

If you think that it can be done better, feel free to open a PR and I'll try to review it, but again - this is just a hobby project.

**Comment by pagoru** [comment]
Sorry!
