### ISSUE TITLE
Feature Request: Authentication endpoints with filters

### ISSUE THREAD

**Issue by notpolyglot** [pocketbase/pocketbase#4008]
```js
const authData = await pb.collection('users').authWithPassword('YOUR_USERNAME_OR_EMAIL', '1234567890');
```
This doesn't allow for multi tenant architecture, however it could be possible if there was a filter parameter. for example:
```js
const authData = await pb.collection('users').authWithPassword(
                                            email: 'YOUR_USERNAME_OR_EMAIL',
                                            password: '1234567890',
                                            filter: 'app_id == "11a4c096-2355-4040-ae7a-f80f1b949a14"');
```

**Comment by ganigeorgiev** [comment]
I'm not sure I follow but there are no plans to add "filter" support as I don't see how this will be useful.

Note that you can also create different [Auth collections](https://pocketbase.io/docs/collections/#view-collection) in addition to the default "users".

If that's not what you are looking for, please elaborate on your use case and/or consider filing a Q&A discussion, but for now this remains out of the scope.

**Comment by ganigeorgiev** [comment]
Additionally, if you want to manage the access to your collection based on some `app_id` field, the better approach will be to perform the checks in the specific collection, aka. `@request.auth.app_id = "..."` instead of restricting the authentication as the auth token can be created via different actions (eg. refresh, OAuth2, etc.).
