### ISSUE TITLE
Authentication Bug with Oauth2

### ISSUE THREAD

**Issue by Bastian1110** [pocketbase/pocketbase#405]
Developing a project with Pocketbase in React (create-react-app). I was using Oauth2 with Google on version 0.4.0 and everything was going great. The day before yesterday I decided to try version 0.7.0, however it seems to me that the authentication has been broken, since doing many tests I have realized that it is "stuck" with a particular user, when I try to log in a user everything goes well , authdata comes with the information of the logged in user, however, when I check what's in authStore, it still has the information (all the model) of the "stuck" user.
Turns out this happens even when it's in production, when users log in with their google account, it takes them to the redirect page, but even with the user being "stuck", even though the user "stuck" has never logged in from that computer.
I don't know if it has something to do with the fact of changing the version from 0.4.0 to 0.7.0 and that I have to update the login system.

Here is the code with the [LogIn Button](https://github.com/Bastian1110/Smart-Campus-React/blob/master/src/components/NavBar.js)

And here is the [Redirect](https://github.com/Bastian1110/Smart-Campus-React/blob/master/src/pages/Redirect.jsx) code

I'm still doing several tests to check where the error is coming from, I hope it's not a bother. I love pocket base <3

**Comment by ganigeorgiev** [comment]
What do you mean by being "stuck" - signed in with different google accounts and while returning the same PocketBase user? 

That shouldn't happen, at least I cannot reproduce it locally.

**Comment by ganigeorgiev** [comment]
@Bastian1110 I guess by "stuck" you mean that there is an error that prevents you to login with your google user account, right?

I've created a new Google OAuth2 app and indeed the auth response wasn't  correctly mapped because I was using https://cloud.google.com/identity-platform/docs/reference/rest/v1/UserInfo for the mapping, but this turned out to be incorrect, since the `localId` is actually returned as `id`.

I've updated the provider mapping in [v0.7.1 release](https://github.com/pocketbase/pocketbase/releases).

_If you are still experiencing errors, please start the PocketBase executable with `--debug` and see if an error message was logged somewhere in the terminal._

_p.s. It is a good idea to update your [JavaScript SDK](https://github.com/pocketbase/js-sdk/releases) version too._
