### ISSUE TITLE
(*PocketBase).DefaultDataDir has no effect

### ISSUE THREAD

**Issue by ca1f** [pocketbase/pocketbase#409]
It seems that calling `(*PocketBase).DefaultDataDir` has no effect on the data dir value used by pocketbase.

Example:
```go
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/pocketbase/pocketbase"
)

func main() {
	app := pocketbase.New()

	baseDir, _ := os.Getwd()
	app.DefaultDataDir(filepath.Join(baseDir, "local", "data"))

	fmt.Println(app.DataDir())

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```

expected output:
`$PWD/local/data`

actual output:
`$PWD/pb_data`

It seems that the default value for the `dir` flag is passed to `cobra` right at the app creation in `pocketbase.New` and subsequent changes to the default value variable held in `PocketBase` have no effect.

**Comment by ganigeorgiev** [comment]
Thanks for reporting the issue.

Yes, this is unfortunetelly a result of the [eagerParseFlags call](https://github.com/pocketbase/pocketbase/blob/master/pocketbase.go#L187). We will have to move it either inside the `pb.RootCmd.PersistentPreRunE` hook or create a config object that could be passed to the `New()` factory so that we can initialize the defaults before parsing the flags.

I'll have a more detailed look at it this weekend, together with [issue #404](https://github.com/pocketbase/pocketbase/issues/404).

**Comment by ganigeorgiev** [comment]
I've just pushed a fix in `master`. It will be part of v0.7.2 release (sometime tomorrow). 

The setters `DefaultDebug`, `DefaultDataDir`, `DefaultEncryptionEnv`, `ShowStartBanner` are removed and replaced with a `NewWithConfig` factory, because there are plans in the future to add more config options and it will be easier to just append them to the config struct:

```go
package main

import (
	"log"

	pb "github.com/pocketbase/pocketbase"
)

func main() {
	app := pb.NewWithConfig(pb.Config{
		DefaultDataDir: "YOUR_CUSTOM_DEFAULT_DIR",
	})

	log.Println(app.DataDir())

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
```
