### ISSUE TITLE
Building a Docker Image

### ISSUE THREAD

**Issue by bscott** [pocketbase/pocketbase#41]
Hello,

Thanks for creating this awesome project. I'm working on a Docker Image for Public use and noticing that Pocketbase forces a user to be created at `serve`. Wondering if there are plans for a config file or ENV Variables?

https://github.com/bscott/pocketbase-docker

**Comment by ganigeorgiev** [comment]
As mentioned in the related issue #31, it doesn't make sense to set env variables for admin email/pass because they are required only once.

I'm closing the issue as duplicated. The interactive cli will be removed and the user will be redirected to "Installer" web page when he to load the admin UI for the first time and there is no admin.

**Comment by bscott** [comment]
@ganigeorgiev Thanks, any idea when that will happen so I can complete the Docker images?

**Comment by ganigeorgiev** [comment]
@krushiraj Sorry, I don't know exactly when it will be done.

In the related issue, @krushiraj mentioned that he wants to work on it, but if he doesn't manage to find time, I may pick it the week after the next one.

**Comment by krushiraj** [comment]
@bscott can you get the binary to execute. I faced issues executing the release binary, hence I went with the following solution https://github.com/krushiraj/pocketbase-docker

**Comment by ganigeorgiev** [comment]
@bscott The installer page is included in the v0.2.0 release.

**Comment by bscott** [comment]
> @bscott The installer page is included in the v0.2.0 release.

Awesome thanks
