### ISSUE TITLE
Documentation for updating Pocketbase Version

### ISSUE THREAD

**Issue by paulHempel** [pocketbase/pocketbase#4111]
I was browsing through the docs and README but didn't find a note on how to properly update to newer versions of pocketbase.

My suggestion would be to
- add menu entry in sidebar of the docs (maybe README as well)
- Mention `pocketbase update` command
- Maybe encourage backing up files before updating, pausing service to prevent data lost in transactions
- Mention possible breaking changes between versions (keep a simple log)

**Comment by ganigeorgiev** [comment]
There is no backward compatibility guarantee before v1 and there are no plans to add individual guides to migrate from older versions since each release could contains different breaking changes.

For list of changes you can refer to the release notes of each [release](https://github.com/pocketbase/pocketbase/releases) or to the [CHANGELOG.md file](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md).
