### ISSUE TITLE
Feature Request: Self Documenting API (OpenAPI / Swagger)

### ISSUE THREAD

**Issue by danfascia** [pocketbase/pocketbase#414]
It would be great if the `/api` route could have a `/doc/api/` version which self documented using [Swagger / OpenAPI](https://swagger.io).

This would be useful for both coming back to projects after a while and also testing whilst building out a frontend. It has also become something of a standard for APIs to include this feature at least as an add-on, if not a core feature. 

There are golang implementations available which could be used.

**Comment by ganigeorgiev** [comment]
This was partially discused in https://github.com/pocketbase/pocketbase/discussions/209#discussioncomment-3217144.

I'm not planning to work on this because I don't think it is worth investing the time working on that. We have autogenerated documentation with examples in the Admin UI if you click on the "Api preview button" (it will change in the near future because collection will have an auth `type` and we will also add the auth endpoints to it). Currently it is per-collection basis, but we can provide in the future a public endpoint that will list/generate a similar documentation for all collections. But I'm against OpenAPI.
