### ISSUE TITLE
Feature Request: Being able to organize collections in folders

### ISSUE THREAD

**Issue by katriellucas** [pocketbase/pocketbase#415]
Just a neat low priority request, would it be possible to add the ability to organize collections in folders?

**Comment by ganigeorgiev** [comment]
At least for now I don't plan implementing custom collections grouping. It will clutter unnecessary the interface in my opinion.

The collection views will be redesigned very soon, because of the users and profiles refactoring, and I may reconsider some grouping mechanism If I happen to find some non-obstructuve way to implement them, but for now this will remain out of the scope for v1.0.0.
