### ISSUE TITLE
Field name index bug

### ISSUE THREAD

**Issue by fly1ted** [pocketbase/pocketbase#4160]
I had a uniq index on `en` field and while trying to add another field, that start with `en`, when typing its name the index started to change as well, see the pic. I'm on [v0.20.1](https://github.com/pocketbase/pocketbase/releases)

<img width="752" alt="image" src="https://github.com/pocketbase/pocketbase/assets/8587695/768a44a1-ec83-4b79-8822-077c6cf7dc02">

**Comment by ganigeorgiev** [comment]
I was able to reproduce it.

It seems that the [replaceIndexesColumn JS function](https://github.com/pocketbase/pocketbase/blob/931f6bc0cb9c72110ca9f6b9a6e8c4c050c8f2f2/ui/src/components/collections/CollectionFieldsTab.svelte#L78-L87) is triggered incorrectly.

I'll submit a fix sometime later this week.

**Comment by ganigeorgiev** [comment]
Should be fixed in [v0.20.7](https://github.com/pocketbase/pocketbase/releases/tag/v0.20.7).

Note that to minimize the returned validation errors and the things users have to update when renaming fields, we try to "guesstimate" whether the index expression is related to the renamed fields and if we can find such index we attempt to update its columns.

If this behavior ended up causing more troubles than actually it tries to solve, I'll consider eventually removing it entirely and leave the changes independent one from another.

**Comment by fly1ted** [comment]
it probably was an edge case, better to keep it
