### ISSUE TITLE
Allow default values on collection fields

### ISSUE THREAD

**Issue by krushiraj** [pocketbase/pocketbase#42]
- Currently there is no field or option to set the default value

I think it would be great to have the feature to set default value for a field.

**Comment by ganigeorgiev** [comment]
This is intentional because it may cause confusions working with the API and it's better to be explicit in this type of situations. 

Or in other words, it's not clear when the default will be applied:
- on create or create/update?
- do we have to fallback to the default when the user provide a value `null` or the property is not found in the sent body?
- what about `multipart/form-data` requests, should users still send `null` as string (PocketBase supports both `json` and `multipart/form-data` content-types)?
- what about other zero values (`0`, `[]`, `""`, etc.)?

Therefore, at least for me, it's better default values to be explicitly set by the user's client-side code.
If for some reason you need to set the default values server-side, then you can always make use of the before update/create [event hooks](https://pocketbase.io/docs/event-hooks/).

**Comment by kikoreis** [comment]
I'm prototyping using pocketbase for a multi-component system status backend. The specific issue I've run into with this limitation is that there's no easy way to allow a request to omit a timestamp and have the server calculate the equivalent to now(); doing this server-side is important for consistency's sake (as it avoids client clock skew issues etc).

**Comment by kikoreis** [comment]
(It would also be nice to be able to default a field to the source IP from the perspective of the server but that's something more sophisticated that would make sense to write a custom hook for)
