### ISSUE TITLE
Create many to many relation with unlimited records

### ISSUE THREAD

**Issue by ElegantSoft** [pocketbase/pocketbase#425]
when I create a schema I can create a relation with another collection but I must enter max select. What if I need the max select is infinity ?

**Comment by ganigeorgiev** [comment]
Currently you can't, you have to type the max allowed js integer (9007199254740991) for example as a workaround of the validator. This is already "fixed" in the refactoring related to #376.

**Comment by ganigeorgiev** [comment]
_Since recently there was a discussion about this, I'll add a note here in case someone ended here in the future - support for storing "unlimited" multiple `relation` field values was reverted as part of the latest refactoring and will be removed in PocketBase v0.23.0. The multiple `relation` field support is usually intended primarily for small/finite number of items like labels, tags, categories, groups, roles, etc. Storing thousands of relations as part of a single db row not only makes it almost impossible to manage from the Admin UI but also is very inefficient because db indexes cannot be utilized properly. For those cases where a lot of multiple relations need to be assigned to a single record, a more traditional SQL approach would be better (either as single one-one `relation` or in a junction collection with 2 `relation` fields). One big limitations with earlier versions was the lack of easy filtering and expanding non-directly related entries but this is already solved with the recent [back-relation support](https://pocketbase.io/docs/working-with-relations/#back-relations). So to summarize, with PocketBase v0.23.0 all multiple valued fields (`file`, `select`, `relation`) will have consistent behavior and the `MaxSelect` option will be required to be > 1 for storing multiple values._
