### ISSUE TITLE
get reverse relations

### ISSUE THREAD

**Issue by ElegantSoft** [pocketbase/pocketbase#426]
If I created post collections and categories collections. I created relation post has many categories and categories has many posts. If I create post with 2 categories I didn't find the posts in category relations. How to do reverse relations and best way to handle many 2 many relations

**Comment by ganigeorgiev** [comment]
Many to many relations could be handled the same way as in a traditional database, for example with a "junction" collection - `post_category_rel` that has 2 relation fields pointing respectively to the post and category collection.

You can filter/query through relations (including nested ones) via dot notation - `someRel.field`. Additionally you can use the `?expand` query parameter to eager load the results from a related collection. Indirect expansion will be also supported soon (see https://github.com/pocketbase/pocketbase/issues/312).

_I'll close the issue because similar questions were filed in the past (eg. https://github.com/pocketbase/pocketbase/discussions/40, https://github.com/pocketbase/pocketbase/discussions/124, etc.), but if the above doesn't doesn't work for you, feel free to comment and I'll reopen it. The existing documentaiton will be improved after the ongoing users management refactoring._

**Comment by ElegantSoft** [comment]
I tried `http://127.0.0.1:8090/api/collections/tags/records?expand=posts(tags)` and it didn't work

**Comment by ElegantSoft** [comment]
@ganigeorgiev 
Okay I will be watching... thanks

**Comment by ganigeorgiev** [comment]
You can still query indirect relations, but you have to eager load the indirect related records on your own, for example by first fetching the relation ids and then making another request to the relation with the previously exported ids (combined with `id = id1 || id = id2 || id = id3`, etc.) See https://github.com/pocketbase/pocketbase/discussions/289#discussioncomment-3370365.
