### ISSUE TITLE
Is there any plans to support web sockets ?

### ISSUE THREAD

**Issue by Tonku** [pocketbase/pocketbase#428]
Amazing framework , thanks...
Will we get websockets ?

**Comment by ganigeorgiev** [comment]
PocketBase is using SSE for the realtime subscriptions. You can find the impmentation in https://github.com/pocketbase/pocketbase/blob/master/apis/realtime.go

I don't plan implementing websockets since I don't see much benefit compared to SSE.
Users can register their own endpoints using the [`OnBeforeServe` event hook](https://pocketbase.io/docs/event-hooks/).

**Comment by Tonku** [comment]
@ganigeorgiev 

I want to make a real-time collaboration app where people can design things on a whiteboard.SSE is server to client only right? How can clients use real time push without websockets?

**Comment by ganigeorgiev** [comment]
@Tonku You use the regular HTTP post requests. This has benefit over websocket, because you have a unified public API and we can make use of the collection create/update API rules without hacky workarounds.

Or in other words, to bubmit a change/new record back to the server, you can call:
```js
await client.records.create("example", { ... });
// or when updating existing record
await client.records.create("example", "RECORD_ID", { ... });
```

_p.s. The SDK records service declaration may change in the near future because of #376 and will look something like: `client.collection("example").create({ ... });`_

**Comment by Tonku** [comment]
Thanks for the details . Can I get real-time mouse moves relayed like firebase real time db ? I mean low latency

**Comment by ganigeorgiev** [comment]
> I mean low latency

Well, thats depends on a lot of factors - your network setup, how close the server is to your users, etc. It also depends how often will you push the mouse events, whether you'll throttle/debounce them or send them in batches, etc.

With websockets you can achieve lower latency times because there is less data to be transimetted over the network but that comes with a maintenance cost because you'll have to maintain 2 different apis for submitting.

My best recommendation would be to create a local POC and benchmark it.
