### ISSUE TITLE
(MinIO) S3 storage problems for SVG and JSON

### ISSUE THREAD

**Issue by dedo1911** [pocketbase/pocketbase#4287]
As already reported in other issues #4274, #2952 and #2068 there seems to be some problems with SVG and JSON files 

I'm using a MinIO setup that is currently having problems with PocketBase.

credentials.go (same credentials used in two tests and a small error check utility to keep rest of the code cleaner)
```go
package main

var (
	bucketName       = "c…t"
	region           = "e…o"
	endpoint         = "s…z"
	accessKey        = "X…Q"
	secretKey        = "O…k"
	s3ForcePathStyle = true
	objectKey        = "q…x/o…r/l…p.svg"
)

func ErrCheck(err error) {
	if err != nil {
		log.Fatalln(err)
	}
}
```

This examples uses `aws-sdk-go` directly, to check if the library can handle MinIO API correctly:
```go
package main

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	"io"
	"log"
)

func main() {
	creds := credentials.NewStaticCredentials(accessKey, secretKey, "")
	sess, err := session.NewSession(&aws.Config{
		Region:           aws.String(region),
		Endpoint:         aws.String("https://" + endpoint),
		Credentials:      creds,
		S3ForcePathStyle: aws.Bool(s3ForcePathStyle),
	})
	ErrCheck(err)
	s3Client := s3.New(sess)

	input := &s3.GetObjectInput{
		Bucket: aws.String(bucketName),
		Key:    aws.String(objectKey),
	}

	result, err := s3Client.GetObject(input)
	ErrCheck(err)
	defer result.Body.Close()

	body, err := io.ReadAll(result.Body)
	ErrCheck(err)

	log.Println("Body:", len(body), "bytes")
}
```
Running the code gives the following output:
_I've ofc saved the file to check it's integrity. It works correctly._
```bash
❯ go run .
2024/02/02 17:15:04 Body: 118469 bytes
```

This example uses PocketBase Filesystem library:
```go
package main

import (
	"github.com/pocketbase/pocketbase/tools/filesystem"
	"log"
)

func main() {
	s3, err := filesystem.NewS3(bucketName, region, endpoint, accessKey, secretKey, s3ForcePathStyle)
	ErrCheck(err)
	defer s3.Close()

	r, err := s3.GetFile(objectKey)
	ErrCheck(err)

	log.Println(r.ContentType(), r.Size())
}
```

Unfortunately as reported in the issues, the file appears to be empty:
```bash
❯ go run .
2024/02/02 17:09:36 image/svg+xml 0
```

**Comment by ganigeorgiev** [comment]
Please provide the svg file you are testing with and a little more details about your MinIO setup (eg.the version you are testing with).

Again, I'm not able to reproduce the issue with other S3 providers. You can try it on your own for example with the Wasabi free trial https://wasabi.com/.

**Comment by dedo1911** [comment]
This is an example file I used today that's not working. Following is also the corresponding json attrs.

![ellieJDM](https://github.com/pocketbase/pocketbase/assets/1364496/0c074608-1640-4cfb-a4ed-64da864f24fe)
```json
{
  "user.cache_control": "",
  "user.content_disposition": "",
  "user.content_encoding": "",
  "user.content_language": "",
  "user.content_type": "image/svg+xml",
  "user.metadata": {
    "original-filename": "logo.svg"
  },
  "md5": "QLT2lgPy3BqUJQcNOj7PAA=="
}
```

**Comment by ganigeorgiev** [comment]
Thank you for the file sample but I still don't think this is PocketBase related.

Keep in mind that your 2 code samples are not equivavlent because as mentioned the file size is read from the attributes/head call.

In other words, to confirm that you get a valid file size with the raw `aws-sdk-go` implementation, please replace `GetObjectInput` with `HeadObjectInput` and check its response length:

```go
in := &s3.HeadObjectInput{
    Bucket: aws.String(bucketName),
    Key:    aws.String(objectKey),
}
resp, err := s3Client.HeadObjectWithContext(ctx, in)
if err != nil {
    return nil, err
}

log.Println(resp.ContentLength) // this should return the same as r.Size() in PocketBase
```

I don't have MinIO setup at the moment to test, but will investigate it further this weekend.

And again, you can try other S3 providers (for example the [wasabi free trial](https://wasabi.com/)) and try to reproduce it with it. If you can't then most likely is a MinIO issue or some peculiarity that will need special handling.

**Comment by dedo1911** [comment]
> In other words, to confirm that you get a valid file size with the raw `aws-sdk-go` implementation, please replace `GetObjectInput` with `HeadObjectInput` and check its response length:

Added your code right after the one I used in the example:
<img width="640" alt="image" src="https://github.com/pocketbase/pocketbase/assets/1364496/7054c1ff-bc53-4a0e-aa2d-9c3958e0e880">
Output:
```bash
❯ go run .
2024/02/02 18:26:39 Body: 118469 bytes
2024/02/02 18:26:39 Len: 118469 bytes
```
> I don't have MinIO setup at the moment to test but will try to investigate it further this weekend.
I can provide you an access key to a dedicated test bucked on my instance.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it using the MinIO playground _(I'm not sure if that matters but I'm testing with the latest PocketBase linux binary)_.

Here is the S3 configuration that you could try (_assuming that no one will change/delete it_):

```
- Endpoint:  https://play.min.io
- Bucket:    pbtest123456
- Region:    us-east-1
- AccessKey: Q3AM3UQ867SPQQA43P2F
- Secret:    zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```

The provided svg file is returned for me with the correct content length (the reported Content-`Length` in the browser console for me is 13240).

**Comment by ganigeorgiev** [comment]
Regarding MinIO - I've tried to investigate it further but I'm not able to reproduce it in the MinIO playground, testing with different files and configurations. Please double check that you are using the latest MinIO version as it is possible to be related for example to https://github.com/minio/minio/pull/4483 (_based on https://play.min.io:9443/support/diagnostics, the reported playground version seems to be "2024-01-18T22:51:28Z"_).

Regarding Cloudflare R2 - I was able to reproduce the zero SVG size issue with Cloudflare R2. The issue is also reproduced with the plain `aws-sdk-go` library using the following minimal code sample:

```go
package main

import (
    "log"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/credentials"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
)

const (
    accessKey  = "..."
    secretKey  = "..."
    region     = "..."
    endpoint   = "..."
    bucketName = "..."
    objectKey  = "..."
)

func main() {
    creds := credentials.NewStaticCredentials(accessKey, secretKey, "")
    sess, err := session.NewSession(&aws.Config{
        Region:      aws.String(region),
        Endpoint:    aws.String(endpoint),
        Credentials: creds,
    })
    if err != nil {
        log.Fatal(err)
    }
    s3Client := s3.New(sess)

    in := &s3.GetObjectInput{
        Bucket: aws.String(bucketName),
        Key:    aws.String(objectKey),
    }

    resp, err := s3Client.GetObject(in)
    if err != nil {
        log.Fatal(err)
    }

    // for some reason there is no ContentLength with the response for SVGs uploaded to R2
    log.Println(resp.ContentLength)
    log.Println(aws.Int64Value(resp.ContentLength)) // 0
}
```

So for R2 it is either some obscure bug with the AWS SDK or there is some peculiarity related to the R2 APIs. But in both cases I don't want and don't have time to invest in this (_also keep in mind that there are plans to remove the `aws-sdk-go` as several users complained about the bloated binary size - https://github.com/pocketbase/pocketbase/discussions/3665_).

But again, this is only for R2 and I'm not able to reproduce the issue with the MinIO playground, so make sure that your local MinIO is up to date. If you still think that it is something related to PocketBase, feel free to open a PR and will try to review it.

**Comment by ganigeorgiev** [comment]
Just tested with `aws-sdk-go-v2` and at least for Cloudflare R2 the zero ContentLength issue is fixed there:

```go
package main

import (
    "context"
    "log"

    "github.com/aws/aws-sdk-go-v2/aws"
    "github.com/aws/aws-sdk-go-v2/config"
    "github.com/aws/aws-sdk-go-v2/credentials"
    "github.com/aws/aws-sdk-go-v2/service/s3"
)

const (
    accessKey  = "..."
    secretKey  = "..."
    region     = "..."
    endpoint   = "..."
    bucketName = "..."
    objectKey  = "..."
)

func main() {
    ctx := context.Background()

    cred := credentials.NewStaticCredentialsProvider(accessKey, secretKey, "")

    cfg, err := config.LoadDefaultConfig(ctx,
        config.WithCredentialsProvider(cred),
        config.WithRegion(region),
        config.WithEndpointResolverWithOptions(aws.EndpointResolverWithOptionsFunc(func(service, region string, options ...interface{}) (aws.Endpoint, error) {
            return aws.Endpoint{URL: endpoint, SigningRegion: region}, nil
        })),
    )
    if err != nil {
        log.Fatal(err)
    }

    s3Client := s3.NewFromConfig(cfg)

    in := &s3.GetObjectInput{
        Bucket: aws.String(bucketName),
        Key:    aws.String(objectKey),
    }

    resp, err := s3Client.GetObject(ctx, in)
    if err != nil {
        log.Fatal(err)
    }

    log.Println(*resp.ContentLength)
}
```

Note that we use `aws-sdk-go` because `aws-sdk-go-v2` is not compatible with GCS out of the box (see the revert from https://github.com/pocketbase/pocketbase/issues/2231).

I'll consider with the next release to upgrade again and will define a custom headers signing function to cover the GCS issue, but once again this is not related to MinIO (or at least not reproducable with `play.min.io`).
