### ISSUE TITLE
Strange backup behavior

### ISSUE THREAD

**Issue by ilyabumblebee** [pocketbase/pocketbase#4328]
Hello!

Yesterday, I set up hourly backups to S3, but it appears the backup process is malfunctioning. Manual backups through a button sometimes work, but occasionally result in 0-byte files. Automatic backups, however, fail entirely, producing a single 0-byte file and then ignoring the scheduled tasks.

![IMG_20240211_155105.jpg](https://github.com/pocketbase/pocketbase/assets/129096750/d9a8d153-7a47-47c1-b56f-c292d42b54a7)

![Screenshot_2024-02-11-15-49-14-958_com.android.chrome.jpg](https://github.com/pocketbase/pocketbase/assets/129096750/4bdd0df4-3924-4d70-b453-d4341bca71ca)

![IMG_20240211_155031.jpg](https://github.com/pocketbase/pocketbase/assets/129096750/f683efcc-8d96-4d82-9c24-74fac4e4801f)

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it.

Check the Admin UI > Logs for any error related to the backups.

It could be also something related to the S3 compatibility APIs of the S3 provider you are using (see similar issue with R2 in https://github.com/pocketbase/pocketbase/discussions/2068).

**Comment by ilyabumblebee** [comment]
Will try disabling s3 for a while and test on local storage.

**Comment by ganigeorgiev** [comment]
Also I just noticed from the screenshot that the 0-byte file you mentioned is `pb_settings_test_*` and this is not the auto generated backup but the file that is generated during the settings test to check whether your S3 configuration is correct.

If the file wasn't removed then that means that either S3 delete api for some reason doesn't work with your provider or you have a file retention policy setup.

**But in any case this file is not the backup.** Check your logs and cron expression. Try also to manually initialize a backup to see if it will be uploaded.

And I remember you from your other question in https://github.com/pocketbase/pocketbase/discussions/4315. Please if you think it is a PocketBase issue make an attempt to provide simple reproduce steps (for example try locally without S3 or with other S3 providers) otherwise there is really no way for me to help you and it will be a waste of time to try to guess what has gone wrong.

**Comment by ilyabumblebee** [comment]
What S3 would you recommend it works fine with?

**Comment by ilyabumblebee** [comment]
Seems indeed a tebi issue

**Comment by ganigeorgiev** [comment]
If you are looking for a free S3 storage for backups, Blackblaze has free plan - https://www.backblaze.com/.
With the next release Cloudflare R2 should also work and the SVG/JSON error reported in https://github.com/pocketbase/pocketbase/discussions/2068 should no longer occur.

**Comment by ilyabumblebee** [comment]
Thanks, will try.
