### ISSUE TITLE
Boolean false value interpreted as missing value

### ISSUE THREAD

**Issue by oSethoum** [pocketbase/pocketbase#436]
Am trying to create new record for the Admin UI, I want the done field to be false since the Todo hasn't been done yet, but I can't find a way to do that. 

![image](https://user-images.githubusercontent.com/88779394/190133787-295ae211-4f4c-4eb6-a184-b4415aa6ce3a.png)

**Comment by ganigeorgiev** [comment]
Yes, this is intentional, since PocketBase fields doesn't support `null` values and automatically fallback to the zero-defaults (similar as in Go). You can read more here - https://github.com/pocketbase/pocketbase/issues/235.

After the users/profiles refactoring I'll add a tooltip somewhere in the field options to clarify the "Required" constraint behavior.

**Comment by kaevupoiss** [comment]
Making a boolean field required should therefore be disabled or at the very least well-documented and hinted. This leads to a lot of confusion. If I understand correctly, required boolean fields can only exist in "true" state, which renders them useless. Am I correct? @ganigeorgiev

**Comment by ganigeorgiev** [comment]
The "Required" constraint means "non-empty/non-zero" value. For PocketBase (and for Go) `false` is the `empty/zero` value. The same apply for strings, where the `empty/zero` value is the empty string and so on. Full table with the supported PocketBase values could be found in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0.

It is not useless because it is a constraint - it allows developers for example to create "I aggree" style type of checkbox with server-side validation.

But as mentioned in the above comment, there will be a tooltip somewhere in the field options to clarify the "Required" constraint behavior.
