### ISSUE TITLE
jpg images are compressed as png thumbnails

### ISSUE THREAD

**Issue by Innovaitec0** [pocketbase/pocketbase#440]
Currently jpg images are compressed as png images which can end up in a larger file. The extend is the right one. But as soon as you open the file with a text editor or look in the infos of the file, you can see that it is actually a png. Tested on 0.6.0.

**Comment by ganigeorgiev** [comment]
@Innovaitec0 Thanks for reporting the issue.

Indeed we were always using PNG as thumb format (the extension doesn't really matter in this case). I've submitted a fix in `master`.

We now will try to detect the image format from the name before generating the thumb (`png` will be always a fallback in case we cannot detect the original).

The fix will be publicly available with the next v0.7.3 release (sometime later this week).

_In any case, even as it is now always storing them as PNG should work just fine even if the  extension is not the correct one and the thumb may be a little larger, since the stored and served mimetype is detected by reading the first couple bytes._
