### ISSUE TITLE
Feature request: restore from backup available from installer UI

### ISSUE THREAD

**Issue by raulrpearson** [pocketbase/pocketbase#4534]
I sometimes start a new Pocketbase instance with the intention of duplicating an existing instance.

I currently run the installer with a dummy admin user and pass and then restore from the backup menu. I think this might be a common flow for some folks.

It'd be more convenient to be able to upload and restore from a backup file directly from the installer UI, to avoid having to create this dummy admin user first.

Thanks for this great piece of software!

**Comment by Fruup** [comment]
Maybe even go as far as specifying a backup to load initially (i.e. `pocketbase serve --initial-backup=init.zip`). This way, no manual steps have to be done.

**Comment by kbruegge** [comment]
> Maybe even go as far as specifying a backup to load initially (i.e. `pocketbase serve --initial-backup=init.zip`). This way, no manual steps have to be done.

I love the idea of having a CLI option to do this. Would help greatly with automated integration tests for me.

**Comment by ganigeorgiev** [comment]
@kbruegge There are no plans to add a CLI option for this and I don't understand what do you mean by _"Would help greatly with automated integration tests for me"_. For automated tests usually you want the test database to be part of your repo and not as archive in order to be able to easily init/change the tests data (eg. `./pocketbase serve --dir="test_pb_data"`).

In any case option to load a backup from the installer UI is already implemented as part of the [ongoing refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and will be available with the next release.

**Comment by kbruegge** [comment]
> For automated tests usually you want the test database to be part of your repo and not as archive in order to be able to easily init/change the tests data (eg. `./pocketbase serve --dir="test_pb_data"`).

Thanks! That's how I currently do it. Just that the I use and empty database with a single predefined user which feels a little weird but works fine :+1:

Thanks for your great work in general. Love Pocketbase ❤️
