### ISSUE TITLE
And (&&) operator not working in API filter

### ISSUE THREAD

**Issue by FedorRasputin** [pocketbase/pocketbase#4546]
Hi.

If I try to send for requests on url http://127.0.0.1:8090/api/collections/users/records?filter=(id='abc' && created='2022-01-01') I got this error
![image](https://github.com/pocketbase/pocketbase/assets/99206375/1202c249-8a33-4100-8104-ddb2d4288a07)
![image](https://github.com/pocketbase/pocketbase/assets/99206375/f98aada3-3f38-4733-8a68-bcced6cae6ec)

If i try use OR operator (http://127.0.0.1:8090/api/collections/users/records?filter=(id='abc' || created='2022-01-01')) pocket base works correctly. 

PocketBase version [v0.22.3]

How to fix this behavior ?

**Comment by ganigeorgiev** [comment]
The operator is working correctly.

Your first example doesn't work because the you are comparing `created` with incomplete date. The full `date` field value format is `Y-m-d H:i:s.uZ` (or `2024-03-12 16:06:57.123Z`).

The second example (with the `||`) works (_if you ignore the fact that there is an extra parenthesis_) because it is a OR condition, aka. probably your  `id='abc'` comparision evaluates to `true`.

If you have further questions, please consider opening a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) instead.

**Comment by migueljr** [comment]
![image](https://github.com/pocketbase/pocketbase/assets/12215747/17b17218-4284-4df3-bd07-c74fd36a1a77)

I can't use && either. Notice how the postman handles this. he understands that it is an empty field.

**Comment by ganigeorgiev** [comment]
@migueljr The `filter` query parameter value must be properly URL encoded. When using the SDKs this happens automatically. For Postman I expect this to be also the case but I guess you need to type your param value in the `Value` column and not in the url bar, but even if that's not the case, this is not PocketBase specific and URL encoding should be applied manually if the tool you are using doesn't do it for you.

If you have other questions, please don't reply on closed issues and consider opening a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with more details about your use case and what you are trying to do.
