### ISSUE TITLE
update: echo version to v4.11.4

### ISSUE THREAD

**Issue by kk7771** [pocketbase/pocketbase#4548]
hi, echo v5 is currently a deprecated, unmaintained version and has not been maintained for a long time, the latest version is v4.11.4 which fixes a lot of bugs.

**Comment by ganigeorgiev** [comment]
echo v5 does't have any bugs that affect the PocketBase execution (if you think that there is such, please report them).

In any case, as mentioned in https://github.com/pocketbase/pocketbase/discussions/4355, the echo router will be replaced with a thin wrapper around the std Go 1.22 mux enhancements.

**Comment by W1M0R** [comment]
I agree with @kk7771. Although it doesn't affect PocketBase execution, it does limit the use of PocketBase as a library. For example, Echo v5 is not able to proxy SSE, which is important for the API I want to hook into PocketBase, but this has been fixed in Echo v4.12.0: https://github.com/labstack/echo/issues/1172#issuecomment-2057527298

Echo v5 hasn't received an update since late 2023.

@ganigeorgiev Your point about replacing Echo with std Go is noted, and will prevent issues like this going forward. Thanks for your efforts!
