### ISSUE TITLE
UNIQUE constraint failed: users.tokenKey error in golang

### ISSUE THREAD

**Issue by xnpltn** [pocketbase/pocketbase#4552]
i am using pocketbase as a golang package. i keep getting this error while creating a new user.
The first user is being created successfully but not the second, i could use some help.

**the code: **
`collection, err := app.Dao().FindCollectionByNameOrId("users")
		
		if err != nil {
			fmt.Println(err)
		}
		values, err := c.FormValues()
		if err != nil {
			return c.JSON(500, map[string]string{"error":"something went wrong"})
		}
		record := m.NewRecord(collection)
		record.Set("username", values.Get("username"))
		record.Set("email", values.Get("email"))
		record.Set("password", values.Get("password"))
		record.Set("passwordconfirm", values.Get("passwordconfirm"))
		record.Set("name", values.Get("name"))
		if err := app.Dao().SaveRecord(record); err != nil {
			fmt.Println("error db: ",err)
			return c.JSON(500, map[string]string{"error":"something went wrong"})
		}`

**the error: **
`UNIQUE constraint failed: users.tokenKey`

**Comment by xnpltn** [comment]
based on #3083 i solved it, and in case someone faces the same issue, 
`record.SetPassword(values.Get("password"))`

the above piece of code solves it all.

**Comment by ganigeorgiev** [comment]
_See also https://github.com/pocketbase/pocketbase/issues/3083_.

The auth collection records doesn't have `password` or `passwordConfirm` fields. These fields are available **only** when loading data from a request and when using the [`forms.RecordUpsert`](https://pocketbase.io/docs/go-records/#create-new-record-with-data-validations).

If you want to set record password through the `Record` you'll have to use the [`Record.SetPassword(pass)` method](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.22.4/models#Record.SetPassword).

You can also check the migrations example from https://pocketbase.io/docs/go-migrations/#creating-new-auth-record.

Note that since you are getting a "UNIQUE constraint" error this means that you've inserted an invalid auth record in the database.

After the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) this will be simplified and no longer needed.

If you have further questions, please consider opening a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) with as much details as possible about your use case and what you are trying to do..

**Comment by ganigeorgiev** [comment]
@xnpltn To avoid eventually security issue, if `values` in the above is coming from untrusted input note that `app.Dao().SaveRecord(record)` doesn't perform any fields validations (it translates to direct insert/update SQL statement).

Note that there are 2 sections how to create records in the docs:
- https://pocketbase.io/docs/go-records/#create-new-record-without-data-validations
- https://pocketbase.io/docs/go-records/#create-new-record-with-data-validations

As mentioned earlier, the above will be simplified in the future and the validations will be executed through the `Record` save operation as explained in https://github.com/pocketbase/pocketbase/discussions/4355.
