### ISSUE TITLE
Please open the hability to verify users from 3rd parties

### ISSUE THREAD

**Issue by miguelgargallo** [pocketbase/pocketbase#4555]
![image](https://github.com/pocketbase/pocketbase/assets/5947268/812df8b5-3663-4507-9069-2044ced70e1e)

**Comment by ganigeorgiev** [comment]
I'm sorry but I consider this a spam or at the minimum - lazy and low effort.

In your previous submitted issue I've asked you to elaborate on your issue and not just submit a random screenshot with a title that clearly lacks context. How duplicating your issue changes anything? Please be considered, otherwise - move on.
