### ISSUE TITLE
Feature Request: Support For Custom File Types on File Field

### ISSUE THREAD

**Issue by LuminareHQ** [pocketbase/pocketbase#4571]
Adding support for custom extension file types on the field level would be extremely useful, for letting users upload a file type not within the mime types. 

Specifically, the case I am trying to account for is allowing users to upload .musicxml files, which is missing in allowed types list.

**Comment by ganigeorgiev** [comment]
The file extension doesn't matter in our case because we check the file mime type.

We can't allow custom user defined mime types because the checks usually require a matching signature of the first couple bytes.

If your mime type is missing from the list, you can try opening a PR with a sample file against the https://github.com/gabriel-vasile/mimetype repo.
