### ISSUE TITLE
migrations

### ISSUE THREAD

**Issue by gedw99** [pocketbase/pocketbase#459]
I need to not just migrate data in the db but also pull data out, transform it and put it back in. 

https://github.com/Boostport/migration#using-go-for-migrations explain this use case better than me.

**Comment by ganigeorgiev** [comment]
This should be already supported. PocketBase DB migrations are regular go files and you can execute practically any custom business logic you want to run only once - https://pocketbase.io/docs/db-migrations/

**Comment by gedw99** [comment]
thanks @ganigeorgiev i should have seen this in the docs already.

**Comment by TomTom101** [comment]
I'd still appreciate a little help, having no idea about Go and just need to mess with it for migrations ;)
So I created a migration as explained in the docs, but struggling with the
>  you simply have to import the above migrations package in one of your main package files:

```
package main

import _ "yourpackage/migrations"

```
I'm playing around with the project in "examples/base" but can't figure out what `yourpackage` should be. Can you help please? Thanks!

**Comment by ganigeorgiev** [comment]
In order to use PocketBase as framework and the Go migrations:

0. Let's assume that your project directory is `myapp`.

1. Create a new Go file, eg. `myapp/main.go` (you can also copy the `examples/base`):
    ```go
    // main.go
    package main

    import (
        "log"

        "github.com/pocketbase/pocketbase"
    )

    func main() {
        app := pocketbase.New()

        if err := app.Start(); err != nil {
            log.Fatal(err)
        }
    }
    ```

2. Run `go mod init myapp && go mod tidy` to initialize the go.mod and fetch the go deps.

3. Run `go run main.go migrate create "your_new_migration"` and modify your generated migration file.

4. Add `import _ "myapp/migrations" in your `main.go`, aka.:
    ```go
    // main.go
    package main

    import (
        "log"

        _ "myapp/migrations"
        "github.com/pocketbase/pocketbase"
    )

    func main() {
        app := pocketbase.New()

        if err := app.Start(); err != nil {
            log.Fatal(err)
        }
    }
    ```
5. Start the application with `go run main.go serve` and the migrations should be executed automatically. Alternatively, you can also use the manual `migrate up` and `migrate down` for finer control.

---

_If you are not familiar with Go, you could check the short official introduction guide - [A Tour of Go](https://go.dev/tour/welcome/1)._

**Comment by TomTom101** [comment]
Lovely! Thanks again for your ultra-fast response – just realized I haven't yet posted a review on [Producthunt](https://www.producthunt.com/products/pocketbase/reviews) – done now!
