### ISSUE TITLE
Trouble creating a column allowing multiple rows with NULL values without violating the unique constraint

### ISSUE THREAD

**Issue by EricNahon** [pocketbase/pocketbase#4640]
Hi,

I have trouble creating a collection with a column effectively allowing multiple rows with NULL values without violating the unique constraint.
Here is what I do:
I create a column named ‘uniquebatch' of type text, then I create a new index described like this:
CREATE UNIQUE INDEX `idx_xW1bI2W` ON `product (`uniquebatch`) WHERE `uniquebatch` IS NOT NULL
Unfortunately doing this way and attempting to create a multiple records with a null uniquebatch gives me a “value must be unique error”.

Any help would be greatly appreciated on how to solve this.

Thanks!

**Comment by ganigeorgiev** [comment]
All field types with exception to the `json` in PocketBase are non-nullable and uses zero-default as missing/empty value (_see the first value listed in the [overview table](https://pocketbase.io/docs/collections/)_).

Or in other words, since you use a `text` field the empty value would be empty string so you could try specifying `WHERE uniquebatch != ''`.

If you have other questions, please consider opening a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) as the format is more suitable for this.
