### ISSUE TITLE
Backup restore doesn't work with network mounted storage directory

### ISSUE THREAD

**Issue by cddqssc** [pocketbase/pocketbase#4647]
ENV： ubuntu22.04(x86) v0.22.6

Restore an automatically backed-up file:
![image](https://github.com/pocketbase/pocketbase/assets/31430047/f484d526-97da-4af6-8861-6b7badb9e323)

Error:
![image](https://github.com/pocketbase/pocketbase/assets/31430047/41ebd9d9-fb49-4e69-9d50-08db7ef64b14)

The specific setup is that I mounted an SMB device to /pb_data/storage.(https://github.com/pocketbase/pocketbase/discussions/4631)
![image](https://github.com/pocketbase/pocketbase/assets/31430047/94c7df9a-1cd1-4b9a-b7d5-2f6a56c585e8)

**Comment by cddqssc** [comment]
![image](https://github.com/pocketbase/pocketbase/assets/31430047/6291d15a-6f21-48bf-85c1-42df4b2b8bec)

It seems the error is unable to rename or mv the mounted network volume.

**Comment by ganigeorgiev** [comment]
The error is most likely caused because on backup restore we replace the entire existing `pb_data` with the content from the backup, which I guess would fail in your case with the custom network mount. The backup restore functionality just wasn't designed with this use case in mind.

For now I'm not planning working on it as I already have enough on my hands but I may consider handling it after the refactoring as there are plans to optimize the backup generation to minimize the write lock time.

**Comment by ganigeorgiev** [comment]
_Side-note: if you are planning to store a lot of files keep in mind that the current PocketBase backup functionality generates a complete snapshot archive everytime of your `pb_data`, aka. it is not partial/incremental and could be slow if you are expecting your storage directory to grow several GBs. For those cases I recommend searching for a different and more efficient backup/restore strategy._

**Comment by cddqssc** [comment]
Thank you for the great work you've done; I fully understand your busyness. 
My current solution involves first stopping the PocketBase service on the server
Then unzipping the backup file, manually replacing the relevant db files, and copying the contents of the storage folder from the backup to the storage directory on the target machine.
![image](https://github.com/pocketbase/pocketbase/assets/31430047/c915d2dc-a5de-4ef8-8563-8b8ad4a22bf6)
So far, no anomalies have been detected. However, I'm not sure if this approach is 'compliant,' or if there are any oversights?

**Comment by cddqssc** [comment]
> _Side-note: if you are planning to store a lot of files keep in mind that the current PocketBase backup functionality generates a complete snapshot archive everytime of your `pb_data`, aka. it is not partial/incremental and could be slow if you are expecting your storage directory to grow several GBs. For those cases I recommend searching for a different and more efficient backup/restore strategy._

I plan to use the backup method mentioned in  https://github.com/pocketbase/pocketbase/discussions/4254.

**Comment by ganigeorgiev** [comment]
> My current solution involves first stopping the PocketBase service on the server
Then unzipping the backup file, manually replacing the relevant db files, and copying the contents of the storage folder from the backup to the storage directory on the target machine.

Yes, this should work.

**Comment by gedw99** [comment]
I do real time backups locally and to as many places as I want using:

https://github.com/maxpert/marmot-pocketbase-flyio

I need to add NATS KV, so that files are also real time copied too

**Comment by michaellenaghan** [comment]
Hey, are you aware of SQLite’s warnings re: network file usage?

https://sqlite.org/useovernet.html

**Comment by michaellenaghan** [comment]
Adding to that: Pocketbase uses WAL mode, and WAL mode requires that all processes using a database be on the same host:

https://www.sqlite.org/wal.html

I don’t think you’re violating that requirement, but if your database is on a network file system is something to be aware of.

**Comment by ganigeorgiev** [comment]
@michaellenaghan The above issue has no relation to the WAL mode or the database at all. The network mount is only for the uploaded files (aka. `pb_data/storage`).

**Comment by ganigeorgiev** [comment]
I've pushed a small update in the `develop` branch slightly related to this that also will prevent unnecessary copying the backup zip when the local file system is used and tested it against an external flash drive mounted in `pb_data/storage`.

Obviously this is not the same as network mount and `os.Rename` operations could still result in errors with "mixed" `pb_data` content (aka. when it has custom network mounted subdirectories) because there are many edge cases around the various platforms discrepancies and network mount locks, but I don't want to complicate further the internals and I don't plan further supporting this use case.

And even we add full support for this, I'm still not sure how useful that would be in the end because usually if you are going to mount a custom storage directory that implies that the main disk where `pb_data` is located is smaller than the mounted `pb_data/storage` which means that the restore may not work with large backups because you simply may not have enough disk space to temporary hold the restore zip content and the copy of the pb_data which is used for revert fallback in case the restore fails for some reason.

I've added a comment to this issue in case other stumble on it but again I'm not planning further complicating the internals for this use case and my recommendation is for use cases where `pb_data` with mixed disks content is necessary to use a different backup/restore strategy as suggested above.

With that said, I'm open to review a PR if someone disagree with the above and think that it can be handled without too much complications.
