### ISSUE TITLE
Suggestion: create a discord server for PocketBase

### ISSUE THREAD

**Issue by kingdevnl** [pocketbase/pocketbase#471]
Suggestion create a discord server for PocketBase.

**Comment by ganigeorgiev** [comment]
This was previously asked in https://github.com/pocketbase/pocketbase/issues/185.

I prefer to use the repo's [Discussions](https://github.com/pocketbase/pocketbase/discussions) because they don't require authentication to be explored and can be indexed by search engines, which is probably how most users first look for issues.

**Comment by rawandahmad698** [comment]
I made one!
https://discord.gg/8TnN92pbFB
