### ISSUE TITLE
Timezone value

### ISSUE THREAD

**Issue by ProfEibe** [pocketbase/pocketbase#472]
When returning a Date-Value from API, ISO 8601 format is used.
But the timezone-part is missing. I'm in central european time, and when I send the value 18:00+2 to the server, it is saved as 16:00.
Thats ok, since it is saved there in UTC-time.

But when fetching the value there is no 'Z' at the end of the string and my client-app interprets it as the local timezone. So everytime I save it will jump 2h in the past.

I think to fix this issue there just has to be a Z at the end of every datetime value.

**Comment by ganigeorgiev** [comment]
This was previously reqiested in https://github.com/pocketbase/pocketbase/issues/357.

The fully-formated ISO8601 datetime is in the format "Y-m-dTH:m:sZ".

Since this will introduce breaking changes to the date handling and how the filter operates (especially the `T` part), for now I'm not planning to change it.

I may reconsider changing the format in the future, but I don't think it's worth breaking existing user-land code for that.

**Comment by ProfEibe** [comment]
Hm okay, i understand you don't want to break some existing code.
But maybe going with the ISO standard is more efficient in the long run.

But I understand that there are more important things to do know.

Thanks for the fast reply btw and for this great project!!

**Comment by ganigeorgiev** [comment]
@ProfEibe We can introduce a breaking change along with the refactoring in #376, but currently the filter syntax [doesn't support "look-around" context parsing](https://github.com/pocketbase/pocketbase/issues/602) and converting the default date layout to iso8601 will complicate user defined filters. Internally when you have something like `date > "2022-01-01 10:00"` we are comparing the value as plain alphanumeric string and having `T` will break this.

**Comment by ganigeorgiev** [comment]
@ProfEibe On second thought, per https://www.gnu.org/software/coreutils/manual/html_node/Combined-date-and-time-of-day-items.html, the `T` separator is optional and the date is still parsable per ISO8601.

At least for web, both the [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) and the experimental [`Temporal`](https://tc39.es/proposal-temporal/docs/index.html) apis parsing iso8601 with space as separator, so adding only the zone suffix should be mostly a "safe" change since partial datetime filter expressions like `created > "2022-01-01 10:20"` will still work.

I'll consider introducing the zone suffix with the refactoring in #376.
