### ISSUE TITLE
Return empty column as null instead of empty string.

### ISSUE THREAD

**Issue by papakay** [pocketbase/pocketbase#4735]
I like to commend the great work you are doing.

Please I noticed an issue where empty column is being returned as empty string instead of null. This appraoch is breaking the app on flutter when trying to decode the json response.

Please see the screenshot below.

<img width="908" alt="Screenshot 2024-04-12 at 6 06 30 PM" src="https://github.com/pocketbase/pocketbase/assets/5013738/8342ddfc-c865-411a-8293-520fcd0cabad">

Thank you.

**Comment by ganigeorgiev** [comment]
This is by design.

All PocketBase fields (with exception to the `json` field type) are non-nullable and returns a zero-value similar as in Go (see the first value in the [Overview table](https://pocketbase.io/docs/collections/#overview)).

> This appraoch is breaking the app on flutter when trying to decode the json response.

I don't understand what do you mean by this but I don't think your issue is PocketBase related (_and in fact the Dart unmarshalization should be even easier because it is guaranteed that the value will be always `String`_).
