### ISSUE TITLE
net::ERR_QUIC_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by herskinduk** [pocketbase/pocketbase#4752]
I'm experiencing errors in the Chrome console when using the real-time API. I see two kinds of errors:

1) These just after the page loads (not sure what the exact pattern is - it's not on every load):
Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR _my_instance_.pockethost.io/api/realtime:1 

2) These for every 100s of idling (this feels like a timeout):
GET https://_my_instance_.pockethost.io/api/realtime net::ERR_QUIC_PROTOCOL_ERROR 200 (OK)

It seems that the API is able to recover, and real-time functionality keeps updating when changes happen.

Server: [PocketBase v0.22.8] in pockethost.io
NPM: /pocketbase@0.21.1

**Comment by ganigeorgiev** [comment]
I don't think your issue is PocketBase related.

The above error could be returned for a lot of reasons, including rate limits or some other connections constraints applied by the host you use (pockethost.io).

In general, realtime connectivity interruptions could be ignored as the JS SDK will try to auto reconnect behind the scene.

You can try to ask about the error in the pockethost discord support server - https://discord.gg/nVTxCMEcGT (https://github.com/pockethost/pockethost/discussions/250).

If you still think that this is a PocketBase issue please create a _minimal_ reproducible example and I'll try to investigate it further.
