### ISSUE TITLE
cronRemove cannot be called from inside a job in JavaScript

### ISSUE THREAD

**Issue by jf908** [pocketbase/pocketbase#4770]
The cronRemove method is not available inside of a job so the following code results in an error.

```js
cronAdd('test', '* * * * *', () => {
  cronRemove('test');
});
```

`ReferenceError: cronRemove is not defined at <eval>:2:13(3)`

I feel like this is a bug because it limits the usefulness of cronRemove as a method and you cannot do things like create single running jobs but perhaps this is intentional and I am missing the point of the function.

**Comment by ganigeorgiev** [comment]
This is because of the way how the JS `pb_hooks` binding works - https://github.com/pocketbase/pocketbase/discussions/2825#discussioncomment-6376210.

`cronAdd`, `cronRemove`, `on*`, etc. functions are currently defined only for the "loader" vm, aka. available only at top level.

Registering `cronRemove` for the "executor" vms could be a little tricky as we don't keep track at the moment of the created [`cron.Cron`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.22.9/tools/cron#Cron) instance outside of its initialization scope.

I've actually already "fixed" this while working on the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) as there will be a single shared `cron.Cron` instance in the `app` but there are no ETAs when that will be released.

I'm not entirely sure that I understand your use case, but as a workaround you can store a flag in `app.store().set("something", true)` and check it with `app.store().get("something")` to skip the execution of your cron handler.

**Comment by jf908** [comment]
Workaround works for me for now, thanks.
