### ISSUE TITLE
Extending with JS: Object access within DynamicModel not ergonomic?

### ISSUE THREAD

**Issue by niravcodes** [pocketbase/pocketbase#4786]
## Issue

Consider the following code I'm using:

```js
routerAdd("POST", "/create", (c) => {
  const data = new DynamicModel({
    name: "",
    parts: {},
  });
  c.bind(data);
  
  console.log(Object.keys(JSON.parse(data.parts.value())));
}
```

So I don't know exactly what keys `parts` will have. Reading the [JsonMap](https://pocketbase.io/jsvm/interfaces/types.JsonMap.html) docs, I didn't find other way to find out the keys.

## Expected behavior

Probably something like this:

```js
routerAdd("POST", "/create", (c) => {
  const data = new DynamicModel({
    name: "",
    parts: {},
  });
  c.bind(data);
  
  console.log(    Object.keys(  data.parts.toObject()  )    );
}
```

Am I missing something or is this the best we have for now?

BTW, loving Pocketbase so far, and open to try and fix this if it is something that needs fixing.

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand what actually is the issue or the expected behavior.

If the problem is that access to the the custom map is not ergonomic then I don't know an easy solution for this without forking goja.

You can also check:
- https://pkg.go.dev/github.com/dop251/goja#hdr-Maps_with_methods
- https://pocketbase.io/docs/js-overview/#engine-limitations
- https://github.com/pocketbase/pocketbase/discussions/2825#discussioncomment-6376210 (_general overview how the goja integration works_)

If you want to access the body parameters as a plain map an alternative could be:

```js
const data = $apis.requestInfo(c).data

console.log(data)
```

If you think that this can be improved, feel free to create a POC implementation and I'll try to review it but note that the routing will change with the next release as part of https://github.com/pocketbase/pocketbase/discussions/4355.

If you have other question, please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose) as the threaded format is more suitable for this.

**Comment by niravcodes** [comment]
`const data = $apis.requestInfo(c).data` is exactly what I was looking for. Thanks :)
