### ISSUE TITLE
Admin interface loads slowly because of the created field

### ISSUE THREAD

**Issue by amtins** [pocketbase/pocketbase#4794]
## Description

I have a database containing 5 million entries and growing at an average rate of 20 requests per second. Very quickly the admin interface became slow to load, until it wouldn't load at all.

## Cause

Since a sort is applied to the `created` field when loading data, this has a negative impact on admin interface performance.

```
https://domain.com/api/collections/6y4hoiy7xc8wcx1/records?page=1&perPage=40&sort=-created&skipTotal=1&filter=&expand=&fields=
```

## Workaround

Creating an index on the `created` field solved the issue.

**Comment by ganigeorgiev** [comment]
I don't think there is much we can do here as the query execution will depend on the available fields and the used filter/sort parameters.

Interface for "Indexes suggestions" could be added in the future but for now other tasks are with higher priority.

There are no plans for now to add index on the `created` field by default if that's what you want because with the [next release](https://github.com/pocketbase/pocketbase/discussions/4355) the `created` and `updated` field will be optional.

With the refactoring I'll consider eventually changing the default sort to the `rowid` column (_this is the "real" primary key of the table and would be indexed by default_).
