### ISSUE TITLE
Import/Export CSV/JSON

### ISSUE THREAD

**Issue by jimafisk** [pocketbase/pocketbase#48]
Thank you for this great project :tada:. This is a feature request (hopefully that's welcome):

In order to make migrating from existing systems easier, it would be helpful to be able to upload a CSV (or similar) file in the admin dashboard to create users and records inside a collection to initially populate the database. Thank you!

**Comment by ganigeorgiev** [comment]
I like the idea of having "Import/Export to CSV" for a collection (json would be easier, but I think we can make CSV to work too).

Also I think this could be done without too much changes (probably even client-side in the admin UI entirely).
My only concern is how the file field values will be handled (downloading them from absolute urls and then upload them to the PocketBase file store?), but I'll have to think more about it and will consider it for future releases.

**Comment by jimafisk** [comment]
I don't have a CSV preference, JSON would work! Files would definitely be challenging, downloading from absolute URLs to the PB file store like you said would work if it's not too complicated. Not sure if it's any easier, but you could force users to manually dump files into the PB file store with specific names that match filenames in their JSON import. The import functionality would be useful even if it doesn't handle files at all initially; that could always be added in a later phase (depending on how you feel about releasing partial features).

**Comment by jduckles** [comment]
Could be handled by the create apii method allowing a JSON list of JSON objects which conform to the table definition. Then you could use anythiing to POST a JSON list to the create method (curl, wget, sdk, whatever). This is how Supabase allows for bulk uploads to tables.

**Comment by sospartan** [comment]
+1 for this 'import schema' feature, It will better having a 'export schema' feature too.  
It's very useful for integrate testing or CI job, for now I have to add a db file to my git repo.

**Comment by supermx1** [comment]
This would be great

**Comment by ganigeorgiev** [comment]
This turned out a little more complicated than I initially anticipated.

Experimental support for only **import/export of collections configuration** from JSON (both from the UI and as a automated migation command) was added in [v0.4.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.4.0) (and even only this ended up troublesome since we have to handle the referenced collection and schema ids which will defer when created manually on different environments).

During my inital POC development for "Import/Export of data" I stumbled on several issues (file uploads are not even the main problem here):
- There is no unambiguous automated way to import records with relation fields (the referencing record ids or even the collections may not even exist).
- Allowing to import large data sets from the UI (or while the application is running) could block other db writers, which practically could make the application unresponsive during the import process.
- Because cross references between 2+ records are allowed, we cannot import them one by one since it will fail the validations. Bulk importing collections configuration have the same caveat, but usually collections are a lot smaller in size (eg. a couple MB top) and the changes can be quickly applied, which for the records data this may not be the case.

So I'll need to spend a little more time to research other approaches how to handle better the import/export of records data properly.

**Comment by gedw99** [comment]
The requirement for bulk upload, means that multi transactions are needed.
This is also related to the need for relations and doing writes that update many collections.

One way to do this is to support 2PC commit style transaction coordinator. 
A byproduct of this is that you can also create many read only mysql with a single write only db, and hence get scale out.

There are a few golang projects that are working on this.

Litestream: https://github.com/benbjohnson/litestream is a sqlite replicator. It stores the mutation is s3 and have backup and restore from s3.

LiteFS: https://github.com/superfly/litefs is also a sqlite replicator that uses Fuse, and sync directly between the mast and slave. 

LiteFS is watching for Transactions at the Fuse level and so it possible that is can also do a type of 2PC, in which it watches for transactions that are bounded, and then holds them all, and then commits when given the command to commit.
The docs on this aspect are here: https://github.com/superfly/litefs#lite-transaction-files-ltx

**Comment by catalinux17** [comment]
Hi @ganigeorgiev, do you have an ETA for this task?

**Comment by ganigeorgiev** [comment]
@catalinux17 No, sorry.

**Currently the ongoing users refactoring from #376 is with highest priority because it blocks everything else.**

After that we'll continue following the existing [roadmap](https://github.com/orgs/pocketbase/projects/2) and data import/export from the Admin UI eventually will be handled after implementing transactional API operations within a single or multiple collections.

**Comment by mirozahorak** [comment]
I wonder if there is any option to import existing SQL schema and data into new pocketbase DB. Without this feature is moving more complex data structures and data to pocketbase too time-consuming. Pocketbase seems to be great when starting new project, but i see in docs no info on importing data from existing DBs. Am I missing something?
I have a project which to me seems to be perfect fit for pocketbase, but with around 500 columns and 100 tables, schema and data import is considerable concern.

**Comment by ganigeorgiev** [comment]
@mirozahorak 

I don't think there is a generic solution that will fit all cases when dealing with project data migrations because 1-1 mapping is not always possible.

If you use PocketBase as framework, you can write Go migrations that will be embedded in your final executable - https://pocketbase.io/docs/migrations/ (including creating collections programmatically - https://pocketbase.io/docs/collection-methods/#create-new-collection)

Or if you use the prebuilt PocketBase executable, prepare plain SQLite migration scripts and then run them against your db file (`pb_data/data.db`). Each collection represent an individual table and all fields are translated to db columns.

The best approach if you are planning to migrate your existing project would be to try PocketBase with a clean state locally, create some collections and records and explore the existing db schema. And then based on the internal structure, plan and prepare the dump/migration scripts.

**Comment by mirozahorak** [comment]
Thanks for the answer.
I have tried to simply modify data.db sqlite database pocketbase created in DBBrowser for SQLite. I added fields to existing table (collection) but they are not showing in admin.
I guess migration is the only option. 
It would be great to have a tutorial for this, especially for people who don't use GO and want to use pocketbase with javascript or dart.

**Comment by ganigeorgiev** [comment]
@mirozahorak 

> I have tried to simply modify data.db sqlite database pocketbase created in DBBrowser for SQLite. I added fields to existing table (collection) but they are not showing in admin.

Yes they will not show up in the admin because they don't have related collections entry. That's the reason why I suggested to first try with a clean state and explore the internal generated PocketBase schema to get a general idea what and how things are connected. I'm currently working on a migration flow improvements for the next release and will consider adding more docs for manual SQL modifications.

You have to create a "_collections" entry for each of your tables. Collections basically store api rules, meta information about the columns (aka. fields), validators, etc.
You can find more details what the collection props represents by looking at the Web collection APIs (the underlying column representation is equivalent) - https://pocketbase.io/docs/api-collections/. If you haven't already, you can read an overview about the collections in https://pocketbase.io/docs/collections/. Alternatively you can also create the collections programmatically via the REST API (you'll have to authenticate as an admin).

**Comment by ganigeorgiev** [comment]
The introduction guide allows downloading a prebuilt binary of PocketBase wich is based on this go file https://github.com/pocketbase/pocketbase/blob/master/examples/base/main.go.

When extending PocketBase (aka. using it as framework) you can follow the guides under the "Extend" section - https://pocketbase.io/docs/use-as-framework/.
PocketBase is distributed as a Go package and you have to use it and import it in the the same way as any other go library (aka. `import "github.com/pocketbase/pocketbase`).

If you are not familiar with Go, you can also check the official [A Tour of Go](https://go.dev/tour/list) guide to get familiar with the basics of the syntax.

_Feel free to open a new [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new) if you need further help with the migration, but once again, my recommendation would be to first play around with a clean PocketBase state in order to explore its features, supported fields and evaluate whether actually it can be used for your use case. Also note that PocketBase is still under active development so backward compatibility is not guaranteed and it may not be suitable if you are don't want to keep up with eventual future breaking changes (although I try to keep them minimal, they are sometimes are unavoidable due to the lack of my insight on the various use cases that different users have)._

**Comment by michal-kapala** [comment]
I'm working on [simple import tooling](https://github.com/michal-kapala/pocketbase-import) using the [JS SDK](https://github.com/pocketbase/js-sdk) (sadly I'm not that proficient with Go). Far from perfect, but it should let you import basic CSVs already. I'll be adding support for flat JSON files in the coming days. Just a temporary solution to help you guys get started.

One feature that I'm missing while implementing this is batch insert endpoint, with large datasets and a remote database it's not feasible to create 1 record per request (imagine a 100k+ records table created with 100k+ requests over a network). I hope that it will become a thing for the integrated feature.

**Comment by ganigeorgiev** [comment]
@michal-kapala If you want to import records via the terminal you can also make use of the `.import` command in the [sqlite3 cli](https://sqlite.org/cli.html) tool, something like:

```sh
sqlite3 pb_data/data.db '.import test.csv foo --csv'
```

The main blockers in this issue are outlined in https://github.com/pocketbase/pocketbase/issues/48#issuecomment-1211775627.

**Comment by trevorstarick** [comment]
If anyone is looking for a semi-automatic way to import data from an existing SQLite DB into Pocketbase, I wrote two scripts to do so for my own use case:

export: https://gist.github.com/trevorstarick/664d4a40c0246eced6b178890d073096
import: https://gist.github.com/trevorstarick/31defb0c288735669530c684855d61b1

**Comment by einarpersson** [comment]
I hope e2e-testing (using a tool such as Playwright) will be easier once this is implemented. For example I want to be able to delete all records in a collection and re-seed it with testing data using the API (not using migrations).

**Comment by michal-kapala** [comment]
> @michal-kapala If you want to import records via the terminal you can also make use of the `.import` command in the [sqlite3 cli](https://sqlite.org/cli.html) tool, something like:
> 
> ```shell
> sqlite3 pb_data/data.db '.import test.csv foo --csv'
> ```
> 
> The main blockers in this issue are outlined in [#48 (comment)](https://github.com/pocketbase/pocketbase/issues/48#issuecomment-1211775627).

@ganigeorgiev sadly simple table import does not create a collection, or at least it doesn't appear in the dashboard, so for that to work you'd need to modify your data (at least)

I've added JSON support to my [pocketbase-import](https://github.com/michal-kapala/pocketbase-import), works pretty decently. I recommend using JSON over CSV as a safer option. A quick look on what the tool does and what it doesn't:

## Pros

- Honors [system columns](https://github.com/pocketbase/js-sdk/blob/master/src/models/utils/BaseModel.ts) (`id`, `created`, `updated`)
     - Column name conflicts resolved with `_` prefix
- Explicit collection structuring
     - field types assigned by regex matchers
     - no constraints or rules added on import
- Customizable CSV parser options

## Cons

- Slowness and network throttling - creates 1 record per request due to API limitations, inserting a 100k rows collection takes a few minutes with local instance
- Currently limited PB type support
- Currently CSVs with complex text fields may not import properly
- `id` cannot be populated by the user - `_id` is created instead. If this is a no-go as for your requirements, you will probably have to modify the database with [SQLite CLI](https://sqlite.org/cli.html) or tools like [DB Browser for SQLite](https://sqlitebrowser.org/)

**Comment by gedw99** [comment]
> If anyone is looking for a semi-automatic way to import data from an existing SQLite DB into Pocketbase, I wrote two scripts to do so for my own use case:
> 
> export: https://gist.github.com/trevorstarick/664d4a40c0246eced6b178890d073096 import: https://gist.github.com/trevorstarick/31defb0c288735669530c684855d61b1

Nice 

would like to extend this to support continuous import using a CDC ( change data capture ) pattern. 

My data lane is JSON based and I want to support data streaming into Pocketbase.

The use case is AI / ML Workflows. 
But it can also be used for general programming .

It will be reentrant styje so that you as a code can push changes to the data lane and have it arrive in your Pocketbase instance.

**Comment by shynome** [comment]
Does anyone have a work around for this? I will implement this in a few days
I already have an implementation, https://github.com/shynome/xlsx-importer

**Comment by fbede** [comment]
@ganigeorgiev  I noticed this issue is still blocked and I would like to offer some suggestions.
1. For numbers one and three,
   > * There is no unambiguous automated way to import records with relation fields (the referencing record ids or even the collections may not even exist).
   > * Because cross references between 2+ records are allowed, we cannot import them one by one since it will fail the validations. Bulk importing collections configuration has the same caveat, but usually collections are a lot smaller in size (eg. a couple MB top) and the changes can be quickly applied, which for the records data this may not be the case.

   I suggest that the importation be done without validations and foreign key checks. I got this idea from [Drift](https://drift.simonbinder.eu/docs/migrations/#tips), an sqlite library that is used to build flutter apps. In the documentation, the author suggests disabling the foreign keys before you start a migration and enabling them after the migration is complete. He also suggests running a 'PRAGMA foreign_key_check' to ensure that there are no inconsistencies in the database before re-enabling the foreign key checks. Considering that data importation is almost as good as a db migration, I was wondering if you can adopt something similar to this.
   
   In my opinion, if there is no way to validate the data or determine the order in which the tables should be imported (because of weird relationships and dependencies), you could simply put a warning that the inbuilt data importer does not validate the data being imported. The developer could always write a script to validate the data themselves, write a manual migration or use the web APIs if they want their data to be validated as it is imported into pocketbase.

2. For number two,
   > * Allowing to import large data sets from the UI (or while the application is running) will block other db write operations, which practically could make the application unresponsive during the import process.
  
   Since I doubt anyone who has read the documentation of pocketbase will try to import a large data set while the application is running in production, I think a simple warning listing all these possible issues should be enough. If you don't want the UI to seem unresponsive when doing bulk imports, you can just create a full screen page that shows the progress of the import but does not accept any input. Not accepting any input means the app does not have anything to respond to and therefore cannot be unresponsive. I will also suggest that all web UI links redirect to this page whenever a bulk upload is in progress.

@ganigeorgiev Thank you so much for all your effort on this application. I would really like to hear what you or anyone thinks about my suggestions.

**Comment by ganigeorgiev** [comment]
@fbede While nice to have, this feature request remains a very low priority and will be implemented at later stage after the upcoming internal refactoring and the bulk/transactional web APIs support.

**Comment by fbede** [comment]
@ganigeorgiev There's no problem. Thank you for your work so far on pocketbase.

**Comment by tymon3568** [comment]
hope upload with csv, so that we can upload woocomerce products to pocketbase

**Comment by jeffscottward** [comment]
> @fbede While nice to have, this feature request remains a very low priority and will be implemented at later stage after the upcoming internal refactoring and the bulk/transactional web APIs support.

What is the status of that refactor?

also QQ: if I wanted to use an LLM to just generate some JSON schema in order to import a basic structure without relations or data, like just a very basic lift I could then dial in, what meta-schema/standard should I point to or give an example of? 
https://pocketbase.io/docs/js-collections/#create-new-collection ?
is the complete enough?

**Comment by evaisse** [comment]
Hi @ganigeorgiev, 

Would that be possible to simply add the ability to inject javascript plugin files into the UI admin ? (potentialy add in like in a collection). That's a bit a of an 'I've just thrown this together' feel, but that would be sufficient to add some basic features, based on available rest APIs.

What do you think of it ?

**Comment by ganigeorgiev** [comment]
@evaisse I don't see how your request is related to the above discussion. For Admin UI extendability please check https://github.com/pocketbase/pocketbase/issues/898 and https://github.com/pocketbase/pocketbase/discussions/4355.

**Comment by evaisse** [comment]
> @evaisse I don't see how your request is related to the above discussion. For Admin UI extendability please check #898 and #4355.

Yes you're right, I was suggesting that we could probably deal with CSV import/export directly in the UI admin just by the addition of 2 buttons and a javascript to pipe the upload of download of data for a given collection.

**Comment by Mashiane** [comment]
![msedge_H9tC1jsbxz](https://github.com/user-attachments/assets/9dfef017-0462-4e97-8f95-b25e018237c8)

Perhaps this could help someone. I have been using PocketHost for a while and between my dev and publishing, I developed this tool. This helps one to sync data from a local pockethost and any other other pocketbase.

All the best.

**Comment by omarmir** [comment]
Looking forward to this feature - primarily for the transactional support (all or fail and rollback). Great project and really enjoying using it thus far!

**Comment by hercules-rockefeller** [comment]
not sure if anyone is still looking for a good solution here, but I'm using DuckDB with the sqlite extension. That gives you very robust CSV handling, you can manipulate with SQL using an in-memory DB and then copy to your pocketbase DB as required. It's a very powerful, very lightweight tool

**Comment by jeffscottward** [comment]
Great tip will check it out. Thanks.

**Comment by michal-kapala** [comment]
> _I have in my todo to eventually add at least a UI option for client-side generated exports for selected records similar to the logs but remains a very low priority for now._

I will try to keep my import tools compatible with the latest release until then, might turn them into a pr one day

**Comment by ganigeorgiev** [comment]
_Just in case someone stumble here - you could also check some of the suggestions in https://github.com/pocketbase/pocketbase/discussions/6287_.
