### ISSUE TITLE
[Feature] Add a 'Duplicate' option to the selected record in the Admin UI

### ISSUE THREAD

**Issue by devmuaz** [pocketbase/pocketbase#4808]
Hi,

I was wondering if it's possible to add an option where the user can `Duplicate` a certain record when it's being selected alongside the `Delete` option.

This is very helpful when trying to add the same record in the database with a few changes to the previous one being duplicated. I faced this use case a lot and am doing it hard currently without such an extra option.

Thank you!

**Comment by ganigeorgiev** [comment]
There is already a "Duplicate" option under the record popover options:
![duplicate_screenshot](https://i.imgur.com/POrA2AL.png).

The option can't be added as part of the bulk selection because the user needs to manually confirm the "Duplicate" operation and eventually adjust some of the fields if needed since it could confict with a unique or other similar constraint. Files are also not duplicated at the moment.
