### ISSUE TITLE
Uploading ".doc" file not allowed

### ISSUE THREAD

**Issue by yfram** [pocketbase/pocketbase#4875]
I have a table named documents which has a file field. Among it's allowed mime types is ".doc - application/msword", but when I send a POST request such as this:
```
curl --request POST \
  --url http://127.0.0.1:8090/api/collections/documents/records \
  --header 'Content-Type: multipart/form-data' \
  --form 'name=test file' \
  --form 'file=@C:\Users\Yoni\Downloads\דף חולין ה1.doc' \
  --form 'author=Jhno doe' \
  --form document_type=bk3hbare1q24pb6
```
An error is returned stating the mime type issn't allowed:
```
{
	"code": 400,
	"message": "Failed to create record.",
	"data": {
		"file": {
			"code": "validation_invalid_mime_type",
			"message": "\"18ncGG0nOJ3_tKUWYuOb8f.doc\" mime type must be one of: image/bmp, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, text/html, image/jpeg, image/png, image/vnd.mozilla.apng, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.ms-powerpoint, image/tiff, text/plain, application/vnd.ms-excel, application/pdf, application/vnd.oasis.opendocument.text, text/rtf, application/msword."
		}
	}
}
```
Iv'e double checked the the file's mime type is corect and Iv'e tryed with other .doc files, and I get the same result.\
Other allowed file types do stil work, so it seems to only be an issue with ".doc" files.\
Thanks!

**Comment by ganigeorgiev** [comment]
Make sure that your file is actually a Microsoft Word file (the file extension doesn't really matter).

If you are still not able to resolve your issue, please open an issue in https://github.com/gabriel-vasile/mimetype with the problematic file.

**Comment by ganigeorgiev** [comment]
Alternatively, since `.doc` is essentially a "zip" you can try to add a `application/zip` mimetype (_I guess increasing the read bytes could help for better mimetype detection but for now I don't want to change the default mimetype limit as I'm not sure what the side-effects on the memory consumption would be_).

**Comment by ganigeorgiev** [comment]
If your file is actually a standard Microsoft Word file, then most likely your issue is similar to https://github.com/gabriel-vasile/mimetype/issues/180 and https://github.com/gabriel-vasile/mimetype/issues/229 since for this type of files the unique format signature is usually at the end of the file, but as mentioned earlier for now I don't feel confident increasing the default limits (_I've added it to my todo to reevaluate it in the future but remains a very low priority_).
