### ISSUE TITLE
Proposal: Add Cache-Control header during file creation

### ISSUE THREAD

**Issue by thangngoc89** [pocketbase/pocketbase#4878]
I'm serving large files directly from Cloudflare R2 by redirecting to pre-signed link for CDN benefits. [See discussion](https://github.com/pocketbase/pocketbase/discussions/4871). 
However, with S3 or any S3 clones, you need to set Cache-Control header during file upload or modify afterwards. The current default is no caching.

Since the `Serve` function always add caching 

https://github.com/pocketbase/pocketbase/blob/5acaa0a55c9f2d5070101857543c746cac823c80/tools/filesystem/filesystem.go#L395

I would like to propose that Cache-Control should be added during writing to the file system.

I'm quite new to Golang but I've done some digging:

[`CacheControl` is a field of `WriterOptions`](https://github.com/google/go-cloud/blob/d8b9c9401f181fe92dffcd55179571141ca430ff/blob/blob.go#L1369) and [Pocketbase is currently calling this in 4 locations](https://github.com/search?q=repo%3Apocketbase%2Fpocketbase%20WriterOptions&type=code).

I could imagine a PR would involve  adding this field to all of the 4 locations and fixing any failed test. If this is the case, I'm happy to send a PR.

**Comment by ganigeorgiev** [comment]
I've considered this during the refactoring but in the end decided against it as it will add unnecessary confusion and I don't really see much point of doing it because often when you want to access public files directly from S3 you would use a CDN and the majority of the CDNs has already an option to set global default headers or other mechanism to control the default caching behavior.

In case a more prominent use case arise I may reconsider it but for now remains out of the scope.
