### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by jimafisk** [pocketbase/pocketbase#49]
There appears to be system emails for common actions like:
- user verification
- user password reset
- user email change confirmation

Is there a way to override the default content of these messages? Is that something that should be done at the SMTP provider level? It would be nice if this could be set in the admin dashboard and make use of replacement patterns. Thanks!

**Comment by ganigeorgiev** [comment]
To change the default user emails you can make use of the `OnMailerBeforeUser*` event hooks - https://pocketbase.io/docs/event-hooks/#mailer-hooks.

Initially it was in the admin dashboard (see [earlier mockups](https://app.presentator.io/#/6mote1hf/prototypes/31143/screens/210839?mode=preview)) but I decided to replace it with event hooks because it provides more options for customizations and the behavior is more consistent when the dev uses PocketBase as framework (otherwise you may end up with something that seems configurable in the dashboard, but actually may not be used by the application due to some intercepted hook event).

**Comment by jimafisk** [comment]
The hooks are great, but is there a way to do both so non-developers could customize emails? Not sure how feasible it would be, but if a mailer hook was implemented by the developer could it disable the template override in the dashboard and throw a warning message that it's been overridden by a hook? The mockup you referenced looks great, I could see that being super useful for folks who don't want to use PB as a framework.

**Comment by ganigeorgiev** [comment]
At the moment, there is no way to know what the attached hook listeners do prior execution.
Even if the developer use for example `OnMailerBeforeAdminResetPasswordSend` hook there is no guarantee that this hook is used to send a different email template (eg. it can be used just to notify some external system).

Although I understand that it's not very user friendly as it is now, it is a lot more consistent and easy to reason in the long run.

I'll move the issue to discussions so the other users can join and share their feedback.
