### ISSUE TITLE
Error: listen tcp 0.0.0.0:443: bind: address already in use

### ISSUE THREAD

**Issue by qxygene1** [pocketbase/pocketbase#4907]
Cant make it work on VPS with apache.

**Comment by hungcrush** [comment]
Just change the port 
`./pocketbase serve --http=0.0.0.0:8092`

Then use apache proxy to :443 or :80 ^^

**Comment by ganigeorgiev** [comment]
For example reverse proxy configuration you can refer to the examples in - https://pocketbase.io/docs/going-to-production/#using-reverse-proxy (there is no example for Apache but the instructions are similar).

If you have other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions/new/choose) instead.

**Comment by qxygene1** [comment]
An example will be so helpfull

**Comment by ganigeorgiev** [comment]
@qxygene1 You are not entitled to anything. Please don't spam.

**Comment by qxygene1** [comment]
Why you are deleting my post?

**Comment by ganigeorgiev** [comment]
Because it doesn't add anything to the discussion and it is just a spam. You are not entitled to anything. Please stop.

**Comment by qxygene1** [comment]
So please explain how to use it with apache.

**Comment by ganigeorgiev** [comment]
This behavior will not be tolerated. I've warned you twice. Please move on.

Your issue is not PocketBase specific. If someone could and wants to help you they will, but again you are not entitled to anything, and you shouldn't expect dedicated support (especially considering that your problem is not really PocketBase related and you'll stumble on the same with any other application that you are trying to host behind Apache). If you need guidance, google for "reverse proxy apache".
