### ISSUE TITLE
Bug: Creating a user from Admin UI crashes pocketbase

### ISSUE THREAD

**Issue by Hugeaux** [pocketbase/pocketbase#4930]
Whenever I try to create a user manually from the Admin UI, pocketbase freezes. This issue has been consistent across multiple versions for me. Nothing related to the error in the logs when running ./pocketbase serve --dev.

Steps to reproduce:
* ./pocketbase serve
* From the users collection, click "New record"
* Nothing will happen, but pocketbase is frozen
* Only way to get out of it is to stop pocketbase

For auth method, I only have Email/Password enabled.
This doesn't happen when creating records manually for any other collection.

Some additional information:
My current version is 0.22.12 for MacOS.
I've tried a fresh install, and even using the arm64 instead of amd64 executable, but no luck

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. Tested it both locally and on the live demo. I'm also using PocketBase in production with [Presentator](https://presentator.io/) and there is no such issue.

Your issue is most likely caused by custom hooks code (eg. using `app.Dao()` inside of a transaction) but there are not enough details to understand or replicate it.

If you still think that it is a PocketBase issue please provide some minimal reproducible steps and I'll try to investigate it. If you need help with your code, please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a).

**Comment by Hugeaux** [comment]
Thanks for the rapid response. Interestingly, this seems browser related. Even when using https://app.pockethost.io/ it happens for me. This is on Firefox. Just tried Chrome (should have done that sooner) and no issue there.

**Comment by ganigeorgiev** [comment]
@Hugeaux I'm not able to reproduce it with Firefox 125 (Linux/Fedora) when testing on the live demo - https://pocketbase.io/demo/. It could be browser extension related, I'm not sure.

**Comment by kangruixiang** [comment]
I'm also running into the same issue. Firefox 127 on Windows. When creating users from admin panel, firefox freezes. The only way out is to terminate the browser.

**Comment by ganigeorgiev** [comment]
@kangruixiang I don't think your issue is PocketBase related. Make sure that it is not caused by a browser extension as shown in the profiler in https://github.com/pocketbase/pocketbase/issues/4903.

If you still think that this is a PocketBase issue, feel free to provide some minimal reproducible steps and I'll try to investigate it further, but until then there is nothing much I can help with.

**Comment by CristianH033** [comment]
I can confirm that the issue occurs when the Firefox Relay extension is enabled. When the extension is disabled, the problem does not occur. (macOS Sonoma, M1, Firefox 128).
