### ISSUE TITLE
Feature suggestion: Add a static "object name" field with string interpolation below "collection -> name"

### ISSUE THREAD

**Issue by manelephant** [pocketbase/pocketbase#494]
It would be nice if each collection could have his own (optional) name attibute based on fields value.

For exemple if you create a "Shoe" collection with "Brand" and "Size" fields then you could fill the "Object name" field with "%Brand%-%Size%". Then each time you call the shoes->name you have "Nike-9.5".

This per-collection name property could be usefull when using relation field inside a collection as the backend UI could render this name in place of the object id.

It is a feature i discovered in an old CMS named ezpublish which was very convenient.

**Comment by ganigeorgiev** [comment]
I'm not sure that I understand how this is expected to work.

Collections are group of records. Do you mean that you want the interpolation to be for each record in the collection? If that's the case, then I think the ["Computed/Raw SQL" issue](https://github.com/pocketbase/pocketbase/issues/311) should cover this.

**Comment by ganigeorgiev** [comment]
@manelephant I'll close the issue because https://github.com/pocketbase/pocketbase/issues/311 should cover the use case for this, but if that's not what this issue is about, please elaborate and I'll reopen it.

**Comment by mjadobson** [comment]
I think I'm looking for the same thing as this issue. In collection views, it's difficult to know what relations are referring to. It would be nice to have a more "user friendly" appearance to relations. See image below:

![pocketbase](https://user-images.githubusercontent.com/787996/190858695-cc996fbe-cb3b-48ae-b32b-db4038fd4279.jpg)


You could also use the "display field" when adding relations to records:


![pb2](https://user-images.githubusercontent.com/787996/190859162-c6ba77c5-0a87-4d04-bfb8-80fded23459b.jpg)

**Comment by ganigeorgiev** [comment]
@mjadobson You'll be able to define readonly computed/raw sql fields wiht https://github.com/pocketbase/pocketbase/issues/311.

Eventually in the future we may allow users to mark a single field (including the computed one) as "displayable" and we could use that as a label, but I don't like the idea of having a custom field just so that it can be visualized in the admin ui. It will clutter the interface and could add unnecessary complication to the collections management (for example it will require adding a constraint when a field that takes part in the display input is renamed/removed, etc.).

> I'd be happy to write a pull request for this, but should it be after your upcoming refactor?

Yes, any PR for new features unfortunately will have to wait until I manage to compete the users and profiles refactoring because there are a lot of changes to the internals.

**Comment by mjadobson** [comment]
@ganigeorgiev A single "displayable" field would work well I think.

> Yes, any PR for new features unfortunately will have to wait until I manage to compete the users and profiles refactoring because there are a lot of changes to the internals (after I finalize the tests, I'll push the local changes to a develop branch).

Thanks for all your work, PB is great. Will check in once things are more finalised and see how I can contribute 👍.
