### ISSUE TITLE
GoogleAuth.URL is empty?

### ISSUE THREAD

**Issue by OfflinePing** [pocketbase/pocketbase#4960]
### Discussed in https://github.com/pocketbase/pocketbase/discussions/4958

<div type='discussions-op-text'>

<sup>Originally posted by **OfflinePing** May 19, 2024</sup>
Hey,
I configured Google as OAuth provider in my Pocket base Application and on Google APIs, but now I have a Button saying sign in with OAuth with a Custom /login endpoint. Where do I need to send the User on the button press in order for them to get the OAuth Screen or how do I get the URL?</div>

I don't think PocketBaseAPP.Settings().GoogleAuth.AuthUrl is supposed to be empty if is configured in the Admin UI or am I missing something?

**Comment by ganigeorgiev** [comment]
It is working correctly. If it is empty it fallbacks to the provider's defaults. See [`AuthProviderConfig.SetupProvider`](https://github.com/pocketbase/pocketbase/blob/master/models/settings/settings.go#L654)

**Comment by OfflinePing** [comment]
Okay,
But the default seems to be empty aswell. I haven't set the URL so when I access .AuthURL it also is empty

**Comment by OfflinePing** [comment]
or do I need to setup the Provider manually in order  to work with it?

**Comment by haupt-pascal** [comment]
I think what he's trying to say is that he can't figure out how to embed oAuth in htmx using golang from the documentation. The only thing asked for here is an example of how to embed oauth using golang. 

Why was this closed immediately when it was simply a communication problem?

**Comment by ganigeorgiev** [comment]
> Why was this closed immediately when it was simply a communication problem?

@haupt-pascal Because it is not an issue with PocketBase and the user already had a discussion post about it. The same user is in my "black list" for suspicious of working on a malware based on his previous posts and I don't want to help him with that.

In any case, in the linked discussion I've provided link to the code that shows how to initializes the OAuth2 form. More than this I can't help further. This is not a general dev support forum. Stack Overflow, Discord, Reddit, etc. are better suited for this.

Can this be documented better - sure but I already have enough on my hands and as explained in the linked discussion this is not a standard PocketBase use case and the user may find it easier to use something else.
