### ISSUE TITLE
Terminates during load testing

### ISSUE THREAD

**Issue by lukepighetti** [pocketbase/pocketbase#4975]
When running on a Digital Ocean 512MB VPC, if I load test it with `hey -m GET -c 5000 -n 10000 <host>` (5000 concurrent, 10000 connections), pocketbase will terminate. my expectation is that it would be resilient enough to stay running

<img width="686" alt="Screenshot 2024-05-22 at 1 36 37 PM" src="https://github.com/pocketbase/pocketbase/assets/666539/3c1a047f-792c-4e88-846e-fff5e9430ccb">

What's the recommended way to make this more durable? One person could take down my server quite easily

**Comment by thangngoc89** [comment]
@lukepighetti Looks like it was terminated by the OS? Need more information on which limit has been reached that lead to termination

**Comment by ganigeorgiev** [comment]
Without clear reproducible steps, how the environment was configured and what are those TLS errors, there is nothing much I can help with.

If the process was terminated it was most likely due to OOM but again without details what is even the above screenshot supposed to show I can't help.

For benchmarks you can check https://github.com/pocketbase/benchmarks.

If you need further assistance, please provide more details in a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose) as the threaded format is more suitable for this.

**Comment by lukepighetti** [comment]
Is there any way to convert this into a discussion? That would have been a better place to post it
