### ISSUE TITLE
FeatureRequest: Make Users and Auth Tenancy aware (Multi Tenancy)

### ISSUE THREAD

**Issue by pwfraley** [pocketbase/pocketbase#5005]
First: I love pocketbase, just stumbled across a few weeks ago. Awesome Project!

I do have a pocketbase instance running with the following collections:

- tenants
- users (with a tenant link field)
- global_collection (a collection without tenant constraints) only admins can add delete or update
- mixed_collection (this collection can contain data without and with a tenancy context, admins can create entries without tenancy context, users can create entries with tenant context)
- tenant_collection (this collection always has a tenancy context)

Now most of this works like a charm just by using the api rules:
- tenant.id = @request.auth.tenant.id for tenant_collection
- tenant = null || tenant.id = @request.auth.tenant.id for mixed_collection
- admin only for global_collection

The Feature I would like to propose is the following:

- Expand the authentication to also respect the tenant (best if configurable)
- Make email and username not unique by themselves, but make them unique email+tenant username+tenant, this way a user could register with the same email address and username twice once on tenant1 and once on tenant2 

Now I do understand that not everyone would need multi tenancy, so the whole thing should be configurable.

Again, thanks for making such a great product and opensourcing it.

**Comment by ganigeorgiev** [comment]
Sorry but for now there are no plans for this as it would introduce too much complexity for very little benefit and it seems to be very app/use-case specific.

See also https://github.com/pocketbase/pocketbase/discussions/4355.

**Comment by ganigeorgiev** [comment]
In general multitenancy could means a lot of things and as mentioned earlier its implementation could differ from one use case to another. What you understand by "tenant" for another user could mean completely different thing depending on their app context.

There is no out of the box option at the moment to allow multiple auth records with duplicated emails in a single auth collection. Even if you change the unique email index constraint it could cause issues with how the OAuth2 auto linking works.

I don't understand your specific use case and I'm not sure what to recommend.

Ideally one PocketBase instance will serve only 1 application context.

A workaround in your case could be to keep the tenant specific user data in a separate "profiles" collection that will have a relation back to a single "user".

Another option could be also to have multiple auth collections for each "tenant".

With that said, PocketBase doesn't try to solve every existing use case out there. While it may sound strange coming from the author of the project, it is fine to use something else if it doesn't work for you. It is simply a tool that I've created for [my own needs](https://github.com/presentator/presentator/issues/183) and there will be always some limitations since I don't plan growing it beyond what I can maintain on my own. There are plenty of other alternatives that may fit better your use case like: Supabase, Nhost, Appwrite, SurrealDB, EdgeDB, Payload, Strapi, Directus, etc.

**Comment by pwfraley** [comment]
Thank you for your answer.

I know that a tenancy concept differs on a usecase.  The 3 most common tanancy usecases:

1. Separate app and services per customer (eats the most ressources)
2. Seperate Database per Tenant
3. Seperate the Data within one Database (TenantId)

I am trying to implement 3.  Meaning one app instance one db instance and the data is seperated with a tenantid.

Like I said most of this works like a charme out of the box, onlything missing is the authentication.  Is there a way to customize this?  I have no knowlede of go, but I saw that one can customize pocketbase with go or javascript/typescript.

**Comment by ClimenteA** [comment]
For multitenant (db wise), adding a new field (tenant_id) on the collections is enough.

**Comment by pwfraley** [comment]
> For multitenant (db wise), adding a new field (tenant_id) on the collections is enough.

Nope does not work.

Consider this:
Company A -> Tenant A
Company B -> Tanant B

User U which has the email address peter@lustig.de now registers an account with Tenant A

Next the same User also wants to create an Account with Tenant B and tries to register with his email address (peter@lustig.de).  Pocketbase expects the email address to be unique. Which prevents the User from Registering an Account on Tenant B. :(

Now you have the choice register with tenant B with a different email address, or not be able to register with Tenant B.

I am currently considering making the tenant field in the user table a multi select field, allowing multiple tenants.  Then I change the registration process and check if the user already exists.  If he does exist and does not have the new tenant in his list, the only thing the registration does is add the tenant to the users list.

It seems to me so far that the multiple tenants would work, but I have not yet got around to testing and implementing this.

Pocketbase is such an awesome tool and allows hacking into it to make it function the way you want.  It would have been nice to have multi tenancy support out of the box, but I do understand that this is not a "regular" usecase.

When and if I figuere this out I will post an update to this.
