### ISSUE TITLE
Bug: Appending body to send options is failing the fetch

### ISSUE THREAD

**Issue by codebryo** [pocketbase/pocketbase#5006]
In my application I try to provide an extra endpoint leveraging the SDK to give certain content to users based on a token and not on a user session. 

The following is there:
1. a collection named `sites`
2. each site has a field named `token`

And here's the code I used to run it and realized it's not working as expected.
```js
import PocketBase from 'pocketbase';
const runtimeConfig = useRuntimeConfig();
const pb = new PocketBase(runtimeConfig.public.pocketbaseHost);
const siteToken = '...' // It's a valid token

const result = pb
            .collection('sites')
            .getFirstListItem(
                pb.filter('token = {:token}', { token: siteToken }),
                {
                    body: {
                        token: siteToken
                    },
                },
            );
```

I would expect, with the proper API rule it would work. For List that rule is the following:

`@request.data.token ?= @collection.sites.token || @request.auth.id = owner.id`

... the thing is, the request will never be sent, and I don't see it pop up in the Network request even. I tested it in a private browser session and was consistently able to not get it working with the `body` param being present. 😢 

🤔 I was able to get it working using a **query param** though.

```js
const result = pb
          .collection('sites')
          .getFirstListItem(
              pb.filter('token = {:token}', { token: siteToken }),
              {
                  query: {
                      token: siteToken
                  },
              },
          );
```

and 

`@request.query.token ?= @collection.sites.token || @request.auth.id = owner.id`

It was just not as I expected.

**Comment by ganigeorgiev** [comment]
The JS SDK uses the native browser `fetch` under the hood for sending the request.

While technically GET requests doesn't forbid having body, the browser's `fetch` implementation doesn't allow it the last time I checked couple months ago.

This would also explain why it doesn't show up in the Admin UI Logs since the request has never made it to the server.

I don't have time at the moment to test it but you can confirm that this is the case by wrapping your call with `try/catch` block and log the original error, something like:

```js
try {
    const result = await pb.collection('sites').getFirstListItem(
        pb.filter('token = {:token}', { token: siteToken }),
        {
            body: {
                token: siteToken
            },
        },
    );
} catch (err) {
    console.log(err.originalError)
}
```

If you are trying to send the field as body param so that it doesn't end up in the logs, an alternative could be to send it as a custom header and check it with `@request.headers.x_custom_token ...`.

I'll close the issue for now but feel free to let me know if the above is not what you are experiencing and I'll try to investigate it further tomorrow.

**Comment by codebryo** [comment]
First of all, big thank you to @ganigeorgiev 

For everyone else stumbling over this, I got this working with headers just fine. Following the docs was straight forward. 

So doing this in the code:
```js
await pb.collection('collection').update(id, updateData, {
  headers: {
    'Super-Secret-Token': token,
  },
})
```

Works, and in the API rules you can even do things like:

```
@request.headers.super_secret_token ?= @collection.super.token
```
