### ISSUE TITLE
Inconsistent behavior of filter rule check with vs without parenthesis

### ISSUE THREAD

**Issue by eipiminus1** [pocketbase/pocketbase#5017]
I try to create a combined filter rule containing the following check as part of a series of checks:

`@request.auth.username ~ "\""`

The rule is accepted if used like written above. As I put the expression in parenthesis, like so

`(@request.auth.username ~ "\"")`

I get the following error message:

> Invalid filter rule. Raw error: expected && or ||, got "test" (identifier).

I also tried to use single quotes instead of escaping the double quote:

`(@request.auth.username ~ '"')`

which gives the same results.

If my check does not include the double quotes, I can happily put parenthesis around my expression. This seems to me like a bug in the filter rule parser.

*Note: This is a minimal code example to reproduce the problem. The actual use case is a little different. If you need more info about the use case, let me know.*

**Comment by ganigeorgiev** [comment]
Thanks for reporting the issue. It is caused because of the unwrapping->wrapping sequence when the text literal is nested in parenthesis.

A fix was submitted in the [fexpr repo](https://github.com/ganigeorgiev/fexpr/commit/6116eee9fed76ceab61d866f6d73b09abe5b8250) (_I'll push the releases tomorrow_).
