### ISSUE TITLE
SQLite Cloud

### ISSUE THREAD

**Issue by Galbuandco** [pocketbase/pocketbase#5038]
Hi, 

First of all let me tell you I love pocketbase. It is so convenient to use!

However I've seen it has recently been announced  https://sqlitecloud.io/ and I was wondering if it could be easily integrated in pocketbase. 

I think it could be very interesting because in this way pocketbase could scale horizontally effortlessly, isn't it? But really I have no experience using both sqlite and go, I was just curious to hear your opinions.

**Comment by ganigeorgiev** [comment]
This was discussed several times before. The database is not the reason why PocketBase can't scale horizontally.

It is just not designed to work in a multi-server setup because there is no synchronization mechanism out of the box for syncing the app event hooks between multiple instances and probably there never will be.

If your use case in reality requires horizontal scaling PocketBase is not suitable for it.

**Comment by Galbuandco** [comment]
Yes, actually sorry I was not really meaning to scale the server horizontally but the db only, as for what I've read from docs etc writes are the only bottlenecks.

Actually my real goal was to use a small instance for the server in go and then let the DB to be managed by the cloud provider  SQLlite cloud because they promise more performance and reliability. 

In fact this need came from the fact that I had computer instance on Google Cloud but it has happened to crash badly a couple of times when trying to upload files.
