### ISSUE TITLE
How to get logs data?

### ISSUE THREAD

**Issue by morethancoder** [pocketbase/pocketbase#5081]
## How to get logs data
Im building a cms app using pocketbase as go extend, 
I want to get access to the logs table and display pocketbase logs in my dashboard to have control over filtering the logs and showing them in my dashboard, however I can't seem to access the logs from within the app instance, 
like for example 
`logs, _ := app.Dao().LogsStats(dbx.NewExp("created <= datetime('now', '-1 hour')"))` 
raises the following error 
```no such table: _logs; failed query: SELECT count(id) AS "total", strftime('%Y-%m-%d %H:00:00', created) AS "date" FROM "_logs" WHERE created <= datetime('now', '-1 hour') GROUP BY "date"```

it says there is no such table as _logs in my database, however logging works fine in admin ui and im able to filter, and display logs just fine.

I want to know how to get the logs data so I can use in other parts of my app, thanks.

**Comment by ganigeorgiev** [comment]
Please don't spam by posting the same questions multiple places.

This will change with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) but in order to perform operations over the logs.db you need to use the `app.LogsDao()`.

If you need further assistance please use the repo discussions as the threaded format is more suitable for this type of questions.
