### ISSUE TITLE
Can not connect SSE method

### ISSUE THREAD

**Issue by yamadaOliva** [pocketbase/pocketbase#5142]
![image](https://github.com/pocketbase/pocketbase/assets/80296624/c962bba8-bad1-4116-8aba-4785aebef31c)
Thanks for awesome project !!

In this case, i can not send to client that message. In client, i got a notification that no active within 45000 milliseconds. No response recceived.
![image](https://github.com/pocketbase/pocketbase/assets/80296624/dabe6af0-768d-4eed-bc45-09a76fcc4d09)

**Comment by ganigeorgiev** [comment]
This is not a PocketBase issue.

In order to receive any messages you need to subscribe to a specific topic - either `collectionId/*` or `collectionId/recordId`. For more details about the realtime APIs please refer to https://pocketbase.io/docs/api-realtime/.

If you need further help, please open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose) elaborating more on your use case and why you can't use the JS SDK.

**Comment by ganigeorgiev** [comment]
Additionally note that the `onRealtimeConnectRequest` hook is triggered **right before** establishing the SSE client connection, so if you are trying to send a realtime message you need to attach to some other hook.

**Comment by yamadaOliva** [comment]
Thanks, I have done this !!
