### ISSUE TITLE
OAuth in same window

### ISSUE THREAD

**Issue by dahjson** [pocketbase/pocketbase#5189]
OAuth should work within the same window and not within a popup or new tab. Both of these methods get blocked by Safari by default as well as popup blockers. The helper page provided by Pocketbase during authentication should also not use _Pocketbase_ as the title of the page, and instead use the _Application name_ listed under _Settings / Application_.

**Comment by ganigeorgiev** [comment]
Regarding Safari blocking the popup - this is most likely because your click handler is async. You can find a workaround in https://github.com/pocketbase/pocketbase/discussions/2429#discussioncomment-5943061.

There are no plans to change how the current OAuth2 integration works. If you have suggestions how something should be implemented feel free to outline how you are planning to do it and I may consider it, but if you are just going to complain about it then please just move on.

**Comment by dahjson** [comment]
I already researched different solutions, and I'm already using that solution, but that solution still doesn't work with Safari.
