### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by martinjanda** [pocketbase/pocketbase#5234]
I use PocketBase v0.22.17 as Go framework. I changed smtp server to https://www.xmox.nl/ and get this error for all e-mail sending.

```
ERROR POST /api/settings/test/email
└─ Failed to send the test email. Raw error: 
501 5.5.2 invalid base64: illegal base64 data at input byte 4 (tQcY-y5_TeS0ToW-Tz6jWQ).
```

I checked configuration, try e-mail clients, another libs for SMTP sending and all works. It looks as bug in PocketBase?

**Comment by ganigeorgiev** [comment]
I'm not familiar with Mox but the above error seems that originate from the mail server and not from PocketBase.

I've just tested the SMTP integration with mailtrap.io and mailgun and in both cases in works fine for me. Additionally I'm using PocketBase on production for [presentator.io](https://presentator.io/) and the mail sending works fine there (the SMTP provider is a shared mail hosting from jump.bg).

If you still think that it is a PocketBase issue feel free to provide clear reproducible steps and I'll try to investigate it further but I'm not going to spend time installing Mox.

If you have access to the mail server logs you can try to compare the mail headers that are being send against your other SMTP libs that you've tested.

**Comment by ganigeorgiev** [comment]
Also note that the above base64 error could be related to some Mox bug when parsing the mail body because the test mail contains a test JWT (eg. verification, password reset, etc. token) that is send in the mail body so when you are testing with other SMTP libs you may not see that error because your mail body probably doesn't contain the token.
