### ISSUE TITLE
Required Number and Boolean Fields throw errors with 0 or false

### ISSUE THREAD

**Issue by jeffmikels** [pocketbase/pocketbase#526]
When creating a new record, if a field is marked `required` the create operation will fail if the value is set to a "false-y" value like `false` or `0`.

To Replicate:

Create a collection.
Create a number field with `required` set to `true`
Use the API or the Web GUI to create a new record with the field = `0`

Create a collection.
Create a boolean field with `required` set to `true`
Use the API or the Web GUI to create a new record with the field = `false`

Error:

`{code: validation_required, message: Missing required value.}`

**Comment by jeffmikels** [comment]
I also get the error when using the web GUI and try to set a required number field to `0`

**Comment by ganigeorgiev** [comment]
This was recently reported in https://github.com/pocketbase/pocketbase/issues/436#issuecomment-1248571689.

This is working as expected, although I agree that it is not very well explained at the moment.

Since v0.3.0 PocketBase doesn't support anymore `null` values (with the exception of the `json` type field). Full table with the supported PocketBase values could be found in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0.

The "Required" constraint means "non-empty/non-zero" value.  In PocketBase (and Go) `false` is the empty/zero value for bools, `0` is the empty/zero value for numbers, empty string for strings, and so on.

I'll consider adding a tooltip explaining better the "Required" constraint behavior for each field after the refactoring.

**Comment by sgruhier** [comment]
it's ok for a bool as UI only allow true/false
It's more an issue with number. 0 is a valide value :(.

**Comment by ganigeorgiev** [comment]
@sgruhier `0` is a zero-default for the number field. If you want to make a number required, use the min/max field options. This will be better documented in the next release.
