### ISSUE TITLE
Proposal: async email send with extend with javascript

### ISSUE THREAD

**Issue by Saad5400** [pocketbase/pocketbase#5261]
Basically a new method $app.newMailClient().sendAsync or something which sends the email without making the code wait for the email to be sent.

I'm actually looking for something like Laravel's queue but it might be too much,

if there's a simple way to do it please do tell me as I'm not that experienced and waiting for the email is causing a decent delay.

**Comment by ganigeorgiev** [comment]
The JSVM doesn't allow running concurrent code. It is possible to register a custom Go binding that will run in a new goroutine a serialized goja code ala `routine.FireAndForget` fashion but I'm not sure if it will be a good idea as it could cause other issues down the road since there will be no information about the state of the execution nor whether the JSVM will have completed or not (the [handler scope limitation](https://pocketbase.io/docs/js-overview/#handlers-scope) will also apply for this case).

For now concurrent code execution with the JSVM remains out of the scope, but there is nothing wrong to create your own "queue" helper collection and register a [cron task](https://pocketbase.io/docs/js-jobs-scheduling/) that will process the records periodically from it (see an example in https://github.com/pocketbase/pocketbase/discussions/5235#discussioncomment-10098391).

**Comment by Saad5400** [comment]
Very much appreciated, thank you @ganigeorgiev
