### ISSUE TITLE
Dates are wrong in record view - Admin UI

### ISSUE THREAD

**Issue by margani** [pocketbase/pocketbase#5268]
In Admin UI, The date fields in the Edit Record form are different from the ones in the list:
![image](https://github.com/user-attachments/assets/82b1c410-6bb9-4400-9021-ecdfc96922e1)

The API shows the values identical to the ones in the list:
![image](https://github.com/user-attachments/assets/05a3fcb0-4e5a-4e4a-ace5-f66b68ca7934)

The issue is the same for all the records, the Seconds values of the date fields are a couple of seconds ahead.

**Comment by ganigeorgiev** [comment]
It is possible to be a bug with how we load the date layout into the flatpickr component but I'm not able to reproduce it with the live demo - https://pocketbase.io/_/#/collections?collectionId=iiydkd3oo4wh4ef&filter=&sort=-created (admin, 123456).

Note that depending how the detail panel was opened it is possible that the state of the record in the detail panel and the listing to differ since the listing doesn't update in realtime at the moment.

If you are still think that it is a PocketBase issue, please provide provide more details about your setup (what PocketBase version do you use and whether do you have custom hooks) and also make sure that there is no browser extension interfering with the UI.

**Comment by margani** [comment]
Yes, you were right. In incognito browser, I can see the dates are shown correctly, and after disabling extensions one by one, I realised that [NordVPN browser extension](https://microsoftedge.microsoft.com/addons/detail/nordvpn-the-fastest-vpn/fphgeikpdcdcheaochkhldmnfblfogla) causes the date like `2024-07-28 15:16:38` to be shown like `2024-07-28 15:16:32`. 

I don't know yet why.

Thank you, I appreciate your help. 🙏
