### ISSUE TITLE
Add subscription to queries 

### ISSUE THREAD

**Issue by yunior123** [pocketbase/pocketbase#527]

**Comment by ganigeorgiev** [comment]
Currently the subscription API works with a single record events only.

If you are asking for Firestore-like subscriptions, you can always call `client.records.getList/getFullList` in the subscribe callback.

Could you elaborate on your use case?

**Comment by yunior123** [comment]
Hi, thanks for the fast reply. Yes, indeed, I am referring to the firebase like subscription to queries.

**Comment by yunior123** [comment]
Hi, thanks for the fast reply. Yes, indeed, I am referring to the firebase like subscription to queries. I think it would be better if that feature could be added, it's something that feels natural when starting a project. I don't think the proposed solution is a nice way of doing it, the callback would be called even if no changes were made to what you are listening to(the query) in the client side.

**Comment by ganigeorgiev** [comment]
Hm, similar discussions were filed in https://github.com/pocketbase/pocketbase/discussions/521 and https://github.com/pocketbase/pocketbase/discussions/304.

Supporting events with query list results may have some performance penalty and could increase the latency due to the complex access checks (especially if expand is used).

I'll have to think a little more on this before adding it to the roadmap, but that will be after the ongoing users and profiles refactoring.

**Comment by ganigeorgiev** [comment]
Experimental `filter`, `expand`, `fields`, custom query and headers parameters support for the realtime subscription was added in the `develop` branch. There are some minor polishing details that needs to be done, but it can be tested with the [v0.20.0-rc prerelease](https://github.com/pocketbase/pocketbase/releases/tag/v0.20.0-rc).
