### ISSUE TITLE
Make it scale horizontally 

### ISSUE THREAD

**Issue by yunior123** [pocketbase/pocketbase#528]
One of the main critics received for this project are related to the database not scaling horizontally. Any plans on solving this problem?. There is a full explanation in the Fireship YouTube channel. Also, nice work guys, I love Golang and aiming to contribute to this project in the future 👍.

**Comment by ganigeorgiev** [comment]
At least for v1.0.0 there are no plans for horizontal scaling.

In the future we can implement a raft-style sync between multiple PocketBase instances (similar to Marmot that was recently posted in https://github.com/pocketbase/pocketbase/discussions/487) but that's out of the scope for now.

PocketBase is suited mainly for small and midsize projects. After we reach a little more stable version, I'll create a proper testbed and benchmarks so that users could have a general idea of what to expect in terms of performance.

Please note that I've created PocketBase because I wanted something small with almost no setup (see [Presentator #183](https://github.com/presentator/presentator/issues/183)) and horizontal scaling often doesn't end with making the database external - we have to think how to sync the realtime events between the different nodes, prevent duplicated event hook calls, maintain a synced app state/cache, etc.

**Comment by ThomasSmWatson** [comment]
I'd like to propose that an ETCD/RAFT integration with the data store may power this possibility. Maybe this could be something the community would be able to get involved in :). Would this be something that Pocketbase would consider?
