### ISSUE TITLE
Custom Routes lack Realtime

### ISSUE THREAD

**Issue by melihsd** [pocketbase/pocketbase#5286]
Like said, custom routes defined per `pb_hooks` lack the functionality of realtime subscription. 

Subscribing to the collection via `pb.collection("xxx").subscribe()` is not a solution since there are many use cases where access control or programmatically accessed data can't be recreated. 

I am using routerAdd via pb_hooks.

**Comment by ganigeorgiev** [comment]
Please don't open issues like this. Without any elaboration on the use case, it is not clear what you are trying to do or what actually is even the problem here.

If you have a general question how to use something, elaborate in a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new?category=q-a) as the threaded format is more suitable for this type of posts.
