### ISSUE TITLE
Integrations test ApiScinarios force ExpectedEvents

### ISSUE THREAD

**Issue by erikd234** [pocketbase/pocketbase#5333]
When I am writing the integrations tests with API scenarios sometimes I don't care too much about what events are expected within the API call.

I think having expected events are kind of like GlassBox testing where that reveals about the implementation of the APIscinario being tested. Could this be optional? For example, If I don't include expected-events in the testAPIscinario struct then it will tell me which events it expected and fail the test if I dont add them. 

My workout right now is that I simply copy what it says it should have into the expected events struct field in the test to make it pass. But if i change my code now to do different things, such as more writes / reads or other event triggers, it will break the test, even though what I care about in the endpoint did not break. I see the value in testing the events emitted I just would just like an option to NOT have to test for these events. In the case I don't care about the event for that endpoint being tested.

example run of a test.

```
=== RUN   TestGetUserStats/test_/userstats_GET
    api.go:180: Expected events map[], got map[OnModelAfterCreate:1 OnModelBeforeCreate:1]
```

On the API scenario that I tested above I did not include an expected Events section at all.

What do we think about the default behaviour should be to ignore this instead of forcing the user to copy paste the events that fired into the api scenario, just to please the testing package.

**Comment by ganigeorgiev** [comment]
I'm not sure. There are many cases where internally we need to verify that an action didn't fire any events (_and if we don't require it many users may also not just know about it_).

I guess we could add support for it if we differentiate `nil` (don't test events) vs empty map (no events should have been fired) but for consistency we may have to do the same for the `ExpectedContent` field.

I'll think a little more on it with the refactoring.

**Comment by erikd234** [comment]
The nil marking could be a good approach,

As a side, for expectedcontent I've also had a test where I was only checking for the status code (404, 400) and didnt want to check the body. The end result was I had a simple string in the expected content since it seems to be doing a substring search.

But in hindsight being forced to check the body makes me write standardized error messaged which is good.

But explicitly marking it as nil is nice since it could mean the developer for whatever reason explicitly doesn't want the test to check that which isn't a bad thing.

**Comment by ganigeorgiev** [comment]
> But explicitly marking it as nil is nice

But that's the problem, it won't be explicit. If users don't set the field it will be `nil` by default since this is the default zero value for map/slice.

**Comment by erikd234** [comment]
Awww yes I see, that makes it a challenge if you want the default mode to be required when the dev doesn't specify anything.

Yeah it's a low priority, it's just now havijg copied paste events to make integration tests pass so many times it feels weird and I wanted to share my feedback.

One again thanks for pocketbase I really love using it! 

Looking forward to the refactor (although I love echo and will be sad to loose echo context and their param / query parsing bind method)

Cheers,
Erik

**Comment by erikd234** [comment]
Awww yes I see, that makes it a challenge if you want the default mode to be required when the dev doesn't specify anything.

Yeah it's a low priority, it's just now havijg copied paste events to make integration tests pass so many times it feels weird and I wanted to share my feedback.

One again thanks for pocketbase I really love using it! 

Looking forward to the refactor (although I love echo and will be sad to loose echo context and their param / query parsing bind method)

Cheers,
Erik

**Comment by ganigeorgiev** [comment]
After some consideration I've decided to change with the upcoming v0.23.0 release the behaviour of the `ExpectedEvents` field to be similar to the `ExpectedContent`/`NotExpectedContent` test fields.

The main reason for the change is that with PocketBase v0.23.0 and the introduction of proxy/projections hooks there will be a lot more events and could be too "boilerpletish" (and most likely unnecessary) to check all hook events for all tests.

Explicitly checking whether a cetain endpoint has fired exactly the specified hook events is mostly important for the internals to ensure that no other hooks were fired accidentanly but this is usually not something users should concern themself with because rarely they invoke the `Hook.Trigger()` method manually.

Or in other words, with the upcoming PocketBase v0.23.0 release, `ExpectedEvents` would be optional and will check only the events that are explicitly listed by the user (this includes support for ensuring that an event has fired 0 times).

Additionally, for the rare cases where this matter like for the internal tests, there is also a special `*` (wildcard) event key that can be used to target all events to ensure that no other events were fired except the listed in the user provided map.

For example, if the application fires `["EventA": 2, "EventB": 1]`, then:

```go
// 𐄂 fail (no such event was fired)
ExpectedEvents: map[string]int{
    "EventC": 1,
}

// 𐄂 fail (mismatched event fires count)
ExpectedEvents: map[string]int{
    "EventA": 3,
}

// 𐄂 fail (exact match, aka. missing EventB check)
ExpectedEvents: map[string]int{
    "*":      0,
    "EventA": 2,
}

// 🗸 succeed
ExpectedEvents: map[string]int{
    "EventC": 0,
    "EventB": 1,
}

// 🗸 succeed (exact match, aka. no other events were fired)
ExpectedEvents: map[string]int{
    "*":      0,
    "EventA": 2,
    "EventB": 1,
}
```

**Comment by stamler** [comment]
Prior to 0.23 (0.22 etc) with ExpectedEvents being mandatory for testing I could see which events were expected in failed tests and then build the tests accordingly. Now in PocketBase 0.23 with ExpectedEvents optional how can I see which events actually fired during a test? There doesn't seem to be a comprehensive list of all standard events either. For example, I had a test for my 0.22 code where I expected "OnBeforeApiError": 1 and "OnAfterApiError":  1, now I don't even know the name of the new events when there's an API error. I'd like to log them to see but can't figure out how to do that.

**Comment by ganigeorgiev** [comment]
@stamler As explained above and in https://pocketbase.io/v023upgrade/go/#test-helpers-changes, you can add `"*": 0` to have the old behavior and to ensure that no other events except the ones listed are fired. In case there are missing events you should see an error message like:

```
--- FAIL: TestCollectionsImport/authorized_as_superuser_+_collections_validator_failure (0.09s)
        api.go:292: Missing expected remaining events:
            map[string]int{"OnCollectionAfterCreateError":2}
            All triggered app events are:
            map[string]int{"OnCollectionAfterCreateError":2, "OnCollectionCreate":2, "OnCollectionCreateExecute":2, "OnCollectionsImportRequest":1, "OnModelAfterCreateError":2, "OnModelCreate":2, "OnModelCreateExecute":2}
```
(_notice that the error messages contains a list with both all and the missing events_)

With that said, keep in mind that v0.23+ has major changes in relation the hooks and some of the old events are no longer available. Specifically for the `OnBeforeApiError` and `OnAfterApiError` they no longer exists because for error handling we use the `e.Next()` result (see https://pocketbase.io/v023upgrade/go/#onbeforeapierroronafterapierror-any-middleware).
