### ISSUE TITLE
Feature Request: Add Username in Logs

### ISSUE THREAD

**Issue by vsnshanmuganathan** [pocketbase/pocketbase#5337]
![Screenshot 2024-08-11 at 8 06 19 AM](https://github.com/user-attachments/assets/8cfd1a54-24f3-42f4-81ed-8407ffb13d76)
In the `data.auth`, we receive values such as admin, authRecord, and guest. Could you please include the username or the format `collectionname_username`? This would make it much easier for us to identify who made the changes, as the current labels provide no useful context.

**Comment by ganigeorgiev** [comment]
Something similar was requested before but for now remains out of the scope, mostly due to security and GDPR concerns since initially we didn't have the option to skip the IP from the logs. I may consider thought adding the user id with the refactoring but for now remains a very low priority.

Note also that with the next v0.23.0 release the `username` field will be no longer required.
