### ISSUE TITLE
Question: Can hooks be in subfolders of `pb_hooks`?

### ISSUE THREAD

**Issue by sean078** [pocketbase/pocketbase#5357]
Can hooks be in subfolders of `pb_hooks`? When I add a record event hook in a subfolder, the watcher sees it and triggers a restart, but the hook doesn't seem to run when the triggering event occurs. The same hook is triggered if put in `pb_hooks/myhooks.pb.js` instead of `pb_hooks/mysubfolder/myhooks.pb.js`.

**Comment by ganigeorgiev** [comment]
No, only direct children/top-level `.pb.js` files are loaded. The watcher restart because it is possible a `*.pb.js` to depend on a non-hook file (images, templates, other plain js files, etc.).

For other questions please use the [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions) instead as the threaded format is more suitable for this type of posts.
