### ISSUE TITLE
smtp connection error

### ISSUE THREAD

**Issue by Andev70** [pocketbase/pocketbase#5378]
i was trying to setup smtp for email sending..but pocketbase refuse to connect to the server even after everything is ok...

**Comment by ganigeorgiev** [comment]
This is not a PocketBase issue. I can confirm that the SMTP integration works because I'm using in production with https://presentator.io/.

Without any details about your setup or the error, there is nothing I can help you with.

To rule out SMTP server misconfiguration you can try testing for example with [mailtrap.io](https://mailtrap.io/) or https://www.smtpbucket.com/ (both works for me when testing locally).

If you are still not able to resolve your issue, please provide more details in a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose).
