### ISSUE TITLE
Feature Request: Use toggle to allow updating certain field

### ISSUE THREAD

**Issue by kyborq** [pocketbase/pocketbase#5380]
Would be nice if we have a feature that can allow us to restrict or allow to update certain fields in table, or event make it invisible in record list

![image](https://github.com/user-attachments/assets/aa529d59-cd62-4c7d-bfb8-d01c65f1026e)

Why?

---

Sure, we can restrict to update field in api rules, but when we want to restrict all fields and made only one field available to update for example?

**Comment by ganigeorgiev** [comment]
There are no plans for this specific toggle as it is not clear who will have access to read and update the field and the create/update API rules already allow granular control over the field.

Additionally note that with the [refactoring](https://github.com/pocketbase/pocketbase/discussions/4355) and the upcoming v0.23.0 release (_there are no ETAs yet_) there will be a "Hidden" field toggle option that will prevent read and write access to the field for non-superusers that to some extend will cover the above (_"admins" with the next release are named "superusers" since they will be special auth collection records, aka. `models.Admin` -> `models.Record`_).
