### ISSUE TITLE
Suggestion: TTL support

### ISSUE THREAD

**Issue by Matthijz98** [pocketbase/pocketbase#5470]
Thanks for this great product.
I use Pocket Base to track some custom event data in my apps and Discord bot.
I would love to be able to set a ttl time on records so they are deleted after x amount of time.

This feature could be done in two ways:
- Add a ttl field or option to the datetimefield. This way, each items could have an other ttl this would be similar to how Redis does it: [https://redis.io/docs/latest/commands/ttl/](https://redis.io/docs/latest/commands/ttl/)
- Set a max ttl to the collection settings page. This could be handy for analytics data that i only want to keep for 365 days

**Comment by ganigeorgiev** [comment]
It was suggested before but for now there are no plans for this as there are too many caveats around it (when and how often needs the check to be performed, what if the record can't be deleted due to some required cascade delete reference, what if the auto delete should be applied only for records matching a specific criteria like `lastAccess` field, what if the user doesn't want real deletion but soft-delete, etc.).

Note that it can be easily achieved programmatically by [registering a cron job](https://pocketbase.io/docs/go-jobs-scheduling/).
