### ISSUE TITLE
Use env variable in JS migration

### ISSUE THREAD

**Issue by alaireselene** [pocketbase/pocketbase#5490]
How can I create a Docker image for PocketBase that allows me to pass arguments for automatically creating an admin account? I’m trying to write a JS migration but am unsure if I can retrieve values from environment variables. Any advice?

**Comment by ganigeorgiev** [comment]
It doesn't really make sense to use env variable as part of admin creation migration because you can't guarantee that the env variable will be set in the environment where the migration will execute.

But in any case, if you really want to you can access the env variable using the [`$os.getenv(key)` helper](https://pocketbase.io/jsvm/functions/_os.getenv.html).

For other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead.
