### ISSUE TITLE
Collection Update Single File Field Error Deleting Existing File

### ISSUE THREAD

**Issue by oscargoldman** [pocketbase/pocketbase#5496]
there seems to be an issue with deleting an existing file associated with a single file field in a collection record. Creating a record for the collection with a file works great, but updating that record with a new file, using the same multipart form data with a different image byte list, the server throws the following validation error:
return validation.Errors{
				key: validation.NewError(
					"validation_unknown_filenames",
					"The field contains unknown filenames.",
				),
			}
updating the record with an empty string for the file field name deletes the record as expected. The documentation states that updating the field with a new file should delete the old file but this doesn't seem to be working.
This is using pocketbase v0.22.19 and flutter pocketbase ^0.18.1

**Comment by ganigeorgiev** [comment]
I can't reproduce your issue because it is not clear how you are sending the request.

Feel free to provide a minimal code sample if you still think that it is a PocketBase issue and I'll try to investigate it but as of now there is nothing much I can help you here.

For other questions, please use the Q&A discussions instead.

**Comment by ganigeorgiev** [comment]
If you are submitting something like:

```dart
pb.collection('example').update(
  'RECORD_ID',
  body: {
    'document': 'example.txt',
  },
  files: [
    http.MultipartFile.fromString(
      'document',
      'example content...',
      filename: 'abc.txt',
    ),
  ],
)
```

Then the above could fail because you are essentially submitting 2 values for the `document` field.

If you just want to replace the document, then remove it from the old string value from the `body`.

If that's not the case, then I'm failing to understand your post even after reading several times.

Please don't treat the issues tracker as llm chat and and try to elaborate more clearly and as much details as possible to avoid the needless back-and-forth, otherwise is just lazy and low-effort.

**Comment by oscargoldman** [comment]
Thanks for your response. here's how I'm calling the request.

response.data = await _client .collection('memorials').update(id, body: body, files: files) where id is the existing record id, body is all other fields the record (this updates fine), and files parameter looks like this:

final files = <MultipartFile>[];
files.add(
          MultipartFile.fromBytes(
            'profile_image',
           validImageByteshere,
            filename: 'newImage.png',
            contentType: MediaType.parse(im.mimeType),
          ),
        );

So 'profile_image' is the field name in the record, and the filename is taken from the new image with which we're trying to update the record. I've also tried using the original(current) file name, and the name returned from the server with the random characters added to it. None of them work.
This is the exception:
ClientException: {url: https://treasuremap.org/api/collections/memorials/records/q1fsztqga4xy33s, isAbort: false, statusCode: 400, response: {code: 400, message: Failed to load the submitted data due to invalid formatting., data: {profile_image: {code: validation_unknown_filenames, message: The field contains unknown filenames.}}}, originalError: null}
I've looked at the source code and this error comes from the process of trying to delete the existing file from the record.

**Comment by oscargoldman** [comment]
ok from the example you provide it looks like it's necessary to "zero out" the value of the current file field in the body, and then upload the new value in the form data. I will try this. The documentation leaves a bit of a gap between deleting an existing file associated with a record, and updating with a new file.
