### ISSUE TITLE
SQL scan error when extending with javascript

### ISSUE THREAD

**Issue by luberius** [pocketbase/pocketbase#5508]
Hello!

when I extend pocketbase (0.22.18) using javascript, I got this error when running my custom query

```
GoError: sql: Scan error on column index 8, name "total_shipped": converting driver.Value type float64 ("1010.3") to a int64: invalid syntax
```

it seems like the engine does not support floating value or somehow expected integer.

is there something I miss?

heres my pb.js file
https://gist.github.com/luberius/75ff1276f77d8163f397142ee208aed4

thank you. 

**Edit**
for work around, I cast the numbers to string in the query 😄

**Comment by ganigeorgiev** [comment]
Hm, this seems to be caused by the `DynamicModel` JS<->Go map values type conversions.

By default goja applies the [following rules](https://pkg.go.dev/github.com/dop251/goja#Value):

> For integer numbers it's int64.
> For any other numbers (including Infinities, NaN and negative zero) it's float64.

So another workaround in your case could be to change the `total_shipped` initialization to `0.1` or `-0` (_the signed 0 is a valid value explicitly defined in the [ECMAScript spec](https://262.ecma-international.org/6.0/#sec-strict-equality-comparison)_).

I guess we can also normalize the value manually and cast it to always be a `float64` because in JS practically that is what usually the [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) values are expected to be (PocketBase's `number` field type also assume this) but it could have some unintended side-effects when operating with custom non-collection data and I'm not sure whether it would be a good idea.

I've added it in my todo to think a little more on it with the ongoing refactoring but for now let's keep the current behavior (_I'll consider at least documenting it in case the auto float64 cast normalization turns out troublesome_).
