### ISSUE TITLE
Expand not working with sign in

### ISSUE THREAD

**Issue by mvrlin** [pocketbase/pocketbase#5522]
Hey! Maybe I'm doing something wrong, but I can't expand fields when signing in.

https://github.com/user-attachments/assets/62783a25-75ad-4ba1-bb6b-6c31414c70b3

```js
fetch('/api/collections/users/auth-with-password?expand=record.res', {
    headers: {
        'Content-Type': 'application/json'
    },
    method: 'POST',
    body: JSON.stringify({
        identity: 'test@test.com',
        password: '1234567890'
    }),
})
```

**Comment by ganigeorgiev** [comment]
`expand` targets relation field, aka. if you have direct relation `res` then it needs to be just `?expand=res`.

For other questions, please use the Q&A discussions instead.

**Comment by mvrlin** [comment]
> `expand` targets relation fields, aka. if you have direct relation `res` then it needs to be just `?expand=res`.
> 
> For other questions, please use the Q&A discussions instead.

Please take a look at the video, I tried `?expand=res` and `?expand=record.res` - results are the same

**Comment by ganigeorgiev** [comment]
Please don't post the same thing multiple places.

If `expand=res` doesn't work, then make sure that your client-request satisfies the View API rule of the related collection.

If you are still not able to identify the culprit, export your collections as json (Admin UI > Export collections) and I'll try to have a look, but I'm pretty sure that `expand` works correctly because we have integration tests for the direct relation case and I'm using it in production in https://presentator.io/.
