### ISSUE TITLE
Api rule more

### ISSUE THREAD

**Issue by Terminator19** [pocketbase/pocketbase#5548]
could you add api rules `@request.headers.origin` == "https://your-allowed-domain.com"``

**Comment by ganigeorgiev** [comment]
It should be already supported as long as the header is sent with the request.

**Comment by Terminator19** [comment]
I need the list rule api to work domain1 and domain2

**Comment by ganigeorgiev** [comment]
Again, if you send the header with your request you'll be able to filter it.

There is no guarantee that the `Origin` header will be present with the request, users can submit whatever headers they want. Even browsers doesn't add it always, if that's your expectations - see https://stackoverflow.com/questions/42239643/when-do-browsers-send-the-origin-header-when-do-browsers-set-the-origin-to-null/42242802.

If you want to apply CORS restrictions, you can start the executable with `--origins=domain1,domain2`.

In any case, please don't treat the issues tracker as chatgpt and try to clearly elaborate on your use case to understand the bigger picture and what actually you are trying to, otherwise it is just lazy and low effort.
