### ISSUE TITLE
[BUG] Subscription (SSE) times out

### ISSUE THREAD

**Issue by AlejandroAkbal** [pocketbase/pocketbase#5552]
I use pocketbase to save posts, and to have an always up to date list of saved posts, I use the realtime server side events subscription, like this:

```ts
await $pocketBase
      .collection('tags')
      .subscribe<IPocketbasePost>('*', function (e) {
        switch (e.action) {
          case 'create':
            savedPostList.value.push(e.record)
            break

          case 'update':
            const index = savedPostList.value.findIndex((post) => post.id === e.record.id)
            savedPostList.value[index] = e.record
            break

          case 'delete':
            savedPostList.value = savedPostList.value.filter((post) => post.id !== e.record.id)
            break
        }
      })
      .catch((error) => {
        console.error({ error })
      })
```

This did work some time ago, but now Im having this issue:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/7ad44851-2da9-4aa0-a9b3-513d294dbbe0">

This is a test user for you to try subscriptions:
TestyMacTestFace
password: TestyMacTestFace

**Comment by AlejandroAkbal** [comment]
In pocketbase logs, in debug mode, I see the client is connected, but on the browser theres always that error

**Comment by ganigeorgiev** [comment]
This is not a PocketBase issue, nor I understand what the above code or "test user" credentials are supposed to show or test.

`ClientResponseError 0` indicates a client-side issue, usually a connection failure error.

To rule out PocketBase error, you can create a static `pb_public/index.html` file:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");
        
        // authenticate if necessary
        await pb.collection("users").authWithPassword("test@example.com", "1234567890")
 
        pb.collection("tags").subscribe("*", (e) => {
            console.log("Change:", e);
        })
    </script>
</body>
</html>
```

Open your browser, navigate to `http://127.0.0.1:8090`, open the inspect console and you should see the "Change" log on "tags" collection change.

If you still think that there is a PocketBase issue, feel free to provide clear reproducible steps and I'll to investigate it but I'm pretty sure that your issue is not PocketBase related because I'm using the realtime subscriptions in production with https://presentator.io/ and everything works correctly for me.

**Comment by AlejandroAkbal** [comment]
Yeah, I still think it's a Pocketbase issue or something in between PB and browser
Because I can connect, auth and fetch data in my browser, but the subscription hangs out and outputs that error, so there is definitely something happening

**Comment by ganigeorgiev** [comment]
Please test the above minimal reproducible. For me it works correctly.

The issues tracker is not a general dev support forum. I'm sorry but until proven otherwise I don't think your issue is PocketBase related and I'm not willing to waste time on this.
