### ISSUE TITLE
typescript sdk

### ISSUE THREAD

**Issue by elycheikhsmail** [pocketbase/pocketbase#556]
I see pb generate js sdk but in most case we use ts in frontend.

**Comment by ganigeorgiev** [comment]
The [JavaScript SDK](https://github.com/pocketbase/js-sdk) is written in TypeScript and all types are exported in the corresponding `.ts` definition file in https://github.com/pocketbase/js-sdk/tree/master/dist.

The types should be automatically loaded for you since we make use of the `"type"` package.json configuration - https://github.com/pocketbase/js-sdk/blob/master/package.json#L18.

If you are not able to import the SDK in your TypeScript project, please open an issue in the  [JavaScript SDK](https://github.com/pocketbase/js-sdk) repo, providing some details how you initialize it, and I'll investigate it further.
