### ISSUE TITLE
Intermittent 404 response when querying records

### ISSUE THREAD

**Issue by amirrezasalimi** [pocketbase/pocketbase#5603]
I'm encountering a strange issue with PocketBase in one of my projects. 
The problem occurs intermittently: sometimes I receive a 404 response for valid queries, while other times the correct data is returned, even when the query and data remain unchanged.

### Setup:
PocketBase version: v0.22.21
Backend: Hosted in Docker along with PocketBase

### Issue Details:
The issue occurs randomly within seconds of sending identical queries.
A 404 response is returned, despite the fact that the resource exists.
There is no clear pattern to the problem (e.g., no server restart or clear environmental factor triggering it).
I’ve tested the query using curl, and the following are two examples of responses:

### Example curl
```bash
curl -X GET   'http://pocketbase:8090/api/collections/tg_users/records?page=1&perPage=1&filter=tg_id%20%3D%20%22181694388%22%20%26%26%20archived%20%3D%20false&skipTotal=1'   -H 'Content-Type: application/json'   -H 'Accept-Language: en-US'   -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA5NTMwNzMsImlkIjoieDg3aHA1cW5tczExeHp2IiwidHlwZSI6ImFkbWluIn0.IWUKu5wTinwTThggLhKWEWkVD9fhizySk27R3RksdUA'
```

###  Correct response:
```json
{"page":1,"perPage":1,"totalItems":-1,"totalPages":-1,"items":[{"active_session":"","age":26,"archived":false,"avatar":"","blocked_bot":false,"collectionId":"fuxmw2639udub6e","collectionName":"tg_users","created":"2024-10-05 00:20:15.422Z","credits":1,"first_name":"Amir","gender":"man","id":"ormn7gf8e60wagr","last_name":"","referral_campaign":"","referral_code":"WLWv3xNLWtth","referral_user":"","tg_id":"181694388","updated":"2024-10-05 00:29:57.595Z","username":""}]}
```
### 404
```json
{"code":404,"message":"The requested resource wasn't found.","data":{}}
```

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/a14a5c86-f868-4da8-be46-04297670da09">

**Comment by ganigeorgiev** [comment]
I don't think your issue is PocketBase related as I'm not able to reproduce it (testing both with the live demo and locally). We also have automated tests that should have failed if randomly the API started returning 404 errors.

I'm also using PocketBase in production with [Presentator](github.com/presentator/presentator) and from a quick glance at the logs I haven't experience such issue so far.

Double check:
- for reverse proxy misconfiguration/cache
- your custom hooks code (if you have any)
- the collections API rules

If you still  think that there is a PocketBase issue, feel free to provide clear reproducible steps and I'll try to have a look at it, but as of now it looks more like a client-side error and I'm not willing to waste time in a wild goose chase.

**Comment by ganigeorgiev** [comment]
Note that the 404 error could be also a side-effect of something else, for example failure to open a db connection due to reached file descriptors limit or other similar.

To help you debug it, you can try to start the executable with `--dev` and check the console logs for any additional information.

I'd also recommend to try to reproduce the issue by connecting directly to PocketBase (without Docker, nginx, etc.) to rule out environment misconfiguration.
