### ISSUE TITLE
downloading backup by admin results in code 403

### ISSUE THREAD

**Issue by Gys** [pocketbase/pocketbase#5613]
Hi

My server runs Pocketbase v0.22.21. I want to download backups using the API. So first I login as admin, get a token, use the token to create a backup, list all backups to find the latest and finally download the latest one. Everything seems to work, but the downloaded <backup name>.zip only has this text as its contents: `{"code":403,"message":"Insufficient permissions to access the resource.","data":{}}`. If I do the same with curl then indeed I get that text as reply. I was expecting the zipped data. So what could go wrong here?

This is my download function:
````
func (c *Client) downloadBackup(filename string) error {
	req, _ := http.NewRequest("GET", baseURL+"/api/backups/"+filename, nil)
	req.Header.Set("Authorization", c.token)
	resp, err := c.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	out, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, resp.Body)
	return err
}
````

**Comment by ganigeorgiev** [comment]
This is not documented very well at the moment but you need to issue a short-lived admin file token (_this is because the `Authorization` header cannot be added with the GET request when accessing directly the url in the browser_). The same apply for downloading [Protected files](https://pocketbase.io/docs/files-handling/#protected-files).

You can check the SDK example in https://pocketbase.io/docs/api-backups/#download-backup.

For the file token generation API you can check https://pocketbase.io/docs/api-files/#generate-protected-file-token.

**Comment by Gys** [comment]
Thank you very much for the explanation! Sorry that I missed it, did not look at the SDK example.
