### ISSUE TITLE
Feature Request: Implement Realtime API for View Collections

### ISSUE THREAD

**Issue by vsnshanmuganathan** [pocketbase/pocketbase#5634]
The Realtime API is currently available for Auth and Base collections, but it is not supported for View type collections. We have implemented some queries for various purposes in View type collections. Could you please consider adding Realtime support for View type collections as well?

**Comment by ganigeorgiev** [comment]
There are no plans for this because it is not clear how it will work.

Views don't have create, update, delete record operations so there are no realtime events for them.
A view query could be practically anything, including a simple expression such as `SELECT 1 as id`.

If you or somebody else have a clear idea how this could be implemented, feel free to outline it and I may reconsider it, but for now this remains out of the scope.
