### ISSUE TITLE
Feature request: Full database encryption

### ISSUE THREAD

**Issue by ibilux** [pocketbase/pocketbase#5637]
Pocketbase is great, and a lot of developers (including me) my used in self-hosted environment on a local PC, where the database file is accessible by others.
It would be great if the database file is encrypted so it won't be edited by someone who my access the physical host or PC.

[SQLite Encryption Extension](https://www.sqlite.org/see/doc/trunk/www/readme.wiki)

**Comment by ganigeorgiev** [comment]
For now there are no plans for this out of the box as it is difficult to make it portable and mantain.

With the upcoming PocketBase v0.23.0 users will be able to define their own custom `database/sql` SQLite driver or custom SQLite build like [go-sqlcipher](https://github.com/mutecomm/go-sqlcipher) if they want to (see https://github.com/pocketbase/pocketbase/discussions/5611).

**Comment by ibilux** [comment]
hello @ganigeorgiev, does the solution you provided above about "custom database/sql SQLite driver" require rebuilding the binaries of pocketbase from source ?

**Comment by ganigeorgiev** [comment]
You need to add the custom driver as Go code, so Yes, you have to build your own binary. 
PocketBase is distributed as regular [Go package](https://pkg.go.dev/github.com/pocketbase/pocketbase), so you don't need to maintain a fork, if that is your concern and updates are managed through the standard `go` tools like any other dependency.

Note that most SQLite drivers (including `go-sqlcipher`) relies on CGO which could make portability/cross-platform builds an issue because the generated executable by default will be dynamically linked and will work only on the platform/OS that you've used to built it on.

**Comment by ibilux** [comment]
@ganigeorgiev thank u very much for the clarification.
