### ISSUE TITLE
Python Client?

### ISSUE THREAD

**Issue by mordy-python** [pocketbase/pocketbase#564]
Are there any plans for a python client for pocketbase in the near future?

**Comment by ganigeorgiev** [comment]
Currently there are no plans for other SDKs. Once we reach a more stable version, I may consider it since it was requested several times already. Community contributions are also welcomed (_please note that if you are planning to work on this, there will be some minor breaking changes in v0.8.0 due the the users management refactoring_).

You could also check this discussion - https://github.com/pocketbase/pocketbase/discussions/391.

**Comment by dannickstark** [comment]
I founded this project: https://github.com/vaphes/pocketbase

It could be interesting
