### ISSUE TITLE
Impossible to change the admin's password

### ISSUE THREAD

**Issue by ThomasGysemans** [pocketbase/pocketbase#5640]
I have setup a PocketBase database a while ago and I wanted to go back to it and connect to the admin dashboard. Unfortunately I forgot the password, I have absolutely no clue what it could be. I tried this:

```bash
cd ~/myproject/pb_data
sqlite3 data.db 'UPDATE _admins SET passwordHash="$2a$10$xWbkSks7OiTmrri2DU6QSe6OAekcdqkOrkcI1wi4uiv9SU2HTlHoq" where email="myemail@gmail.com"'
```

From: https://www.programonaut.com/how-to-reset-the-admin-account-in-pocketbase/#db

The command above should change the password to `123456`.

When I do a "select" SQL command, i can see the password hash has changed, but when I try and connect in the admin dashboard, it doesn't work.

When I try and reset the password from the UI by receiving an email, it doesn't work. I'm not receiving the mail.

How can I reset the password please ?

**Comment by ganigeorgiev** [comment]
The above command should work as long as you are using the specified email is correct.

But as mentioned in your [earlier commented issue](https://github.com/pocketbase/pocketbase/discussions/2496), with PocketBase v0.16+ there is a dedicated command to change the admin password:

```
./pocketbase admin update myemail@gmail.com 1234567890
```
> When I try and reset the password from the UI by receiving an email, it doesn't work. I'm not receiving the mail.

This is because most likely you haven't enable the SMTP configuration.

More than this I don't think I can help you because this neither a but with PocketBase, nor I have access to your environment.

**Comment by ThomasGysemans** [comment]
I forgot to mention it @ganigeorgiev but the ./pocketbase admin command doesn't work either. Well, the command is successful, but i still cannot connect to my pocketbase account.

**Comment by ThomasGysemans** [comment]
Okayyy so I fixed my issue. Basically, I was trying the `sqlite3` command in the wrong folder... If someone does the same mistake than me someday, then here's what I did to fix it :

```bash
# assuming the pocketbase executable is in /opt/pocketbase:
cd /opt/pocketbase/myproject/pb_data
# if sqlite3 is not already installed:
sudo apt-get install sqlite3
# sets the password to 123456 for a given email
sudo sqlite3 data.db 'UPDATE _admins SET passwordHash="$2a$10$xWbkSks7OiTmrri2DU6QSe6OAekcdqkOrkcI1wi4uiv9SU2HTlHoq" where email="myemail@gmail.com"'
```

**Comment by ganigeorgiev** [comment]
Again, the raw setting a hash is not needed with PocketBase v0.16+.

The `admin` command works because I just verified it locally and we also have automated tests for it - https://github.com/pocketbase/pocketbase/blob/master/cmd/admin_test.go#L91.

It doesn't work in your case because most likely you didn't run the executable against the correct `pb_data` directory.
