### ISSUE TITLE
Proposal:  global context of the app

### ISSUE THREAD

**Issue by axshor** [pocketbase/pocketbase#5698]
Is there a application level context? 
in my case I need a k/v db to persistent data, where is the best place to keep the reference of the db. thanks.

**Comment by ganigeorgiev** [comment]
I'm sorry but it is not clear what you are asking or trying to do.

Please don't treat the issues tracker and discussions as some low-effort chat and try to clearly elaborate on your use case and problem in a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions).

**Comment by toby1991** [comment]
I have the same question:

If I have a global configuration or some single instance like db, redis that need to access in the whole app lifecycle, for example:

* I want to use redis in the http handler
* I need get a custom configuration from the Viper in the cron

So I think `core.App` is the global instance which used by PocketBase by many situation, but I cannot add custom configuration or instance into `core.Settings`, which used to initialize PocketBase.

So if we could add a global `Context`, which may included in `core.App`, that will be better~

**Comment by ganigeorgiev** [comment]
@toby1991 No sorry, it is not clear  what are these global configurations or why do you have a need for Redis in the first place.

There are no plans to introduce `context.Context` field as part of the `core.App` because it doesn't make much sense to me.

If you want a shared state to plumb user-defined options, then you can use [`app.Store()`](https://pocketbase.io/docs/go-miscellaneous/#app-store).

Another alternative of course could be to create a wrapper struct that embeds the PocketBase `core.App` but again, it is not clear what actually you are asking or trying to do (_see [XY problem](https://xyproblem.info/)_). Feel free to elaborate but for now this remains out of the scope.
