### ISSUE TITLE
Backrelation expansion does not work properly in with list getter methods

### ISSUE THREAD

**Issue by devmonster123** [pocketbase/pocketbase#5710]
I am using the Javascript client to expand back relations.  I have noticed that if I use the get*List methods, the back relations do not expand however if I use the getOne and use the same expand it works. Only back relation to one of the collections works and I have made sure that all the API rules and index settings are the same between them.

This does not work:
```
const result = await pb.collection("user_profile").getList(1, 1, {
  filter: "user.username = 'apollo'",
  expand: "user_availability_via_user_profile",
});
```

This works:
```
  const result = await pb
    .collection("user_profile")
    .getOne("6425nwxsn66jmm8", {
      expand: "user_availability_via_user_profile",
    });
```

The user_availability has a relation to user_profile but not the other way around. I have other collections similar to user_availability.

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it. I've just tested it locally and on the live demo and it works correctly for me.

Make sure that for both requests your client satisfies the View API rule of the expanded collection.

Another possible common reasons why this may not work:
- error in custom hooks code
- external cache (common if use Next.js because they have custom `fetch` implementation enabled by default)

For the latter, I recommend to test the requests directly against PocketBase to rule out 3rd party misconfiguration, either with curl or add a plain `pb_public/index.html`:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        your requests...
    </script>
</body>
</html>
```

Open your browser and navigate to `http://127.0.0.1:8090` and test it.

If you still think that there is a PocketBase issue, please provide a minimal reproducible example + export of your collections configuration as json (Admin UI > Settings > Export collections) and I'll try to have a look at it.

**Comment by devmonster123** [comment]
@ganigeorgiev Thanks for the prompt reply. It magically started working so I am assuming this was related to Next.js caching. I will let you know with more info if it happens again.

**Comment by ganigeorgiev** [comment]
Please make sure to read https://github.com/pocketbase/pocketbase/discussions/5313.
