### ISSUE TITLE
feature request: @ macros for rules

### ISSUE THREAD

**Issue by 5P5** [pocketbase/pocketbase#5739]
I frequently find myself having to write exact duplicate rules for the _List/Search Rule_ and _View Rule_.

<details>
<summary>
am I missing something here??
</summary>

I suppose I could do `pb.collection('posts').getFirstListItem('id="RECORD_ID"', {` and just have a _List/Search Rule_

instead of `pb.collection('posts').getOne('RECORD_ID', {` which needs a separate _View Rule_

that seems a bit hacky??
</details>

In those cases It would be great to have macros for referencing a rule, like:
```
@listRule
@viewRule
@createRule
@updateRule
@deleteRule
```

So I could just specify a complicated and long _List/Search Rule_
and have the same values in _View Rule_ with `@listRule`.

<hr>

Another option would be to implicitly inherit the _List/Search Rule_ in case of empty _View Rule_, 
tho I think rules should be explicit :/
 so macro would be better :)

**Comment by ganigeorgiev** [comment]
No, sorry. I think it will complicate unnecessary too many things and for now remains out of the scope.

**Comment by ganigeorgiev** [comment]
The [existing macros](https://pocketbase.io/docs/api-rules-and-filters/#-macros) like `@now`, `@todayStart`, etc. are just placeholders for a single dynamic/computed value. The computed value has no relation to anything else from the collection other than the current time, which is globally accessible.

As mentioned earlier, I'm against introducing macros referencing an entire rule because it could complicate a lot of things, just to mention some:

- it changes the `OPERAND OPERATOR OPERAND` semantics of the API rules syntax
- it will require extra validation and parsing to prevent cyclic references (e.g. `List rule: @viewRule` and `View rule: @listRule`)
- individual rule will not be able to be used on its own because it could have dependency on other rules to which we may not always have access
- we will no longer have a quick check for admins/superusers only (or at least not a direct one)

I'm most likely missing other minor issues that this could cause at the moment but my main point remains - it introduces a lot of complications for very little to none benefit.

There was another suggestion for combining and grouping API rules via "actions" (e.g. inverse the rule - operation(s) relation) and it exists somewhere buried in my never ending todo to consider eventually in the future but for now remains out of the scope for v1.
