### ISSUE TITLE
[v0.23.0-rc] Unable to Recreate Collection with Original Name After Renaming – Error "Failed to create collection."

### ISSUE THREAD

**Issue by uteminhduc** [pocketbase/pocketbase#5741]
I'm using PocketBase version `v0.23.0-rc8`. When I create a collection named "a" and then rename it to "b", I encounter an issue if I attempt to create a new collection with the original name "a" afterward.

**Steps to Reproduce:**

- Create a collection named "a".
- Rename the collection from "a" to "b".
- Attempt to create a new collection with the name "a".

**Expected Result:**
A new collection with the name "a" should be created successfully.

**Actual Result:**
The following error occurs:

```json
{
  "data": {
    "id": "The model id is invalid or already exists."
  },
  "raw": "id: The model id is invalid or already exists.."
}
```

**Additional Context:**
It appears that renaming the collection does not free up the original name for reuse, resulting in a conflict when attempting to create a new collection with the same name.

**Comment by ganigeorgiev** [comment]
Hm, this is a side-effect of the new autogenerated crc32 checksum of the id (since both collection have the same name during create their id would be the same).

I'm not sure what would be the solution here but I may end up removing the crc32 generation entirely. I'll have to think a little more on it.

**Comment by ganigeorgiev** [comment]
I've submitted a "fix" in the `develop` branch and reverted the old functionality to use a random string as id for non-system collections and fields (_for the system collection fields should be safe because they are not allowed to be renamed/deleted_).

The crc32 name checksum was introduced mostly because:
- to make tests easier because the id is predictable and you can compare a new collection/field directly without accounting for the randomness
- to partially minimize eventual conflicts if users attempts to import collections from different projects/environment (aka. when there is more than source of truth for the database schema) but even then it doesn't always guarantee conflict-free resolution so it's not really that helpful here.

In any case, the id value doesn't really matter - it needs only to be a unique identifier that cannot be changed.

**Comment by ganigeorgiev** [comment]
_Just for info in case someone stumble here:_

On second thought, the randomness of the collection and field ids actually may not be a good idea because it could results in conflicts when manual typed migrations are combined with full snapshots.

The same issue actually exists in <= v0.22.x but changing the Collection model and Fields is not an option there since it will be too large of a breaking change.

I'll have to think a little more on it before the final v0.23.0 release as I'm not sure how to proceed yet.

**Comment by ganigeorgiev** [comment]
I've pushed another update that reverted the crc32 checksum but now we perform additional check for duplicated ids and append a counter in case such is found. It ended up complicating the internal more than I wanted to but for now it is the best option I could think of to have a deterministic default id value.
