### ISSUE TITLE
How can I access app / CollectionUpsertForm within a migration?

### ISSUE THREAD

**Issue by J7mbo** [pocketbase/pocketbase#5742]
I have a migration file, the default for which contains:

```javascript
migrate((db) => {

}, (db) => {

})
```

Looking at the documentation [here](https://pocketbase.io/docs/js-collections/#create-new-collection-with-data-validations) for creating a new collection with validations, there are references to an `$app` variable.

I believe that I need this so that I can run:

```javascript
new CollectionUpsertForm($app, collection)
```

Currently, I believe `$app` may not exist here? Or at least, `CollectionUpsertForm` does not:

```bash
Failed to apply migration 1730198216_create.js: ReferenceError: CollectionUpsertForm is not defined at <eval>:5:22(4)
```

So my question is, how can I use `CollectionUpsertForm` and `$app` here correctly within this migration file?

---

For the _why_ behind why I want to do this, I noticed that when creating a migration file locally that contains a relation to the users table, then uploading this file to the production server, the migration would not run successfully because it would have a problem with the relation. Even though the relation is on the table id: `_pb_users_auth_` which is exactly the same in both environments (my local machine and production).

The only way I solved this was to create the migration file on the production server by doing it via the UI, and then downloading it and running it on my local machine, which did work.

So instead of doing that, I wonder if it's possible to make sure the migration will work by creating with data validations locally.

**Comment by ganigeorgiev** [comment]
I don't understand what actually is the issue you are trying to describe but you can't access the form or the app instance as part of the migrations at the moment.

This will change with the upcoming v0.23.0 release (_there are no ETAs yet_) where all forms are essentially removed or no longer required since they are replaced with the more generic `app.Save()`/`app.SaveNoValidate()` (see https://github.com/pocketbase/pocketbase/discussions/4355; for all v0.23.0 changes you could refer to the [`develop` branch CHANGELOG](https://github.com/pocketbase/pocketbase/blob/develop/CHANGELOG.md) or the [tagged releases notes](https://github.com/pocketbase/pocketbase/releases)).

For other questions please use the [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) instead as the thereaded format is more suitable for this type of posts.
