### ISSUE TITLE
v0.23.0-rc8: event hooks not running on auth collection

### ISSUE THREAD

**Issue by Sleepful** [pocketbase/pocketbase#5795]
On the client I am updating a collection:
```ts
// here the record.collectionName is a Users auth collection
    const record = await pb.collection(authVal.record.collectionName).update(authVal.record.id, {
      name
    });
```
On the server I a trying to log this update request:
```go
	app.OnCollectionUpdateRequest().BindFunc(func(e *core.CollectionRequestEvent) error {
		app.Logger().Info("Hook for CollectionUpdateRequest")
		fmt.Printf("%#v\n", e.Request.Header)

		return e.Next()
	})
```

```go
	app.OnRecordUpdateRequest(core.CollectionNameSuperusers).BindFunc(func(e *core.RecordRequestEvent) error {
		app.Logger().Info("Hook for RecordUpdateRequest")
		fmt.Printf("%#v\n", e.Request.Header)
		if err := e.Next(); err != nil {
			return err
		}
```
Neither of these gets logged

**Comment by Sleepful** [comment]
`OnRecordUpdate` seems to work but it doesn't include the HTTP context

```go
	app.OnRecordUpdate().BindFunc(func(e *core.RecordEvent) error {
		app.Logger().Info("Record update...")
		// cannot get http headers from this type :(
		// fmt.Printf("%#v\n", e.Context.Value())
		return e.Next()
	})
```

**Comment by ganigeorgiev** [comment]
I'm confused and not sure that I understand what you are trying to do but we have multiple integration API tests that verify that the correct hooks are fired.

`OnCollection*` hooks fire when making Collection model changes (e.g. changing fields).

`OnRecord*` hooks fire when making Record model changes but in your case it doesn't fire because you have specified the superuser tag (aka. it will fire **only** when a `_superusers` record is changed). You need to either remove the tag or specify the name of the targeted record collection.

Regarding your followup question - only `*Request` suffixed hooks have information about the request context, in your case that would be [`app.OnRecordUpdateRequest`](https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.23.0-rc9/core#BaseApp.OnRecordUpdateRequest). To read a request header from that hook you can call `e.Request.Header.Get("Some-Header")`.

In any case, please don't open issues like this. Prefer the Q&A discussions instead and try to clearly elaborate what actually you are trying to do to avoid the needless back-and-forth (see [XY problem](https://xyproblem.info/)).

**Comment by Sleepful** [comment]
Oh, thank you so much, I had to `remove the superuser tag` indeed. My bad, I missed that bit and thought I found a bug!
