### ISSUE TITLE
Object has no member 'findCollectionByNameOrId'

### ISSUE THREAD

**Issue by weeebdev** [pocketbase/pocketbase#5811]
```
TypeError: Object has no member 'findCollectionByNameOrId' at <eval>:95:59(52)
```
Even though I used it correctly:
```js
  const problemSubmissions = $app.dao().findCollectionByNameOrId("problem_submissions");
```

`$app.dao()` works correctly, e.g. `$app.dao().findRecordById` is fine.

**Comment by ganigeorgiev** [comment]
It is working correctly for me. I'm not sure how to reproduce it.

Make sure that you are calling `$app.dao()` after application bootstrap, otherwise `$app.dao()` would be null.

If you still think that it is a PocketBase issue, please provide a more complete code sample and I'll try to investigate it.
