### ISSUE TITLE
Errors parsing go.mod

### ISSUE THREAD

**Issue by chnfyi** [pocketbase/pocketbase#5830]
In v0.22.23 i got `go.mod:3: invalid go version '1.22.0': must match format 1.23` on `go test`.

Go directive should be `go 1.22` instead of `go 1.22.0` format.

**Comment by ganigeorgiev** [comment]
That's strange because neither locally, nor the GitHub CI complain about it.

Could you provide the exact steps that can trigger it?

**Comment by ganigeorgiev** [comment]
Seems similar to https://github.com/golang/go/issues/61888#issuecomment-1716987059.

Make sure to update your gopls version.

**Comment by ganigeorgiev** [comment]
I'm closing it because I think it is the same.

Make sure to update to Go 1.22+. If you still are not able to resolve it, feel free to provide more details about your setup and I'll try to investigate it but note also that the message has changed in Go 1.21+ to the current format per https://go-review.googlesource.com/c/mod/+/527897/2/modfile/rule.go.

**Comment by chnfyi** [comment]
Yes, it works with an up-to-date Go version.

My bad ! The issue happened on a computer with limited support to Go 1.21 or earlier. I checked go.mod v0.22.23 history and v0.23.0rc and i wrongly assumed that the accepted format was still `1.20`.
