### ISSUE TITLE
Insanse backup size for a small database

### ISSUE THREAD

**Issue by bloor** [pocketbase/pocketbase#5882]
PocketBase v0.22.12

I suddenly could not access my pb instance. 
After few hours of debugging between hosting and cloduflare, i narrowed it down to db being corrupted or something (i cannot access it to verify).
I downloaded the 700MB backup from S3 unzipped it and VOILA!

![image](https://github.com/user-attachments/assets/6340504e-b129-444f-af99-57e2c9d20119)

Tried to open the file and it seems it has tons of empty spaces. Which explains how 13GB file got zipped to 700 MB.
![image](https://github.com/user-attachments/assets/7c1c0c31-ee6b-46f3-8fbb-ce8d53827e90)

I don't know what happened. I can take into account even vulnerability / security / hack attempt. I might have such "fans" on the project.
Will try to use one of the older 7days backups.. this one obviously unusable and done.

![image](https://github.com/user-attachments/assets/89fc5fa0-8a8d-462c-a7af-2a091d2a1ae4)
LE: all my auto-backups are corrupted.

Also, 
![image](https://github.com/user-attachments/assets/20a88f3a-766e-46bc-944c-126b97c1803c)

**Comment by bloor** [comment]
Ok, somehow (since I was using S3 and did not have to manually upload the backup) .. I could restore one of the backups.
Everything seems normal.. any ideas what to debug !?

**Comment by ganigeorgiev** [comment]
@bloor Before making bold statements like "insane" and that something is corrupted it will help to provide an error illustrating that. The side-car `-wal` file is not a plain text and I'm not sure what exactly do you expect to see as a content.

In any case, what actually is the problem - the backup size?

The WAL file could grow if there is a blocking transaction, as it is the case with the backup operation:
> https://www.sqlite.org/wal.html
> A checkpoint can only complete when no other transactions are running, which means the WAL file cannot be reset in the middle of a write transaction. So a large change to a large database might result in a large WAL file. The WAL file will be checkpointed once the write transaction completes (assuming there are no other readers blocking it) but in the meantime, the file can grow very big.

This unfortunately is a limitation of both the current SQLite WAL implementation (_there was attempt to fix it in [WAL2](https://sqlite.org/cgi/src/doc/wal2/doc/wal2.md) but the effort exist only as experimental SQLite trunk/branch_) and how the PocketBase backups work (during backup the application is in "read-only" mode and writes are blocked).

For the latter part, there are plans to optimize it together with https://github.com/pocketbase/pocketbase/issues/4647 but remains for later consideration because it has a lot of edge cases and I don't want to block further v0.23.0 release.

If the current backups implementation causes you trouble, you can simply disable them and chose a different backup strategy, e.g. running `sqlite3 .backup` command + rsync (_you can find an example script in https://github.com/pocketbase/pocketbase/discussions/4254; while more performant note that this has the limitation that the db file is not locked with the storage changes meaning that during the db backup generation there could be storage files that were removed or added_).

I also strongly recommend to update your PocketBase executable to v0.22.25 because there were several fixes since v0.22.12 (including a security one related to the OAuth2 email autolinking). For more details, please check the v0.22.x [CHANGELOG](https://github.com/pocketbase/pocketbase/blob/master/CHANGELOG.md) (_technically big jump with just `./pocketbase update` should be safe in this case but make sure to test it first locally and to have a recent backup for just in case_).

If the above doesn't help, please elaborate more clearly what actually is the issue but for now there is nothing much I can help you further with.

**Comment by ganigeorgiev** [comment]
I've pushed a small update in [v0.22.26](https://github.com/pocketbase/pocketbase/releases/tag/v0.22.26) that performs manual checkpoints and eventually help with the accumulated data of the `-wal` file(s) but again as mentioned above the WAL files can grow if there are blocking transactions and it just how the current backup implementation works.

**Comment by bloor** [comment]
Well, good to know, but as you can see manual backups acts ok. 55MB or ~130MB if I add 2days logs retention.
![image](https://github.com/user-attachments/assets/ebac0189-d6b4-4fbd-bff0-e5945dc8c64f)

Still 700MB for my tiny project ?! And from the printscreens above you can see the autobackup was on a constant size increase. Even though the db usage was fairly constant and Logs Settings is set for 2 days retention. Basically it unknowingly grew from 130MB to 700MB in ~3months (and then it crashed).

Not a DB guru, don't know how WALS work, but having 12 GB WAL for a ~10MB of data (if u exclude the few thumbnails from backup file) seems unreasonable. 

But in my case, something happened and the whole pocketbase instance crashed and was 100% all my 6 vCPUs.
I restarted server, service etc.. the only way it worked was to install a fresh pb instance and use the backups.
So obviously the issue was somewhere lying in the database itself. Something was throttling process even after several restarts.

I will update the version. Again, my attempt was to find out what happened, so it doesn't happen again.

**Comment by ganigeorgiev** [comment]
Please update to the latest version and test again.

**Comment by bloor** [comment]
After updating version it seems the backup is **no longer increasing "randomly" in size**
![image](https://github.com/user-attachments/assets/9694eac6-f362-4fa7-b78a-1754f23b9783)
