### ISSUE TITLE
SSE Delete and Create Events Not Triggered for Auth Collection in PocketBase

### ISSUE THREAD

**Issue by corentin59** [pocketbase/pocketbase#5898]
**Description**
I am experiencing an issue with PocketBase's SSE (Server-Sent Events). Specifically, the delete and create events are not being intercepted, while update events are working as expected.

I am subscribing to events using the following endpoint:

`/api/realtime/` (COLLECTION_ID/RECORD_ID)

The collection in question is of type Auth. When a record is updated, I receive the event notification correctly. However, when I delete or create a record, I do not receive any corresponding SSE events.

**Authentication Context**
I am authenticated as a regular user (via login/password) and not as a super-admin.

**Rules Configuration**
The collection has the following rule set for record access:

`@request.auth.id = id`

**Steps to Reproduce**

1. Set up a PocketBase server with an Auth collection.
2. Apply the rule @request.auth.id = id to restrict access.
3. Authenticate as a regular user (via login/password).
4. Subscribe to SSE for a specific record using the endpoint realtime
5. Perform the following operations on the subscribed record:
- Update the record (event received as expected).
- Delete the record (no event received).
- Create a new record with same id (no event received).

**Expected Behavior**
Receive SSE event notifications for all create, update, and delete operations on the specified record or collection.

**Actual Behavior**

- Only update events trigger SSE notifications.
- delete and create events do not trigger any SSE notifications.

**Additional Context**
The rule @request.auth.id = id might be affecting the behavior, but the expectation is that events should still be sent when the rule applies.

Thx a lot !

**Comment by ganigeorgiev** [comment]
For the create action is expected because the user was deleted and the realtime connection has lost its old auth state (it could be even considered a security issue if we allow deleted users to continue their session).

For the delete action the situation is slightly different and technically what you are experiencing is intended behavior (see https://github.com/pocketbase/pocketbase/blob/671a6a3aed7816fa5b566f4feea9ee69d8b0aa11/apis/realtime.go#L241), but there is currently one problem as it is implemented because we remove the client but doesn't notify the connection about it (_it will be closed automatically after the idle timeout or when the user close it from their end_). I'll consider later today or tomorrow to experiment and make an exception for the delete and will consider clearing only the auth state from the client and preserve the connection so that they can receive an event for it, aka. it will be converted to a "guest" connection after the delete event.

**Comment by corentin59** [comment]
Thank you for your prompt response and for taking the time to explain the situation.

The proposed solution would definitely address my use case: in case of deletion, either being disconnected or, ideally, notified of the event would be perfect.

**Comment by ganigeorgiev** [comment]
I've pushed a small fix in [v0.22.27](https://github.com/pocketbase/pocketbase/issues/5898) and the deleted user should be able to receive the `delete` event.

I'll apply the change tomorrow in the `develop` branch too.
