### ISSUE TITLE
Getting deprecation warning on JsonSerializable

### ISSUE THREAD

**Issue by PROTAG0N1ST** [pocketbase/pocketbase#5946]
Getting deprecation warning on JsonSerializable autogenerator code on Dart `SDK v0.19.0`

## app_model.dart
![image](https://github.com/user-attachments/assets/60753b0d-ac99-4db1-a04a-e8f8ff8ff85e)
## app_model.g.dart
![image](https://github.com/user-attachments/assets/ca16b19f-4e77-4f0c-a460-68c562f196fc)

**Comment by ganigeorgiev** [comment]
You can ignore it for now. I'll consider with the next minor Dart SDK release to exclude it with annotation.

If you stumble on something else related to the Dart SDK, please submit it at https://github.com/pocketbase/dart-sdk.

**Comment by ganigeorgiev** [comment]
_As a side-note, I'm not sure that I can recommend extending the `RecordModel` the way how it is shown in the screenshot (_I'm not sure that I understand the desired behavior either_) since practically a single instance of the `App` class will have both the `RecordModel` and the `App` values, meaning that you may ended up with out of sync field values (e.g. `App.version` could ended up having a different value from `RecordModel.get("version")`)._

**Comment by ganigeorgiev** [comment]
I've pushed a small update in [Dart SDK v0.19.1](https://pub.dev/packages/pocketbase) that should exclude the deprecated field from the parent serialization (_you'll have to rerun the build runner_).

But again, based only on the screenshots and without any other context the above usage of the RecordModel doesn't really make sense to me and I'd advice either keep your custom `App` class as simple DTO (aka. without extend) or if for some reason you need to extend the `RecordModel`, prefer replacing your properties with get/set pair reading from `RecordModel.get/set`.
