### ISSUE TITLE
failed when I upgrade to v0.23.1

### ISSUE THREAD

**Issue by franklili3** [pocketbase/pocketbase#5956]
platform: render.com
os: linux
data path:/var/data
When I sync fork on my fork repo, redeployed on render.com, there is error:

>  ==> Deploying...
> ==> No open ports detected, continuing to scan...
> ==> Docs on specifying a port: https://render.com/docs/web-services#port-binding
> ==> Running './base serve --http="0.0.0.0:10000" --dir /var/data'
> 2024/11/25 22:28:13 Failed to apply migration 1717233556_v0.23_migrate.go: migrated collection "portfolio_cum_returns_month" validation failure: fields: (1: (name: cannot be blank.).).
> ==> Exited with status 1
> ==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys
> ==> Running './base serve --http="0.0.0.0:10000" --dir /var/data'
> 2024/11/25 22:28:16 Failed to apply migration 1717233556_v0.23_migrate.go: migrated collection "portfolio_cum_returns_month" validation failure: fields: (1: (name: cannot be blank.).).
How can I do?

**Comment by ganigeorgiev** [comment]
The migration error indicates that you have an existing collection (`portfolio_cum_returns_month`) with invalid fields definition (it seems that you have previously inserted a field without a name, which was possible if you had custom migrations because in v0.22.x Dao operations didn't perform validations, which is no longer the case with v0.23). Or in other words, check your existing collection definitions and make sure that they comply with the validators.

If you need further help, please open a [Q&A discussions](https://github.com/pocketbase/pocketbase/discussions) as the threaded format is more suitable for this type of posts, and export your original collections configuration as json (Dashboard > Settings > Export collections).
