### ISSUE TITLE
Iso8601 time strings work when creating and saving but not when filtering.

### ISSUE THREAD

**Issue by jeffmikels** [pocketbase/pocketbase#602]
Using iso8601 time strings for dates is pretty standard, and they are processed as expected when creating and saving records.

However, when filtering on a date field, they fail to produce an expected result.

Replication steps

- Create a record with a date field named `event_day`.
- Save the value `2022-09-21T12:00:00.000` to that field, and the time is properly parsed.
- Now perform a filter using the exact same time string and receive no results.
- Now perform a filter request using `2022-09-21 12:00:00` and receive the result.

Expected result:

Saving and filtering should understand the same number formats.

**Comment by ganigeorgiev** [comment]
We are normalizing and trying to cast the submitted dates so that internally they are always saved in the following layout [`2006-01-02 15:04:05.000`](https://github.com/pocketbase/pocketbase/blob/master/tools/types/datetime.go#L12) and that is the proper date format when you submit a datetime value (outside of godocs, it is not documented at the moment).

I may consider in the future making the filter parser a little more smarter and detect the expression context, so that it can "normalize" the user string when comparing to a date field (currently it doesn't support "look-around" type of parsing).

**Comment by jeffmikels** [comment]
My report wasn't a feature request. It was a bug report. Using the T separator is currently supported when doing a create or update operation, but is not supported in filter strings. I think the same date parsing code should be used in both filter operations and in create and update operations.

**Comment by ganigeorgiev** [comment]
@jeffmikels Hi, as mentioned, when submitting user data we are normalizing them to the correct internal value. That is also true even if you try to submit `null` (PocketBase record fields don't have null values). So, if you submit a date in an ISO8601 formats, we have 2 options - either throw an error or try to normalize the submitted value (if it is safe and non-ambiguous). The filter check is consistent with what is actually stored (and returned) for the record.

Supporting the same kind of "normalizations" in the filters, requires a smarter parsing than what we currently do in [`fexpr`](https://github.com/ganigeorgiev/fexpr) (eg. lookaround/lookahead checks, expressions context, etc.). I have it in my todo to research how difficult it would be and whether there will be any performance impact and it may be added in the future, but for now this is out of the scope for v1.0.0.

btw. The stored datetime format will change in v0.8.0 to iso8601 (kind of; instead of `T` as separator we will use space; see https://github.com/pocketbase/pocketbase/issues/472#issuecomment-1255056640)

**Comment by spance** [comment]
@ganigeorgiev  You enjoy RFC standards, and others may have a preference for ISO standards. Instead of asking why others should adapt to one choice, wouldn’t it be wonderful to provide users with the option to decide for themselves?
