### ISSUE TITLE
Documentation Extend with JS is WRONG

### ISSUE THREAD

**Issue by pafr-zyata** [pocketbase/pocketbase#6026]
In the Documentation ExtendWithJS, specifically the Hooks section contains broken examples:

https://pocketbase.io/docs/js-sending-emails/

The example states on line 9:
```js
to:      [{address: e.record.email()}],
```

This leads to an error:
Object has no member 'email'

Now I also tried:
```js
to:      [{address: e.record.email}],
```

Which leads to an empty to:

The correct way, as I found out the hard way is in hooks:
```js
to:      [{address: e.record.get("email")}],
```

Then the hook works fine. It would be awesome if you could fix the examples, to reflect the correct way to access the properties.

**Comment by ganigeorgiev** [comment]
I've just tested it locally with PoketBase v0.23.4 and I'm  not able to reproduce it. Both `e.record.email()` and `e.record.get("email")` should work.

Feel free to provide the full error and the codesample you are testing with I'll try to investigate it but as of now it seems correct to me.

**Comment by pafr-zyata** [comment]
I am also on v23.4, I tried the sending email example and it threw the error reported above.

System:
x86
Fedora 40

**Comment by pafr-zyata** [comment]
Dont know if this is relevant:

node v20.17.0

but I assume pocketbase has his own js interpreter?

**Comment by ganigeorgiev** [comment]
No, sorry it doesn't make sense.

Your code probably differ from the one in the examples (e.g. using different hook).

**Comment by ganigeorgiev** [comment]
The example is the docs is just that - an example. How you populate the `new Message` fields could vary from where you invoke it.

In the example it is shown that the the email is being sent after `users` create, meaning that in this case `e.record` refers to a user record. Depending on what hook you use you may not have `e.record` because each hook has its own different context when it is invoked. Please read the documentation, but again the example as it is is correct and this entire pointless back-and-forth could have been avoided if you just paste that you've tried.

In any case, for other questions please use the Q&A discussions as the threaded format is more suitable for this type of posts.

**Comment by pafr-zyata** [comment]
I guess I did not clearly comunicate what I did, I am sorry, let me clarify:

1. I went to the examples page
2. I copied and pasted the email example hook into pb_hooks/register.pb.js
3. Then I tried it

It did not get any data from e.record.email() it only got the data when I changed it to e.record.get("email").  No self written code, just plain copy the example.

**Comment by ganigeorgiev** [comment]
Again, I'm not able to reproduce it and it works correctly for me. `e.record.email()` literally calls `e.record.get("email")`. Both methods should return the same.

Either the error you are experiencing is from somewhere else or there is something else that you are not sharing regarding your setup, but in all cases without clear steps to reproduce I'm not willing to continue this back-and-forth or spend time on wild goose chase.
