### ISSUE TITLE
Consider exporting `AuthMethodsResponse`

### ISSUE THREAD

**Issue by benallfree** [pocketbase/pocketbase#6050]
I am updating https://github.com/pluja/pocketbase/pull/12 and encountered a test to list auth methods. Rather than [duplicating the AuthMethodsResponse struct](https://github.com/pluja/pocketbase/pull/12/files#diff-45de0bd4aaf95610331d821cef35a07e8d980d9a5f4a2e596e642b3fa48f7325R57-R107), it would be helpful if AuthMethodsResponse were public so we could reference it.

https://github.com/pocketbase/pocketbase/blob/844f18cac379fc749493dc4dd73638caa89167a1/apis/record_auth_methods.go#L52

**Comment by ganigeorgiev** [comment]
There are no plans for this as I want to be able to change the fields without introducing breaking changes (e.g. removing the legacy fields and methods) on multiple APIs.

Additionally I don't think it would be a good idea to import PocketBase into the linked package because you may ended up pulling too much unnecessary stuffs which will increase the build time and binary size of every program that imports the specific Go package.

**Comment by benallfree** [comment]
>  import PocketBase into the linked package

That's a good point, I didn't realize Go would link in code when only types were referenced.

> change the fields

Isn't it currently considered a public API though? It is the structure returned from a public API endpoint.

**Comment by ganigeorgiev** [comment]
It is public for the Web API consumers, but it is not public for those who use Go. For the Web we can remove the legacy fields safely after some period, but doing so will require also issuing a warning for the Go APIs which seems unnecessary to me.

**Comment by benallfree** [comment]
Yeah maybe this is a unique case, the above project is a Go client for the Web API so it can use the same structs.
