### ISSUE TITLE
Setting verified key on auth record is causing an error

### ISSUE THREAD

**Issue by kermage** [pocketbase/pocketbase#6051]
This works on v0.22.19

```js
onRecordBeforeCreateRequest((e) => {
	if (e.httpContext.get("admin")) {
		return;
	}

	// ...

	e.record.set("verified", true)
}, "users");
```

But not this on v0.23.4
```js
onRecordCreateRequest((e) => {
	if (e.hasSuperuserAuth()) {
		return e.next();
	}

	// ...

	e.record.set("verified", true)
	e.next();
}, "users");
```

The error produced
```json
{
    "data": {
        "verified": {
            "code": "validation_values_mismatch",
            "message": "Values don't match."
        }
    },
    "message": "Failed to create record.",
    "status": 400
}
```
![image](https://github.com/user-attachments/assets/4d5902a0-4d54-4fe3-ad6c-b57388d1b700)

**Comment by ganigeorgiev** [comment]
In v0.23 `onRecordCreateRequest` hook fires before the form request validations.

If you want to change the verified field you'll have to do it via one of the DB hooks, e.g. [`onRecordCreate`](https://pocketbase.io/docs/js-event-hooks/#onrecordcreate).

There are not enough details to understand why you need to manually set the `verified` field, but note that this could also have security implications, especially around the OAuth2 linking, I'd recommend against it unless you really know what you are doing.

For other questions, please use the Q&A discussions instead since the threaded format is more suitable for this type of posts.

**Comment by kermage** [comment]
Thank you for that information.

I simply followed your provided example here https://github.com/pocketbase/pocketbase/discussions/3786#discussioncomment-7612327

**Comment by ganigeorgiev** [comment]
That's fine but that doesn't change the fact what is written in the linked discussion.

If `verified` has no meaning in your context you can simply ignore the field, there is no need to change its value.

For why manually changing it could cause a security issue see https://github.com/pocketbase/pocketbase/security/advisories/GHSA-m93w-4fxv-r35v.

**Comment by kermage** [comment]
Noted. Thanks again for the very prompt responses.
