### ISSUE TITLE
Bug: Length of id check is broken on UI

### ISSUE THREAD

**Issue by sonovice** [pocketbase/pocketbase#6066]
Screenshots of giving a custom id to a new record:
![image](https://github.com/user-attachments/assets/f654b129-25d9-4d7c-8f69-ee58f91017a8)

![image](https://github.com/user-attachments/assets/321185c3-e9c2-4b19-82be-936161ce027e)

**Comment by ganigeorgiev** [comment]
What PocketBase version are you using?

**Comment by sonovice** [comment]
PocketBase v0.23.5

**Comment by ganigeorgiev** [comment]
I don't understand what actually is the bug here. Could you elaborate a little more what is the expected behavior?

**Comment by sonovice** [comment]
Sorry, it seemed obvious while submitting. If the ID is below 15 characters, it asks me to enter 15 _or more_ characters. However, more than 15 gives the other error message.

Also, the UI is inconsistent for "too many" and "not enough" characters.

**Comment by ganigeorgiev** [comment]
If you mean the error messages inconsistencies - then I guess we can improve it but this is not a bug. The error message is a server-side validation and the form popup is a browser one.

The difference regarding "less" vs "exactly" is because min/max validators just runs separately.

I'll consider eventually changing it with the next but again it works correctly for me.

**Comment by sonovice** [comment]
If the correct behavior is that there should be exactly 15 characters, than it works correctly but says something different in the UI if you put in more or less than 15 chars.

**Comment by ganigeorgiev** [comment]
I've pushed in `master` an update for the server validation error message to use "no more" instead of "less".

I've also added a `maxlength` attribute to the form field to prevent users from submitting more than the allowed characters but note that the default browser error message could still show the "X characters or more" message and I don't want to provide a custom client-side error message for this.

**Comment by sonovice** [comment]
Thanks so far! Maybe I misunderstand this, but shouldn't it just say "exactly 15 characters"?

**Comment by ganigeorgiev** [comment]
Again, the server min/max validations runs separately. We could make it to say "exactly X characters" but this will require special check in https://github.com/pocketbase/pocketbase/blob/9efd68ff4cb3e3dd39cd4f57c8ad747aafa3484a/core/field_text.go#L224-L237 just for the min=max case and it seems unnecessary for me.

**Comment by ganigeorgiev** [comment]
Just to clarify, the "X characters or more" message is the default browser one (it could differ depending on the used browser) and it is triggered based on the `minlength`/`maxlength` attributes.

**Comment by sonovice** [comment]
> the "X characters or more" message is the default browser one
Ah, that was my missing piece! Thank you!
