### ISSUE TITLE
Is there anyway to reasonably reset auth token during dev?

### ISSUE THREAD

**Issue by nicosql** [pocketbase/pocketbase#6069]
I like to pick and prod at this awesome project, not as a framework but just forking the entire project and messing around; but often the auth tokens will expire and even after a complete rebuild of the UI & Go app the *** ***** expired tokens still follow me around - does anybody know of a script or something to refresh?  

It is crazy annoying.  You can't even logout when this happens, the whole UI just appears to become a dead canvas.

**Comment by ganigeorgiev** [comment]
There is definitely something wrong with your setup but without a clear reproducible steps to reproduce I don't think anyone will be able to help you (for all I know what you are expericing could be a browser extension issue).

In any case, the issues tracker is not the place for this type of posts. Feel free to open a [Q&A discussion](https://github.com/pocketbase/pocketbase/discussions) but please don't treat the discussions as llm chat and try to clearly elaborate on your setup so that others can reproduce it (e.g. on what environment, how you are testing, do you have reverse proxy, docker, etc.).
