### ISSUE TITLE
Allow to make field names human-readable 

### ISSUE THREAD

**Issue by sgtpep** [pocketbase/pocketbase#61]
It would be nice to see more human-readable field names in tables and forms, other than in the camelCase format. For instance, the human-readable names could be generated and displayed automatically unless they're overwritten by a dedicated standalone field option, like 'Displayed Name'.

**Comment by ganigeorgiev** [comment]
This was done intentional in order to simplify managing the collection and its records.

In addition to being used as api keys, the record fields are also part of the collection API rules and record filters.
Having a single representation everywhere helps avoid ambiguities like for example seeing in the listing `User ID` and you have to guess what the actual field name is so that you can use in the search bar to filter by it - is it `userId`, `user_id` or just `user`, etc.

I understand from the point of content management that it doesn't look very pretty, but you also have to keep in mind that the PocketBase admin UI is expected to be used primarily by the developer(s) of your app.

If you are looking for more headless CMS-like features, then I could recommend checking [Strapi](https://strapi.io/) or [Directus](https://directus.io/).
