### ISSUE TITLE
[Bug] Inserting image from collection into rich editor does not use application URL

### ISSUE THREAD

**Issue by Blobtoe** [pocketbase/pocketbase#6206]
Inserting an existing image from another collection into the rich editor uses the local address instead of the application URL. I use Pocketbase behind a reverse proxy, so this mean the URLs inserted into the content are not accessible in deployment.

![Screen Shot 2024-12-30 at 22 23 54](https://github.com/user-attachments/assets/0103f44b-1e3d-45ab-8fa4-92dd23cdb993)
![Screen Shot 2024-12-30 at 22 24 45](https://github.com/user-attachments/assets/3e253ef3-f361-4710-9597-e13892d4322c)

Pocketbase v0.23.12

**Comment by ganigeorgiev** [comment]
It is not really a bug, it is just how it is work at the moment because we rely on the JS SDK `files.getURL` service to generate the final url (see https://github.com/pocketbase/pocketbase/blob/master/ui/src/components/records/fields/EditorField.svelte#L73).

I've added [task#92239639](https://github.com/orgs/pocketbase/projects/2/views/1?pane=issue&itemId=92239639) in the roadmap to consider using the settings app url + some other minor changes either for the next v0.24 or v0.25 releases.

For now you can manually change or remove the host part.

**Comment by ganigeorgiev** [comment]
_Edit: The `convertURLs`, aka. "Strip urls domain" field option, should already work, so you can enable it for your `editor` field._

**Comment by ganigeorgiev** [comment]
Edit2: Regarding _"this mean the URLs inserted into the content are not accessible in deployment"_ note that even with the above planned task the above may still not work because we can't insert the image in the editor with a url pointing to a different environment because simply could be invalid, (aka. the image to not exist on the environment) which will simply cause the image to be empty/broken on the local environment when previewing the record. If you want your content to be "portable" between environment then use the "Strip urls domain" field option.

**Comment by Blobtoe** [comment]
The "_strip urls domain_" field option is indeed useful, but in my case Pocketbase is on it's own subdomain at `pocketbase.example.com` but the content is served at `example.com`, so it doesn't work. I could rearrange my reverse proxy to make it work, but I'll stick to doing a big _find and replace all_ to replace URLs for now.

You're correct that after replacing the URLs, the images are empty/broken when viewing the record because they violate the content security policy.
