### ISSUE TITLE
sending a test email not working

### ISSUE THREAD

**Issue by abacef** [pocketbase/pocketbase#6210]
I am running pocketbase on debian and created a superuser. When sending a test email without a SMTP server it fails saying it is unable to find the send mail executable. I installed the send mail executable then I tried to send another test email, and I did not receive it in my inbox or junk folder.

**Comment by ganigeorgiev** [comment]
_Please don't open issues like this, especially when this was discussed at least several times in the past. The Q&A discussions are usually the better place for this type posts._

Anyway, as mentioned in the documentation it is recommend to use a SMTP server for sending emails because by default it fallbacks to the unix `sendmail` command which may not be available or enabled on all platforms. And even if it is enabled, the mail server of the receiver may reject the email and refuse to deliver it to the receiver. We have no control over this. For test purposes I recommend using mailtrap.io or smtpbucket.com.

**Comment by ganigeorgiev** [comment]
I also forgot to mention that if you are running PocketBase on a VPS keep in mind that most hosting providers (_at least the one I've tested in the recent couple years - Linode, Hetzner, DigitalOcean) blocks common outgoing emails ports like 25, 465, etc. as a very rudimentary abuse protection and may require to contact their support to be explicitly enabled.
