### ISSUE TITLE
authstore not updating after user creation

### ISSUE THREAD

**Issue by z89** [pocketbase/pocketbase#676]
Hi, so I am trying to create (register) a new user.  Following the js-sdk docs, I should do the following:
```
import PocketBase from 'pocketbase';

const client = new PocketBase('http://127.0.0.1:8090');

// create user
const user = await client.users.create({
    email: 'test@example.com',
    password: '123456',
    passwordConfirm: '123456',
});

// set user profile data
const updatedProfile = await client.records.update('profiles', user.profile.id, {
    name: 'test',
});
```
client.users.create works just fine, however when I go to update the profile data it returns this error:
`{"code":404,"message":"The requested resource wasn't found.","data":{}}`

I confirmed on pocketbase that the record does exist, and that I can manually update the profiles collection name record. I am also using the default update API rule on my users collection "userId = @request.user.id". After some playing around, I only got it working if I login after creating the user (which updates the authstore) and then get the profile id from the authdata:
```
const user = await client.users.create({
    email: 'test@example.com',
    password: '12345678',
    passwordConfirm: '12345678',
});

const authData = await client.users.authViaEmail("test@example.com", "12345678");

const updatedProfile = await client.records.update('profiles', authData.user.profile.id, {
  name: 'test',
});
```
I checked the client.authStore before & after creating the user, and the authstore model remains null after the user is created. This is what I think is causing the record update to fail, since no user id is given from the authstore on the update request which the update API rule needs. Just to make sure it wasn't my application, I created a new react app and tested it on there as well, with the same error occurring.

I would like to cut down on the API usage, so are there any idea's as to why the authstore isn't updating after the user is created? Is this the default behavior of the authstore, meaning the documentation example doesn't work or am I doing something wrong? Thanks. 

EDIT: the documentation example uses a password with six characters instead of the minimum length of 8. I would've submitted a pull request changing each example for you to save you time, but the docs aren't open source sadly.

**Comment by ganigeorgiev** [comment]
That's correct. After creating a user you have to manually authenticate them if you want to execute any following action authorized as the created account.

This is not mentioned in the documentation because the user `profiles` create/update permissions are managed by the API rules and technically you can allow other users to update the profile record (or even guests).

About the password - it is just an example. The default limit is 8 character, but that could be changed from Admin UI:
"Settings > Auth Providers > Email/Password > Minimum password length".

_btw. Please note that the users and profiles management will be soon simplified as part of https://github.com/pocketbase/pocketbase/issues/376._

**Comment by z89** [comment]
Ahh ok, thanks for letting me know. 

I didn't realize you could change the default password limit, I assumed it was a feature yet to come, so ignore my edit :)
