### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by Sleepful** [pocketbase/pocketbase#680]
in https://pocketbase.io/docs/client-side-integration/ it says: `documentaion`

I looked for the docs repo to submit PR but couldn't find it 🤔

**Comment by sanathusk** [comment]
Even i couldn't find the docs repo. making the public would be helpful in improving documentation.

**Comment by ganigeorgiev** [comment]
@Sleepful Thanks, fixed it.

@sanathusk The documentation is not public because currently it is a little complicated to be edited by users not familiar with the codebase. For v0.8.0 release we'll have a new documentation and I'll try to simplify it (or at least remove the partial automation part and make the editing more consistent_).
