### ISSUE TITLE
feature request: consider adding an `--exec` flag for builtin process supervision

### ISSUE THREAD

**Issue by ollema** [pocketbase/pocketbase#689]
Hi!

I think a really cool feature with another Go-based project, `litestream`, is the fact that you can easily run it together with your main app in a Docker container by using the `-exec` flag.

More information here:
https://litestream.io/guides/docker/#running-in-the-same-container

In short:
> You can bundle both your application and Litestream together using Litestream’s built-in process supervision. You can specify your application’s process and flags by passing them to the `-exec` flag:
```
litestream replicate -exec "myapp -myflag myarg"
```
> Litestream will monitor your application’s process and automatically shutdown when it closes.

---

A similar flag would fit also work very well with PocketBase in my opinion.

Considering that there is a JS SDK - I think that many users will end up deploying their app by doing:
```
./pocketbase serve
```
and
```
node build
```

This works well when you deploy on a VPS but it would be great if you could deploy this with Docker (and/or on fly.io) and have a single entrypoint:
```
./pocketbase serve --exec "node build"
```

---

I guess the main questions now are:
* Is this something you think would fit in with the idea/philosophy of PocketBase? Is this also something that would be low maintenance enough to warrant being added? Or is it out of scope for PocketBase?
* If yes, is this something that you would consider adding to the roadmap or would it be a low priority/nice-to-have feature?
* If yes to the first question, is this something that you would want help with?

Thanks!

**Comment by ganigeorgiev** [comment]
I don't think this will be too hard to implement (at least the basic functionality) but I'm not sure how useful it would be in general because this will work only for a single process. In addition, often you may need more control over the secondary process, eg. on error try to restart while keeping the PocketBase server running, etc.

There are already existing tools for this like [s6](https://skarnet.org/software/s6/), [supervisord](https://github.com/Supervisor/supervisor), etc. that allow finer controls and multi-process configurations.

Alternatively, if you don't need too much control over the running processes, you can also create a simple shell script and start your services from there, as shown in https://docs.docker.com/config/containers/multi-service_container/.

For now, I'll leave this out of scope for v1.0.0 because there're already a lot of tasks piled in the roadmap and in my todo to research, but depending on the users demand for this feature, I may reconsider it in the future.
