### ISSUE TITLE
Bug: Uploaded Videos in files are not playing when opened

### ISSUE THREAD

**Issue by Adarsh077** [pocketbase/pocketbase#693]
How to Reproduce:
1. Create a collection with one file feild
2. Create a new record with a sample video file uploaded
3. Click on the video thumbnail icon - which open a new tab with video url
Here, in the new tab, we get to see a video dailog, but it doesn't play any video

Video Url Opened in new tab (for checking format just in case):
http://127.0.0.1:8090/api/files/1c4o6nnvz9jap52/di9yk1a17aox8bv/sample_mp4_file_small_VkHUk9sZaQ.mp4

When I check the **pb_data/storage/1c4o6nnvz9jap52/di9yk1a17aox8bv/** folder
Video file is there, and when opened from file manager it is playing.

**Comment by ganigeorgiev** [comment]
I don't think this is PocketBase related.

When you open directly the video in a new tab it is up to the browser to play the video. Maybe you are missing some required codecs or have a browser extension that prevents playing it.

**Comment by Adarsh077** [comment]
You are right, I am using chrome. When I open that url in firefox, video starts to play perfectly.
[browser extension:](https://github.com/pocketbase/pocketbase/issues/693#:~:text=or%20have%20a-,browser%20extension,-that%20prevents%20playing) Although I do not think it is because of any extension since I opened that in guest mode.
[missing some required codecs](https://github.com/pocketbase/pocketbase/issues/693#:~:text=Maybe%20you%20are-,missing%20some%20required,-codecs%20or%20have): When I open that same video in chrome from file manager, there is no problem. Video starts playing. So I don't think its a codec issue

I see this error in the console  [image](https://user-images.githubusercontent.com/47920913/193446239-b9a3dd34-f975-46af-9833-20b94f34c774.png)

I believe Content-Security-Policy has to be changed on server while sending a response. I may be wrong, I don't know much about CSP

**Comment by ganigeorgiev** [comment]
@Adarsh077 You are right. It is a CSP issue and looking at the [media-src directive documentation](https://udn.realityripple.com/docs/Web/HTTP/Headers/Content-Security-Policy/media-src) it makes sense since the default fallback is none when missing, but the strange thing is that this rule is not enforced in Firefox for some reason.

I've pushed a fix in `master` and it will be available in the next minor bugfix release v0.7.8 (sometime next week).

**Comment by ganigeorgiev** [comment]
@Adarsh077 Yep, this seems to work in Firefox because of a bug in how they apply the CSP. Similar issue could be found for the `script-src` directive - https://bugzilla.mozilla.org/show_bug.cgi?id=1313937 (it is almost 6 years old). Anyway, the Chorme behavior is the correct one and with the fix from `master` it should no longer result in an error when playing media files inside the browser.
