### ISSUE TITLE
Add Rpi zero support

### ISSUE THREAD

**Issue by emrahamet** [pocketbase/pocketbase#710]
Thanks

**Comment by ganigeorgiev** [comment]
I believe the available armv7 release should be compatible - https://github.com/pocketbase/pocketbase/releases
(https://github.com/pocketbase/pocketbase/releases/download/v0.7.8/pocketbase_0.7.8_linux_armv7.zip).

**Comment by emrahamet** [comment]
no it doesn't work i tried it before i open an issue, says Illegal instruction
when i compile it for v6 everything works

**Comment by ganigeorgiev** [comment]
Ah, I was confused by this spec - https://cdn.sparkfun.com/assets/learn_tutorials/6/7/6/PiZero_1.pdf, which ended up to be wrong per the comments in https://forums.raspberrypi.com/viewtopic.php?t=253166.

We can add a armv6 target to the, but I'm not sure how many users will use it and I'm afraid it may increase the build time during releases (currently the github release action takes ~ 12min to complete).

If there is a users demand for armv6 target I'll consider adding it to the [gorelease config](https://github.com/pocketbase/pocketbase/blob/master/.goreleaser.yaml), but for now I'll leave it aside because it will increase the build time during releases and test runs (currently the github release action takes ~10min to complete after tagging).

**Comment by scipilot** [comment]
I can confirm that compiling for armv6 on the Pi Zero v1.1 does work and it runs ok. It's an ARM11 i.e. armv6 achitecture, and so running the armv7 prebuilt pocketbase binaries fails with "illegal instruction". 

The newer Pi Zero 2 is an Arm64 so should work with the arm64 prebuilt binary, but I've not tried that as I don't have one.

These were my steps, should anyone else want to use an older Pi Zero. It took about 2hrs.

Install Go for armv6 on the Pi

    wget https://go.dev/dl/go1.25.1.linux-armv6l.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.25.1.linux-armv6l.tar.gz
    nano ~/.profile
        PATH=$PATH:/usr/local/go/bin
     . ~/.profile

Build pocketbase on the Pi

    nano .goreleaser.yaml 	
        change goarm=7 to goarm=6 
    cd examples/base
    GOOS=linux GOARCH=arm CGO_ENABLED=0 go build

    ./base serve

Expose to LAN (use IP or mDNS address)

    ifconfig | grep netmask
    ./base serve –http="10.200.72.143:8090"
    http://raspberrypi.local:8090/
