### ISSUE TITLE
Number fields default to 0 instead of null when not specified

### ISSUE THREAD

**Issue by jensstephansen** [pocketbase/pocketbase#729]
As the title says, number fields automatically default to 0, even when null is entered explicitly.

Is this the intended behavior, and if so, is there a way to circumvent it?

**Comment by ganigeorgiev** [comment]
This is an intended behavior (I'll consider documenting it after v0.8). PocketBase doesn't store `null` values for the records since [v0.3.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0) and fallbacks to the zero-default for each field type (except for the `json` type field).

> is there a way to circumvent it?

There are 3 workarounds (kindof):

- use the `json` type field, but keep in mind that the only validation this field has is for a valid json formatted input

- store the numbers as text and use digit as a regex pattern

- use a negative number to indicate `null`
