### ISSUE TITLE
Feature Request: Mobile Authentication 

### ISSUE THREAD

**Issue by amirhoseinjfri** [pocketbase/pocketbase#747]
Some of the apps uses mobile to authorize the user it will be cool feature to have this in PocketBase or custom authentication.thanks 👾

**Comment by ganigeorgiev** [comment]
@amirhoseinjfri If you mean authentication with phone/sms, then  I don't think we can implement this because there isn't a unified api and it is heavily dependent on the provider (and there are a lot of them, including local providers).

For now this is not planned, but depending on the users demand I may reconsider it and implement integration with some more popular providers like twilio.
