### ISSUE TITLE
Feature request: check settings

### ISSUE THREAD

**Issue by Lex-2008** [pocketbase/pocketbase#75]
When changing some settings (SMTP server, S3 storage, maybe auth providers), it might be useful to have an option to check and verify that new settings work (that you can connect to server, password is correct, s3 bucket exists and lets you create / download files), preferably as verbose as possible when something goes wrong - so user could easily figure out what went wrong.

I'm currently trying to setup minio to be used with pocketbase without much luck :)

**Comment by ganigeorgiev** [comment]
This is now available with the latest [v0.5.0 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.5.0).

The S3 connection test is performed in the background (if it is enabled). In case of an error or some incompatibility, you should see something like the following:
![s3-error](https://i.imgur.com/VIQZGPT.png)

_(The test performs a dummy file upload and delete)_

For the emails - you can now send test emails from the Admin UI.

For the OAuth2 providers - there is no "Check settings" toggle for that because I'm not sure how to perform the test without some additional action/configuration from the user. Since this doesn't have many option to configure (most providers support only client id and secret) I think it worth investing the time to try to test the oauth2 connection (the users needs to implement the client-side part of the OAuth2 integration anyway so if there is any error it will be quickly discovered).
