### ISSUE TITLE
AuthStore model id is different from profile.id

### ISSUE THREAD

**Issue by Anu-cool-007** [pocketbase/pocketbase#762]
Listing the profile records:
```
{
  "page": 1,
  "perPage": 30,
  "totalItems": 1,
  "totalPages": 1,
  "items": [
    {
      "@collectionId": "systemprofiles0",
      "@collectionName": "profiles",
      "avatar": "",
      "created": "2022-09-23 10:23:01.524",
      "id": "4o63z34c1l1n4pi",
      "name": "",
      "updated": "2022-09-23 10:23:01.524",
      "userId": "yzx0ljt0q1ugspf"
    }
  ]
}
```

The id is different from userId

This is causing issue when trying to update the user profile after oAuth with
`client.records.update("profiles", client.authStore.model.id, {...})`

Error: no records found with id yzx0ljt0q1ugspf

**Comment by ganigeorgiev** [comment]
That's because you need to provide the profile id, not the user id, to the `profiles` update call.

`client.authStore.model.id` is the user id. To get the profile id from the authStore, you could try accessing it like: `client.authStore.model.profile.id`.

_This ambiguity will be removed very soon with v0.8 and the users management will be simplified as part of the ongoing users refactoring in #376._

**Comment by Anu-cool-007** [comment]
Thanks for the quick reply. I'm using typescript and the model had User | Admin type.
Since Admin doesn't have the profile field, it was unavailable in the model.
Casting to User fixed it.
