### ISSUE TITLE
blob file upload, admin page photo column thumbnail image not load

### ISSUE THREAD

**Issue by heoyongun** [pocketbase/pocketbase#783]
blob file upload, admin page photo column thumbnail image not load

os ubuntu 22.04
db version pocketbase_0.3.2_linux_amd64
use quasar

store file
![스크린샷, 2022-10-16 02-02-18](https://user-images.githubusercontent.com/6076067/195998922-530bc2f3-d759-4da6-a0be-9ea254d1552d.png)

vue file
![스크린샷, 2022-10-16 02-02-25](https://user-images.githubusercontent.com/6076067/195998933-2f77ad54-2f5e-498c-906b-3bed78c1a6e9.png)

chrome debugger
![스크린샷, 2022-10-16 01-53-05](https://user-images.githubusercontent.com/6076067/195998835-560f9412-dd31-4c18-b17d-30714e14e11b.png)

admin page thumbnail image
![스크린샷, 2022-10-16 01-53-22](https://user-images.githubusercontent.com/6076067/195998880-cc96c77c-5d6f-4828-974c-b7bad5538fca.png)

**Comment by ganigeorgiev** [comment]
I think this is because the filename is missing an extension.

In order to minimize the number of requests the UI file preview is determined based from the filename and its extension. The only workaround I can think of at the moment without making an extra API call would be to normalize the filename on upload and always add an extension based on the mimetype for the common media types.

**Comment by heoyongun** [comment]
It work's thank you.
