### ISSUE TITLE
Feature Request: Special Increment field value

### ISSUE THREAD

**Issue by kidus-tiliksew** [pocketbase/pocketbase#786]
It would be extremely useful to have an increment field value similar to what we have with [firestore](https://firebase.blog/posts/2019/03/increment-server-side-cloud-firestore). It should be able to automatically update the counter based on user input. The calculation happens on the server side.

**Comment by ganigeorgiev** [comment]
It could be added but I'm not sure what could be the real use case for this. The illustrated example is very limited and the only benefit I see is the "safe" concurrent writes (still one of the writers could submit `-99999` to reset the counter and override it).

@kidus-tiliksew Could you elaborate on your use case and why do you thing it would be useful?

**Comment by kidus-tiliksew** [comment]
A `FieldValue.increment(-99999)` field value would not override the existing value but rather subtract from it in a safe transactional way. 

A use case I am working on is an electronic health record where each patient would need a unique field called Medical Record Number (MRN). The MRN could be random, but the number is usually displayed to the user and so it's good to have an incremental value (like a primary key in an SQL database) for the user to get an idea of the number of patients they have.

I don't remember all the use cases but I have used the increment value on Firestore many times before, one I remember is incrementing the number of likes a blog post gets. I imagine it's useful to a lot of people

**Comment by ganigeorgiev** [comment]
@kidus-tiliksew I'm not sure that I understand what do you mean by "safe transactional way". There are no transactions here. Every writer will just operate (substract or add) based the last stored value. The concurrent "safety" in Firestore to some extend comes from the fact that they restrict the updates to the same document to only 1 write per second (or at least that was the case a year ago).

I could understand the example with the likes counter. I'll have to thing a little more on this before adding it to the roadmap, because I want to avoid bloating the field dropdown with unnecessary types. Eventually this could be integrated as an option to the existing `number` field type.

**Comment by kidus-tiliksew** [comment]
When I said "transactional", I wasn't necessarily talking about implementation, I just meant to say it should be accurate. If multiple users are operating on the same counter field, the last stored value might not be the same for all, and so definitely won't be accurate unless there is special implementation for it. 

Thanks for the responses ✌️

**Comment by ganigeorgiev** [comment]
This is implemented in the latest v0.11.0 release via the `+` or `-` field modifiers - https://github.com/pocketbase/pocketbase/releases/tag/v0.11.0:

```js
{
    // oldValue + 2
    "someNumberField+": 2
}
```

**Comment by terdampar** [comment]
Is it possible to add rules on the field only to update `+1` per request, not `-99999`? Maybe something like `@request.data.field+ = 1` or `(field + @request.data.field) = (field + 1)`(?)

**Comment by ganigeorgiev** [comment]
@terdampar No, sorry this is not planned at the moment since it will complicate too much the filter syntax and internals.

For more advanced server-side validations you can register a [`OnModelBefore*`](https://pocketbase.io/docs/event-hooks/#db-hooks) or [`OnRecordBefore*Request` hook](https://pocketbase.io/docs/event-hooks/#record-crud-api-hooks)

**Comment by bart** [comment]
@ganigeorgiev Could you please provide a short example on how to use field modifiers? I couldn't find anything in the docs except that supported modifiers column under "Collections" Would highly appreciate it, thanks!

**Comment by ganigeorgiev** [comment]
@bart I'll consider documenting it better, but in general field modifiers are just an extra suffix to the field name:

```js
await pb.collection("example").update("RECORD_ID", {
    "totalA+": 10, // old totalA + 10
    "totalB-": 20, // old totalB - 20
})
```

**Comment by bart** [comment]
Ah okay, got it. Thanks @ganigeorgiev So it's just an increment of the current field value on update and not an auto increment over all fields in that collection on creation, correct?

**Comment by ganigeorgiev** [comment]
@bart Yes, that's correct. The field modifiers operate only on their related record field value.
