### ISSUE TITLE
OpenAPI 

### ISSUE THREAD

**Issue by HamAndRock** [pocketbase/pocketbase#799]
Hey, 
is there a plan to output API routes / responses to Open API format so it can be easily imported to Postman or used for generating the client typescript bindings?

**Comment by ganigeorgiev** [comment]
For now there are no plans for adding OpenAPI spec generation support out of the box.

I may reconsider it in the future since it was asked already several times (https://github.com/pocketbase/pocketbase/issues/414, https://github.com/pocketbase/pocketbase/discussions/209), but there are already a lot of other tasks piled in the [roadmap](https://github.com/orgs/pocketbase/projects/2) and for now this will remain out of the scope for v1.0.0.

 For TS types generation you may want to check - https://github.com/pocketbase/pocketbase/discussions/773.

**Comment by septatrix** [comment]
I think this would definitely be a worthwhile investment. As you already indicated in one of the other issues parts of the documentation are already auto-documented and adapting this to a different output format should not be too hard (also there seem to be some projects which auto generate them for echo servers but I did not use any of those yet).

The advantage is that this makes it soo much easier to generate bindings for all kinds of languages which currently do not have an SDK, get automatic TS types including collections etc.
