### ISSUE TITLE
Feature Request: Expand client SDK examples in `API Preview` and add an example for file upload

### ISSUE THREAD

**Issue by MarvinJWendt** [pocketbase/pocketbase#805]
Hi, thanks for this awesome project! 

Currently, the data in the `API Preview` is shown as a placeholder: `const data = { ... };`. 

<img width="826" alt="image" src="https://user-images.githubusercontent.com/31022056/196676378-0f250891-70de-480f-b9f2-121db9f625f3.png">

I think the actual body parameters could be entered here directly, with placeholders or empty values. This would improve user experience, as the user would not have to write the data object by himself.

Additionally, I also propose to add a file upload example to the preview, if the collection has a file column, as it's currently not documented on the `API Preview`.

**Comment by ganigeorgiev** [comment]
Hm, I'll consider populating the `data` object in the new API preview in v0.8, but maybe with not all possible fields since it may cause users to incorrectly think that they need to pass all fields on create/update.

For file upload - this is too env specific. For the Dart SDK it's a little bit easier, but the JS SDK could be used in both browser and/or node and the way how you construct the `FormData` object would differ (and to make things even worse, for earlier node version you may need to load various polyfill as explained in https://github.com/pocketbase/js-sdk#nodejs-via-npm).
For a more detailed file upload example you could check - https://pocketbase.io/docs/files-handling/#uploading-files (I'll consider adding a link in the API preview).

I'll close the issue for now since new documentation is already planned and will be available shortly after the upcoming pre-release of v0.8.
