### ISSUE TITLE
profiles records id is not user id

### ISSUE THREAD

**Issue by mgwrd** [pocketbase/pocketbase#821]
I'm not sure if this is on purpose or not. On my instance of pocketbase the id of a records in the profiles-collection is not the same as the user id. In the documentation it is written, that update requests can be made with the user id ([User Documentation](https://pocketbase.io/docs/manage-users/)). However I need to use `userModel.profile.id` in the Dart SDK.

btw: absolutely awesome project!

**Comment by ganigeorgiev** [comment]
That is because the `users` and `profiles` are 2 different entities. Each user has 1 profile, where the profile is a `profiles` collection record. By default, only admins and the authorized user owner is allowed to update the profile (this could be changed from the `profiles` collection API rules), but even if you are authorized as user or admin, you still need to provide the profile id that you want to update, the same as for any other collection record.

The confusion between the `users` model and `profiles` collection will be fixed with the upcoming v0.8 release (you could also check this issue - https://github.com/pocketbase/pocketbase/issues/376).
