### ISSUE TITLE
Files: Thumb not working with WEBP format

### ISSUE THREAD

**Issue by Siumauricio** [pocketbase/pocketbase#825]
Hi, I was testing to upload and resize WEBP images with the thumb property, the file upload is working fine, but the resize is not working I was checking the code probably this is the issue, it's just taking these formats and not WEBP.

https://github.com/pocketbase/pocketbase/blob/efda3d5a0b7e2dfd6ced4e1217cccfb9497a9759/apis/file.go#L12

https://github.com/pocketbase/pocketbase/blob/efda3d5a0b7e2dfd6ced4e1217cccfb9497a9759/apis/file.go#L71

**Comment by ganigeorgiev** [comment]
Unfortunately It's not just the file extension that is missing.

Webp is not supported at the moment because the image library that we use, [disintegration/imaging](https://github.com/disintegration/imaging), doesn't support webp (mostly due to the lack of native go webp encoding - https://github.com/golang/go/issues/45121; most webp go packages seems to rely on `libwebp` which requires cgo and I want to avoid that).

There are workarounds, like decoding the uploaded image and converting it to jpg/png thumb, but for now this remains out of the scope for v1.0.

**Comment by KnockOutEZ** [comment]
@ganigeorgiev can I look into this and try to solve this without cgo?

**Comment by ganigeorgiev** [comment]
@KnockOutEZ I'm open for suggestions but please first outline some of your planned implementation details to avoid investing unnecessary time and efforts in something that may not get merged.

**Comment by Wikidepia** [comment]
I stumbled upon this issue, just want to add that there are CGo-free webp encoder/decoder: git.sr.ht/~jackmordaunt/go-libwebp :)

**Comment by laszlo1337** [comment]
Hello. I understand there are difficulties with this issue, but since Safari now supports webp (finally after 13 years smh) I anticipate real uptick in WEBP format adoption, since it's a superior format in many aspects. So I am just asking if perhaps including this improvement could be moved up the schedule - especially if, like @Wikidepia mentioned, a solution is available. Thank you

**Comment by ganigeorgiev** [comment]
@laszlo1337 I'm not planning working on this for now as other tasks are with higher priority (see https://github.com/pocketbase/pocketbase/discussions/4355). I haven't tried the suggested library and I'm not sure how difficult it would be to integrate with, nor what platforms are supported (_see also this comment of the author of the above library - https://github.com/golang/go/issues/45121#issuecomment-1880348171_).
Note that this doesn't necessary need to be part of the core repo and can be implemented to some extend by attaching to the [`OnFileDownloadRequest`](https://pocketbase.io/docs/go-event-hooks/#onfiledownloadrequest) hook, meaning that if you have the time you can try to create a proof-of-concept "plugin"/package and if there is enough user demand and the code doesn't complicate too much the internals we can implement it and merge it into the main repo.

**Comment by aalokkamble** [comment]
@ganigeorgiev, I have a suggestion regarding adding WebP support. We can still utilize the [disintegration/imaging](https://github.com/disintegration/imaging), library, but with a slight adjustment. We can incorporate another library to convert WebP images to JPEG format, then proceed with imaging to generate thumbnail blobs. Subsequently, we can use this webp library to convert the thumbnail blobs back to WebP format and save them.

If you're okay with this approach, I'm ready to dive into the coding process!

**Comment by ganigeorgiev** [comment]
@aalokkamble Feel free to create a POC implementation but I'm not interested on working on this for the moment.
Note that your custom implementation doesn't necessary need to be part of the core repo and can be implemented to some extend as a "plugin"/library by attaching to the [OnFileDownloadRequest](https://pocketbase.io/docs/go-event-hooks/#onfiledownloadrequest) hook (see example "plugins" in https://github.com/pocketbase/pocketbase/tree/master/plugins).

**Comment by ganigeorgiev** [comment]
_Old issues cleanup: I'm closing this because I'm not planning working on it. I've briefly checked the suggested https://git.sr.ht/~jackmordaunt/go-libwebp but it comes with too high maintanence cost I want to avoid. The currently supported thumb formats are listed in the documentation. If someone want to work on it, feel free to link your PoC and I may reconsider it._

**Comment by ganigeorgiev** [comment]
_Just for info: partial WebP thumbs support was enabled as part of https://github.com/pocketbase/pocketbase/pull/6744 (thumbs for now are stored as PNG)._
