### ISSUE TITLE
While sending 0 in number type field it gives me error that   "errorDetails": "won: Missing required value.",

### ISSUE THREAD

**Issue by rajesh6161** [pocketbase/pocketbase#832]

**Comment by ganigeorgiev** [comment]
_This was recently discussed in https://github.com/pocketbase/pocketbase/issues/526, https://github.com/pocketbase/pocketbase/issues/604, https://github.com/pocketbase/pocketbase/issues/436 and probably others._

I'll document it better in the next v0.8 release. It is working as expected because PocketBase doesn't store `null` values for the record fields and uses zero-defaults (for number that is `0`). If you want to allow the number field to accept `0` as value then don't mark it "Required".
