### ISSUE TITLE
Upsert for records

### ISSUE THREAD

**Issue by albertcui** [pocketbase/pocketbase#844]
As far as I can tell, to implement "update or create" a record behavior, you have to query using `getList` first to check if a given record already exists. SQLite supports `UPSERT`; could this be supported in the REST api?

**Comment by ganigeorgiev** [comment]
_This was recently discussed in https://github.com/pocketbase/pocketbase/discussions/753._

There are no plans to add UPSERT support API since it is not very clear what API rule will be used and how it will be applied (eventual upsert-like behavior may be added in relation to the import feature in #48 but that action will require admin authentication).

> As far as I can tell, to implement "update or create" a record behavior, you have to query using getList first to check if a given record already exists

Yes, currently you have to use `getList` if you want to query a record with a filter expression, but in the upcoming v0.8 release there will be a dedicated helper `getOneByFilter(filter)` that will return the first matching record.

**Comment by karniv00l** [comment]
> there will be a dedicated helper getOneByFilter(filter) that will return the first matching record.

Quick question: will this follow the `view action` API access rule or `list action`? Because this is something that I actually require in my app. Thanks!

**Comment by ganigeorgiev** [comment]
@karniv00l Good question. It'll use the `List API rule` because internally it is sending a `getList` with `page` and `perPage` set to 1 and it will return the first found record that matches the provided filter. I'll make sure to document it alongside the client-side helper.

**Comment by lukepighetti** [comment]
> _This was recently discussed in #753._
> 
> There are no plans to add UPSERT support to the API since it is not very clear what API rule will be used and how it will be applied (eventual upsert-like behavior may be added in relation to the import feature in #48 but that action will require admin authentication).
> 
> > As far as I can tell, to implement "update or create" a record behavior, you have to query using getList first to check if a given record already exists
> 
> Yes, currently you have to use `getList` if you want to query a record with a filter expression, but in the upcoming v0.8 release there will be a dedicated helper `getOneByFilter(filter)` that will return the first matching record.

use create rule on create and update rule on update?
