### ISSUE TITLE
Null values and zero values

### ISSUE THREAD

**Issue by iskaa02** [pocketbase/pocketbase#852]
On non required fields Null values should be `null` rather than using a zero value like the one [Golang uses](https://www.geeksforgeeks.org/zero-value-in-golang).

The issue is most clear in numbers where the null value in this case `0` can be mistaken for an actual value `0`.
I have a required number field that takes value between `0-100` when `0` is provided the value is considered missing, and on other number field which is not required when `null` is provided it's considered to be `0`.
I don't think that's an optimal for handling null values especially in numbers.

the first bug it's a validation bug could be solved easily, but for the second it has to do with the `DEFAULT` in the SQL code which gives the columns a value when none is provided.

**Comment by iskaa02** [comment]
Another bug is that when a non-required number field has Min and Max conditions, the value is always required.
an example where column `a` is a non-required number have a min `1` condition, and being provided as null.

Request:
```json
{
    "a":null
}
```
Response:
```json
{
    "code": 400,
    "message": "Something went wrong while processing your request.",
    "data":
        "a": {
        "code": "validation_min_number_constraint",
        "message": "Must be larger than 1.000000."
        }
}

```

**Comment by ganigeorgiev** [comment]
This was recently discussed in https://github.com/pocketbase/pocketbase/issues/832, https://github.com/pocketbase/pocketbase/issues/526, https://github.com/pocketbase/pocketbase/issues/604, https://github.com/pocketbase/pocketbase/issues/436.

This is not documented well, but it is an intended behavior.

Since PocketBase v0.3, we no longer store `null` values. You could find all supported field values with their zero-default in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0.

**Comment by margani** [comment]
But the method for updating is PATCH, it makes sense if I don't include a property in the update, it doesn't validate it.

In the above example, if `a` is **not required**, but there is a min and max defined for it, and I send a PATCH request to update:

`PATCH /api/collections/entity/records/:id`
```json
{
  "b": "some value",
  "c": 10
}
```
it shouldn't say:

```json
{
  "code": 400,
  "message": "Something went wrong while processing your request.",
  "data": {
    "a": {
      "code": "validation_min_number_constraint",
      "message": "Must be larger than 1.000000."
    }
  }
}

```

**Comment by ganigeorgiev** [comment]
@margani The update action is applying a merge of the existing record fields + the submitted data. This is to ensure that newly enabled constraints, like the required/nonempty are checked.

In your case it seems that the the min and max options were defined after you've created the record and the above is expected because the old record field value is probably zero.
