### ISSUE TITLE
404 "database is locked" on parallel requests

### ISSUE THREAD

**Issue by tinawng** [pocketbase/pocketbase#875]
Hi
First thanks for your work, I'm really enjoying pocketbase so far!

I am experiencing random query failures when doing parallel queries.
For example when making a `Promise.all()` on multiple `getOne()` requests. In the dashboard I can see the error code is `404` with 
`{ "errorDetails": "database is locked (5) (SQLITE_BUSY)", "errorMessage": "The requested resource wasn't found."}`
I found it a bit counter-intuitive to have a 404 not found when it's more of a server problem.
From what I understand the database is locked on writing but here my request is a reading one. So the logging mechanism could be the bottleneck?

Here my test case is a couple hundred of parallel queries with random ID, collection contains 30k records and hardware is a Raspberry PI 4

I understand that I'm pushing against the limit with "big" parallel requests, but what are the limits ?
Can this happen with any big load on the database ?

![image](https://user-images.githubusercontent.com/8183977/198979820-bce0eb2c-c6e0-40a3-8f8a-247aca181d0a.png)

**Comment by ganigeorgiev** [comment]
What version of PocketBase are you using - v0.7.9 or v0.8.0-rc?

That's definitely strange and shouldn't happen on reads. SQLite in WAL mode supports multiple readers and a single writer so `SQLITE_BUSY` errors are generally expected only on heavy concurrent writes. Log writes happen in a separate database (log.db) in their own goroutine so it shouldn't be the reason for the error. Something else is going on here but I'm not sure what exactly.

I'll try to test it later today and will see if I can reproduce it.

**Comment by ganigeorgiev** [comment]
I was able to reproduce the error (even on <1k parallel GET requests).

I'm still not sure what exactly is causing it (I double checked that we are executing only `SELECT` queries), but it seems related to [`modernc.org/sqlite`](https://gitlab.com/cznic/sqlite) driver that we use by default. When switching to the [`mattn/go-sqlite3`](https://github.com/mattn/go-sqlite3) cgo driver the error doesn't happen.

With the cgo driver you may get "too many open files" error but that's expected because every network connection is a file descriptor and the default OS limits are usually ~1024 (you can check them with `ulimit -n`), but after increasing the limits (eg. `ulimit -n 50000`) the `mattn/go-sqlite3` driver works fine.

---

I'll try to create MRE and file an issue in the upstream `cznic/sqlite` repo, but for the meantime I would suggest to batch your parallel get queries to limit the number of concurrent requests and/or manually build PocketBase with the `mattn/go-sqlite3`  driver enabled (aka. `CGO_ENABLED=1`):

0. [Install go](https://go.dev/doc/install) (if you haven't already)    
1. Download/clone the repo
2. Navigate to `examples/base`
3. Run `GOARCH=arm64 GOOS=linux CGO_ENABLED=1 go build main.go`

**Comment by ganigeorgiev** [comment]
Just for info, I've opened an issue in the upstream repo with a minimal reproducible example - https://gitlab.com/cznic/sqlite/-/issues/115.

**Comment by tinawng** [comment]
I built with your latest commit from the `rc` branch, it seems to work fine now.
Thank you for the quick fix! 🙏

**Comment by ganigeorgiev** [comment]
@tinawng Yes, the latest commit in the `rc` branch do 2 things:

- defines the `busy_timeout` as the first pragma because the connection needs to be set to block on busy before WAL mode
- sets explicit db pool limits to avoid starving the open file descriptors and reduce the max memory usage

The underlying problem though is still not exactly clear why it is happening and it may be just an implementation detail how the noncgo driver works - https://gitlab.com/cznic/sqlite/-/issues/115#note_1156310378

But for now, the above workarounds should help with the `SQLITE_BUSY` errors on heavy concurrent load.
