### ISSUE TITLE
Feature Request: Sign in with (just) email

### ISSUE THREAD

**Issue by danibjor** [pocketbase/pocketbase#904]
Would be nice to have an option to sign in with just the email address. 

Workflow would be something like:
- User provides email address
- Server creates (one time) token, stores in collection alongside email and expire date (1 hour/configurable)
- Server emails token to the user, including callback url (something like: my-site.com/api/auth/token/xxyyzz)
- User clicks link and token is deleted from collection, user is now authenticated
- A profile should be created on first use of an email address, so profile details can be accessed between sessions.

As with other oauth providers, we don't get the blame if a site is compromised. There is no credentials (passwords) to loose.

It would also be nice to be able to disable the default user/pass auth when using one of the optional auth providers.

**Comment by ganigeorgiev** [comment]
This seems similar to the "magic link" authentication request in https://github.com/pocketbase/pocketbase/issues/119.

For now this is a low priority, mainly because users will need to provide always their own endpoint where to exchange the token from the email for auth token because PocketBase doesn't have sessions and there is no way to share the received auth data with the client if we have a default post-email click page.

**Comment by gamedevsam** [comment]
This almost seems like it would be fairly easy to implement as an example / template, PocketBase seems too low level to add this functionality as is (again, no sessions considering Pocketbase is not meant to be an application server without extensive modification by end users). But it would be helpful to demonstrate the implementation, perhaps with Next.js or something like that.
