### ISSUE TITLE
Bug: Invalid validation on required number fields with 0 value

### ISSUE THREAD

**Issue by returnednull** [pocketbase/pocketbase#907]
# Bug: Validation fails on required number fields with 0 value
## How to reproduce:

- Create a new collection
- Create a new required field with number type
- Send value as 0 when creating new record with JSON body
- API will respond with `validation_required` error code

### Collection:
  
  ![image](https://user-images.githubusercontent.com/68191254/199620701-fd704e11-1b64-4857-aeff-0d75231490c9.png)
  
### Request Body:
  
  ```json
  {
    "from_hours": 10,
    "from_minutes": 0,
    "to_hours": 22,
    "to_minutes": 0
  }
  ```
### Response Body:
  
  ```json
   {
    "code": 400,
    "message": "Something went wrong while processing your request.",
    "data": {
        "from_minutes": {
            "code": "validation_required",
            "message": "Missing required value."
        },
        "to_minutes": {
            "code": "validation_required",
            "message": "Missing required value."
        }
    }
   }
  ```
### Also Admin UI:
   
![image](https://user-images.githubusercontent.com/68191254/199623671-af623add-8df1-4127-88fd-be03fdee37b7.png)

## Probable Cause and Solution:
- github.com/pocketbase/pocketbase/forms/validators/record_data.go#L78
- github.com/go-ozzo/ozzo-validation/required.go#L16 > as comment says 0 values fails on validation.Required instance
I didn't debug error with probable solution but I think changing validation method to `validation.NilOrNotEmpty.Validate(value) != nil` in 'record_data.go#L78' is solution

**Comment by ganigeorgiev** [comment]
This was recently discussed in https://github.com/pocketbase/pocketbase/issues/852, https://github.com/pocketbase/pocketbase/issues/832, https://github.com/pocketbase/pocketbase/issues/526, https://github.com/pocketbase/pocketbase/issues/604, https://github.com/pocketbase/pocketbase/issues/436 and probably others.

In short, it is working as intended because since PocketBase v0.3 we no longer support `null` for field values and uses zero-defaults. You can check the table with the supported values in https://github.com/pocketbase/pocketbase/releases/tag/v0.3.0.

In v0.8.0 the "Required" constraint was renamed to "Nonempty" and a tooltip was added to explain what does this mean. You check it on the live demo - https://pocketbase.io/demo/.
