### ISSUE TITLE
What ist the problem with admin login?

### ISSUE THREAD

**Issue by paulanergarten** [pocketbase/pocketbase#948]
![image](https://user-images.githubusercontent.com/65194572/200180610-a27641a0-c603-42d7-a44d-c9e349defa37.png)
Why does it say not found?

**Comment by ganigeorgiev** [comment]
@paulanergarten My guess is that you are using PocketBase v0.8.0-rc, right?

If that's the case, then new api route for admin auth is "GET /api/admins/auth-with-password" and instead of "email" as key in your json you have to use "identity".

List with v0.8.0 changes could be found in https://github.com/pocketbase/pocketbase/releases/tag/v0.8.0-rc1.

**Comment by paulanergarten** [comment]
You're right, thanks!
