### ISSUE TITLE
Feature Request: OnUserAuthFailure Hook

### ISSUE THREAD

**Issue by LaurenceJJones** [pocketbase/pocketbase#950]
we have `OnUserAuthRequest` which runs a hook when user manages to authenticate properly, however, for monitoring purposes we may want to take action if a user or ip have failed so many times. Add event hook to do some action on auth failure?

**Comment by ganigeorgiev** [comment]
Hm, I think this will be confusing because there are multiple type of errors that could be returned depending on when in the request lifecycle the error was returned or on what route, eg. `authWithPassword`, `authRefresh`, etc. (especially with the upcoming v0.8.0 where `users` are now regular collection).

Instead, I think a generic error hook could be added and leave the developer to decide and identify on their own the type of action they want based on the error type and/or some request parameters like route path, body params, etc.

I've added the hook in the list here https://github.com/pocketbase/pocketbase/issues/468 and it will be handled sometime after the v0.8.0 release.
